{
  "Delilah": "Delilah",
  "He was stationed in Two Forks — your lookout — with his dad Ned three summers ago.  Great kid.": "Trzy lata temu spędził lato w Wieży na Rozdrożach, czyli tam \ngdzie ty, ze swoim ojcem, Nedem. Świetny dzieciak.",
  "He was stationed there in Two Forks with his dad, Ned, three summers ago. He was a great kid.": "Trzy lata temu spędził lato w Wieży na Rozdrożach ze swoim ojcem, Nedem. Świetny dzieciak.",
  "Henry": "Henry",
  "You can bring children out here?": "Można tu przyjeżdżać z dziećmi?",
  "No… you know, I'm not a stickler for rules. They took off halfway through the summer.": "Nie, ale nie jestem taką służbistką. W połowie lata już ich nie było.",
  "Why, where did they go?": "Czemu, gdzie się udali?",
  "Why?": "Czemu?",
  "I don't know. I never really hit it off with ol' Ned. And one day they were just… gone. Sucks.": "Nie wiem. Z Nedem nigdy się nie dogadywałam. \nPewnego dnia po prostu zniknęli. Kicha.",
  "Is Ned that guy from the note I told you about? About that guy leaving his post?": "Ned to ten gość z notatki, o której ci mówiłem? Tej o facecie, \nktóry rzucił robotę?",
  "Is Ned the guy from that note?": "Ned to ten gość z notatki?",
  "Oh, could be. Yeah. But I think at one point they just realized this job wasn't for them. For Brian, at least.": "Możliwe. Tak, ale chyba w pewnym momencie zdali sobie sprawę, \nże to nie jest robota dla nich. A przynajmniej nie dla Briana.",
  "Huh.": "Hm...",
  "What, they couldn't handle your unique brand of charm?": "Nie dali rady twojemu wyjątkowemu urokowi?",
  "Couldn't handle your charms?": "Twój urok ich przerósł?",
  "Not many can.": "Niewielu potrafi.",
  "Unsurprising.": "Nic dziwnego.",
  "You guys keep in touch? You and the Goodwin kid?": "Macie jakiś kontakt? Ty i ten dzieciak Goodwina?",
  "Did you keep in touch?": "Utrzymujecie kontakt?",
  "Nah, they took off pretty unceremoniously. Plus, what is a 40 year old woman going to do with a teenage pen-pal?": "Nie, odeszli z dnia na dzień. Poza tym na co czterdziestolatce nastoletni kolega na odległość?",
  "Hmm, good point.": "Słuszna uwaga.",
  "Anyway. So it goes.": "Tak to już bywa.",
  "Have fun with that camera.": "Baw się dobrze z tym aparatem.",
  "Try not to snap anything that would scar a Fotodome employee.": "Tylko nie zrób zdjęć czegoś, co przerazi fotografa \nprzy wywoływaniu.",
  "I don't know, I've got a lot of hiking to do; I might get bored.": "Nie mogę obiecać, czeka mnie sporo łażenia. Mogę się znudzić.",
  "Well, I'm bored as rocks, so I'll keep you company while you find those girls, huh?": "Sama nudzę się jak mops, więc dotrzymam ci towarzystwa, \na ty poszukasz tamtych dziewczyn, co?"
}