{
  "Henry": "Henry",
  "It's actually pretty damn cold out here.": "Całkiem tu zimno.",
  "It's actually cold out here.": "Całkiem tu zimno.",
  "Delilah": "Delilah",
  "Roger that. It warms up fast.  The mornings are cold in Boulder though, right?": "Przyjęłam. Ale szybko robi się cieplej. W Boulder poranki też są chłodne, co?",
  "Yeah, they are.": "Są, są.",
  "What did you get up to down there? I mean, what's life like?": "Czym się tam zajmowałeś? Znaczy... jak ci się tam żyło?",
  "You know, boring if you don't ski. We used to go to this bar called, \"The Dollar\" though. I love that place.": "Jak nie jeździsz na nartach, wieje nudą. Chodziliśmy do takiego baru, „The Dollar”. Uwielbiam to miejsce.",
  "Talk about your favorite bar.": "Opowiedz o swoim ulubionym barze.",
  "Oh wait, is that down on Pearl? They have all the money pinned to the ceiling?": "Czekaj, to ten na Pearl Street? Gdzie mają monety poprzyczepiane do sufitu?",
  "Yeah, that's it. Yeah.": "Tak, ten sam.",
  "I love that bar. Why don't you go anymore?": "Uwielbiam ten bar. Czemu już tam nie chodzisz?",
  "Well, I'm sure you have your reasons. I mean, it kinda smelled like beer puke in the bathroom.": "Na pewno masz swoje powody. W sumie w łazience zawsze czuć było wymiociny zmieszane z piwem.",
  "I just don't.": "Po prostu.",
  "Fair enough.": "Rozumiem.",
  "I took this job.": "Wziąłem tę robotę.",
  "Oh. Duh.": "No tak...",
  "I got a DUI.": "Prowadziłem pod wpływem...",
  "Ohhhhh…": "Aha...",
  "Yeah. Not particularly proud of it.": "Nie jestem z tego jakoś specjalnie dumny.",
  "Well, I mean… Look, I haven't told anyone this, but… I got one, too. Five years ago.": "Wiesz... nie mówiłam tego nikomu, ale mnie też odebrali prawko. Pięć lat temu.",
  "Yeah?": "Tak?",
  "Yeah. God, it was stupid. It was so stupid! But you know, it's late, it's winter, the streets are empty, and you just want to get home.": "No... Boże, to była głupota. Taka głupota! Ale wiesz jak jest, zima, \npóźna godzina, puste ulice, a człowiek chce jak najszybciej być \nw domu.",
  "Totally.": "Jasne.",
  "So fucking dumb.": "Idiotyzm...",
  "Talk about Julia.": "Opowiedz o Julii.",
  "I just spend a lot of time with Julia.": "Masę czasu spędzam tam z Julią.",
  "Oh. So you have someone there?": "Czyli masz tam kogoś?",
  "Well…": "Cóż...",
  "But you're taking a little break. Or…?": "Ale macie małą przerwę, czy może...",
  "We're…": "Jesteśmy...",
  "Look, I don't mean to pry or anything. A lot of lookouts like to gossip and talk about, you know, girlfriends, boyfriends, whatever. I'm just… just making conversation.": "Nie chcę być wścibska. Obserwatorzy lubią sobie poplotkować o dziewczynach, facetach i takich tam. Po prostu próbuję podtrzymać rozmowę.",
  "Ugh, I'm sorry. Can you hold that thought?": "Przepraszam, wrócimy do tego za moment?",
  "And I'll be right back. I got a call.": "Daj mi chwilę, telefon.",
  "Hey, can you hold on a sec?": "Możesz chwilkę zaczekać?",
  "Talk about Mayhem.": "Opowiedz o Masie.",
  "You know, uh, I don't know. I used to just spend a lot of time with our dog, Mayhem.": "Sam nie wiem... Sporo czasu spędzałem z naszym psem. \nWabił się Masa.",
  "Mayhem? What kind of name is that?": "Masa? Co to za imię?",
  "He was a German Shepherd, big as a truck.": "To był owczarek niemiecki, wielki jak ciężarówka.",
  "So why not call him Chevy?": "Czemu nie nazwaliście go Chevy?",
  "Well, we walked out of the shelter and there was some graffiti on a trash can, and it said \"Dicko Mayhem.\" And he walked over and peed all over it and there you go.": "Wyszliśmy ze schroniska, a na kuble na śmieci było graffiti: „Masa rządzi”. A on podszedł, odlał się na ten napis i już.",
  "Uh, that's a really… cute story?": "To naprawdę... urocza historia.",
  "It is what it is.": "Tak było.",
  "Talk about Bucket.": "Porozmawiaj o Biszkopcie.",
  "You know, I don't know. I used to just spend a lot of time with our dog, Bucket.": "Sam nie wiem... Sporo czasu spędzałem z naszym psem. \nWabił się Biszkopt.",
  "Aww, that's a good name.": "Fajne imię.",
  "He was a good dog.": "To była dobra psina.",
  "What type?": "Jaka rasa?",
  "A beagle. We got him from the pound.": "Beagle. Wzięliśmy go ze schroniska.",
  "That's great.": "Super."
}