{
  "Delilah": "Delilah",
  "Did your wife's illness having anything to do with you taking this job? Or did you just fall prey to the service's big recruiting push?": "Przyjąłeś tę pracę ze względu na chorobę żony? A może jesteś jedną z ofiar ostatniej łapanki przeprowadzonej przez nasze służby?",
  "I take it you fell prey to the Forest Service's big recruiting effort?": "Stawiam, że padłeś ofiarą jednej z łapanek Służby Leśnej?",
  "When it comes to how the hell you ended up out here.": "Pytam o to, jak, u diabła, wylądowałeś w tym miejscu.",
  "Henry": "Henry",
  "I saw the job in the paper and figured, you know, what the heck.": "Znalazłem ogłoszenie w gazecie i uznałem, \nże nie mam nic do stracenia.",
  "I got the job out of the paper.": "Znalazłem ogłoszenie w gazecie.",
  "What the heck, I've got no ties and no life, better go spend what's left of it in utter loneliness!": "Co mi tam, nie mam żadnych zobowiązań, więc mogę dokonać żywota w kompletnej głuszy!",
  "Something like that.": "Coś w tym rodzaju.",
  "Thanks to last summer, the bump in Forest Service budget actually allowed for us to advertise for the job.  Glad it worked.": "Po ostatnim lecie zastrzyk gotówki do budżetu Służby Leśnej pozwolił nam rozreklamować tę robotę. Cieszę się, że podziałało.",
  "Sorry, I don't really know what you mean by \"recruiting effort.\"": "Wybacz, nie bardzo rozumiem, co masz na myśli przez „łapankę”.",
  "What do you mean?": "Co masz na myśli?",
  "After last summer, you know. Budgets went through the roof, a lookout in every lookout for the first time in twenty years.": "No wiesz, ostatnie lato. Wpompowali do budżetu mnóstwo kasy, \npo raz pierwszy od dwudziestu lat zapełnili wszystkie wieże \nobserwacyjne.",
  "Last summer…?": "Ostatnie lato?",
  "You're from Denver, not Delaware. This was national news for pete's sake!": "Jesteś z Denver, nie Delawere. Huczał o tym cały kraj, \nna litość boską!",
  "Boulder. I'm from Boulder.": "Boulder. Jestem z Boulder.",
  "Same dif!": "Bez różnicy!",
  "Actually, I went looking for the job. I just wanted to get out of town for a while.": "Właściwie sam zacząłem szukać pracy. Chciałem się na trochę wyrwać z miasta.",
  "I was looking for a job like this.": "Szukałem dokładnie takiej roboty.",
  "Oh yeah, that's right. I remember.": "No tak, racja. Teraz sobie przypominam.",
  "Well, you've come to the right place.": "Trafiłeś więc w odpowiednie miejsce.",
  "Thanks to last summer, we got a bump in Forest Service budget and can actually afford to have you.": "Po ostatnim lecie dostaliśmy zastrzyk gotówki do budżetu Służby Leśnej, więc stać nas na twoje utrzymanie.",
  "Anyway….": "W każdym razie...",
  "What happened last summer that accounted for this, uh, windfall?": "Co takiego stało się zeszłego lata, że spadł na was ten deszcz pieniędzy?",
  "What happened last summer?": "Co wydarzyło się ostatniego lata?",
  "So are you going to let me know what happened that caused this budget increase or what?": "Zdradzisz mi w końcu, skąd taki nagły zastrzyk gotówki do budżetu czy nie?",
  "You going to tell me what happened or what?": "Powiesz mi w końcu, co się wydarzyło czy nie?",
  "Ha, wow, I can't believe you don't know.": "Po prostu nie wierzę, że o tym nie słyszałeś.",
  "I was a little preoccupied last summer.": "Miałem inne rzeczy na głowie.",
  "Oh you're talking about that uh, giant fire that, probably caused some damage. Turned an an entire jamboree of Brownies to dust.": "Zaraz, mowa o tym wielkim pożarze, który narobił chyba nieco spustoszenia... Wykurzył cały zlot skautów.",
  "Oh, you mean the fire.": "Masz na myśli pożar?",
  "Brownies don't have jamborees.": "Skauci nie urządzają zlotów.",
  "Well they should.": "Powinni zacząć.",
  "And you don't know what the hell I'm talking about, do you.": "A ty nie masz zielonego pojęcia, o czym mówię.",
  "I do not.": "Bingo.",
  "Jeez. The federal government almost let Yellowstone National Park burn to the ground. Ring a bell?": "Jezu... Rząd federalny niemal sprawił, że Park Narodowy Yellowstone poszedł z dymem. Brzmi znajomo?",
  "Yellowstone is like, what, fifteen miles away. Why would they do that?": "Przecież od Yellowstone dzieli nas ponad 20 kilometrów. \nPo co mieliby to robić?",
  "Why would they do that?": "Po co mieliby to robić?",
  "Well, the short story is that for sixty years we got very good at not letting forest fires happen.  And then, about fifteen years ago they decided that forest fires in wilderness areas, like Yellowstone, should be left to burn.  So that's what they did.": "Krótko mówiąc, przez 60 lat udawało nam się skutecznie \nzapobiegać  pożarom lasów. Do czasu aż jakieś 15 lat temu \nuznano, że ogień na terenach dzikich, jak Yellowstone, \npowinien wypalać się sam. I na to też pozwolono.",
  "I can't believe you didn't hear about this.": "Nie wierzę, że o tym nie słyszałeś.",
  "There were reports that the entire park was gone; Dan Rather telling the country that President Reagan didn't care on the nightly news.": "Spekulowano, że ogień strawił cały park. Dan Rather grzmiał \nw wieczornych wiadomościach, że prezydent Reagan ma to w nosie.",
  "I mean what the hell is he going to do, smoke jump in and snuff one out for the Gipper?": "A co, do licha, miałby zrobić? Przywdziać swój kostium strażaka \ni ugasić pożar w pojedynkę?",
  "So what should they have done?": "A co powinni byli zrobić?",
  "What should they have done?": "Co powinni byli zrobić?",
  "I don't even know. By the time the Yellowstone folks realized the little fires weren't going to burn themselves out 100,000 acres were gone.": "Sama nie wiem. Zanim władze Yellowstone doszły do wniosku, że pożary same się nie ugaszą, ogień pochłonął sto tysięcy akrów ziemi.",
  "It's Yellowstone, you know? People don't want to touch it. But we touch it every single day.": "Mówimy o Yellowstone. Ludzie chcą, by te tereny zostały nietknięte, ale naruszamy je każdego dnia.",
  "But hey, I got a thirty cents an hour raise because we can't have another fiasco! Like the goddamn park can burn down again.": "Za to ja zarabiam 30 centów więcej na godzinę, by zapobiegać kolejnym katastrofom! Tak jakby ten cholerny park miał znów stanąć w ogniu..."
}