{
  "Henry": "Henry",
  "There's an abandoned pack out here.": "Znalazłem jakiś porzucony plecak.",
  "Report hanging backpack": "Zgłoś wiszący plecak",
  "Delilah": "Delilah",
  "It's not one of the teens'?": "Którejś z tych małolat?",
  "No, it looks like it was lost a long time ago.": "Nie, raczej jest tu już dłuższy czas.",
  "Well, you could always pilfer it for supplies.": "Przeszukaj go, może coś znajdziesz.",
  "I think I just found Brian Goodwin's backpack.": "Chyba znalazłem plecak Briana Goodwina.",
  "Really? Where?": "Naprawdę? Gdzie?",
  "On the backside of the wire — there's a big rock face and it looks like he would've had to drop it from the top.": "W okolicy słupów telefonicznych. Jest tutaj duża ściana skalna. Wygląda na to, że upuścił go ze szczytu.",
  "Whoopsy.": "Ups.",
  "I'll see what he left.": "Zobaczę, co zostawił.",
  "Well, I'm flush with ropes now.": "Teraz mam lin po uszy.",
  "I just found an old pack full of them. In decent condition too.": "Znalazłem stary plecak pełen lin. W dobrym stanie.",
  "That pack was full of them. In decent condition too.": "W plecaku było ich sporo. Na dodatek w dobrym stanie.",
  "That's lucky.": "Ty szczęściarzu.",
  "There's enough rope here that I can just leave them hooked up, I think. Oh, get this — this pack came with one of those cardboard single-use cameras.": "Jest tu tyle lin, że spokojnie będę mógł zostawiać je przypięte. \nTy, słuchaj, w środku znalazłem też taki jednorazowy aparacik.",
  "With pictures left?": "Zostało coś na kliszy?",
  "Yeah, he only used three or four.": "Tak, ktoś zrobił raptem trzy czy cztery zdjęcia.",
  "Neato.": "W dechę.",
  "Thanks Brian Goodwin.": "Dzięki, Brianie Goodwinie.",
  "Wait, wait… who?": "Czekaj, kto?",
  "The bag had the name Brian Goodwin sewn into the top.": "Na plecaku naszyto plakietkę z imieniem Brian Goodwin.",
  "I actually found some of his stuff back in my desk.": "Znalazłem część jego rzeczy w moim biurku.",
  "Huh. Wow.": "A niech mnie...",
  "Do you know him?": "Znasz go?",
  "Yeah, I just haven't heard that name in a few years.": "Tak, ale nie słyszałam o nim od lat.",
  "He was a lookout?": "Też był obserwatorem?",
  "Lookout?": "Obserwator?",
  "Ha! Yeah kinda, I guess.": "No, tak jakby.",
  "Was he a ranger or something?": "Był leśniczym, czy coś?",
  "Ranger?": "Leśniczy?",
  "Oh, no, no.": "Nie, nie...",
  "What, was he a fella you had a thing with?": "Miałaś z nim romans?",
  "Ex-lover?": "Były kochanek?",
  "Oh yeah, it was hot and heavy. Of course, Brian Goodwin was twelve years old so our love could never really be understood.": "O tak, było namiętnie i żarliwie. Brian Goodwin miał dwanaście lat, więc naszej miłości niestety nikt by nie zrozumiał.",
  "Yuck.": "Fuj.",
  "I'm kidding. Not about him being an actual twelve year old. That part's true.": "Żartuję. Znaczy prawdą jest to, że miał dwanaście lat.",
  "Anyway, yeah, Brian Goodwin.": "No ale tak, Brian Goodwin...",
  "Huh, the name Brian Goodwin is sewn into the top of this bag.": "Na plecaku naszyto plakietkę z imieniem Brian Goodwin.",
  "Huh.": "Hm...",
  "He must've dropped it from the top of the rock face out here. Maybe he was climbing?": "Musiał go upuścić ze szczytu tej skały. Może się wspinał?",
  "That doesn't sound like Brian. Well, the dropping the bag does.": "To nie brzmi jak Brian. Poza upuszczeniem plecaka.",
  "Well, his bag has enough ropes that I can just leave them hooked, I think. And he had one of those single-use cardboard cameras with him too.": "W jego plecaku jest na tyle lin, że będę mógł zostawiać je przypięte przy stanowiskach. Był też posiadaczem jednego z tych jednorazowych aparacików.",
  "Poor kid must've really wanted this thing back — he had a disposable camera with him.": "Biedny dzieciak, na pewno chciał odzyskać ten plecak. Miał tu spakowany jednorazowy aparat.",
  "I wonder what he took.": "Ciekawe, co sfotografował.",
  "Maybe I'll fill it up and then have it processed when I get back.": "Może zapcham kliszę i po powrocie wywołam zdjęcia.",
  "Try not to snap anything that would scar a Fotodome employee.": "Tylko nie zrób zdjęć czegoś, co przerazi fotografa \nprzy wywoływaniu."
}