{
  "I feel like I'm going to be murdered when I'm in there.": "W takich właśnie miejscach na ludzi czyha śmierć.",
  "Henry": "Henry",
  "I feel like I'm going to be murdered when I'm in the outhouse.": "W takich właśnie wychodkach na ludzi czyha śmierć.",
  "Delilah": "Delilah",
  "Feeling a little exposed, are we?": "Czyżbyś czuł się bezbronny?",
  "Hey, no man in the history of the world has felt tough with his pants around his ankles.": "Każdy mężczyzna przestaje być twardzielem, kiedy ma majtki przy kostkach.",
  "Well, be strong. You can always call if you're having trouble.": "Trzymaj się tam. Zawsze możesz zgłosić, jak coś będzie nie tak.",
  "Oh sure, I'll do that.": "Tak właśnie zrobię.",
  "It's still gross.": "Nadal jest ohydny.",
  "The outhouse is gross today and it will be gross forever.": "Ten wychodek jest ohydny i już zawsze taki pozostanie.",
  "Well, the bacteria die during the winter so anything you smell and don't like in there is your own brand. Just so you know.": "Bez obrazy, ale zarazki wymierają podczas zimy, więc wszystkie nieprzyjemne zapachy to twoja sprawka.",
  "Ugh, well, then I'm a disgusting animal.": "Wychodzi więc na to, że jestem odrażającym zwierzęciem.",
  "About this outhouse…": "Co do wychodka...",
  "Uh… so it's just the outhouse, then, in terms of going to the bathroom?": "Czyli w kwestii potrzeb naturalnych mogę liczyć tylko na wychodek?",
  "So this outhouse…": "Co do tego wychodka...",
  "I like the outhouse in that rustic, \"I'm roughin' it\" way.": "Podoba mi się ten wychodek. Kojarzy mi się z taką nieociosaną wiejskością.",
  "I actually like the outhouse.": "Mnie się tam wychodek podoba.",
  "It's a little privacy among the seemingly endless expanse of, well, privacy.": "To odrobina prywatności w tym pozornym bezmiarze... prywatności.",
  "I like it all the same.": "I tak mi się podoba.",
  "You're a man, Henry. You can go wherever you want. Number one, at least.": "Jesteś mężczyzną, Henry. Możesz to robić, gdzie chcesz. Przynajmniej jedynkę.",
  "And — full disclosure — I pee wherever I want to as well.": "I, przyznam ci się bez bicia, też sikam, gdzie chcę.",
  "So this generator is all the power I've got out here?": "Ten agregat to moje jedyne źródło prądu?",
  "This is all the electricity I've got?": "To jest jedyne źródło prądu w tym miejscu?",
  "Yep. It doesn't go through much gas and you don't have much in the way of electronics, so…": "Tak. Nie wymaga zbyt wiele paliwa, a ty nie przytachałeś tu chyba za dużo sprzętu, więc...",
  "What about my hair dryer?": "Co z moją suszarką do włosów?",
  "But my hairdryer!": "A co z moją suszarką do włosów?!",
  "Aww, I'm sorry. You might just have to make peace with frizzy locks.": "Oj, jak mi przykro. Musisz przyzwyczaić się do loczków.",
  "I could never!": "W życiu!"
}