{
  "Delilah": "Delilah",
  "You've got a front row seat for what might be the biggest fire of the year.": "Masz świetny widok na być może największy pożar roku.",
  "Henry": "Henry",
  "Yeah, it's really going.": "No, mocno daje.",
  "I’m going to call it in. They’ll send in a hotshot crew for some suppression, but I bet we'll be stuck with her for the rest of the summer.": "Zgłoszę to. Przyślą grupę strażaków, nieco go przytłumią, \nale pewnie będziemy się z nim męczyć do końca lata.",
  "And she doesn’t have a name yet.  I usually think of something funny, or something practical or a little risque when coming up with them.": "Nie ma jeszcze nazwy. Zazwyczaj wymyślam coś zabawnego, \npraktycznego albo troszkę wulgarnego.",
  "But why don’t you do the honors?": "Może tym razem ty coś wymyślisz?",
  "Uh, well, we should just call it The Big Fire, if we think it's going to be.": "Skoro może to być wielki pożar, to tak powinniśmy go nazwać.",
  "How about \"The Big Fire\"?": "Co powiesz na „Wielki Pożar”?",
  "The Big Fire?": "Wielki Pożar?",
  "Yeah.": "Tak.",
  "Well, that is… practical.": "To dość... praktyczne podejście.",
  "Always my goal.": "Staram się.",
  "I'm actually amazed we've never used that name.": "Dziwię się, że nigdy nie użyliśmy tej nazwy.",
  "Sometimes the best names are the most obvious.": "Czasami najlepsze nazwy to te najbardziej oczywiste.",
  "The Big Fire it is.": "A więc Wielki Pożar.",
  "Uh, maybe we call it The Flapjack Fire. Can you sell that as a name?": "Może nazwijmy go Pożarem Ciapciaka. Nadaje się na nazwę?",
  "Maybe \"The Flapjack Fire.\"": "Może „Pożar Ciapciaka”?",
  "You really like that, huh?": "Serio ci się podoba, co?",
  "Ha. I didn't know you liked that stupid joke.": "Nie wiedziałam, że spodobał ci się ten głupi żart.",
  "Well, I did. It was my second day and I didn't feel as, um—": "Spodobał. To był mój drugi dzień i nie czułem się zbyt...",
  "Effusive?": "Wylewnie?",
  "Yeah, sure. Effusive.": "Właśnie. Wylewnie.",
  "Fair enough. Flapjack Fire it is. They'll probably ask me if it was a camp cooking accident or something.": "Bardzo dobrze. Niech będzie Pożar Ciapciaka. Pewnie będą pytać, czy to jakiś wypadek przy grillowaniu.",
  "Yeah, I said I did. It’s funny.": "Mówiłem przecież, że tak. Był śmieszny.",
  "Uh, Delilah's a nice name.": "Delilah to ładne imię.",
  "What about \"Delilah\"?": "Co powiesz na „Delilah”?",
  "Haha! No, you big dummy!": "Nie, ty głuptasie!",
  "Ha, I was kidding.": "Żartowałem.",
  "Mm-mm. No, you were not. You're sweet. But we can't call it the Delilah Fire.": "Wcale nie. To było słodkie. Ale nie możemy nazwać pożaru Delilah.",
  "Okay, what then?": "No to jak?",
  "How about my middle name, June?": "A może moje drugie imię, June?",
  "The June Fire. Even though it's July.": "June jak czerwiec. Mimo że jest lipiec.",
  "I like it.": "Podoba mi się.",
  "So, no ideas, huh?": "Żadnych pomysłów?",
  "Come on. There’s got to be something creative in that brain of yours.": "No dalej. Rusz tą swoją mózgownicą.",
  "I guess you’re in one of your quiet moods.": "Chyba masz jeden z tych cichych dni.",
  "How about the Elk Fire? I saw a herd crashing through the timber there a couple hours ago.": "Co powiesz na Pożar Wapiti? Jakiś czas temu widziałam stado biegnące przez las.",
  "Okay. “The Elk Fire” it is.": "Dobra. Niech będzie „Pożar Wapiti”.",
  "So there's this creek down the hill, and you know what my favorite thing to do is?": "U stóp wzgórza jest taka zatoczka, a wiesz, co lubię robić najbardziej?",
  "What's that?": "Co takiego?",
  "I love to take a bottle of whatever I have on hand, plunge it deep into the water, and let it chill in there all day.": "Uwielbiam wziąć butelkę tego, co mam pod ręką, wsadzić głęboko do wody i chłodzić tam cały dzień.",
  "And then on nights like tonight, when it is so disgustingly hot, I have something nice and cool to drink.": "Wtedy w nieziemsko gorące noce, takie jak ta, mogę się napić czegoś przyjemnie schłodzonego.",
  "I learned that from my sister in Santa Fe. She’d do that with a bottle of tequila near her house and make margaritas the size of your head.": "Nauczyłam się tego od siostry w Santa Fe. Robiła tak z butelką tequili, a potem przyrządzała drinki wielkie jak twoja głowa.",
  "You’d like it there.": "Spodobałoby ci się tam.",
  "If I was there with you I’m sure I’d like it a lot.": "Z tobą na pewno by mi się podobało, i to bardzo.",
  "I would if I was with you.": "Spodobałoby, gdybyś tam była.",
  "I've had one too many bad experiences with tequila. I'm a little reticent to try again.": "Mam kiepskie doświadczenia z tequilą. \nNie mam ochoty znowu próbować.",
  "I've had a bad time with tequila.": "Nie wspominam dobrze tequili.",
  "Well maybe you just need a new, good experience with it.": "Może po prostu potrzebujesz dobrych wspomnień.",
  "Yeah, maybe.": "Może.",
  "I’m sure I would. Sounds pretty great.": "Pewnie tak. Brzmi świetnie.",
  "I'm sure.": "Na pewno.",
  "It is.": "Wiadomo.",
  "Are you looking at the fire?": "Patrzysz na ogień?",
  "Yeah, I am.": "Tak.",
  "No. I'm looking at you.": "Nie, patrzę na ciebie.",
  "No, I'm not.": "Nie.",
  "You should. Let me know when you are.": "Powinieneś. Daj znać, jak będziesz.",
  "Oh! Well, um… let me know when you are.": "No to... daj znać, jak będziesz.",
  "Come look at this with me.": "Obejrzyjmy go razem.",
  "Call me when you’re watching it.": "Odezwij się, jak będziesz oglądać.",
  "Okay, I'm looking at it again.": "Dobra, znów patrzę na pożar.",
  "I love how they look at night. During the day it's just smoke, but when the sun is down you can just… get lost.": "Uwielbiam widok ognia nocą. W ciągu dnia to tylko dym, \nale kiedy zajdzie słońce, można... po prostu się zagubić.",
  "I’m glad you’re here.": "Cieszę się, że tu jesteś.",
  "Me too.": "Ja też.",
  "Good.": "Dobrze.",
  "I don't talk to the other lookouts as much as I talk to you.  Not in the same way.": "Nie rozmawiam z innymi obserwatorami tyle co z tobą. \nNie w ten sam sposób.",
  "I know it's probably been awhile since you've connected with someone the way we have. I don’t mean to get all heavy, but… it’s been really nice.": "Pewnie minął już jakiś czas, odkąd zaprzyjaźniłeś się z kimś tak jak teraz. Nie chcę być sentymentalna, ale... jest naprawdę miło.",
  "I look forward talking to you, even if you don’t feel comfortable opening up. You always can.": "Zawszę cieszę się, że mogę z tobą pogadać, nawet jeśli nie chcesz się otwierać, choć zawsze możesz.",
  "Sure you are.": "No jasne.",
  "I am.": "Naprawdę.",
  "I don't know what that means.": "Nie wiem, co to znaczy.",
  "It means, I guess, you don't really— or can't really— feel the same way? Which is okay. I like you anyway.": "To chyba znaczy, że nie czujesz... albo nie możesz czuć tego samego? W porządku. I tak cię lubię.",
  "It doesn't matter. I get it. With Julia and everything, you probably don’t want to be here.": "To nie ma znaczenia. Rozumiem. Z powodu Julii i w ogóle pewnie nie chcesz tu być.",
  "I don't know if that's true.": "Nie wiem, czy to prawda.",
  "Forget I said anything. I just meant I like that you’re here.": "Zapomnij, że cokolwiek mówiłam. Po prostu cieszę się, że tu jesteś.",
  "Why do you say that?": "Czemu tak mówisz?",
  "Because I do. I'm not crazy. I mean, we've had a such a good time, right?": "Bo tak. Nie jestem szalona. Znaczy... było nam dobrze, nie?",
  "Well, I like you.": "Cóż, lubię cię...",
  "Yeah, I think so.": "Tak myślę.",
  "And I know you're not really available, but I want you to know, well… Maybe it'd be nice to get together at the end of the summer.": "I wiem, że nie jesteś wolny, ale chcę, żebyś wiedział, że... może fajnie byłoby się spotkać pod koniec lata.",
  "I dunno. Maybe it'd be nice to get together at the end of the summer.": "Nie wiem. Może fajnie byłoby się spotkać pod koniec lata.",
  "Umm…": "Hm...",
  "Look, we don't have to plan or even talk about it. I'm… just having the thought.": "Nie musimy nawet nic planować. Po prostu... głośno myślę.",
  "I wish I was over there.": "Chciałabym tam z tobą być.",
  "Why don't we both just go watch this fire and try to imagine all the old dead things it's burning away.": "Może po prostu obserwujmy pożar i wyobrażajmy sobie, jak wypala wszystkie nasze problemy. ",
  "I wish you were too.": "Też bym tego chciał.",
  "We could sit outside.": "Moglibyśmy posiedzieć na zewnątrz.",
  "It'd be nice to be near somebody.": "Byłoby miło być blisko kogoś.",
  "…": "...",
  "We could talk. Without these radios. We could, um… You know.": "Moglibyśmy rozmawiać. Nie przez krótkofalówki. Moglibyśmy... No wiesz.",
  "What? What could we do?": "Co? Co moglibyśmy?",
  "What could we do?": "Co moglibyśmy?",
  "Well. Let me tell you.": "Powiem ci.",
  "Well, we could just watch this fire. It's gonna burn for a long time.": "Moglibyśmy po prostu oglądać ogień. Będzie jeszcze długo szalał.",
  "It'd be nice to be close to someone.": "Byłoby miło być blisko kogoś."
}