{
  "Hideout": "Kryjówka",
  "Report cave incident and hidden fort": "Zgłoś wydarzenie w jaskini i ukryty fort",
  "Henry": "Henry",
  "I just had to dig my way out of the cave because someone locked the gate behind me.": "Właśnie musiałem przekopać się przez jaskinię, bo ktoś zamknął za mną bramkę.",
  "Delilah": "Delilah",
  "Oh my God! Are you okay?": "Mój Boże! Wszystko w porządku?",
  "I'm fine. Just spooked.": "Tak, trochę się przestraszyłem.",
  "I'm going back in there but I need to find some climbing equipment. There's no place to attach a rope.": "Muszę tam wrócić, ale najpierw znajdę jakiś sprzęt wspinaczkowy. Nie da się zamocować nigdzie liny.",
  "Okay, that sounds that dangerous.": "Brzmi to niebezpiecznie.",
  "Yeah. But listen, when I came out I found a rock outcropping that someone was using as a little fort.": "Słuchaj, na zewnątrz znalazłem formację skalną, z której ktoś zrobił sobie mały fort.",
  "Report secret hideout": "Zgłoś kryjówkę",
  "Delilah, I just found an outcropping that someone was using as a little fort.": "Delilah, właśnie znalazłem formację skalną, z której ktoś zrobił mały fort.",
  "I think it was Brian Goodwin.": "To zapewne dzieło Briana Goodwina.",
  "Really?": "Serio?",
  "Yeah. He built himself a real castle.": "Tak. Zbudował sobie prawdziwy zamek.",
  "Report \"fortress wall\"": "Zgłoś „mury obronne”",
  "A bunch of rocks stacked up, he made a wall and a perimeter.": "Mnóstwo poustawianych kamieni, zrobił mury graniczne.",
  "Ha, God. Yeah, that's perfect.": "Boże, idealnie.",
  "But, you know, maybe he did it because he was afraid of \"them.\"": "Ale wiesz, może zbudował to, bo bał się „ich”.",
  "Whenever I think of Brian possibly going through this crap I get sick to my stomach.": "Za każdym razem kiedy pomyślę, że Briana mogłoby to spotkać, \nrobi mi się niedobrze.",
  "Yeah. Sorry.": "Przepraszam.",
  "Gosh, Brian had everything he loved out there.": "Boziu. Brian miał tutaj wszystko, co kochał.",
  "It's a little weird that he'd just leave so some of this stuff out here.": "To trochę dziwne, że tak po prostu zostawił tu tyle rzeczy.",
  "Well, maybe they were in a hurry when they left. Like I said, he wasn't supposed to be out here.": "Może odchodzili w pośpiechu. Jak mówiłam, nie powinno go tu być.",
  "Yeah.": "Tak.",
  "I uh, they almost got busted. Brian liked to go out on the railing of the tower and wave at the planes that dump water on fires and I got a call because someone thought a kid was up in Two Forks. I lied and just said it was Ned.": "Prawie ich przyłapali. Brian uwielbiał wchodzić na barierkę wieży \ni machać do samolotów zrzucających wodę na pożary. Zapytano \nmnie, czy jakiś dzieciak jest w Wieży na Rozdrożach. Skłamałam, \nże to Ned.",
  "If I ratted him out they would've been forced to leave and, I dunno, I guess I felt like I was saving him from whatever shitty life Ned was going to bring him back to.": "Gdybym go podkablowała, musieliby odejść, a ja nie chciałam, żeby Ned zaciągnął go z powrotem do tego beznadziejnego życia.",
  "Not that that ended up mattering.": "Ostatecznie i tak nie miało to znaczenia.",
  "Report in-progress decor": "Zgłoś niedokończone prace",
  "He was in the middle of really sprucing up the joint when they left.": "Nieźle odpicował to miejsce, zanim odeszli.",
  "Report comic book": "Zgłoś komiks",
  "He'd hide out here to read comics. \"The Black Band: His grief is his enemy's sorrow.\"": "Zaszywał się tutaj, żeby czytać komiksy. „Czarna Opaska: Jego żal jest smutkiem jego wroga”.",
  "Everyone this guy loves gets killed so he honors them with a black arm band; which gives him super powers.": "Każdy, kogo ten facet kochał, został zabity, więc na ich cześć nosił czarną opaskę na ramieniu. Dawała mu super moce.",
  "Well, that's fucking…dark.": "To cholernie... mroczne.",
  "Report electronic game machine": "Zgłoś grę elektroniczną",
  "There's a busted old toy out here. Some sort of electronic game.": "Jest tu jakaś zepsuta, stara zabawka. Jakaś elektroniczna gra.",
  "Yeah? I like Pong.": "Tak? Ja lubię Ponga.",
  "Everybody likes Pong.": "Wszyscy lubią Ponga.",
  "Report pillows": "Zgłoś poduszki",
  "He made the place pretty comfy, too.": "Wygodnie się tutaj urządził.",
  "That's an achievement.": "To już jakieś osiągnięcie.",
  "Yeah, at the expense of what are probably stolen pillows.": "Ta, do którego przyczyniły się prawdopodobnie skradzione poduszki.",
  "That little shit.": "Mały drań.",
  "Report radio schematic": "Zgłoś schemat radiowy",
  "There's a HAM radio schematic here. Something Brian was working on.": "Jest tutaj schemat amatorskiego radia. Coś, nad czym Brian pracował.",
  "Yeah, I think that was the one thing Ned did do with him. Tinkering on stuff like that.": "Myślę, że grzebanie w takich rzeczach było jedynym, co Ned robił razem z synem.",
  "Report nerdy document": "Zgłoś nerdowy dokument",
  "There's some grade-a dork contraband here.": "Jest tu jakaś kontrabanda mega nerda.",
  "You found his pocket protector?": "Znalazłeś jego kieszonkowy piórnik?",
  "I found a uh, I guess data sheet for a one \"Gladius Silva,\" half elf. Armor…seven.": "Znalazłem kartę postaci dla jakiegoś „Gladiusa Silvy”, półelfa. Zbroja... siedem.",
  "Classic Wizards & Wyverns.": "Klasyczni „Czarodzieje i Wiwerny”.",
  "Between this and that map I found in my tower, ol' Brian created quite the fantasy world.": "Sądząc po tym i mapie, którą znalazłem w wieży, Brian stworzył całkiem niezły świat fantasy.",
  "Report note to ranger": "Zgłoś notatkę do leśniczego",
  "He's got his dad's pitons in here. I think he stole them.": "Ma tutaj haki ojca. Chyba je ukradł.",
  "He also stole his dad's climbing equipment. His anchors.": "Ukradł też sprzęt wspinaczkowy ojca. Jego haki.",
  "Huh. Brian stole his dad's climbing gear. His anchors.": "Brian ukradł ojcu sprzęt wspinaczkowy. Jego haki.",
  "I actually need these to keep exploring the cave. It dead ends at a drop off with nowhere to hook in.": "W sumie to przydadzą mi się, żeby zbadać dalej jaskinię. Jest dość głęboka i nie ma gdzie zamocować liny.",
  "That's convenient.": "Wygodnie.",
  "Yeah it is.": "Owszem.",
  "Brian says he swiped these anchors from his dad.": "Brian pisze, że rąbnął te haki ojcu.",
  "Oh?": "Jak to?",
  "I think he was gonna hide them in a cache box or something and never got around to it. He left a note for a ranger to find them and send them to him back in Nebraska.": "Chyba chciał schować je w skrzynce, ale nigdy nie miał ku temu \nokazji. Zostawił notatkę leśniczemu, by je znalazł i odesłał\nz powrotem do Nebraski.",
  "Because he hated climbing?": "Bo nienawidził wspinaczki?",
  "Yeah. It sounds like Ned was pushing him and pretending to lose his anchors was the easiest way to put a stop to it.": "Wygląda na to, że Ned go przymuszał i najprościej było po prostu udać, że je zgubił.",
  "Ugh, I hope it worked. What an asshole.": "Mam nadzieję, że zadziałało. Co za dupek.",
  "Yeah. Man, that's the sort of thing that woulda caused me to catch a beating growing up.": "Za dzieciaka pewnie nieźle bym oberwał za coś takiego.",
  "I wouldn’t put it past ol’ Ned.": "Ned byłby do tego zdolny.",
  "Report bundle of pitons": "Zgłoś haki wspinaczkowe",
  "Oh my gosh. Brian has a bundle of anchors out here.": "Nieźle. Brian ma tutaj haki wspinaczkowe.",
  "I didn't think he was much of a sportsman. Or sports-boy.": "Nie sądziłem, że był takim sportowcem.",
  "Yeah, he's not.": "Bo nie był.",
  "He left a note with them.": "Zostawił przy nich notatkę.",
  "I'm gonna grab these anchors and be on my way.": "Wezmę te haki i ruszam dalej.",
  "And loop back around to the cave entrance?": "Wrócisz do wejścia jaskini?",
  "Yeah, I think so.": "Tak myślę.",
  "Report school folder": "Zgłoś szkolną teczkę",
  "I found an old school folder. Brian was a hell of a doodler.": "Znalazłem starą teczkę szkolną. Brian dużo bazgrał.",
  "Report postcard": "Zgłoś pocztówkę",
  "There's also a postcard here from Brian to, I guess his neighbor?": "Jest tu też pocztówka od Briana do jego sąsiada, jak sądzę.",
  "What's it say?": "Co jest tam napisane?",
  "That he's with his dad and sorry he can't mow his lawn this summer.": "Że jest z tatą i przykro mu, że tego lata nie będzie mógł skosić mu trawnika.",
  "Gosh.": "Boziu.",
  "Also he was worried his dad didn't know when school started. I'd say that's a lucky break if I were him.": "Martwił się też, że tata nie wie, kiedy zaczyna się szkoła. \nNa jego miejscu bym się cieszył.",
  "Yeah, that doesn't surprise me. Ned didn't really seem like a \"with it\" dad.": "Nie dziwi mnie to. Ned nigdy nie sprawiał wrażenia najlepszego ojca.",
  "Report science project writeup": "Zgłoś projekt naukowy",
  "Umm… Brian was doing a science fair project about bouncing radio waves off of a meteor shower.": "Brian robił projekt naukowy o falach radiowych odbijających się \nod deszczu meteorytów.",
  "Poor kid left his homework?": "Biedak zostawił swoje zadanie domowe?",
  "Yeah. He must've been pretty smart, huh?": "Tak. Musiał być całkiem mądry, co?",
  "Sharper than a lot of the grown-up knuckleheads I'm used to, yeah.": "Bystrzejszy niż większość dorosłych półgłówków jakich znam.",
  "Smarter than me?": "Mądrzejszy niż ja?",
  "Yeah, but not smarter than yours truly, right?": "Tak, ale nie mądrzejszy niż ja, no nie?",
  "Wait, are you seriously feeling threatened by the intelligence of a twelve year old you've never even met?": "Naprawdę czujesz się zagrożony inteligencją dwunastolatka, którego nigdy nie poznałeś?",
  "I'm just saying, I'm pretty, you know, with it. A pretty bright bulb.": "Tylko mówię. Jestem całkiem... no wiesz, bystry. Jarzę wszystko jak jarzeniówka.",
  "Yeah Henry, you're a regular Rhodes Scholar.": "Jasne, Henry, jesteś stypendystą z Oxfordu.",
  "Nice.": "Nieźle.",
  "Are you saying I'm a knucklehead?": "Mówisz, że jestem półgłówkiem?",
  "What, you're saying I'm one of those knuckleheads, is that it?": "Mówisz, że jestem jednym z półgłówków, tak?",
  "I wasn't, but now that I think about it…": "Nie, ale teraz jak o tym myślę...",
  "Because I know lots of stuff.": "Bo wiem całkiem sporo.",
  "Oh please, drown me in your surplus of knowledge.  I've been waiting all these years for a man as wise as you to take this job.": "Proszę, zalej mnie morzem wiedzy. Wszystkie te lata czekałam, \naż ktoś tak mądry jak ty weźmie tę robotę.",
  "Well that wait's over, sweetheart.": "Trochę przesadziłaś, ptaszyno.",
  "Uh, call me sweetheart again and you'll use that big sexy brain of yours to fill out your unemployment paperwork.": "Nazwij mnie ptaszyną raz jeszcze, a wykorzystasz swój seksowny mózg przy wypełnianiu papierów dla bezrobotnych.",
  "Sorry, boss.": "Wybacz, szefie.",
  "Report backpack retrieval plan": "Zgłoś plan odzyskania plecaka",
  "Remember that pack I found?": "Pamiętasz, jak znalazłem tamten plecak?",
  "Back on your second day? Yeah.": "Drugiego dnia? Tak.",
  "I found a plan Brian drew about he was gonna get it back.": "Brian narysował plan jego odzyskania.",
  "Oh, I'm sure it was quite elaborate.": "Na pewno jest bardzo szczegółowy.",
  "It's some \"Wile E. Coyote\" stuff, I'll tell you that much.": "Powiem tylko, że to coś w stylu Wilusia E. Kojota.",
  "So… something I never told you, or, uh, anyone about Brian.": "Jest coś, czego nikomu nie powiedziałam o Brianie.",
  "In regards to him being out here being against the rules.": "Że był tam wbrew zasadom."
}