{
  "I can't find that communications wire.": "Nie mogę znaleźć tego przewodu.",
  "Henry": "Henry",
  "Hey, I'm by that supply box near my tower.": "Jestem przy skrzynce niedaleko mojej wieży.",
  "Am I headed towards that communications wire?": "Idę w dobrą stronę do tego przewodu?",
  "Delilah": "Delilah",
  "Not quite. You want to go through Thunder Canyon.": "Nie do końca. Musisz przejść przez Kanion Grzmotu.",
  "And that is…?": "Czyli...",
  "The trail starts just north of your tower.  The one that was closed off but you managed to hike up last night.": "Szlak zaczyna się na północ od twojej wieży. To ta droga, która była zamknięta, ale zeszłej nocy nią szedłeś.",
  "Got it, thanks.": "Zrozumiałem, dzięki.",
  "I still can't find that communication wire.": "Ciągle nie mogę znaleźć tego przewodu.",
  "I’m back at my supply box. I still can’t seem to find the trail.": "Wróciłem do mojej skrzynki. Ciągle nie mogę znaleźć szlaku.",
  "You’re not far off. You just need to go back through Thunder Canyon.": "Jesteś niedaleko. Musisz tylko przejść przez Kanion Grzmotu.",
  "Right, which is…": "Jasne, czyli...",
  "It’s just north of your tower.": "Na północ od twojej wieży.",
  "Just north of my tower! I was gonna say that. Yes, yep. Already heading that way.": "No tak, na północ! Miałem to powiedzieć. Dobra, już tam idę.",
  "Still no sign of those kids.": "Ani śladu tych dzieciaków.",
  "Does anyone ever refill these things?": "Ktoś uzupełnia zapasy w tych skrzynkach?",
  "Excuse me?": "Słucham?",
  "I stumbled upon my local supply box again. Still no sign of those kids, though.": "Znowu trafiłem do mojej skrzynki z zapasami. Ale tych dzieciaków nie widać.",
  "I can't find that wire.": "Nie mogę znaleźć przewodu.",
  "Okay, I just came out of the cave and I see a supply box, but no wires to speak of.": "Dobra, wyszedłem z jaskini i widzę skrzynkę z zapasami, ale żadnych przewodów.",
  "It's okay, you're on the right track. There should be a trail to the north that crosses right under the wire.": "Dobrze, jesteś na właściwiej drodze. Powinien tam być szlak prowadzący na północ, wiedzie do samych przewodów.",
  "I still can't find that wire.": "Nadal nie mogę znaleźć tego przewodu.",
  "Hey, so this wire of yours…": "Ten cały przewód...",
  "…yesss?": "Tak?",
  "It should be easy to see, right? Like hanging from a telephone pole or something?": "Powinien być dobrze widoczny, prawda? Pewnie wisi na jakimś słupie czy coś?",
  "You got it, Hank.": "Dokładnie, Hank.",
  "Well, I'm back at that cache box by the cave and I'm still not seeing it.": "Jestem przy skrzynce obok jaskini i nadal nic nie widzę.",
  "Did you head north? Follow the trail north, northeast. And keep your eyes up!": "Poszedłeś na północ? Idź w tym kierunku, na północny wschód. Dobrze się rozglądaj!"
}