{
  "Call Delilah Back": "Odpowiedz Delilah",
  "Henry": "Henry",
  "Okay, I'm alright. I'm headed towards the site.": "Wszystko w porządku. Zmierzam w stronę ośrodka.",
  "Okay, I'm alright.": "Wszystko w porządku.",
  "Delilah": "Delilah",
  "Good. Keep your head up.": "Dobrze. Zachowaj czujność.",
  "I wish you would’ve told me about your wife, before.": "Żałuję, że nie opowiedziałeś mi wcześniej o swojej żonie.",
  "Well, I didn't. Sorry.": "Przepraszam za to.",
  "Well, I didn't.": "Czasu nie odwrócę.",
  "It’s something I wish I would’ve known about.": "To coś, o czym powinnam była wiedzieć.",
  "I don’t know what else to say.": "Nie wiem, co mógłbym dodać.",
  "Yeah, well. I just realized there’s probably a lot more I don’t know about you.": "Po prostu uświadomiłam sobie, że pewnie nie wiem o tobie jeszcze wielu rzeczy.",
  "I couldn’t muster what it took.": "Nie potrafiłem się zdobyć na odwagę.",
  "I couldn't.": "Nie byłem w stanie.",
  "I get it. I just wish I would’ve known.": "Rozumiem. Po prostu żałuję, że nie wiedziałam.",
  "I should’ve just stayed with her. Then I wouldn’t be in this mess.": "Powinienem był przy niej zostać. Uniknąłbym wtedy całego tego bagna.",
  "I should have stayed with her.": "Powinienem był przy niej zostać.",
  "No. Neither of us would be.": "Tak. Oboje byśmy go uniknęli.",
  "Yeah, I know.": "Tak, wiem.",
  "I know.": "Wiem.",
  "It’s fine. I might’ve just read things wrong. It’s fine.": "Mniejsza z tym. Widać źle odczytałam pewne sygnały.",
  "…": "...",
  "Look, you must be close by now. Let me know what you find.": "Zbliżasz się do celu. Powiadom mnie o tym, co tam znajdziesz."
}