{
  "Delilah": "Delilah",
  "Hey. Uh, I just thought of something not… not great.": "Hej. Właśnie wpadła mi do głowy... niewesoła myśl.",
  "Henry": "Henry",
  "What is it?": "O co chodzi?",
  "What did you just think of?": "Co masz przez to na myśli?",
  "I filed a report that said neither of us ever talked to or saw those girls; the ones that went missing a few weeks back.": "Napisałam w raporcie, że żadne z nas nie miało do czynienia \nz tymi dziewczynami, które zaginęły kilka tygodni wcześniej.",
  "What? Why would you do that? I told you to say the minimum and just keep it vague!": "Co? Dlaczego to zrobiłaś? Przecież ustaliliśmy, że dodasz zwięzłą notatkę!",
  "Why would you do that?": "Dlaczego to zrobiłaś?",
  "I know. And… I didn't. I just didn't want to be hassled.": "Wiem, ale... zmieniłam zdanie. Chciałam mieć święty spokój.",
  "Yeah, I told you to not to say anything. You agreed with me.": "Zaproponowałem, byśmy to przemilczeli. Przyznałaś mi rację.",
  "I told you to not say anything.": "Zaproponowałem, byśmy to przemilczeli.",
  "I know I did.": "Tak, wiem.",
  "Oh shit.": "O kurwa.",
  "My thoughts exactly.": "Lepiej bym tego nie ujęła.",
  "Our radios were tapped.": "Nasze krótkofalówki miały podsłuch.",
  "So? I'm sorry, I'm not following you.": "I? Wybacz, chyba nie nadążam.",
  "So what?": "I co z tego?",
  "Henry, our radios were tapped the entire time we talked about it. Maybe even your first day when you had the run in with them.": "Henry, nasze krótkofalówki miały założony podsłuch przez \ncały ten czas. Może nawet od pierwszego dnia, gdy wpadłeś \nna te dziewczyny.",
  "Ohhh. Oh no.": "O nie...",
  "Oh yes.": "O tak.",
  "And now someone probably has a transcript of that entire conversation.": "A teraz ktoś prawdopodobnie jest w posiadaniu pełnego zapisu tamtej rozmowy.",
  "And I've filed a report that's a blatant lie.": "A raport, który wypełniłam, jest stekiem kłamstw.",
  "And those girls are still missing.": "No i dziewczyny nadal się nie odnalazły.",
  "Yep.": "Ano.",
  "Fuck, Delilah.": "Kurwa, Delilah.",
  "Fuck.": "Ja pierdolę.",
  "Fuck, indeed.": "Mamy przejebane.",
  "We really need to get to the bottom of this.": "Naprawdę musimy dotrzeć do prawdy."
}