{
  "Henry": "Henry",
  "Hey, I heard some thunder.": "Właśnie słyszałem grzmot.",
  "Report thunder": "Zgłoś grzmot",
  "Delilah": "Delilah",
  "Yeah, I've got eyes on a storm out to the north.": "Potwierdzam, obserwuję nawałnicę na północy.",
  "That's bad, right?  Because of the lightning?": "To źle, tak? Błyskawice i w ogóle?",
  "It just means we'll be busy. Hurry home. And try not to get hit by lightning.": "To znaczy, że będzie robota. Wracaj prędko i niech cię nic nie trafi.",
  "I got hit by lightning when I was nine.": "Oberwałem piorunem, jak miałem dziewięć lat.",
  "I got hit by lighting when I was nine years old, so, I'm safe. It's not going to strike twice and all that.": "Oberwałem piorunem, jak miałem dziewięć lat, więc nic mi nie grozi. Piorun nie trafia dwa razy, czy jak to idzie.",
  "I'm not sure I have much of a choice.": "Nie wiem, czy mam jakiś wybór.",
  "I'm not sure I got a lot of choice in getting struck down.": "Nie wiem, czy mam jakiś wybór w tej kwestii.",
  "Well, there was an old lookout named Roy Sullivan who got hit by lightning seven times.": "Był taki starszy obserwator, Roy Sullivan, który dostał piorunem siedem razy.",
  "I don't like the sound of that.": "Nie pociesza mnie to.",
  "Yeah. Well, if it makes you feel better, it wasn't what killed him.": "Jeśli ma ci to pomóc, to wiedz, że to nie piorun go zabił.",
  "What killed him?": "To jak zginął?",
  "Suicide. Would you believe?": "Samobójstwo. Uwierzyłbyś?",
  "Especially not with your ELECTRIC personality.": "Zwłaszcza z twoją elektryzującą osobowością.",
  "Oof.": "Ech...",
  "I'm just going to let her have that one.": "Niech będzie, punkt dla niej.",
  "…": "...",
  "Ugggggggh.": "Uch!",
  "Uggggggh.": "Dość.",
  "I see my joke did not SPARK your sense of humor.": "Widać moje żarty nie są dla ciebie dość... błyskotliwe.",
  "What, you're not enjoying our CURRENT conversation?": "Co, nasza rozmowa nie robi na tobie... piorunującego wrażenia?",
  "OH MY GOD, LADY.": "O mój Boże, kobieto!",
  "Oh my god.": "O mój Boże.",
  "The… the ARC of our budding friendship?": "Przyjaźń spadła na nas... jak grom z jasnego nieba?",
  "They put the entire wilderness in the hands of an insane person. How exactly are you in charge?": "Powierzyli całą tę dzicz jakiejś szajbusce. Jakim cudem zrobiłaś \ntak błyskawiczną karierę?",
  "How are you in charge?": "Jak zrobiłaś tak błyskawiczną karierę?",
  "How exactly are you… in CHARGE?": "Jakim cudem zrobiłaś tak... błyskawiczną karierę?",
  "How are you in… CHARGE?": "Jak zrobiłaś tak... błyskawiczną karierę?",
  "Awww HENRY! That's a good one.": "Dobre, Henry!",
  "Are you satisfied?": "Zadowolona?",
  "Yes!": "Tak!",
  "Ah, CHARGE, Henry?": "„Błyskawiczną” karierę?",
  "Okay. I'm done responding to you. Bye.": "Dobra, kończę rozmowę. Pa.",
  "I'm done, bye!": "Kończę rozmowę, pa!",
  "Hmm, I see. DC. …AC/DC.": "Rozumiem... Obyło się bez spięć.",
  "I GOT IT.": "Załapałem!"
}