{
  "Delilah": "Delilah",
  "There's a storm headed your way. It won't rain. Just lightning and wind—which might make our jobs pretty eventful tomorrow.": "Burza zmierza w twoim kierunku. Nie ma deszczu, tylko wiatr i błyskawice... które z pewnością nie ułatwią nam jutro pracy.",
  "Henry": "Henry",
  "I'm in some canyon, trying to get back.": "Jestem w jakimś kanionie, próbuję wrócić.",
  "If it's the one I think it is, there should be an old trail the Forest Service closed off a couple years back.": "Jeśli jesteś tam, gdzie myślę, to trafisz na starą ścieżkę zamkniętą przed laty przez Służbę Leśną.",
  "Oh, it washed out and became a fucking death trap.": "Zmyło ścieżkę i teraz to zajebiście śmiertelna pułapka.",
  "So, you know, be careful.": "Także wiesz... bądź ostrożny.",
  "And I'm sure their reasons for closing it off had nothing to do with safety, right?": "Domyślam się, że zamknięcie ścieżki nie było związane \nz bezpieczeństwem, co nie?",
  "I'm down in this canyon.": "Jestem w kanionie.",
  "Hey! Just checking in.": "Tak tylko się melduję.",
  "I see a canyon. Can I get back through there?": "Widzę kanion. Mogę tędy wrócić do wieży?",
  "I see a canyon.": "Widzę kanion.",
  "Yeah, there should be a trail you can climb up at the end. Well, there used to be.": "Świetnie, powinna tam być ścieżka, którą wrócisz do góry. A przynajmniej kiedyś tam była.",
  "What do you mean \"used to be\"?": "Co masz na myśli, mówiąc, że „kiedyś tam była”?",
  "This is the canyon north of the lake?": "Czy ten kanion jest na północ od jeziora?",
  "Uh, sure? Yeah? I'm not a mariner.": "Tak, chyba? Nie jestem żeglarzem.",
  "You know what? I don't even want to know.": "Wiesz co? Chyba jednak nie chcę wiedzieć.",
  "I don't want to know.": "Chyba nie chcę wiedzieć.",
  "I've had more than my fair share of unmaintained trails today.": "Chyba wykorzystałem mój dzienny przydział niebezpiecznych szlaków.",
  "But they installed an elevator?": "Zainstalowali tam windę?",
  "Mm-hmm. Yeah, there's a little man in there who presses the buttons and everything. It's great!": "Tak. Siedzi tam taki mały facet, który naciska masę przycisków i innych wihajstrów. Świetna sprawa!",
  "Hey, I can see my tower!": "Widzę moją wieżę!",
  "I can see my tower.": "Widzę moją wieżę.",
  "Yeah, we experimented with hidden, underground towers for a while, but we weren't really happy with the results.": "Tak, eksperymentowaliśmy kiedyś z ukrytymi pod ziemią wieżami, ale efekty nie były zadowalające.",
  "You did not.": "Żartujesz sobie.",
  "No. Anyway, happy hiking!": "Oczywiście. Miłej wspinaczki!",
  "I'm with you all summer, huh? With whatever this sense of humor is?": "Mam spędzić z tobą całe lato, tak? I z tym twoim poczuciem humoru?",
  "We're together all summer?": "Mamy spędzić razem całe lato?",
  "Can you even believe? You're going to love it.": "Dasz wiarę? Jeszcze je pokochasz!",
  "Mm-hmm.": "Mhm.",
  "The sarcasm's not going to get old. Not at all.": "Sarkazm nigdy się nie zestarzeje. Nigdy.",
  "The sarcasm is not going to get old.": "Sarkazm nigdy się nie zestarzeje.",
  "Wait a minute. Was that sarcasm?": "Chwileczkę. Czy to był sarkazm?",
  "Shut up.": "Przymknij się.",
  "Where are you?": "Gdzie jesteś?",
  "Hey, I can see my tower. How do I get back?": "Widzę moją wieżę. Jak mogę do niej wrócić?",
  "How do I get up to my tower?": "Jak mogę wrócić do wieży?",
  "How do I get back?": "Jak mogę wrócić?",
  "I can see my tower from far away.": "Widzę z daleka moją wieżę.",
  "What are these powerlines doing out here to the North?": "Co te linie telefoniczne robią tu, na północy?",
  "Report utility pole": "Zgłoś słup telefoniczny",
  "Those are comms lines. They connect folks like me to central command.": "To przewody komunikacyjne. Łączą takich ludzi jak ja z centralą.",
  "Got it.": "Jasne.",
  "AND if you can see them that means you turned north at the cave and far away from Two Forks. You should head back.": "Jeśli je widzisz, to znaczy, że odbiłeś przy jaskini na północ, z dala od Wieży na Rozdrożach. Powinieneś zawrócić."
}