{
  "Henry": "Henry",
  "I'm down in Thunder Canyon.": "Jestem w Kanionie Grzmotu.",
  "I'm down in that canyon again.": "Wróciłem do kanionu.",
  "I'm still can't see the smoke plume from here in the canyon.": "Z tego miejsca nie widzę smugi dymu.",
  "Delilah": "Delilah",
  "Trust me, I'm looking due south at it now.": "Zaufaj mi, patrzę na południe i mam go przed oczami.",
  "And take my advice: follow the canyon past the lake, past that rock outcropping down there, and keep your eyes out for a climb that will take you south.": "Skorzystaj z mojej rady. Idź kanionem, miń jezioro, masywy skalne i rozglądaj się za miejscem do wspinaczki, którym przejdziesz na południe.",
  "Alright, I'll keep looking.": "Dobra, będę się rozglądał.",
  "I'm not seeing that smoke anymore.": "Nie widzę już dymu.",
  "Oh, it's still burning away. Try heading west from where you are.": "Nadal się tam pali. Spróbuj iść na zachód.",
  "If you loop past the lake there should be a trail that'll take you further south.": "Jak miniesz jezioro, powinieneś trafić na szlak, którym pójdziesz dalej na południe.",
  "Thanks, that helps.": "Dzięki za pomoc.",
  "Hmm, I can't see to find a way north. I'm back in the canyon.": "Nie mogę znaleźć drogi na północ. Wróciłem do kanionu.",
  "I'm not sure how to get north.": "Nie wiem, jak pójść dalej na północ.",
  "You made it down through the cave already though, right?": "Ale jaskinią już przeszedłeś, prawda?",
  "Yes.": "Tak.",
  "Good. Find your way back to the supply box there, then about-face and head straight north looking for the trail.": "Dobrze. Teraz poszukaj tamtej skrzynki z zapasami, stamtąd idź \nna północ i rozglądaj się za szlakiem.",
  "If you're ever unsure, don't forget to check your compass.": "Jeśli nie jesteś pewien drogi, sprawdzaj kompas.",
  "Roger.": "Przyjąłem.",
  "So I hung a left out of the cave and I'm passing through Thunder Canyon now.": "Wyszedłem z jaskini i idę właśnie Kanionem Grzmotu.",
  "Where should I go from Thunder Canyon?": "Gdzie mam iść z Kanionu Grzmotu?",
  "So I hung a left out of the cave and I'm passing through that canyon now.": "Wyszedłem z jaskini i idę właśnie kanionem.",
  "Where should I go from the canyon?": "Gdzie mam iść z kanionu?",
  "I'm not seeing any wires in here.": "Nie widzę tu żadnych przewodów.",
  "Oh no no no. Sounds like you turned east towards Jonesy Lake. From the cave, you just want come out and go straight, to the north.": "Nie, nie. Chyba poszedłeś na wschód, w kierunku jeziora Jonesy. \nZ jaskini powinieneś kierować się prosto na północ.",
  "Got it.": "Jasne."
}