{
  "Henry": "Henry",
  "What's in this cave down here?": "Co jest w tej jaskini?",
  "What's in this cave?": "Co jest w tej jaskini?",
  "It looks like the path leads through the cave.": "Wygląda na to, że ścieżka prowadzi przez jaskinię.",
  "It's alright to hike through here?": "Można tędy przejść?",
  "Delilah": "Delilah",
  "Back in the cave, huh? Man, I don't need to lose another lookout in there.": "Znowu w jaskini, co? Nie chcę tam stracić kolejnego obserwatora.",
  "ANOTHER lookout?": "Kolejnego obserwatora?",
  "They go in, they never come out.": "Wchodzą, a potem nigdy nie wracają...",
  "Oh, this is another one of your jokes.": "No tak, kolejny dowcip.",
  "Yeah, it is.": "Dokładnie ta.",
  "In Thunder Canyon?": "W Kanionie Grzmotu?",
  "THUNDER Canyon?": "Kanionie Grzmotu?!",
  "Hey, I didn't name it.": "Ej, nie ja to wymyśliłam.",
  "But in the cave? I don't know, rocks. NFS tells people not to go too far in there. It's pretty dangerous.": "Może skały? Narodowa Służba Leśna odradza zapuszczanie się tam. To niebezpieczne.",
  "So…": "Więc...",
  "Sooo I say, fuck it. You're a grown man. You can go where you want.": "Więc... pieprzyć to. Jesteś dorosły. Możesz iść, gdzie tylko chcesz.",
  "Great. I used to go caving with someone back in Colorado. She loved it. Might be great to explore it sometime this summer.": "Świetnie. Chodziłem razem ze znajomą po jaskiniach w Kolorado. Kochała to. Można byłoby ją zwiedzić tego lata.",
  "That could be fun. Obviously, be VERY careful.": "Brzmi fajnie. Pamiętaj, bądź bardzo ostrożny.",
  "It doesn't seem that danger—whoooooaaaaaa! Ahh, nooo!": "Nie wydaje się być aż tak niebezp... O nie!",
  "Ahh! Danger!!": "Uwaga!",
  "HENRY!": "Henry!",
  "Seriously, it's completely fine in here.": "A tak serio, to nic mi nie jest.",
  "Goddamnit.": "Cholera.",
  "This cave is gated off.": "Wejście do jaskini jest zamknięte.",
  "Report locked gate": "Zgłoś zamkniętą bramkę",
  "It's to stop spelunkers from dying without getting the keys from the Forest Service office first.": "Jest zamknięte, żeby grotołazy nie ginęły w jaskini, \nzanim nie otrzymają kluczy od Służby Leśnej.",
  "Makes sense.": "Ma to sens.",
  "Although Debbie says she lost them like three years ago, so, maybe its mysteries are locked away for good.": "Chociaż Debbie mówi, że zgubiła je jakieś trzy lata temu, \nwięc może tajemnice tej jaskini pozostaną niezbadane.",
  "Aw, that's too bad. I used to go caving in Colorado a lot with someone. Would be really nice to pick that back up.": "Szkoda... Chodziłem razem ze znajomą po jaskiniach w Kolorado. Byłoby miło do tego wrócić.",
  "Fond memories, huh?": "Miłe wspomnienia?",
  "Big time.  I'll keep an eye out for those keys.": "Nawet bardzo. Będę się rozglądał za tymi kluczami.",
  "Don't hold your breath.": "Tylko się nie napalaj.",
  "Ah, damn.": "Szkoda.",
  "Yeah, but maybe you can find another one to get your caving kicks in.": "No, ale może znajdziesz inną, która pozwoli ci się spełnić.",
  "This one's so close to home and convenient though.": "Ale ta jest tak blisko mojej wieży...",
  "Aww, sorry Hank.": "Jakże mi przykro, Hank.",
  "Helloooooo!": "Halo!",
  "Play with the cave's echo": "Wywołaj echo w jaskini",
  "Hmm.  I bless the rains down in AFFFRICAAAA!": "Niech w Afryce spadnie deszcz!",
  "Play with the echo again": "Ponownie wywołaj echo w jaskini",
  "[howls like a wolf]": "Auu!",
  "Play with the echo one more time": "Wywołaj echo w jaskini raz jeszcze"
}