{
  "Cottonwood Creek": "Dolina Topoli",
  "Henry": "Henry",
  "I'm here. I'm at Cottonwood Creek.": "Jestem tutaj, w Dolinie Topoli.",
  "Report location": "Zgłoś swoją lokalizację",
  "Delilah": "Delilah",
  "You see the cache box there?": "Widzisz w pobliżu skrzynkę?",
  "I just checked it and the code doesn't work.": "Właśnie sprawdziłem. Szyfr nie działa.",
  "That's because I changed it.": "Bo go zmieniłam.",
  "Yeah, I see it.": "Tak, widzę ją.",
  "Okay, I changed the code and left you something.": "Zmieniłam szyfr i coś ci zostawiłam.",
  "What's the new code?": "Jaki jest nowy szyfr?",
  "It must be around here somewhere.": "Musi gdzieś tu być.",
  "It is. Find it and open it. I changed the code.": "I jest. Znajdź ją i otwórz. Zmieniłam szyfr.",
  "It's “5-6-7-8.”": "Teraz to: 5-6-7-8.",
  "Are you kidding me?": "Jaja sobie robisz?",
  "Are you joking?": "Żartujesz?",
  "I was in a rush!": "Spieszyło mi się!",
  "I think I found that cache box, the one from before.  Where you said you left me the radio.": "Chyba znalazłem skrzynkę. Tę samą, co poprzednio, gdzie czekała na mnie krótkofalówka.",
  "Report cache box": "Zgłoś skrzynkę",
  "And?": "I?",
  "It’s empty.": "Nic tu nie ma.",
  "Well it wasn’t. Sorry, Hank.": "Wcześniej była pełna. Wybacz, Hank.",
  "Okay, found the cachebox.": "Okej, widzę skrzynkę.",
  "Great, open it.": "Dobra, teraz ją otwórz.",
  "There's a cachebox here.": "Widzę tu jakąś skrzynkę.",
  "Yes there is, but I changed the code and left you something in it.": "Tak, ale zmieniłam szyfr i coś ci tam zostawiłam.",
  "Really!": "Serio?",
  "Hey, I'm here and found a cachebox that does not open with \"1-2-3-4.\"": "Jestem na miejscu i znalazłem skrzynkę, ale szyfr „1-2-3-4” nie działa.",
  "What did you change it to, again? I'm blanking.": "Możesz powtórzyć nowy szyfr? Zdążyłem zapomnieć.",
  "What was the code again?": "Możesz powtórzyć ten szyfr?",
  "Seriously?": "Serio?",
  "It's nerve-wracking out here.": "To miejsce szarga mi nerwy.",
  "It's “5-6-7-8.” Which you can also attribute to wracked nerves.": "Szyfr to 5-6-7-8. Tak, to też wina nerwów.",
  "Hey, there's a different walkie-talkie in here.": "Widzę tu inne walkie-talkie.",
  "There's a walkie-talkie here.": "Widzę tu walkie-talkie.",
  "God dammit, Henry!": "Do diabła, Henry!",
  "Oh, THIS is what you left me.": "Czyli to mi zostawiłaś...",
  "Yeah, and I was really hoping to keep it a secret.": "Tak. Chciałam to utrzymać w tajemnicy.",
  "Take it… and chuck the other one. And call me.": "Weź je i wyrzuć to drugie. Potem się odezwij.",
  "I found what you left me.": "Znalazłem to, co mi zostawiłaś.",
  "Good. Call me back with— when you have it.": "Dobrze. Odezwij się, używając... jak już to weźmiesz."
}