{
  "Henry": "Henry",
  "There's some guy out here.": "Jest tu jakiś gość.",
  "Report some guy": "Zgłoś tajemniczą postać",
  "Delilah": "Delilah",
  "The creeps?": "Gęsią skórkę?",
  "There's some guy out here giving me the creeps.": "Jest tu jakiś gość i przyprawia mnie o gęsią skórkę.",
  "Report creepy guy": "Zgłoś dziwną postać",
  "Look, bumping into someone in the middle of nowhere is part of the fun.": "Wpadanie na kogoś w kompletnej głuszy to część zabawy.",
  "Yeah yeah, okay, I get it.": "Dobra, dobra, łapię.",
  "The whole thing. And people come and go as they please. It's… it's madness!": "Cały teren. Ludzie pojawiają się i znikają bez zapowiedzi. \nIstne szaleństwo!",
  "Come on.": "No weź...",
  "It's outside.": "Jest na powietrzu.",
  "What is it?…": "O co chodzi?",
  "Henry, there's something I… something someone should've told you about this area.": "Henry, jest coś, co powinnam... co ktoś powinien był ci powiedzieć wcześniej o tym miejscu.",
  "I… I don't think so?": "Raczej nie...",
  "Wait. He's looking at you? Is he doing anything else?": "Czekaj. Obserwuje cię? Robi coś jeszcze?",
  "Being some guy?": "Po prostu stał?",
  "Creeping?": "Czaił się?",
  "Some guy?": "Jakiś gość?",
  "Yeah, I came out of this cave in a canyon and he was just—": "No, wyszedłem z tej jaskini w kanionie, a on tam..."
}