{
  "Delilah": "Delilah",
  "You see that plane?": "Widzisz ten samolot?",
  "Henry": "Henry",
  "Hard to miss.": "Ciężko go przegapić.",
  "No, I was just busy packing up.": "Nie, skupiłem się na pakowaniu.",
  "There's going to be a lot more. The service says this thing is 2% contained.": "Przyleci ich jeszcze więcej. Według raportów póki co okiełznali zaledwie 2%.",
  "Is this The Big Fire, or the site fire, or…?": "Mowa o Wielkim Pożarze czy pożarze w ośrodku badawczym?",
  "Is this the Flapjack fire or the site fire or?": "Mowa o Pożarze Ciapciaka czy ośrodku badawczym?",
  "Is this the June fire or the site fire or?": "Mowa o Czerwcowym Pożarze czy ośrodku badawczym?",
  "Is this the Elk fire or the site fire or?": "Mowa o Pożarze Wapiti czy ośrodku badawczym?",
  "The two fires merged into one unmitigated disaster. They're renaming it after my lookout.": "Oba pożary scaliły się, tworząc katastrofalną w skutkach pożogę. Chcą ją ochrzcić na cześć mojej wieży.",
  "You about packed up?": "Kończysz się już pakować?",
  "Shouldn't we talk for a sec? You know, about… things?": "Nie powinniśmy chwilę pogadać? No wiesz, o... tym?",
  "About what?": "Czym?",
  "About how all this stuff is connected… the surveillance, the Goodwins, Brian's death.": "O tym, że elementy układanki zdają się łączyć... podsłuch, Goodwinowie, śmierć Briana.",
  "About how this is all connected.": "O tym, że elementy układanki się łączą.",
  "I don't know what to say… it's like the universe cooked up the cruelest thing to have happen. Does it connect to everything else? I don't know. I don't know if I even want to.": "Nie wiem, co odpowiedzieć... Zdaje się, że wszechświat zwrócił się przeciwko nam. Czy to się w jakiś sposób łączy? Nie mam pojęcia. Nie wiem nawet, czy chcę to wiedzieć.",
  "Of course you do. There's got to be a reason.": "Oczywiście, że chcesz. To nie dzieje się bez powodu.",
  "Does there?": "Jesteś pewien?",
  "Maybe… maybe not. I wouldn't even know where to begin.": "Sam nie wiem. Nie miałbym pojęcia, od czego zacząć poszukiwania.",
  "Well, fuck. For starters I guess you could find the source of that signal.": "Kurwa... Myślę, że na dobry początek możesz znaleźć źródło tego sygnału.",
  "We still don't know who was listening to us, who was following me around, who made that tape.": "Wciąż nie mamy pojęcia, kto nas podsłuchiwał, śledził mnie \ni podrzucił tę kasetę.",
  "About who was surveilling us.": "O naszym podsłuchiwaczu.",
  "All we have is the body of a dead boy who did nothing wrong.": "Odkryliśmy jedynie ciało chłopca, który niczemu nie zawinił.",
  "But maybe we can still find these people?": "Ale może jest jeszcze szansa na odnalezienie tych ludzi?",
  "Look, I think whoever is out there caused the site fire to cover their tracks. And I'm almost certain that when I get off the helicopter I'm going to be led into a room and made to listen to a tape of me saying we started it.": "Słuchaj, ktokolwiek za tym stoi, wywołał pożar lasu, by zatrzeć \npo sobie ślady. A ja jestem niemal pewna, że gdy tylko wysiądę \nz helikoptera, aresztują mnie i zmuszą do wysłuchania nagrania, \nw którym przyznaję się do winy.",
  "And we don't know shit. What can I do?": "A my gówno wiemy. Co mogę zrobić?",
  "Well, THERE's something for you to do. Holy shit.": "Najwyraźniej jest jedna rzecz... Jasny gwint.",
  "About what happened to Brian.": "O tym, co spotkało Briana.",
  "What, you going to tell me it was my fault again?": "Co, chcesz mnie o to obwinić po raz kolejny?",
  "No, come on…": "Nie, no coś ty...",
  "I don't have much to say. I'm fine. I'm sad. I'm whatever.": "Nie mam wiele do dodania. Czuję się dobrze. Smutna. \nWszystko mi jedno.",
  "I keep thinking about him down there, and I just want to get far away from here.": "Wciąż o nim myślę, jak tam leży... i mam ochotę wynieść się \njak najdalej stąd.",
  "What can I do?": "Co mogę zrobić?",
  "We have to just wait for the helicopters.": "Musimy zaczekać na śmigłowce.",
  "Okay.": "Dobrze...",
  "Until then you could follow that signal. Maybe.": "Do tego czasu możesz podążyć za tym sygnałem.",
  "Believe it or not, I'm… out of things to say.": "Wierz lub nie, ale... nie mam nic do powiedzenia.",
  "Hey. Hey… do you hear that?": "Hej... słyszysz to?",
  "Yeah. Jesus. Beep beep.": "Jezu. Wykryło coś.",
  "So, what do we do?": "To co robimy?",
  "I think you follow it, Henry.": "Idź za sygnałem, Henry.",
  "I'm sorry, I don't mean to be a bitch.": "Przepraszam, nie chcę wyjść na sukę.",
  "He's dead and I… I don't know. Maybe I'm not thinking straight.": "On nie żyje, a ja... sama nie wiem. Chyba mam mętlik w głowie.",
  "Holy crap, yeah. Oh my God.": "Jasny gwint, tak. O mój Boże...",
  "We don't know what it is. It could be nothing.": "Nie wiemy, dokąd prowadzi. Może to ślepy zaułek.",
  "It could also be whoever was listening to us. Whoever made the tape.": "A może wiedzie do osoby, która nas podsłuchiwała i spreparowała tę kasetę.",
  "Okay. Yeah. You should pack up everything you need in case we get the call and you can't come back.": "No tak. Powinieneś spakować cały potrzebny sprzęt, w razie gdyby nas wezwali, odcinając ci możliwość powrotu.",
  "Alright look, if something happens…": "Dobra, słuchaj. Jeśli coś mi się stanie...",
  "I'll remember you.": "Nie zapomnę cię.",
  "Am I walking into a trap right now?": "Czy zmierzam właśnie do paszczy lwa?",
  "Could this be a trap?": "Myślisz, że to pułapka?",
  "I hope not. I'd rather remember you from a bar somewhere and not a jail cell.  Please find who made that tape.": "Oby nie. Wolę wspominać cię w jakimś barze, nie zza krat. \nProszę, postaraj się znaleźć twórcę tej kasety.",
  "Oh, well that's nice.": "Miło z twojej strony.",
  "Well, that's nice.": "Miło to słyszeć.",
  "I was hoping you'd have a backup plan or something": "Liczyłem raczej, że masz w zanadrzu plan B, czy coś.",
  "I was hoping you'd have a plan.": "Liczyłem, że masz jakiś plan.",
  "Yeah um, okay. I'm probably going to move to Canada. Ontario, maybe.": "Tak, jasne. Prawdopodobnie przeprowadzę się do Kanady. \nMoże do Ontario.",
  "No, I meant if something happens to me.": "Nie. Chciałem wiedzieć, co zrobisz, gdyby coś mi się stało.",
  "Right. If you don't find out who made that tape and I have to hit the road.": "Racja. W razie gdybyś nie odnalazł twórcy kasety i musiałabym nawiać.",
  "Forget it.": "Mniejsza z tym.",
  "Be safe, Henry.": "Uważaj na siebie, Henry.",
  "Is this the Big fire or the site for or?": "Mowa o Wielkim Pożarze czy ośrodku badawczym?"
}