{
  "Henry": "Henry",
  "Do you see anything from yours? You know, like, clues as to where they could be?": "Widzisz coś ze swojej wieży? No wiesz, jakieś wskazówki, które pomogą nam je namierzyć?",
  "Can you see any clues from your lookout?": "Widzisz jakieś wskazówki ze swojej wieży?",
  "Delilah": "Delilah",
  "Haha, clues.  I really like your enthusiasm for mystery.": "Wskazówki... Podoba mi się twoje detektywistyczne zacięcie.",
  "I'm just doing my job.": "Po prostu robię swoje.",
  "I like it, I do! I just can't wait for you to give these girls a piece of your— our— mind. Minds! Collective.": "Uwielbiam to, naprawdę! Nie mogę się doczekać, aż przekażesz \ntym dziewczynom, co o nich myślisz. A raczej myślimy!",
  "But no, no clues. I can't see anything from here.": "Niestety, żadnych wskazówek. Stąd nic nie widać.",
  "Can you see the communication wires from where you are?": "Widzisz stamtąd przewody?",
  "Can you see the wire?": "Widzisz ten przewód?",
  "I can see the poles but I have no idea if they wire is in good shape or not.": "Widzę słupy, ale nie mam pojęcia, w jakim stanie są przewody.",
  "They run a good distance up to a spot called Beartooth point. You just need to walk along them all the way up there and make sure everything is in ship shape.": "Ciągną się do miejsca zwanego Niedźwiedzim Kłem. Musisz się tam dostać i sprawdzić, czy wszystko z nimi gra.",
  "You wake up pretty early then, huh?": "Wstałaś dziś dość wcześnie, co?",
  "You wake up pretty early.": "Wstałaś dość wcześnie.",
  "As soon as the sun comes up.  The Forest Service really frowns on us putting up curtains for some reason.": "Wraz ze wschodem słońca. Służba Leśna krzywo na nas patrzy, \njak zasłaniamy okna.",
  "I'll get used to it. I've been a bit of a night-owl for a long time, now.": "Przyzwyczaję się. Długi czas byłem nocnym markiem.",
  "I'll get used to it.": "Przyzwyczaję się.",
  "Oh, it's fine!  Fires don't start til 11am or so.": "Spoko. Pożary nie zdarzają się przed 11 rano.",
  "Seriously?": "Serio?",
  "No. Good Lord…": "Nie, na Boga!",
  "I thought maybe it was one of those things like how earthquakes only happen at sunrise and sunset.": "Myślałem, że to tak jak z trzęsieniami ziemi, że zdarzają się \ntylko rano i na wieczór.",
  "That's not true either, Henry.": "To także bzdura, Henry.",
  "Geez, we're really letting anyone in these days.": "Kurczę, widać przyjmujemy ostatnio kogo popadnie.",
  "Yeah, I just kinda covered my head with my pillow. Seems to do the trick.": "Ja po prostu zakryłem głowę poduszką. Daje radę.",
  "I covered my head with my pillow.": "Ja zakryłem głowę poduszką.",
  "Wow, the forest could never burn down on your watch.": "Na twojej warcie żaden las by nie spłonął!",
  "Hey, I can see your tower, I suppose that means you can see me.": "Widzę twoją wieżę. Czyli ty pewnie też możesz zobaczyć mnie.",
  "Can you see me?": "Widzisz mnie?",
  "Yeah, well enough.": "Tak, dość dobrze.",
  "You're in your tower.": "Jesteś w swojej wieży.",
  "That I am.": "Ano.",
  "Also, you need a new barber.": "Przydałaby ci się wizyta u fryzjera.",
  "Jeez, do you have the Hubble telescope over there?": "Matko, co ty tam masz za sprzęt, teleskop Hubble'a?",
  "I'm just kidding. You're just a little blob to me.": "Zbijam się. Z tej odległości jesteś jak mrówka.",
  "You're at the canyon, wearing the orange backpack, I presume.": "Jesteś w kanionie, masz, z tego co widzę, pomarańczowy plecak.",
  "Yep, that's me.": "Tak, to ja.",
  "Hey, is that you way over there?": "Hej, to ty tam stoisz?",
  "Is that you over there?": "To ty tam stoisz?",
  "Yep. That's me. Hi.": "Tak, to ja. Cześć.",
  "You're not that far away.": "Nie jesteś tak daleko.",
  "Your tower is pretty close to mine.": "Twoja wieża jest dość blisko mojej.",
  "What do you mean?": "Co masz na myśli?",
  "I'm looking at your tower.": "Patrzę teraz na twoją wieżę.",
  "Yep, just a hop, skip and a big-ass jump over a jagged ravine.": "To tylko jeden krok w siedmiomilowych butach przez jar.",
  "I can see your tower from over here.": "Widzę stąd twoją wieżę.",
  "I can see your lookout.": "Widzę twoją wieżę.",
  "Yeah, hello. Now why don't you use those same skills to identify your firefinder.": "Czołem. To może teraz w ten sam sposób namierzysz swój kierunkomierz?",
  "Hey, I can see your tower.": "Hej, widzę twoją wieżę.",
  "Yep, great. I'm north of you, these fireworks are west of you.": "Super. Jestem na północ od ciebie. Fajerwerki są na zachód.",
  "Your lights are on.": "Masz zapalone światło.",
  "Hey, you keep your lights on at night?": "Zostawiasz zapalone światło na całą noc?",
  "I'm doing a crossword puzzle.  I do… a lot of crossword puzzles.": "Rozwiązuję krzyżówkę... dużo krzyżówek.",
  "Hey— someone broke into my tower.": "Ktoś się włamał do mojej wieży.",
  "Someone broke in.": "Ktoś się włamał.",
  "Did you see anyone from over there?": "Widziałaś kogoś?",
  "Did you see anyone?": "Widziałaś kogoś?",
  "No, I didn't—": "Nie, nikogo...",
  "I was, you know.": "Byłam zajęta, wiesz...",
  "Doing the crossword.": "Rozwiązywaniem krzyżówki.",
  "Yeah.": "Ta."
}