{
  "Delilah": "Delilah",
  "Heyo. I don't think so. Why, have you?": "Czołem. Raczej nie, a ty?",
  "Okay. Good.": "Dobra, dzięki.",
  "No, I don't think he has any idea.": "Nie, raczej o tym nie wie.",
  "I'm absolutely sure.": "Jestem pewna.",
  "Would you?": "Ty byś tak zrobiła?",
  "Alright. I'll let you know if anything changes in that regard.": "Dobrze. Dam znać, jak coś się w tej sprawie zmieni.",
  "Hey, sorry about that.": "Przepraszam za to.",
  "Anyway, Bucket's a cute name. You, uh, you owned him with someone?": "Biszkopt to urocze imię. Z kimś jeszcze go miałeś?",
  "Anyway, if there's anyone or anything you want to talk about, fire away.": "Jeśli chcesz o czymś, albo o kimś, pogadać, wal śmiało.",
  "Talk about Julia": "Opowiedz o Julii.",
  "Henry": "Henry",
  "That would be my wife, Julia.": "Z moją żoną, Julią.",
  "Uh, we can talk about my wife, Julia.": "Możemy porozmawiać o mojej żonie, Julii.",
  "Oh. Like, your wife? Or, like, \"she's taking half my stuff,\" wife?": "To prawdziwa żona, czy raczej taka, z którą podzieliłeś się majątkiem?",
  "My wife.": "Prawdziwa.",
  "But you're here.": "Ale ty jesteś tu...",
  "She's sick. And I shouldn't be here, but I am.": "Jest chora, a mnie nie powinno tu być. No ale jestem.",
  "She's sick and I shouldn't be here.": "Jest chora, a mnie nie powinno tu być.",
  "I… I'm sorry, Henry.  What is it?": "Przykro mi, Henry. Na co jest chora?",
  "We'll get into it.": "Dojdziemy do tego.",
  "Okay. Well, in the meantime you are here, and it's beautiful, and escaping isn't always something bad.": "Dobra. Póki co jesteś tutaj, jest świetnie, a ucieczka nie zawsze jest czymś złym.",
  "Yeah. Sure.": "No...",
  "Look, I gotta go do a thing but I'll have a radio, okay? Call me if you need to.": "Słuchaj, muszę się czymś zająć, ale będę miała krótkofalówkę. \nW razie czego, odezwij się.",
  "It's not really your business.": "W sumie to nie twoja sprawa.",
  "It's not your business.": "To nie twoja sprawa.",
  "I'm sorry, but you're the one who brought her up.": "Wybacz, ale to ty o niej wspomniałeś.",
  "Yeah, well you ask a lot of fucking questions, you know that?": "A ty zadajesz w chuj pytań, wiesz?",
  "You ask a lot of fucking questions, you know that?": "Sama zadajesz w chuj pytań, wiesz?",
  "Would you rather we just don't get to know each other?": "Wolałbyś, żebyśmy nic o sobie nie wiedzieli?",
  "No.": "Nie.",
  "Then don't swear at me.": "No to mi tu nie klnij.",
  "Then please don't be so nosy.": "To nie bądź taka wścibska.",
  "Or maybe I'm just being nice. God, your wife must be a saint to put up with such a fucking asshole.": "A może jestem zwyczajnie miła? Boże, twoja żona ma anielską cierpliwość, żeby wytrzymać z takim dupkiem.",
  "I'm going to go do something. I'll have a radio if you need anything or, better, if you decide to chill out.": "Muszę się czymś zająć. Ale jakbyś czegoś potrzebował albo jak już wyluzujesz, odezwij się.",
  "Sorry, you're right.": "Przepraszam, masz rację.",
  "Yeah. I did. Sorry.": "Prawda. Przepraszam.",
  "Whatever. It's fine.": "Dobra, to nic takiego.",
  "Look, I gotta go do a thing downstairs. Um… I'll bring a radio, though.": "Słuchaj, muszę się czymś zająć, ale będę mieć ze sobą krótkofalówkę.",
  "Everything's fine. Just, you know, taking some time apart. Getting some fresh air.": "Wszystko gra. Po prostu potrzebowałem tej rozłąki. \nOdetchnięcia świeżym powietrzem.",
  "Everything's fine.": "Wszystko gra.",
  "A little change.": "Małej odmiany.",
  "Yeah, like I said.": "Tak jak mówiłem.",
  "Yeah.": "No...",
  "Alright. Well, we can just leave it at that.": "Dobra, możemy na tym poprzestać.",
  "Thanks.": "Dzięki.",
  "Ask about that call.": "Zapytaj o jej rozmowę.",
  "Who was that?": "Kto to był?",
  "Who was who?": "Ale kto?",
  "\"I don't think he has any idea.\" What was that? Were you talking about me?": "„Raczej o tym nie wie”. O co chodziło, mówiłaś o mnie?",
  "Uh, what?": "Że co?",
  "You left your button pressed or something.": "Musiałaś zostawić wciśnięty guzik.",
  "Henry, that call was work. I was just talking to… actually, it's not really your business. Why are you freaking out?": "Henry, to moja praca. Rozmawiałam z... właściwie to nie twoja sprawa. Co ci tak odwala?",
  "I'm not freaking out.": "Nie odwala mi.",
  "Good. I'm gonna go quiet for a little bit. Call me if it's important.": "To dobrze. Pozwól, że się wyciszę. Odezwij się, gdyby działo się \ncoś ważnego.",
  "Delilah stepped away": "Delilah się rozłączyła",
  "She's annoyed.": "Jest poirytowana.",
  "She was annoyed.": "Była poirytowana.",
  "She walked away for a moment.": "Tymczasowo się rozłączyła.",
  "Anyway, I thought about it and that story IS cute. And um—sorry, but you said \"we\"? You owned him with someone?": "Myślałam o tym i to bardzo słodka historia. Ale mówiłeś w liczbie mnogiej, z kimś jeszcze go miałeś?",
  "Anyway. Uh, Julia. Girlfriend? Ex? Sorry, I don't mean to pry.": "Julia to twoja dziewczyna? Była? Wybacz, nie chcę być wścibska.",
  "Anyway, I empathize with the DUI thing. Did your, um, girlfriend get mad? Or whoever? You said \"we\" used to go to the bar. Ugh, sorry. I'm the most awkward woman on earth.": "Co do odebrania prawa jazdy, to doskonale cię rozumiem. Twoja... dziewczyna się wkurzyła? Czy partnerka? Mówiłeś, że „chodziliście” do baru. Kurczę, wybacz. Jestem najdziwniejszą kobietą na Ziemi.",
  "Anyway, The Dollar! The Dollar's a great bar. Did your, uh, girlfriend like it too?": "„The Dollar”! To świetny bar. Twoja dziewczyna też go lubiła?",
  "Well, looks like I might've lost you. You could be down in one of those valleys? Call me if you need anything.": "Chyba straciłeś zasięg. Może zszedłeś do jakiejś doliny. Odezwij się, jakbyś czegoś potrzebował.",
  "Talk about Julia.": "Opowiedz o Julii.",
  "Call out": "Odezwij się",
  "Listen": "Słuchaj",
  "Sure, I'm just going to keep hiking and hoping it warms up.": "Jasne, będę szedł przed siebie z nadzieją, że się ociepli."
}