{
  "Henry": "Henry",
  "Oh, God— it's a nightmare out there!": "Boże, to jakiś koszmar!",
  "Hello?": "Halo?",
  "Delilah!": "Delilah!",
  "Hello? Is anybody there?": "Halo? Jest tam kto?",
  "Delilah": "Delilah",
  "Hi. Yeah, it's me.": "Cześć. Tak, to ja.",
  "I'm back a staging area near the trail-head. I think I see your truck.": "Jestem przy stacji na początku szlaku. Chyba widzę twój wóz.",
  "Red, Colorado plates?": "Czerwony, blachy z Kolorado?",
  "Yeah.": "Tak.",
  "It's a piece of shit.": "Straszny szrot.",
  "It's better than whatever you drive.  What do you drive?": "I tak jest lepszy niż twój. Czym ty w ogóle jeździsz?",
  "Better than whatever you drive.": "I tak jest lepszy niż twój.",
  "A piece of shit.": "Szrotem.",
  "Well there you go.": "Sama widzisz.",
  "Hey, that's a man's pickup you're talking about.": "Hej, mówisz o moim pickupie.",
  "Hey now.": "Uważaj sobie.",
  "Well, yeah.": "Cóż... tak.",
  "Yeah, it is.": "Dokładnie ta.",
  "I think there might be a raccoon living in it.": "Chyba zamieszkał w nim szop.",
  "…though I think there's a raccoon living in yours.": "Chociaż w twoim mieszka szop...",
  "Probably the one who attacked my face.": "Pewnie to ten, który skoczył mi na twarz.",
  "Make sure he's comfy, I guess.": "Upewnij się, że mu tam wygodnie.",
  "You're not here.": "Nie ma cię tu.",
  "No…": "Nie...",
  "Don't be mad.": "Nie gniewaj się.",
  "You're mad.": "Gniewasz się.",
  "I just couldn't be out there for another minute.": "Nie mogłam tam zostać ani minuty dłużej.",
  "I'm not mad, I'm just—": "Nie gniewam się, tylko...",
  "I'm disappointed.": "Jestem zawiedziony.",
  "You're not mad, you're just disappointed?": "Nie gniewasz się, tylko jesteś zawiedziony?",
  "I'm not your dad after you got busted smoking pot.": "Nie traktuj mnie jak ojca, który przyłapał cię na paleniu zioła.",
  "You could've just said that.": "Mogłaś to powiedzieć.",
  "You really wanted me to stay.": "Naprawdę chciałeś, żebym została.",
  "I did, and now I'm—": "Tak, a teraz jestem...",
  "Disappointed.": "Zawiedziony.",
  "I know.": "Wiem.",
  "I'm not.": "Nie gniewam.",
  "I get it.": "Rozumiem.",
  "You… you do?": "Naprawdę?",
  "I think so.": "Tak myślę.",
  "I am.": "Gniewam.",
  "Well I couldn't be out there another minute.": "Nie mogłam tam zostać ani minuty dłużej.",
  "Not ANOTHER minute? Come on.": "Ani minuty dłużej? Daj spokój.",
  "Henry, how did you feel when you left Boulder to come out here?": "Henry, a co czułeś, kiedy wyjeżdżałeś z Boulder, żeby tu pracować?",
  "Like I couldn't get here fast enough.": "Że muszę tu przyjechać jak najszybciej.",
  "Exactly. That's how I've felt for the past 24 hours.": "Dokładnie. Tak samo ja czułam się przez ostatnie 24 godziny.",
  "Well, I'm still mad.": "Nadal się gniewam.",
  "But you understand?": "Ale rozumiesz?",
  "Eh, what's it matter if I do?": "A co za różnica?",
  "It doesn't matter.": "To bez znaczenia.",
  "Well, I'm sorry anyway.": "Ale i tak mi przykro.",
  "Not really. It was just a few minutes.": "Nie do końca. To była kwestia kilku minut.",
  "No.": "Nie.",
  "I'm sorry.": "Przepraszam.",
  "It's alright.": "W porządku.",
  "Sure. Yeah.": "Jasne.",
  "Yes.": "Tak.",
  "It shouldn't take long for the helicopter to reach you.": "Śmigłowiec niedługo po ciebie przyleci.",
  "Okay.": "Okej...",
  "There's a debrief in a situation like this. Lots of questions.": "W takim przypadku zdaje się sprawozdanie. Zadają masę pytań.",
  "Ugh, shit.": "Cholera...",
  "Yeah…": "No...",
  "So, taking stock. We found out an old lookout killed his only son and decided to become a lonely hermit.": "Podsumujmy. Odkryliśmy, że były obserwator zabił swojego jedynego syna i postanowił wieść życie pustelnika.",
  "And we prevented… one fire?": "I powstrzymaliśmy... jeden pożar?",
  "Basically started another.": "W sumie to rozpętaliśmy kolejny.",
  "Okay so that's a wash.": "To wychodzimy na zero.",
  "I'll have to figure out what I'm doing every summer from now on that isn't this.": "Muszę pomyśleć, czym będę zajmować się od przyszłych wakacji.",
  "You're not coming back?": "Nie wracasz?",
  "No. And you'll have to… I don't know.": "Nie. A ty będziesz musiał... sama nie wiem.",
  "Me neither. I don't know what's next.": "Też nie wiem. Nie mam pojęcia, co dalej.",
  "Tell you what: why don't you choose me for me, and I'll choose you for you.": "Wiesz co? Może ty dokonasz wyboru za mnie, a ja za ciebie.",
  "Ha. Alright, sure. Maybe…": "No dobra. To może...",
  "Maybe you could come back to Boulder with me and figure it out down there.": "Może mogłabyś wrócić ze mną do Boulder i tam zastanowimy się, \nco dalej.",
  "Come to Boulder with me.": "Wróć ze mną do Boulder.",
  "I'll take you to The Dollar.": "Zabiorę cię do „The Dollar”.",
  "Um…": "Hm...",
  "Just… just a thought.": "Tak tylko głośno myślę.",
  "You don't want me down there.": "Nie chciałbyś, żebym z tobą wróciła.",
  "Well, I just asked you.": "Przecież sam poprosiłem.",
  "No, you didn't.": "Nieprawda.",
  "I am asking you.": "Właśnie cię proszę.",
  "I've got some things to do in Casper and maybe I'll head south sometime after that. I could come by. Sure.": "Mam kilka spraw do załatwienia w Casper, a później może pojadę \nna południe. Mogę zahaczyć o Boulder, jasne.",
  "So, what about me?": "A co ze mną?",
  "Maybe move to Santa Fe. Open a jade emporium with your sister.": "Wyjedź do Santa Fe. Otwórz z siostrą jakiś rodzinny interes.",
  "Move to Santa Fe.": "Wyjedź do Santa Fe.",
  "Hmm… I'd be trading cute ski bums for yoga retreat hippies but maybe that's not all bad.": "Musiałabym zamienić wypady na narty na spotkania fanów jogi... \nale może to nie taki zły pomysł.",
  "Plus the margarita situation.": "A do tego jeszcze margarita...",
  "I mean, yeah.": "No tak.",
  "So… so what about me?": "A co ze mną?",
  "Well, you could always go take over the crossword at the New York Times.": "Mogłabyś przejąć sekcję z krzyżówkami w New York Timesie.",
  "Become crossword editor at the New York Times.": "Przejmij sekcję krzyżówek w New York Timesie.",
  "Oh yeah, I could probably fall right into that.": "Mogę to zrobić nawet od ręki.",
  "New York, big city.": "Nowy Jork, wielkie miasto.",
  "Couldn't be further from here.": "Dalej stąd by się chyba nie dało.",
  "I've never been.": "Nigdy tam nie byłem.",
  "Well, when I end up out there.": "No, jak już tam skończę...",
  "Yeah. So, what about me?": "A co ze mną?",
  "Well, you'd make a great shrink.": "Byłby z ciebie świetny psychiatra.",
  "You'd make a good shrink.": "Byłby z ciebie świetny psychiatra.",
  "Are you kidding me? You spent ten weeks with me and God knows how much therapy it's going to take to undo this experience.": "Jaja sobie robisz? Spędziłeś ze mną raptem dziesięć tygodni i Bóg jeden wie, ile zajmie terapia, dzięki której o tym zapomnisz.",
  "You're a good conversationalist, I guess.": "Dobrze się z tobą gada.",
  "Thanks. I try.": "Dzięki, staram się.",
  "I mean, you definitely still have some stuff to learn at shrink school. Like a lot of stuff.": "Chociaż nadal musisz wiele się w tej materii nauczyć. Naprawdę wiele...",
  "Noted.": "Zanotowałam.",
  "Even though you never told me about whoever you left behind.": "Nawet mimo że nie zdradziłeś mi, od kogo uciekłeś.",
  "Well, they'd probably give you some pointers at shrink school.": "W szkole dla psychologów pewnie daliby ci kilka porad.",
  "Okay, Henry.": "Dobra, Henry.",
  "So… what about me, then?": "A co w takim razie ze mną?",
  "I think you should go to Julia.  And then you can figure it out. Maybe put that typewriter to good use. Give me a sexy accent or something if you write about this.": "Ty powinieneś wrócić do Julii. Wtedy pomyślisz, co dalej. Może \nzrób użytek z maszyny do pisania. Jak o tym napiszesz, to dodaj \nmi jakiś seksowny akcent.",
  "I, umm… yeah.": "Dobra...",
  "You gotta go see her.": "Musisz się z nią zobaczyć.",
  "…": "...",
  "Yeah. Sure.": "No...",
  "Yeah, sure.": "Tak, jasne.",
  "Would you?": "Ty byś tak zrobiła?",
  "Henry… I. You came out to put your memories behind you and they're still right there in front of you.": "Henry... Przyjechałeś, żeby zostawić za sobą wspomnienia, ale one ciągle są tuż pod twoim nosem.",
  "She won't even recognize me, Delilah.": "Ona mnie nawet nie pozna, Delilah.",
  "She won't recognize me.": "Ona mnie nie pozna.",
  "You're not just going for her.": "Nie wracasz tylko dla niej.",
  "You don't know what it's like.": "Nie wiesz, jak to jest.",
  "Ugh. Bad things happen, okay? And you have to… you HAVE to find a way to contain the damage. A good way.": "Złe rzeczy się zdarzają, jasne? I musisz... odnaleźć sposób, by ograniczyć szkody. I to dobry sposób.",
  "Hopefully I can figure out a way to do that.": "Oby udało mi się to jakoś zrobić.",
  "Yeah, I hope so.": "Oby.",
  "God, this got dark.": "Ale się zrobiło mrocznie.",
  "No shit. Sorry.": "Bez jaj... Wybacz.",
  "There's the helicopter.": "Jest śmigłowiec.",
  "Good. They'll land back where you hiked up.": "Dobrze. Wylądują tam, gdzie wysiadłeś z kolejki.",
  "Good luck, Henry.": "Powodzenia, Henry.",
  "I’ll uh… see you when I see you.": "No to... do zobaczenia... kiedyś.",
  "See ya soon.": "Do zobaczenia.",
  "Yeah… sure thing. Bye, Henry.": "Jasne... Cześć, Henry.",
  "Goodbye, Delilah.": "Do widzenia, Delilah.",
  "Goodbye.": "Do widzenia.",
  "I mean it, okay? Good luck.": "Mówię poważnie. Powodzenia.",
  "Bye Hank.": "Cześć, Hank.",
  "Thanks, Delilah. I appreciate it.": "Dzięki, Delilah. Doceniam to.",
  "Thank you.": "Dziękuję.",
  "Thanks.": "Dzięki.",
  "You too. Good luck.": "Tobie też. Powodzenia.",
  "You too.": "Tobie też.",
  "You keep it for yourself.": "Zachowaj to dla siebie.",
  "I've… I gotta move on. I don't expect you to know what that's like but I have to find some way to move on. Something to do.": "Muszę iść naprzód. Nie oczekuję, że wiesz, jak to jest, ale ja muszę znaleźć sposób, by nie stać w miejscu. Muszę coś robić.",
  "I have to move on.": "Muszę iść naprzód.",
  "What if you can't?": "A jeśli nie dasz rady?",
  "Then… that's why God invented booze, I guess.": "Po to Bóg stworzył alkohol.",
  "Henry…": "Henry...",
  "I'm kidding.": "Żartuję.",
  "I gotta move on. Somehow.": "Muszę iść przed siebie... jakoś.",
  "Then maybe they're hiring lookouts in the Adirondacks.": "Może szukają obserwatorów w górach Adirondack.",
  "Ha, I don't believe that for a second.": "W życiu w to nie uwierzę.",
  "I've just… I gotta move on. Somehow.": "Muszę jakoś... iść przed siebie. Jakoś...",
  "I hope you do.": "Obyś dał radę.",
  "They'll land back where you hiked up.": "Wylądują tam, gdzie wysiadłeś z kolejki.",
  "Huh. I mean it, alright? Good luck. Bye Hank.": "Mówię poważnie. Powodzenia. Trzymaj się, Hank.",
  "I'll see you when I see you.": "Do zobaczenia... kiedyś.",
  "I mean it, Henry. Good luck.": "Mówię poważnie, Henry. Powodzenia.",
  "Thanks, D.": "Dzięki, D.",
  "You keep it for yourself. You need it more than I do.": "Zachowaj to dla siebie. Tobie bardziej się przyda.",
  "You're right. I mean… I think you're right.": "Masz rację. Znaczy... tak myślę.",
  "I'll go see her.": "Pojadę się z nią zobaczyć.",
  "Good.": "Dobrze.",
  "When I get back, maybe I could…": "Może po powrocie mógłbym...",
  "We shouldn't focus on this summer. Next year will roll around, and then the year after that, and then it's just a… I don't know. My Aunt Judy called it a pause in the hallway of time.": "Nie powinniśmy skupiać się na tym lecie. Ten rok szybko zleci, później następny i kolejny, a potem już tylko... nie wiem... Moja ciotka, Judy, nazywała to przerwą w nadawaniu.",
  "Did your Aunt Judy smoke a lot of pot?": "Czy twoja ciotka jarała dużo zielska?",
  "You should try to take her advice too.": "Tobie też radzę wziąć jej rady do serca.",
  "Yeah we'll see.": "Zobaczymy...",
  "Oh. Okay. Um, well… yeah, they'll land back where you hiked up. ": "Dobra... Wylądują tam, gdzie wysiadłeś z kolejki. ",
  "Thank you, Delilah. I appreciate it.": "Dzięki, Delilah. Doceniam to.",
  "I mean it. Good luck.": "Mówię poważnie. Powodzenia.",
  "No. Henry, you keep it for yourself.": "Nie. Henry, zachowaj to dla siebie.",
  "I’ll… see you when I see you.": "To... do zobaczenia... kiedyś.",
  "See you when I see you.": "Do zobaczenia... kiedyś.",
  "Yeah. Okay. Sounds good.": "Jasne. Brzmi nieźle.",
  "Jeez… well, you should probably put that typewriter to good use. If you ever decide to write about this, I'd appreciate if you gave me a sexy accent or something that would play well in the movie version.": "Kurczę... Może zrób użytek z maszyny do pisania. Jak o tym napiszesz, będę wdzięczna za dodanie mi jakiegoś seksownego akcentu. Czegoś, co dobrze by wyglądało w potencjalnej ekranizacji.",
  "Alright, I'll see what I can do.": "Zobaczę, co da się zrobić.",
  "At the very least it'll keep your mind off things for a while.  And get a new Bucket. A new dog.": "W najgorszym wypadku odciągnie cię to od różnych spraw. \nI kup sobie nowego Biszkopta. Nowego psa.",
  "At the very least it'll keep your mind off things for a while.  And get a new Mayhem. A new dog.": "W najgorszym wypadku odciągnie cię to od różnych spraw. \nI kup sobie nowego Masę. Nowego psa.",
  "Maybe get a dog?": "Może kup sobie psa?",
  "Hold on, let me write all this down.": "Poczekaj, zapiszę to sobie.",
  "Whenever the season is about to wrap up I usually find myself thinking \"When I get back I'm going to call him, you know, casual, see how he's doing.": "Zazwyczaj jak kończy się sezon, myślę sobie, że jak wrócę, \nto do niego zadzwonię. Po prostu zapytam, co u niego.",
  "My ex, that is.": "Znaczy do mojego byłego.",
  "I'll say something like, “Hey! I had a dream about you this summer and thought I'd call,\" you know, something that lets him know that I want him… without letting him know I want him.": "Powiem coś w stylu: „Hej, przyśniłeś mi się niedawno i pomyślałam, że zadzwonię”. Wiesz, coś takiego co sprawi, że będzie wiedział, że chcę do niego wrócić... ale żeby nie miał też tej pewności.",
  "Yeah… whatever you do, don't do that.": "No... cokolwiek zamierzasz, tak nie rób.",
  "Um, why don't you keep that luck for yourself?": "Może lepiej zachowaj całe powodzenie dla siebie.",
  "Yeah. Definitely.": "Tak, zdecydowanie.",
  "Dammit.": "Cholera."
}