{
  "Delilah": "Delilah",
  "Hey. I called around. Things seems normal with everyone else.": "Rozpuściłam wici, u innych brak niecodziennych zdarzeń.",
  "Henry": "Henry",
  "Should we call the cops or the Forest Service and let them know this is going on?": "Powinniśmy zgłosić glinom albo Służbie Leśnej o tym, \nco się tu wyprawia?",
  "Should we call the cops?": "Powinniśmy powiadomić gliny?",
  "Um… don't you think that would sound, you know, crazy?": "Nie sądzisz, że wzięliby nas za szaleńców?",
  "Yeah— it IS crazy. We have to tell someone.": "To jest czyste szaleństwo. Musimy kogoś poinformować.",
  "Tell them what, Henry? Tell them we're being stalked and you were attacked and we don't have any proof?": "I co powiemy, Henry? Że ktoś nas prześladuje, a ciebie zaatakowano, choć nie mamy żadnych dowodów?",
  "I don't know, tell them we're being bothered or something.": "Nie mam pojęcia. Zgłosimy, że ktoś nam się naprzykrza, czy coś.",
  "Henry, I really like this job, okay? And if I give off even a hint of cuckoo to my bosses, they are never going to let me back out here. Do you understand that?": "Henry, naprawdę lubię tę robotę. A jeśli moje szefostwo odniesie wrażenie, że zaczyna mi odbijać, już nigdy mnie nie zatrudnią. Rozumiesz?",
  "Has anything strange been happening on your end?": "A u ciebie nie działo się nic niepokojącego?",
  "Anything strange with you?": "A u ciebie nie działo się nic dziwnego?",
  "No, nothing really.": "Nie, właściwie nie.",
  "Nothing really, or nothing?": "To nie czy „właściwie” nie?",
  "Nothing. My door was open the other night but that's not strange.": "Nie. Wczorajszej nocy odkryłam, że moje drzwi były otwarte, \nale to nic.",
  "That it doesn't sound like nothing.": "Nie brzmi jak nic.",
  "It's nothing. I promise.": "Nie przejmuj się, naprawdę.",
  "Well, are the other lookouts telling the truth?": "A czy możemy ufać innym obserwatorom?",
  "Are the lookouts telling the truth?": "Możemy ufać innym obserwatorom?",
  "Of course, why wouldn't they be?": "Oczywiście, dlaczego nie mielibyśmy?",
  "I dunno, maybe someone told them not to.": "Nie wiem. Może mówią to, co ktoś kazał im powiedzieć.",
  "You're suggesting that you and I are actually being watched by… whom, exactly?": "Sugerujesz, że jesteśmy obserwowani przez... tak właściwie przez kogo?",
  "There's no point in wild theories until we've got something to go on, okay? Talk to you in a bit.": "Porzuć teorie spiskowe, dopóki nie dokopiemy się do sedna sprawy. Odezwę się niedługo.",
  "Maybe the government?": "Może przez rząd?",
  "The United States Forest Service? Are you a douglas fir? Is your trunk infested with bark beetles? Because if not, I promise you, they don't give a shit about you.": "Służbę Leśną Stanów Zjednoczonych? Obrosłeś w liście? A może \nmasz na pieńku z kornikami? Bo jeśli nie, to uwierz mi, że mają cię \nw dupie.",
  "You know, people.": "No wiesz, ludzi...",
  "As opposed to what, aliens?": "W przeciwieństwie do czego, kosmitów?",
  "Mad scientists? The CIA? Wild separatists? The fucking… illuminati?! Come on.": "Szalonych naukowców? CIA? Eko-oszołomów? \nPieprzonych illuminati?! Nie żartuj.",
  "I don’t know, obviously.": "Wiadomo, że nie wiem.",
  "I don't know.": "Nie wiem.",
  "Someone who is telling folks I’ve worked with for years to lie? Big Brother is not casting his shadow on the Shoshone, Henry.": "Twierdzisz, że ktoś zmusza ludzi, z którymi pracuję od lat, do kłamstwa? W Shoshone nie werbują ludzi do „Big Brothera”, Henry.",
  "Look, you should've seen this clipboard, Delilah.": "Powinnaś była zobaczyć ten notatnik, Delilah.",
  "Yeah. I guess should have.": "Najwyraźniej.",
  "I just thought you’d like to know that. To repeat, this is just happening to you and me. There’s got to be a reasonable explanation for all of this.": "Po prostu uznałam, że chciałbyś wiedzieć. Powtarzam, ta sprawa dotyczy tylko naszej dwójki. Musi istnieć na to jakieś racjonalne wyjaśnienie.",
  "Alright. I'm headed towards the camp, anyway.": "W porządku. Tak czy inaczej, zmierzam w stronę obozu.",
  "Keep your radio close to you.": "Nie spuszczaj krótkofalówki z oka.",
  "Okay. Keep your radio close to you.": "Okej. Nie spuszczaj krótkofalówki z oka.",
  "About my radio": "Co do krótkofalówki",
  "Hey, what you just said, keep my radio close to me.": "Powiedziałaś, żebym nie spuszczał krótkofalówki z oka.",
  "About my radio…": "Co do krótkofalówki...",
  "Yeah?": "Tak?",
  "Well I was thinking about that radio I found near the lake and the notes about our conversations.": "To przywiodło mi na myśl tę krótkofalówkę znalezioną w pobliżu jeziora razem z zapisem naszych rozmów.",
  "Before I got attacked back at the lake, I saw a radio on the ground… kind of like the one I use.": "Zanim zostałem znokautowany nad jeziorem, natknąłem się tam \nna krótkofalówkę... podobną do mojej.",
  "And?": "I?",
  "Do you think that, maybe, someone was, you know, uh—": "Myślisz, że ktoś mógł jej używać, żeby...",
  "I don’t know… what?": "Nie rozumiem... Żeby co?",
  "Maybe intercepting our frequency with other radios or something.": "By z jej pomocą nasłuchiwać naszego pasma, czy coś.",
  "Intercepting our frequency?": "Prowadzić nasłuch naszej częstotliwości?",
  "Henry…": "Henry...",
  "It’s just a thought.": "To tylko luźna myśl.",
  "I don’t even know how you would DO that.": "Nawet nie wiem, czy to jest wykonalne.",
  "Yeah, well you sound worried.": "A mimo to brzmisz na zmartwioną.",
  "No. I'm not, okay? Let's not spin out of control. Keep hiking.": "Wydaje ci się. Nie popadajmy w paranoję. Nie zatrzymuj się.",
  "Whatever you say, boss.": "Jak sobie życzysz, szefie.",
  "Tailing me? Following me around, like, working with other people.": "Śledzić mnie? Z pomocą innych ludzi podążać za mną krok w krok?",
  "Tailing me?": "Śledzić mnie?",
  "Henry you are way too much of a dope to be in the mob.": "Henry, takie ciapy jak ty nie wpasowują się w mafijne porachunki.",
  "Someone is clearly able to hear us sometimes AND was hiding near the lake. Come on.": "Nie ma wątpliwości, że ktoś, kto koczował przy jeziorze nas podsłuchuje. Nie próbuj zaprzeczać.",
  "I… I just—": "Ja tylko...",
  "Just admit it, you’re a little worried!": "Po prostu przyznaj, że cię to trochę martwi!",
  "Of course I'm worried! But let's just try to keep things calm, okay? Keep things on an even keel.": "Oczywiście, że tak! Ale postarajmy się nie tracić głowy. \nWeźmy to na chłodno.",
  "Oh nothing, just passing thoughts. Feeling a little paranoid, maybe, that’s all.": "Nieważne, myślę na głos. Najwyraźniej dałem się nieco ponieść paranoi.",
  "Nothing, just feeling paranoid.": "Mniejsza o to, chyba mi odbija.",
  "It's okay. Keep your head on straight and let me know if you need anything, alright?": "Nie przejmuj się. Zachowaj trzeźwy umysł i daj mi znać, gdybyś czegoś potrzebował, dobrze?",
  "Hello?  Whatever it is, just try to keep your head on straight, Henry.": "Halo? Cokolwiek się dzieje, zachowaj zimną krew, Henry.",
  "I know we don't know what's going on yet but… I don't have a good feeling.": "Wiem, że jeszcze nie rozwikłaliśmy tej zagadki, ale... targają mną złe przeczucia.",
  "I don't like feeling vulnerable. It's not like you can just call the police.": "Nienawidzę poczucia bezradności. A gliny nam tu w niczym nie pomogą.",
  "I was thinking about the Goodwins.": "Rozmyślałam o Goodwinach.",
  "It just struck me that if anything weird like this happened to them, happened to Brian…  just how scared he would've been.": "Przeszła mi przez głowę myśl o tym, jak przestraszony mógłby być Brian, gdyby spotkało go tutaj coś takiego...",
  "His dad could protect him.": "Ojciec by go obronił.",
  "He had his dad to protect him. Ned, right?": "Był pod stałą opieką ojca. Neda, dobrze pamiętam?",
  "Yeah.": "Tak.",
  "You don't think he could…?": "Nie uważasz, że on...",
  "No, you're probably right.": "Nie, pewnie masz rację.",
  "Maybe he'd actually enjoy it. Spies taking notes, walkie talkies, the whole thing might actually be fun if you were too young to realize how creepy it is.": "Kto wie, może miałby z tego frajdę. Szpiegowskie notatki, walkie-talkie... dla dzieciaka, który nie zdaje sobie sprawy z powagi sytuacji, to mogłaby być niezła przygoda.",
  "Maybe he'd actually enjoy it?": "Może miałby z tego frajdę?",
  "That's one way of looking at it.": "Można i tak na to spojrzeć.",
  "He's fine, D.": "Nic mu nie jest, D.",
  "I'm sure he's fine, Delilah. Don't you think if this started happening to them he or his dad would've said something?": "Delilah, na pewno nic mu nie jest. Nie sądzisz, że gdyby spotkało \nto jego albo jego ojca, powiadomiliby kogoś o tym fakcie?",
  "I'm sure he's fine.": "Z pewnością nic mu nie jest.",
  "I don't know. Ned was a weird guy.": "Sama nie wiem... Ned sprawiał dziwne wrażenie.",
  "Nobody is THAT weird. The moment you hear someone in the bushes or get punched from the shadows you're getting you boss on the phone.": "Nikt nie jest aż tak dziwny. Będąc ofiarą czyjegoś ataku albo prześladowań, w pierwszym odruchu informujesz o tym przełożonego.",
  "Brian's fine.": "Brian ma się dobrze.",
  "I hope so.": "Mam taką nadzieję.",
  "It was three years ago. He's in high school now. He's on summer break.": "Minęły już trzy lata. Korzysta właśnie z wakacji, odpoczywając \nod liceum.",
  "Yeah, you're right. You're right.": "Tak, masz całkowitą rację.",
  "Anyway, I don't expect you to care as much about it… and I'm probably just working myself up into a tizzy over nothing. Sorry. We need to just focus on what's happening to us.": "Tak czy inaczej, wiem, że to nie twój problem... a ja pewnie wpadam w panikę z byle powodu. Przepraszam. Musimy skupić się na naszej aktualnej sytuacji."
}