{
  "Delilah": "Delilah",
  "I'm having a hell of a time getting this fucking flapjack off his ass and out to repair that wire.": "Próbuję zmusić tego jebanego ciapciaka, żeby ruszył dupsko \ni naprawił ten przewód.",
  "Anyway, a few thinly veiled threats should be all it takes to get us back up and running.  The guy's a pushover.": "Kilka subtelnych gróźb powinno zmusić go do działania. Ten gość to prawdziwe popychadło.",
  "Henry": "Henry",
  "You want me to go back and see what I can do?": "Mam tam wrócić i sprawdzić, co da się zrobić?",
  "Want me to go back?": "Mam tam wrócić?",
  "No, I want this guy to have to roll his lazy ass out all the way out here.": "Nie. Chcę tylko, żeby ten fagas ruszył tam swoje dupsko.",
  "Flapjack is a *choice* phrase, by the way.": "Ciapciak to tak specjalnie, przy okazji.",
  "It really fits the bill in this case.": "Naprawdę pasuje tu jak ulał.",
  "Haha, oh man.": "O w mordę.",
  "Haha!": "Haha!",
  "What, you like that. This guy is the frickin King of the Flapjacks.": "Co, podoba się? Ten gość to prawdziwy król ciapciaków.",
  "Yeah, that's solid. I'll have to keep that one in my pocket.": "No, dobre jest. Zapiszę je sobie.",
  "It's all yours.": "Śmiało.",
  "Excuse me? \"Flapjack?\"": "Że co? Ciapciak?",
  "…Flapjack?": "Ciapciak?",
  "You know. Like a  loser. A chach.": "No wiesz, taka ciapa, faja.",
  "I really don't. But I do now.": "Nie do końca ogarniam, ale dobra.",
  "The next time you're at a bar and some banker steps on your foot so he can order his crappy martini, you've got just the name to use.": "Następnym razem jak jakiś bankier w barze stanie ci na stopę \nw trakcie zamawiania swojego gównianego martini, możesz \ngo tak nazwać.",
  "Hey flapjack, why don't you wait your turn before I bounce your face off a dumpster!": "Hej, ciapciaku! Może poczekasz na swoją kolej, zanim wrzucę cię \ndo śmietnika!",
  "\"Hey, flapjack!\"": "„Hej, ciapciaku!”",
  "It's beautiful!": "Pięknie!"
}