{
  "Delilah knows you don't like to be called Hank. Day 2.": "Delilah dowiaduje się, że nie lubisz być nazywany Hankiem. Dzień 2.",
  "Delilah knows you have someone named Julia. (Could be girlfriend or wife, doesn't matter)": "Delilah wie, że spotykasz się z niejaką Julią (która jest twoją dziewczyną lub żoną, nieistotne).",
  "Learns about your dog's name (Mayhem) when asking about Boulder on Day 2.": "Dowiaduje się, jak wabi się twój pies (Masa), gdy pyta o Boulder drugiego dnia.",
  "She knows you have a dog (indescriminate of its name).": "Wie, że macie psa (niezależnie od jego imienia).",
  "Learns about your dog's name (Bucket) when asking about Boulder on Day 2.": "Dowiaduje się, jak wabi się twój pies (Biszkopt), gdy pyta o Boulder drugiego dnia.",
  "Knows you went to the bar The Dollar on Pearl Street in Boulder, CO.": "Wie, że chadzałeś do baru „The Dollar” na Pearl Street w Boulder, w stanie Kolorado.",
  "Delilah learns you got a DUI when talking about Boulder on Day 2.": "Delilah dowiaduje się, że prowadziłeś pod wpływem w rozmowie o Bulder drugiego dnia.",
  "She knows she told you about her DUI she got five years ago. In About Boulder, Day 2.": "Wie, że powiedziała ci, że pięć lat temu prowadziła pod wpływem. W „O Boulder”, dzień 2.",
  "Delilah knows you are married.": "Delilah wie, że jesteś żonaty.",
  "She learns your partner (probalby your wife but not always 100%) is sick. Day 2. Day 33. Lots of places!": "Dowiaduje się, że twoja partnerka (zapewne żona, ale nie zawsze w 100%) jest chora. Dzień 2. Dzień 33. Wiele możliwości!",
  "Delilah remembers that when confronted with hearing her on the call, you were really weird. (Day 2) ": "Delilah pamięta, że w zapytany o podsłuchiwanie jej rozmowy, zachowywałeś się bardzo dziwnie. (Dzień 2) ",
  "Remembers saying \"your wife must be a saint for putting up with such a fucking asshole.\"": "Pamięta słowa: „twoja żona ma anielską cierpliwość, żeby wytrzymać z takim dupkiem”.",
  "You tell her that your partner (wife/gf agnostic, but almost sure it has to be wife) has Alzheimers.": "Mówisz jej, że twoja partnerka (żona/dziewczyna, choć najpewniej musi być to żona) ma Alzheimera.",
  "Remembers all the times you did not answer her when she was asking about your personal life on Day 2.": "Pamięta wszystkie rozmowy, w których zbyłeś milczeniem jej pytania o twoje życie osobiste podczas drugiego dnia.",
  "Delilah believes/believed you and your wife are on a break because you told her that. (Lie)": "Delilah wierzy/uwierzyła, że jesteście z żoną w separacji, bo ją o tym zapewniłeś. (Kłamstwo)",
  "Delilah assumes or believes or is told you went through a regular break up. Day 2.": "Delilah przypuszcza, wierzy lub wie od ciebie, że rozstałeś się z kimś. Dzień 2.",
  "If you directly deflect talking about what happened with your split.": "Jeśli w wyraźny sposób zmienisz temat zapytany o rozstanie.",
  "Remembers she told you the complete story about the love lives of both of her aunts. Day 2.": "Pamięta, że opowiedziała ci pełną historię o życiu miłosnym obu ciotek. Dzień 2.",
  "D knows you told her Julia teaches at Yale.": "D. wie, że zdradziłeś jej, że Julia wykłada na Yale.",
  "D knows you were with a professor.": "D. wie, że spotykałeś się z wykładowczynią.",
  "D knows you told her Julia teaches at CU Boulder.": "D. wie, że zdradziłeś jej, że Julia wykłada na CU Boulder.",
  "D knows she told you she had no relationship or ex that sent her to this job. Day 2.": "D. wie, że powiedziała ci, że podjęła tę pracę nie ze względu na związek czy byłego chłopaka. Dzień 2.",
  "Remembers you told her Julia was Australian.": "Pamięta, że powiedziałeś jej, że Julia jest Australijką.",
  "D knows you and Julia met in a bar.": "D. wie, że poznałeś Julię w barze.",
  "She remembers it if you snap at her about asking so much about your relationship.": "Pamięta o tym, jeśli dogryzłeś jej za zbytnie wścibstwo dotyczące twojego związku.",
  "D remembers telling you to go see Julia in Australia.": "D. pamięta, że kazała ci spotkać się z Julią w Australii.",
  "Believes you told her a lie about Julia going to be on research.": "Jest przekonana, że okłamałeś w sprawie statusu związku z Julią.",
  "D remembers telling you about Javier, her ex.": "D. pamięta, że opowiadała ci o byłym chłopaku, Javierze.",
  "Defautls to false, if false could mean:  on a break, taking time apart, assumed a split, etc. Lots of things can turn this on.": "Domyślnie: fałsz, jeśli może to znaczyć: w trakcie przerwy, rozłąkę, prawdopodobne rozstanie, itd. Wiele może zmienić ten stan rzeczy.",
  "This is like \"I don't want to talk about me,\" from jump street of the game.": "To brzmi jak: „Nie mam ochoty rozmawiać o sobie” od samego początku gry.",
  "If you said your relationship isn't her business. Used as a catch-all for the starting of 2.4.": "Jeśli powiedziałeś, że twój związek to nie jej interes. Użyte uniwersalnie na początku dnia 2.4.",
  "This just means D knows/believes you are going through a breakup.  Set by \"Assumes\" and \"wasTold.\"": "To oznacza tylko, że D. wie/wierzy, że przechodzisz rozstanie. Ustalone przez \"Assumes\" i \"wasTold\".",
  "In About prof 2 -- when you lie to her about the breakup. ": "W „O wykładowczyni 2”... gdy okłamujesz ją, mówiąc o rozstaniu. ",
  "If she says \"what does she ahve\" and you dont tell her": "Jeśli pyta: „Co jej dolega?”, a ty nie odpowiadasz",
  "If you dont answer how you met in 3.3.": "Jeśli nie opowiesz, jak się spotkaliście w dniu 3.3.",
  "This is at the very end of freezing her out: ltierally I DO NOT WANT TO SHARE.": "Gdy naprawdę nie chce z nikim rozmawiać: dosłownie, nie wydam z siebie słowa."
}