{
  "Delilah": "Delilah",
  "When you get there I think you should try to get in and look around.": "Kiedy już tam dotrzesz, spróbuj się włamać i rozejrzeć po okolicy.",
  "You’re out there getting punched by God knows who and we just need to take control of the situation.": "Łazisz tam sobie i dostajesz po twarzy od Bóg wie kogo. Musimy przejąć kontrolę nad sytuacją.",
  "There’s got to be a simple answer to why this is happening and I think it’s best if you just go in there see what you can find.": "Musi istnieć jakieś proste wytłumaczenie całej tej sytuacji. Najlepiej będzie, jeśli po prostu się tam udasz i poszukasz wskazówek.",
  "Henry": "Henry",
  "You got it.": "Jasne.",
  "Well, obviously keep an eye out. Don’t be dumb about it.": "Oczywiście, pilnuj się. Nie szalej.",
  "Says the woman in no danger of being shot.": "Mówi kobieta, której nie grozi zostanie postrzeloną.",
  "Okay, how about this.": "Dobra, a co powiesz na to?",
  "Do you really think we should just start breaking into places?": "Naprawdę myślisz, że powinniśmy zacząć się wszędzie włamywać?",
  "Should we really break in?": "Naprawdę mamy się włamać?",
  "If any time you’re in danger, we should pick a, you know, a code word.": "Na wypadek, gdybyś wpadł w tarapaty, powinniśmy wybrać jakieś słowo-klucz.",
  "You just have to make sure I hear it and I’ll do whatever I have to do to get out of the Thorofare and get help.": "Musisz się tylko upewnić, że je usłyszę, a zrobię wszystko, co mogę, żeby wydostać się z wieży i sprowadzić pomoc.",
  "A lot of good that’ll do me however many days later but yeah, lets do that.": "Ta pomoc na wiele się zda tych kilka dni później, ale zgoda, zróbmy tak.",
  "So, are you going to give me the code word or what?": "To podasz mi to słowo, czy co?",
  "I thought you were going to come up with it.": "Myślałam, że to ty je wymyślisz.",
  "I do everything!": "Muszę wszystko robić sam!",
  "Well, I'm drawing a blank, here.": "Ja nie mam żadnego pomysłu.",
  "Fine.": "Dobra...",
  "How about Mayday.": "Może: „Mayday”?",
  "Mayday.": "Mayday.",
  "Great, nice and straightforward.": "Świetnie, krótkie i do rzeczy.",
  "How about Zulu.": "Może: „Zulu”?",
  "Zulu.": "Zulu.",
  "Zulu. You got it, GI Joe.": "Zulu. Proszę bardzo, żołnierzyku.",
  "How about Pussy-willow?": "Może: „kocimiętka”?",
  "Pussy willow.": "Kocimiętka.",
  "Pussy-willow.": "Kocimiętka.",
  "Yeah.": "Tak.",
  "You’re alright with “pussy-willow” possibly being your last words.": "Odpowiada ci myśl, że twoim ostatnim słowem może być „kocimiętka”.",
  "Could be worse.": "Mogło być gorzej.",
  "Could it?": "Naprawdę?",
  "How about “achtung!”": "A może: „achtung!”?",
  "Fine. We’ll just hope they're not German.": "W porządku. Miejmy nadzieję, że nie są Niemcami.",
  "You know, I’ve always had a thing for German men.": "Wiesz co, zawsze pociągali mnie niemieccy mężczyźni.",
  "Jesus Christ, can we not, right now?": "Chryste, może zwierzysz się kiedy indziej?",
  "Let’s hope you don’t have to use it.": "Miejmy nadzieję, że nie będziesz musiał go używać."
}