{
  "Delilah": "Delilah",
  "So… I have a bit of a confession to make.": "Muszę się do czegoś przyznać...",
  "Henry": "Henry",
  "What is it?": "O co chodzi?",
  "…": "...",
  "You have some highly contagious pun-related disease?": "Masz jakąś wysoce zaraźliwą chorobę związaną z grami słownymi?",
  "You have a pun sickness?": "Masz skrzywienie na punkcie gier słownych?",
  "No. Well, yes, but that's not the confession.": "Nie. To znaczy tak, ale nie o to chodzi.",
  "Anyway, let me know when you get back to your lookout.": "Tak czy siak, daj mi znać, jak już wrócisz do swojej wieży.",
  "Um… Look, I was drunk last night when I welcomed you to the job.": "Słuchaj, zeszłej nocy, kiedy przywitałam cię w pracy, \nbyłam wstawiona.",
  "Yeah, well, you're not the first boss to be guilty of that.": "Nie jesteś pierwszym szefem, który tak zrobił.",
  "I know. I just… I know I can get a little pushy, putting you on the spot about why you're out here and stuff.": "Wiem, tylko że... Zdaję sobie sprawę, że czasem przeginam, dopytując cię o to, czemu tu jesteś i w ogóle.",
  "AND you thought it was a good idea to get into your uh, love life, I guess you'd call it.": "I uznałaś, że to dobry pomysł, żeby rozwodzić się nad swoim... życiem miłosnym, że tak to nazwę.",
  "Yeah… um. Anyway, I'm sorry.": "No... W każdym razie przepraszam.",
  "Yeah, whatever.": "Spoko...",
  "Uh huh.": "Taa.",
  "I'll um, you know, I'll try to make it up to you.": "Spróbuję ci to jakoś... wynagrodzić.",
  "It's fine.": "W porządku.",
  "It's not a big deal.": "Nic się nie stało.",
  "I'll… keep that sort of a thing to a minimum.": "Ograniczę takie akcje do minimum."
}