{
  "Delilah": "Delilah",
  "Well, I mean, whatever it is, you’ll find this job will either make it a lot better or a lot worse.": "Cokolwiek cię tu sprowadza, zobaczysz, że dzięki tej pracy albo znacznie ci się polepszy, albo pogorszy.",
  "Henry": "Henry",
  "Hello? I’m here now.": "Halo? Już jestem.",
  "I'm here now.": "Już jestem.",
  "Um, hello? Whoever this is?": "Halo? Kimkolwiek jesteś...",
  "Hello?": "Halo?",
  "It’s Henry, right?": "Henry, tak?",
  "Your lights aren't on.": "Masz wygaszone światła.",
  "Yeah. Uh, no. You can see me?": "Tak... A co, widzisz mnie?",
  "I can see all the lookouts.": "Widzę wszystkie wieże.",
  "Yeah.": "Tak.",
  "I’m Delilah.": "Jestem Delilah.",
  "Yeah, that’s what the guy said on the phone.": "Wiem, tak mówił gość w słuchawce.",
  "So, what’s wrong with you?": "To co z tobą nie tak?",
  "Excuse me?": "Słucham?",
  "People take this job to get away from something. So what’s wrong?": "Ludzie biorą tę robotę, żeby przed czymś uciec. \nTo jak to jest u ciebie?",
  "What’s wrong with you?": "A co nie tak z tobą?",
  "That’s a great idea. Go ahead.": "Co za świetny pomysł. No, śmiało.",
  "Look, I just hiked for two days so I don’t really follow whatever it is you’re doing right now.": "Słuchaj, łaziłem bite dwa dni, więc nie do końca nadążam, o co ci chodzi.",
  "You take a stab at what’s wrong with me.": "Zgadnij, co jest nie tak ze mną.",
  "Fine, then can I sleep…? Forever?": "Dobra, a będę mógł później iść spać? Już na zawsze?",
  "Sure, buddy. Now, go ahead.": "Jasne, kolego. A teraz dawaj.",
  "You’re just going to wait me out on this?! Fiiiine. But I'm gonna take a second here and have a guess about you.": "Masz zamiar zbyć mnie milczeniem? No dobra. Ale w takim razie teraz moja kolej.",
  "Okay. You're probably out here because nobody back home can stand you.": "Dobra. Jesteś tu, bo pewnie cała rodzina cię nie znosi.",
  "Nobody back home can stand you.": "Rodzina cię nie znosi.",
  "Which, after this brief introduction, isn’t a big shock.": "Co, po naszej krótkiej wymianie zdań, wcale mnie nie dziwi.",
  "Ouch! I’ll chalk that up to you being tired and grumpy.": "Uznam, że powiedziałeś to, bo jesteś zmęczony i nie w sosie.",
  "Well I'd better get some sleep then.": "No to lepiej uderzę w kimono.",
  "One sec! Now it's my turn.": "Chwila! Teraz moja kolej.",
  "Okay. You're probably just rebelling against a mom who wishes you had given her grandkids, by the sound of your voice, at least fifteen years ago?": "Dobra. Pewnie zbuntowałaś się przeciwko mamusi, która chciałaby mieć już wnuki... z piętnaście lat temu, sądząc po twoim głosie?",
  "You're rebelling against mom.": "Zbuntowałaś się przeciw mamusi.",
  "You come out here and it really grinds her gears and you love it. Can I sleep now?": "Przyjeżdżasz tu, co ją wpienia, a tobie w to graj. Mogę już iść spać?",
  "Well, she also says I fuck immature men. But in my defense, who wouldn’t want a twenty-eight year old with ambition and energy and some fire in his belly in bed?": "Narzeka też, że pieprzę się z niedojrzałymi facetami. Ale na swoją obronę dodam, że kto nie chciałby ambitnego, energicznego dwudziestoośmiolatka w łóżku?",
  "Me. I’m going now.": "Na przykład ja. A teraz znikam.",
  "Just a second. Now it's my turn.": "Poczekaj, teraz moja kolej.",
  "Okay. You've killed three husbands. You're a black widow. You're just out here until the heat dies down and then you'll kill again.": "Dobra. Zabiłaś trzech mężów. Jesteś czarną wdową, która chce tutaj przeczekać, aż sprawy przycichną, żeby zabić ponownie.",
  "You've killed three ex-husbands.": "Zabiłaś trzech byłych mężów.",
  "VERY good. Bra-vo, Henry.": "Doskonale. Brawo, Henry.",
  "Okay. I sleep now?": "Super. To mogę już iść spać?",
  "Not quite. Now, you.": "Nie do końca. Teraz ty.",
  "Okay. Goodnight. Bye.": "To dobranoc. Pa.",
  "Let’s see… I don’t know anything about you.": "Zobaczmy... Nic o tobie nie wiem.",
  "But maybe you just really like trees. Maybe it’s, gosh, maybe it’s a borderline fetish. A tree fetish.": "Ale może uwielbiasz drzewa. Albo to jakieś zboczenie... \nCzujesz pociąg do drzew.",
  "Good night.": "Dobranoc.",
  "I say you got fired from your job and have finally decided to write your novel. That’s the sort of bullshit reason you’ll find a man out in the woods.": "Stawiam, że wywalili cię z roboty i w końcu znalazłeś czas, by napisać własną powieść. Zazwyczaj takie pierdoły sprowadzają facetów do lasu.",
  "Welcome to the job.": "Witaj w brygadzie.",
  "But nine times out of ten, folks out here simply got dumped.": "Ale w dziewięciu przypadkach na dziesięć powodem jest rozpad związku.",
  "Is that it?": "To wszystko?",
  "Close?": "Byłam blisko?",
  "G’night.": "Dobrej nocy.",
  "Good night. Welcome to the job.": "Dobranoc. Witaj w brygadzie.",
  "Got another big talker, I see.": "Widać znów trafiłam na mruka.",
  "Well…": "Cóż...",
  "Hello, Two Forks Tower!": "Czołem, Wieżo na Rozdrożach!",
  "I know you're there. Your lights are on.": "Wiem, że tam jesteś. Widzę światło.",
  "Hello, Two Forks? Come back. Pick up your radio.": "Halo, Rozdroża? Odpowiedz. Odbierz krótkofalówkę.",
  "Two Forks Tower, this is Thorofare Tower. Come in.": "Wieżo na Rozdrożach, tu Wieża Główna. Odbiór."
}