{
  "Henry": "Henry",
  "I'm near my tower at the closed trail. Where's that rope supposed to be?": "Jestem w pobliżu mojej wieży, przy zamkniętym szlaku. \nGdzie powinna być lina?",
  "Where's that rope, again?": "Przypomnij mi, gdzie lina?",
  "Delilah": "Delilah",
  "Down the trail that leads west of your tower, so, just a teensy bit south and west of you.": "Idź szlakiem na zachód od swojej wieży, kawałeczek na południowy zachód.",
  "Well… that trail isn't \"closed\" anymore.": "Szlak nie jest już zamknięty...",
  "Report fallen \"Trail Closed\" sign": "Zgłoś przewrócony znak: „Szlak zamknięty”",
  "Hey, so, the trail out of the canyon isn't \"closed\" anymore.": "Słuchaj... szlak prowadzący z kanionu nie jest już zamknięty.",
  "Oh really?": "Serio?",
  "Yeah, I took care of the blocked path. It was back-breaking but, you know, anything for the service.": "Tak, odblokowałem przejście. Nie było łatwo, ale wiadomo, \nczego się nie robi dla pracy.",
  "Well thank you!": "Wielkie dzięki!",
  "Any time.": "Żaden problem.",
  "I found a sweatshirt from the University of Eastern Colorado.": "Znalazłem bluzę z nadrukiem Uniwersytetu Wschodniego Kolorado.",
  "Report university sweatshirt": "Zgłoś bluzę z nadrukiem",
  "Maybe it's one of the girls'? Eh, it's been here a long time.": "Może któraś z dziewczyn ją zgubiła? Nie, raczej za długo tu leży.",
  "There's a University of Eastern Colorado?": "Oni tam w ogóle mają jakiś uniwersytet?",
  "I really don't think there is.": "Nie wydaje mi się.",
  "Why would somebody make that up?": "Po co ktoś by to zmyślał?",
  "Right, and then put it on a sweatshirt.": "I jeszcze robił bluzę z takim nadrukiem.",
  "The world is a weird place.": "Świat jest dziwny.",
  "It's a little warm for long sleeves.": "Jest za ciepło na długi rękaw.",
  "Also, University of Eastern Colorado? That's not even a real University.": "Uniwersytet Wschodniego Kolorado? To nawet nie jest prawdziwy uniwerek.",
  "No, it isn't.": "Właśnie.",
  "Someone found a fossil and put it in a cache box.": "Ktoś znalazł jakąś skamielinę i wrzucił do skrzynki.",
  "Report claw": "Zgłoś szpon",
  "Oh really.": "Serio?",
  "Could be the same person who left that antler?": "Może ta sama osoba zostawiła tamto poroże?",
  "Maybe they're leaving me an entire creature, piece by piece.": "Może mam sobie złożyć całe zwierzę, kawałek po kawałku.",
  "Well, something has nested in one of these cache boxes.": "Coś się zagnieździło w jednej ze skrzyń.",
  "Report nest": "Zgłoś gniazdo",
  "It's probably a squirrel or field mouse or a—": "To chyba wiewiórka albo jakaś mysz polna, albo...",
  "A rattlesnake, or a scorpion…": "Wąż lub skorpion...",
  "Neither of those things nest.": "One nie budują gniazd.",
  "What, you've never heard of a nest of scorpions? Really?": "Nigdy nie słyszałeś o gnieździe skorpionów? Serio?",
  "Well now that you say it it sounds like a real thing.": "W sumie jak o tym mówisz, to nie brzmi tak nieprawdopodobnie.",
  "I'd never lie to you.": "Nigdy bym cię nie okłamała.",
  "Hey, I'm out at a ravine. What's this thing that spans across it?": "Jestem przy wąwozie. Co to się tak rozciąga ponad nim?",
  "Report cable car": "Zgłoś kolejkę",
  "That is how you get to my sector.": "Tak możesz dostać się do mojego sektora.",
  "No kidding! Well, let me hike over.": "Nie żartuj! No to się przejadę.",
  "It's locked up and mainly for emergencies. I've never actually used it.": "Jest wyłączona, służy głównie w nagłych wypadkach. Nigdy jej nawet nie użyłam.",
  "Rangers use it from time to time, but that's it.": "Leśniczowie czasem z niej korzystają, ale to tyle.",
  "HELP! OH GOD, it's an emergency!": "Ratunku! Boże, to nagły wypadek!",
  "HELP! It's an EMERGENCY!": "Ratunku! To nagły wypadek!",
  "Yeah, I've got, uh, eyes on a tornado! I gotta get out of here!!": "Zbliża się do mnie tornado! Muszę się stąd ewakuować!",
  "A tornado in the heart of the Rockies?!": "Tornado tutaj?!",
  "YES!": "Tak!",
  "Holy moly, I need to call this in! Tom! Two Forks sees a tornado! He says he needs an evac into my sector! …It's a meteorological impossibility? There haven't been tornadoes in the Greater Yellowstone region in 100 million years? You're going to need him to stay and take a detailed personal account even if it means giving his life? Okay, I'll tell him!": "Rany! Muszę to zgłosić! Tom! W okolicy Rozdroży szaleje tornado! Henry mówi, że musi ewakuować się do mojego sektora! To w ogóle możliwe? To pierwsze tornado w rejonie Yellowstone od jakichś stu milionów lat? Ma zostać i zbierać informacje nawet za cenę swojego życia? Dobra, przekażę mu!",
  "Sorry Hank, no dice.": "Wybacz, Hank, nie da rady.",
  "Man…": "Kurczę...",
  "That is how you get to my sector.  It's locked up and only used by rangers.": "Tak możesz dostać się do mojego sektora. Ale jest wyłączona, używają jej wyłącznie leśniczowie.",
  "It's mainly an emergency measure — it's ridiculously unsafe but better than one of us getting trapped by a fire.": "Korzysta się z niej głównie w nagłych wypadkach. Jest strasznie niebezpieczna, ale lepsze to niż utknąć w pożarze.",
  "And if we ever have to be evacuated by chopper, it means lookouts can just meet here.": "A gdybyśmy musieli zostać ewakuowani śmigłowcem, obserwatorzy mogliby się tu spotkać.",
  "Well, maybe I should come over there, given what's going on?": "To może powinienem przyjechać, zważywszy na to, co się tu dzieje?",
  "Maybe I should come over?": "Może powinienem przyjechać?",
  "The car is really only for emergencies, Henry.": "Kolejka jest wyłącznie do nagłych wypadków, Henry.",
  "Alright, okay.": "Dobra, dobra...",
  "This won't become an emergency. We'll figure it out.": "Nie będzie żadnego nagłego wypadku. Coś wykombinujemy.",
  "Yeah, we'll figure it out.": "No, coś wykombinujemy.",
  "Hey, what's this thing that crosses the ravine?": "Hej, co takiego jest nad wąwozem?",
  "It's an emergency tram between sectors, yours and mine.": "To kolejka linowa łącząca nasze sektory.",
  "Hey, I'm at the ravine. It kinda feels like what we're dealing with out here is \"an emergency.\"": "Jestem w wąwozie. Mam wrażenie, że mamy do czynienia z nagłym wypadkiem.",
  "Wouldn't you say this is an emergency? How have we not buddied up in the past couple of days?": "Nie uważasz, że to nagły wypadek? Czemu nie zakumplowaliśmy się przez ostatnie kilka dni?",
  "Don't you think this is an emergency?": "Nie sądzisz, że to nagły wypadek?",
  "Because I didn't think that was a good idea.": "Bo uznałam, że to nie najlepszy pomysł.",
  "Delilah, come on.": "Delilah, no weź.",
  "Do you really blame me?": "Serio mnie obwiniasz?",
  "What about me? I'm the one actually going through this stuff.": "A co ze mną? To ja przez to wszystko przechodzę.",
  "What about me?": "A co ze mną?",
  "And I'm a woman out in the woods and they don't let us keep guns.": "To ja jestem samotną kobietą w lesie, a nie pozwalają nam mieć broni.",
  "Jesus, Delilah.": "Jezu, Delilah.",
  "Oh come on, don't give me crap for feeling safer over here by myself, alright?": "Daj spokój, nie wiń mnie za to, że czuję się bezpieczniej pozbawiona towarzystwa, dobra?",
  "Fine.": "Dobra...",
  "Look, that fire is burning out of control so if you're yearning for a rickety ride on an old tram you might just get your wish.": "Słuchaj, ten pożar zaczyna wymykać się spod kontroli, więc jeśli marzysz o przejażdżce rozklekotaną kolejką, może niedługo będziesz miał szansę.",
  "Hey, I'm at the evac spot near the ravine.": "Jestem przy punkcie ewakuacji, niedaleko wąwozu.",
  "Delilah, are you there?": "Delilah, jesteś tam?",
  "Delilah?": "Delilah?",
  "Hi, what is it?": "Hej, o co chodzi?",
  "I'm at the ravine.": "Jestem w wąwozie.",
  "We're not leaving, yet. When the time comes I'll let you know okay? I'm dealing with a shit-storm over here.": "Jeszcze tu zostajemy. Jak będzie odpowiednia pora, dam ci znać, dobrze? Sama mam do ogarnięcia niezłe gówno.",
  "Yeah, got it.": "Jasne, rozumiem.",
  "Whoa, Delilah, the trail I hiked in on, it's… it's gone.": "Delilah, szlak, którym szedłem... zniknął.",
  "Report rock slide": "Zgłoś osuwisko",
  "What, is this The Twilight Zone?": "Jesteśmy w Strefie Mroku?",
  "There was a rock slide. Is there another path out of the Thorofare?": "Skały się osunęły. Jest jeszcze jakaś droga do Wieży Głównej?",
  "Ah. Um… let me think.": "Niech no pomyślę...",
  "Oh my God, I guess I'm lucky I wasn't on it when it happened.": "Boże, miałem szczęście, że tędy nie szedłem, kiedy to nastąpiło.",
  "Yeah, for sure. You know, without some impossible mountaineering, there's not really another way out.": "Dokładnie. Nie mając porządnego sprzętu wspinaczkowego, właściwie jesteś tam uwięziony.",
  "So what the hell?": "To co mam robić?",
  "We'll fly you out. Sometimes folks get cut off by fire and we just scoop them up when it's time to go.": "Ewakuujemy cię śmigłowcem. Czasami ogień kogoś odetnie, więc trzeba go podjąć w odpowiednim czasie.",
  "Okay.": "Okej...",
  "Don't be nervous.": "Nie denerwuj się.",
  "I'm not.": "Nie gniewam.",
  "Well you sound nervous.": "Brzmisz na zdenerwowanego.",
  "Well, the fact that I could always just hike out was some comfort.": "Lepiej się czułem wiedząc, że ewentualnie wydostanę się stąd \no własnych siłach.",
  "I promise I'll be here for you in this difficult time.": "Obiecuję, że będę z tobą w tych ciężkich chwilach.",
  "I don't like to fly.": "Nie lubię latać.",
  "Sometimes the guys have peanuts and pretzels.": "Czasami na pokładzie dają orzeszki i precelki.",
  "Doesn't help.": "Żadna pociecha.",
  "And beer?": "A piwo?",
  "Okay, yeah.": "To co innego.",
  "Maybe I'll just live out here, now.": "W takim razie może tu zostanę.",
  "Maybe I'll just live out here.": "To może tutaj zostanę.",
  "Henry the Hermit.": "Henry pustelnik.",
  "I'll find myself a baby bear to keep as a pet and live off the land like Grizzly Adams.": "Znajdę sobie niedźwiadka dla towarzystwa i będę żył z tego, \nco zrodzi ziemia, tak jak Grizzly Adams.",
  "It's starting to feel like it.": "Zaczyna to brzmieć kusząco.",
  "Well, look, don't freak. This happens. At the end of the summer we just fly you out.": "Nic się nie bój. Tak bywa. I tak na koniec lata stąd odlatujemy.",
  "Or, you know, if there's an emergency.": "Chyba że nastąpi jakiś nagły wypadek.",
  "I'm sensing an emergency.": "Wyczuwam taki wypadek.",
  "What did I say about calling for a flight out?": "Co mówiłam na temat wzywania śmigłowca?",
  "It's expensive and you're not asking.": "To droga zabawa, a ty się nie będziesz prosić.",
  "Good memory.": "Brawo za pamięć.",
  "I can't call and ask for a fifteen thousand dollar helicopter ride because there might be someone out here, uh, harassing us.": "Nie mogę poprosić o przylot śmigłowca w cenie 15 tysięcy dolarów tylko dlatego, że może tu być ktoś, kto próbuje nas... zastraszyć.",
  "Well, let me know when you can, okay?": "To daj znać, jak będziesz mogła, dobra?",
  "Okay, Henry.": "Dobra, Henry.",
  "Holy hell, Delilah — the path out of here is blocked off.": "Do diabła, Delilah... Droga jest zablokowana.",
  "Henry… why don't we talk about that when you've taken your hike?": "Henry... może porozmawiamy o tym, jak już się przespacerujesz?",
  "But—": "Ale...",
  "Please, Henry.": "Proszę, Henry.",
  "Hey — I'm back at the trail out of here and it's blocked off.": "Hej... Wróciłem na szlak i droga jest zablokowana.",
  "The trail out of here is blocked off.": "Ten szlak jest zablokowany",
  "What?!": "Co?!",
  "There was a rock slide or something.": "Osunęły się skały, czy coś.",
  "Well, shit. Don't worry. Stuff like this happens, fires, rock slides. Don't worry.": "Cholera. Nie martw się, tak bywa. Pożary, osuwiska. Nie martw się.",
  "You just said don't worry twice.": "Dwa razy powiedziałaś: „nie martw się”.",
  "Is it possible that someone caused the rock slide and took out the path?": "Możliwe, że to ktoś spowodował osunięcie się skał i zablokował drogę?",
  "Do you think someone did this?": "Myślisz, że to czyjaś sprawka?",
  "No, that's crazy.": "Nie, to szaleństwo.",
  "As crazy as our radios being tapped.": "Takie szaleństwo jak podsłuchiwanie naszych rozmów.",
  "Look, if we start thinking every single thing that happens to us is \"them,\" we'll go nuts.": "Jeśli każde wydarzenie będziemy przypisywać „im”, zwariujemy.",
  "Maybe that's part of their plan.": "Może to część ich planu.",
  "We've got new radios, we've got a plan. It's going to be okay.": "Mamy nowe krótkofalówki, mamy plan. Wszystko będzie dobrze.",
  "Now get to Wapiti Station.": "Teraz dostań się do Stacji Wapiti.",
  "There must've been a rock slide or something.": "Musiało dojść do osunięcia się skał, czy coś.",
  "Holy shit, do you think someone did this?": "Cholera, myślisz, że to czyjaś sprawka?",
  "No, Henry, I think that is what's called an act of God.": "Nie, Henry, myślę, że to tak zwane „dzieło Boże”.",
  "I can't get outta here.": "Nie wydostanę się stąd.",
  "I can't imagine they're going to keep us out here much longer, not with all the fire in the area.": "Nie wyobrażam sobie, żeby dłużej nas tu trzymali, kiedy niedaleko szaleje pożar.",
  "And then the helicopter comes?": "W takich przypadkach przylatuje śmigłowiec?",
  "And then the helicopter comes.": "I wtedy przylatuje śmigłowiec.",
  "Good thing they're lifting us out today, huh?": "Dobrze, że zgarną nas dzisiaj, co?",
  "Yeah… good thing.": "No... dobrze.",
  "You have any interest in any of Brian's stuff? This map he drew, maybe?": "Interesuje cię może coś z rzeczy Briana? Może własnoręcznie stworzona mapa?",
  "Report hand-drawn map": "Zgłoś ręcznie narysowaną mapę",
  "No, that's alright.": "Nie, dziękuję.",
  "You sure?": "Na pewno?",
  "Yeah Henry, I'm sure. I don't want a dead boy's drawing.": "Tak, Henry, na pewno. Nie chcę rysunku martwego chłopca.",
  "There's a map in my tower that I'm pretty sure is not USGS regulation.  Unless I've unknowingly been assigned to work in \"Two Orcs\" and the lake to the east is made of acid…?": "W wieży znalazłem mapę, która ma chyba niewiele wspólnego \nz rzeczywistością. No chyba że miałem przydział do \nWieży na Porożach, a jezioro na wschodzie wypełnia kwas...",
  "Two Orcs?": "Wieży na Porożach?",
  "It looks like it was made by Brian Goodwin.": "Chyba autorem jest Brian Goodwin.",
  "It goes along with that paper I found when I got out of the cave.": "Przypomina to notatki, jakie znalazłem, wychodząc z jaskini.",
  "I wonder if his dad hated this type of stuff and he felt like he had to hide it…?": "Ciekawe, czy jego ojciec nienawidził tego typu zabaw i mały chciał to wszystko ukryć?",
  "Oh man. That would be sad.": "To by było przykre.",
  "Oh, you have a soft spot for the nerds?": "A co, lubisz takich nerdów?",
  "I really do.": "Tak.",
  "Uh, that sounds… erroneous.": "To brzmi... źle.",
  "It looks like a previous resident was into fantasy.": "Chyba poprzedni mieszkaniec miał bzika na punkcie fantasy.",
  "I assume it was Brian Goodwin. Kid must'a really liked wizards.": "Domyślam się, że to był Brian Goodwin. Serio musiał lubić czarodziejów.",
  "Brian Goodwin?": "Brian Goodwin?",
  "Yeah, looks like he was big into wizards.": "No, chyba fascynowali go czarodzieje.",
  "Wait, who?": "Chwila, kto?",
  "I found something drawn by a kid who is definitely into wizards and stuff.": "Znalazłem rysunek dzieciaka, którego ewidentnie fascynowali czarodzieje i takie tam.",
  "You don't like wizards?": "Ty nie lubisz czarodziejów?",
  "I love wizards. Who doesn't like wizards?": "Uwielbiam. Jak można ich nie lubić?",
  "Who doesn't love wizards?": "Jak można nie lubić czarodziejów?",
  "Wyverns.": "Powiedz to Wiwernom.",
  "Excuse me?": "Słucham?",
  "Winged reptiles with magical or unusual abilities. They soar over the lands, scorching townships with their breath of flame, taking considerable care to devour their sworn enemies: the sorcerers, mages, witches and, you know.": "Skrzydlate jaszczury o magicznych lub niezwykłych zdolnościach. Szybujące w przestworzach, niszczące miasta swym ognistym podmuchem, pożerające swych arcywrogów, czyli czarnoksiężników, magów, wiedźmy, no i... wiesz.",
  "Wizards?": "Czarodziejów?",
  "Wizards…?": "Czarodziejów?",
  "Yeah, wizards.": "Tak, czarodziejów.",
  "Holy shit.": "Cholera.",
  "…and wizards. I think dragons and wizards are pretty boss. Wyverns too. Um, gotta go!": "I czarodziejów... Smoki i czarodzieje są czaderskie. Wiwerny też. Dobra, ja muszę lecieć!",
  "Delilah's Away": "Delilah się rozłączyła",
  "Back in a flash!": "Za moment wracam!",
  "That fantasy map from before looks like it was made by Brian Goodwin. The handwriting matches everything in that folder I found.": "Tamta mapka fantasy wygląda, jakby narysował ją Brian Goodwin. Charakter pisma pasuje do tego z teczki, którą znalazłem.",
  "Brian drew this map.": "Brian narysował tę mapę.",
  "Hmm. Maybe it just fell out of a while back?": "Może wypadło mu to gdzieś wcześniej?",
  "I guess.": "Możliwe...",
  "Well, antlers are made of bone and horns are made of the same stuff as your fingernails.": "Poroże wyrasta z kości czołowej, a róg zbudowany jest z tej samej tkanki, co twoje paznokcie.",
  "Those boxes are bear proof. I wouldn't worry about it.": "Te skrzynki są odporne na ich ataki. Nie przejmuj się tym.",
  "I guess this is a bone.": "To chyba jakaś kość.",
  "Antler. A ranger must've found it this spring.": "Poroże. Jakiś leśniczy pewnie znalazł je tej wiosny.",
  "I get the sense not everything in here is useful.": "Mam wrażenie, że nie wszystko tutaj jest przydatne.",
  "Not everything in here is useful, huh?": "Nie wszystko tutaj jest przydatne, co?",
  "In the boxes? Why's that?": "W skrzynkach? Czemu?",
  "I don't really know what I'll do with a deer horn.": "Nie wiem, co mi po rogu jelenia.",
  "Firstly they're called antlers and secondly, stay out here long enough and you'll get creative.": "Po pierwsze, to poroże, a po drugie, im dłużej tam jesteś, \ntym lepsze pomysły przyjdą ci do głowy.",
  "There's a horn or an antler or whatever.": "Jest tu róg, czy tam poroże, czy coś...",
  "There's a horn in here.": "Jest tu jakiś róg.",
  "People just stuff these things with old food? That's how you get bears.": "Ludzie upychają tu stare jedzenie? W ten sposób przyciąga się niedźwiedzie.",
  "I thought we weren't supposed to leave food out.": "Myślałem, że nie wolno nam zostawiać tu jedzenia.",
  "Whatever's in there has been in there for years. That's how you get food poisoning.": "Cokolwiek tam jest, leży od lat. Zatrucie pokarmowe jak się patrzy.",
  "You definitely do not want to do that.": "Naprawdę nie chcesz tego robić.",
  "There's a snack in here. I'm probably going to eat it.": "Jest tu jakiś batonik. Chyba go zjem.",
  "Hey, a snack!": "O, batonik!",
  "I found a flashlight.": "Znalazłem latarkę.",
  "Report flashlight": "Zgłoś latarkę",
  "There's one in there? Great.": "Naprawdę? To super.",
  "The sun's going to go down soon so if the batteries still work, you're in luck.": "Niedługo zajdzie słońce, więc jeśli baterie wciąż działają, \nmasz szczęście.",
  "GAH!": "Och!",
  "Y’know, I don't think there's any fictional character I hate more than Forrest Byrnes.": "Wiesz co, Lesiek Podpałka to najbardziej przeze mnie znienawidzona fikcyjna postać.",
  "Report thoughts on Forrest Byrnes.": "Zgłoś przemyślenia na temat Leśka Podpałki",
  "HENRY! As an employee of the Forest Service, that is treason!": "Henry! W ustach pracownika Służby Leśnej to zdrada stanu!",
  "Well he really freaked me out as a kid.": "Naprawdę bałem się go jako dziecko.",
  "He inspired me to spend the bulk of my thirties keeping the wilderness safe.": "To dzięki niemu sporą część dorosłego życia poświęciłam ochronie dzikich terenów.",
  "A shrink would have a field day with you.": "Psycholog miałby z tobą zabawę.",
  "Thanks mom.": "Dzięki, mamo.",
  "What kind of name is “Forrest Byrnes,” anyway?": "A co to w ogóle za imię, Lesiek Podpałka?",
  "What kind of name is that anyway?": "A co to w ogóle za imię?",
  "Well that would be a pun, Hank.  A glorious pun.": "Tu chodzi o żart słowny, Hank. I to dobry.",
  "I went to junior high with a guy named “Royal Butts.”": "Do liceum chodziłem z gościem, który nazywał się Rosław Zad.",
  "ROYAL?": "Rosław?",
  "Butts.": "Zad.",
  "Hahaha, I didn't think anyone had been named “Royal” since the 1850s!": "Chyba od lat 50. XIX wieku nikomu nie nadano imienia Rosław!",
  "Well, Royal's mom Flo was a bit of a trendsetter.": "Mama Zada, Flora, wiedziała, jak ustanawiać nowe trendy.",
  "His mom was creative.": "Jego mama miała fantazję.",
  "FLO BUTTS? Oh man, that's even worse!": "Flora Zad? To jeszcze gorzej!",
  "Well it's still better than “Forrest Byrnes.”": "Lepsze to niż Lesiek Podpałka.",
  "PAIRS PARES PEARS!": "Bóg, Bug, buk!",
  "What the hell?": "Co jest?",
  "Are you okay? You didn't just have a stroke did you?": "Nic ci nie jest? To nie był udar, co?",
  "Are you okay?": "Wszystko w porządku?",
  "No!": "Nie!",
  "Do you smell burnt toast?": "Czujesz przypalone tosty?",
  "Is this some sort of code I missed? Are we evacuating or something?": "To jakiś kod, o którym nie wiem? Ewakuujemy się, czy coś?",
  "Is this a code I missed?": "To jakiś kod, o którym nie wiem?",
  "Ha, no.": "Nie.",
  "Then what then?": "No to o co chodzi?",
  "I'm doing a crossword and I figured out the theme. It's homonyms. Pairs pares pears.  The clue was couples peeling fruit. Haha, anyway, hope you're having a good afternoon.": "Rozwiązuję krzyżówkę i wpadłam na klucz. To homonimy. \nBóg, Bug, buk. Chodziło o święte drzewo nad rzeką. \nW każdym razie mam nadzieję, że miło spędzasz popołudnie.",
  "Thanks?": "Dzięki?",
  "Umm, there's a critter out here. A raccoon.": "Jest tu jakiś zwierzak. Szop.",
  "Report raccoon": "Zgłoś szopa",
  "I can't understand you…": "Nie rozumiem cię...",
  "Because I'm whispering…": "Bo szepczę...",
  "Because you're whispering…": "Bo szepczesz...",
  "Report dead elk": "Zgłoś martwego wapiti",
  "I've got a dead elk out here. It's torn up something good.": "Znalazłem martwego wapiti. Nieźle jest poharatany.",
  "You think it got wise to a government program?": "Myślisz, że rozpracował rządowy program?",
  "Shut up.": "Przymknij się.",
  "I found a dead elk out here. It's wearing a tracking collar like the one I found at the site.": "Znalazłem tu martwego wapiti. Miał na szyi lokalizator, podobny do tego, który znalazłem w tamtym ośrodku.",
  "This elk is wearing a tracking collar.": "Wapiti ma na szyi lokalizator.",
  "The wave receiver picked it up.": "Namierzył go detektor fal.",
  "Is that right.": "Naprawdę?",
  "Yeah. It's numbered.": "Tak. Jest oznakowany.",
  "Like the subjects they were following.": "Jak te obiekty, które śledzili.",
  "Makes sense.": "Ma to sens.",
  "Yeah, like that.": "Dokładnie.",
  "That would make a lot of sense.": "To by miało sens.",
  "Yeah, it would.": "Właśnie.",
  "Maybe they were tracking elk at the site.": "Może w tamtym ośrodku namierzali wapiti.",
  "Maybe they were just tracking elk?": "A może po prostu namierzali wapiti?",
  "Maybe they were doing exactly what they said they were.": "Może robili to, o czym mówili.",
  "Yeah.": "Tak.",
  "There was lots of equipment there, they could've been up to a lot, you know?": "Tam była masa sprzętu. Mogli się zajmować Bóg wie czym, prawda?",
  "Yeah, sure.": "Tak, jasne.",
  "They could be.": "Możliwe...",
  "Hey, what’s to the south of here?    ": "Co jest na południe stąd?    ",
  "Report vista": "Zgłoś widok",
  "Uh, Mexico? Is this some sort of riddle?": "Meksyk? To jakaś zagadka?",
  "I just have a nice view to the south. Trees and mountains forever.": "Mam świetny widok na południe. Same góry i drzewa.",
  "Eventually you'll wander into the area overseen by Chimney Rock Lookout, but that's probably an impossible hike in terms of terrain.": "Dotarłbyś w okolice Wieży przy Kominowej Skale, ale taka piesza wędrówka w tym terenie jest niemożliwa.",
  "There’s a really nice waterfall down here.    ": "Jest tu śliczny wodospad.    ",
  "Report waterfall": "Zgłoś wodospad",
  "Do you know anything about this waterfall down here?": "Wiesz coś o tym wodospadzie?",
  "Given those girls' love of skinny dipping, I bet they're nearby.": "Skoro te dziewuchy lubią kąpać się na waleta, na pewno są niedaleko.",
  "I don't. We've got one over here that's a hundred and fifty feet tall.": "Nie bardzo. Jest tu jeden wysoki na niemal 500 metrów.",
  "One-upper.": "Popisówka.",
  "People snowmobile in during the winter to ice climb it.": "Zimą ludzie przyjeżdżają tutaj, żeby się na niego wspinać.",
  "I am not one of those people.": "Ja do takich ludzi nie należę.",
  "I am not that type of person.": "Ja taki nie jestem.",
  "Yeah, I figure there's enough normal ways to die.": "Jasne, jest tyle normalnych sposobów na śmierć.",
  "Agreed.": "Zgadzam się.",
  "What are these powerlines doing out here to the North?": "Co te linie telefoniczne robią tu, na północy?",
  "Report utility pole": "Zgłoś słup telefoniczny",
  "Those are comms lines. They connect folks like me to central command.": "To przewody komunikacyjne. Łączą takich ludzi jak ja z centralą.",
  "Got it.": "Jasne.",
  "AND if you can see them that means you turned north at the cave and far away from Two Forks. You should head back.": "Jeśli je widzisz, to znaczy, że odbiłeś przy jaskini na północ, z dala od Wieży na Rozdrożach. Powinieneś zawrócić."
}