{
  "Delilah": "Delilah",
  "Are you there? I had a thought.": "Jesteś tam? Naszła mnie pewna myśl.",
  "Alright, well let me know when you can talk.": "Dobra, odezwij się, gdy będziesz mógł rozmawiać.",
  "You had a thought": "Naszła cię myśl",
  "Henry": "Henry",
  "You said you had a thought.": "Mówiłaś, że naszła cię pewna myśl.",
  "You had a thought?": "Naszła cię myśl?",
  "Yeah, I did.": "Tak.",
  "Let's hear it.": "No to słucham.",
  "Yeah.": "Tak.",
  "You heard someone in the bushes.": "Słyszałeś kogoś w krzakach.",
  "Yeah…": "No...",
  "Okay, so let's assume we're being tailed. Or you are, at least.  Where are you right now?": "Więc załóżmy, że jesteśmy śledzeni. Albo przynajmniej ty. \nGdzie teraz jesteś?",
  "In a meadow on my way back.": "Na polanie, w drodze powrotnej.",
  "Just on my way back. In and out of trees, in the middle of nowhere.": "W drodze powrotnej. Niekiedy mijam drzewa, na zupełnym pustkowiu.",
  "Do you see anybody?": "Widzisz kogoś?",
  "No, definitely not.": "Nie, zdecydowanie nie.",
  "Alright, so tell me what you think of this—": "Dobrze, to powiedz mi, co o tym sądzisz...",
  "Did you just cough?": "Czy ty właśnie kaszlnąłeś?",
  "No, did you just cough?": "Nie. A ty?",
  "No.": "Nie.",
  "Teddy Krueger…": "Teddy Krueger...",
  "Oh fuck.": "O kurwa.",
  "Um, there isn't any way someone like another lookout could be on this line, is there?": "Nie ma szans, żeby inna wieża była na tej linii, co nie?",
  "No. Not without tapping our radios.": "Nie. Ktoś musiałby podłożyć pluskwę.",
  "What about when I heard you talking to someone else?": "A co z tą sytuacją, gdy słyszałem, jak rozmawiałaś z kimś innym?",
  "I just left your line open. That's not what this is.": "Po prostu zostawiłam otwartą linię. To nie to samo.",
  "Get in your tower. Shut the door. Don’t leave and don’t use your radio. I’ll call you. Understand? I will call you.": "Wracaj do swojej wieży. Zamknij się na klucz. Nie opuszczaj jej i nie korzystaj z krótkofalówki. Ja się odezwę, jasne?",
  "Alright, I don't know if you can hear me but I'm just going to lay into it.": "Dobra, nie wiem, czy mnie słyszysz, ale stawiam, że tak.",
  "So we'll just assume you're being tailed.": "Uznajmy jednak, że ktoś cię śledzi.",
  "I hope you're somewhere private right now…and if you're not, well…": "Mam nadzieję, że jesteś w jakimś odosobnionym miejscu. Jeśli nie, to cóż...",
  "This is what I think we should do–": "Uważam, że powinniśmy zrobić tak...",
  "So, uhh… here's a funny thing about ol' Delilah.": "Dowiesz się czegoś zabawnego o swojej koleżance Delilah.",
  "Okay…": "Okej...",
  "I'm a bit of pack-rat.": "Uwielbiam chomikować rzeczy.",
  "I have no doubt that this is relevant information.": "Przyznaję, że to niesamowicie ważna informacja.",
  "I keep everything. I mean, I have an entire drawer of parking tickets from like seven states.": "Niczego nie wyrzucam. Mam nawet całą szufladę pełną mandatów za złe parkowanie z siedmiu stanów.",
  "Wow, that's very thorough yet completely irresponsible of you. Congrats.": "Jesteś drobiazgowa, lecz to dość nieodpowiedzialne z twojej strony. Gratuluję.",
  "BUT… I'm not so good with the following up with stuff part.": "Ale czasem nie ogarniam już niektórych rzeczy.",
  "So those parking tickets?": "A te mandaty...",
  "Yeah, they're all unpaid. I'm the scourge of every meter maid from here to Mexico.": "Tak, wszystkie są niezapłacone. Jestem przekleństwem każdego krawężnika stąd do Meksyku.",
  "ANYWHO, I was digging through all of my documents and memos and updates and I found something from April about a fence in the middle of the woods. At Wapiti Meadows.": "Tak czy siak, przekopywałam się przez stosy dokumentów i notatek, gdy znalazłam coś z kwietnia o ogrodzeniu w środku lasu. W rejonie Polany Wapiti.",
  "Delilah…": "Delilah...",
  "I know, I know. It's about how we're supposed to report any damage to our bosses… or University officials.": "Wiem, wiem. Piszą w nim, że powinniśmy zgłaszać szkody przełożonym albo władzom uniwersytetu.",
  "University?": "Uniwersytetu?",
  "Because they're doing some sort of study. It's a research site.": "Robią tu jakieś pomiary. To jakiś ośrodek badawczy.",
  "So, the question is… what do we think they're studying?": "Pytanie brzmi... jakie według nas badania tam przeprowadzają?"
}