{
  "Henry": "Henry",
  "What the hell?!?": "Co do diabła?!",
  "Who the hell are you?!": "Coś za jeden?!",
  "I'll die in here you son of a bitch!": "Zginę tutaj, ty skurwysynu!",
  "HELLO!": "Halo!",
  "HELLO?!?": "Halo!?",
  "Holy shit.": "Cholera.",
  "I'm heading into the cave.": "Idę w kierunku jaskini.",
  "Alright, I'm headed in.": "Okej, idę.",
  "Delilah": "Delilah",
  "Okay. I don't know the last time anyone's been in there, officially, but if you need to use your ropes keep an eye out for anchor points; the ones that cavers leave are usually pretty safe.": "Nie wiem, kiedy ostatni raz ktoś tam był oficjalnie, ale jeśli będziesz musiał użyć liny, zwróć uwagę na punkty asekuracyjne poprzednich grotołazów. Przeważnie są bezpieczne.",
  "Usually.": "Przeważnie.",
  "These are folks who know what they're doing. More than you do, at least.": "Oni wiedzą, co robią. Przynajmniej bardziej niż ty.",
  "Delilah, someone locked me in the cave.": "Delilah, ktoś mnie uwięził w jaskini.",
  "Report locked gate": "Zgłoś zamkniętą bramkę",
  "Is this thing working?": "To w ogóle działa?",
  "DELILAH! SEND SOMEONE TO THE CAVE. PLEASE.": "Delilah! Wyślij kogoś do jaskini, błagam!",
  "I can't get any damn reception.": "Brak zasięgu...",
  "I don't think I can unlock it from this side.": "Z tej strony nie dam rady jej otworzyć.",
  "I'm screwed.": "Mam przesrane.",
  "Someone's been climbing in here, but the anchors are all gone.": "Ktoś się tu wspinał, ale wszystkie haki zniknęły.",
  "Yes. Yes.": "Tak, tak...",
  "Maybe I can get out through here.": "Może uda mi się tędy przedostać.",
  "It's freezing in here.": "Idzie tu zamarznąć.",
  "Jesus, this is a big cave.": "Jezu, duża ta jaskinia.",
  "Observe climbing anchor point": "Spójrz na punkt asekuracyjny",
  "Huh, an anchor was probably jammed right in here. Doesn't bode well for whoever was using it.": "Hak musiał tutaj utknąć. Nie za dobrze dla tego, kto go używał.",
  "Dammit, I can't go any further.": "Cholera, nie mogę iść dalej.",
  "Observe dead end": "Spójrz na ślepy zaułek",
  "IS ANYBODY DOWN THERE?!?": "Czy ktoś tu jest?!",
  "Footsteps": "Ślady",
  "Somone is running out of the cave": "Ktoś wybiega z jaskini"
}