{
  "Report fence": "Zgłoś ogrodzenie",
  "Henry": "Henry",
  "Hey, Delilah?": "Delilah?",
  "Delilah": "Delilah",
  "What do you got? You found them?": "Co tam? Znalazłeś je?",
  "What's up? You found the problem?": "Co tam? Znalazłeś nasze utrapienie?",
  "No, not yet.": "Nie, jeszcze nie.",
  "Well, what's wrong?": "Więc co się stało?",
  "Why would there be a fence out here?": "Na co komu ogrodzenie w takim miejscu?",
  "Oh, because sometimes hikers go ass over teakettle when on a trail.": "Czasem turyści się wywracają na szlaku.",
  "The Forest Service would put up a big chain link fence?": "I dlatego Służba Leśna postawiłaby wysokie ogrodzenie z metalowej siatki?",
  "A chain link fence?": "Metalowej siatki?",
  "Yeah. It looks like it surrounds a huge area.": "Tak. Wygląda na to, że otacza ogromny obszar.",
  "Huh. That's weird.": "To dziwne.",
  "Who are they keeping out of there… and why?": "Kogo chcą utrzymać na dystans... i dlaczego?",
  "Who are they keeping out?": "Od kogo chcą się odgrodzić?",
  "Ah geez. I don't know. Maybe it's biologists. You know?": "O Jezu, nie wiem. Może to biolodzy, wiesz?",
  "Well they don't want people traipsing on their precious lichens.": "Nie chcą, żeby ludzie zadeptywali ich cenne porosty.",
  "What's a lichen?": "Czym jest porost?",
  "Well wouldn't you lichen to know?": "Chciałbyś tak porostu wiedzieć, co?",
  "Oh my God. Goodbye!": "O mój Boże. Żegnam!",
  "But yeah, no idea about what's going on with that.": "Ale ogólnie nie mam pojęcia, o co chodzi z tym ogrodzeniem.",
  "I'll ask next time I talk to someone but that'll probably be a few days.": "Zapytam kogoś przy kolejnej rozmowie, niestety najwcześniej \nza kilka dni.",
  "What do you think they are keeping in? What do they not want to get out of there?": "Jak myślisz, co tam trzymają? Co chcą tam zatrzymać?",
  "What are they keeping in?": "Co tam trzymają?",
  "Well, geez. So *many* things.": "Mogę mnożyć teorie.",
  "Should I just stop you now?": "Powinienem cię powstrzymać?",
  "Maybe loads of hedgehogs.": "Mogą to być stadka jeży.",
  "Okay.": "Okej...",
  "Thousands, even. Full percentage points of the global hedgehog population.": "Pewnie są ich tam tysiące. Calutka światowa populacja jeży.",
  "Uh huh.": "Taa.",
  "The New Zealand government is up in arms. \"Where are all the hedgehogs?!\" Well, folks are hiding them all in Wyoming, that's where they are.": "Rząd Nowej Zelandii wariuje: „Gdzie zniknęły wszystkie jeże?!”. Znalazły schronienie w Wyoming, ot co.",
  "Who would do that? And why? Aha! That's the real mystery.": "Kto byłby do tego zdolny? I dlaczego? To ci dopiero tajemnica.",
  "Really glad I kept you in the loop! Thanks for all of the high quality information.": "Dopuszczenie cię do głosu było świetnym pomysłem. \nDzięki za te jakże cenne informacje.",
  "Okay, okay. I'll ask what's up if I talk to someone in the next few days who I think might know.": "Dobra, dobra. Postaram się niedługo porozmawiać o tym z kimś, kto może być obeznany w temacie.",
  "Hey, remember that guy from yesterday? The guy I saw hiking home?": "Pamiętasz tego gościa z wczoraj? Tego, na którego wpadłem podczas powrotu?",
  "Remember the guy yesterday?": "Pamiętasz gościa z wczoraj?",
  "The sheet thief!": "Złodziej prześcieradeł!",
  "The completely unmotivated vandal!": "Wandal z przypadku!",
  "Yep. That guy.": "Tak, dokładnie.",
  "Go on.": "Kontynuuj...",
  "Yes…": "Tak...",
  "Maybe he was from this fence place.": "Może przybył zza tego ogrodzenia.",
  "Maybe he was from the fence place.": "Może przybył zza ogrodzenia.",
  "Mmmm, from the land of the fence.": "Przybysz zza płota...",
  "Yes.": "Tak.",
  "You know what, I'll make a note. You might be onto… something.": "Wiesz co, zanotuję to. Możesz być na tropie... czegoś.",
  "Hey, remember that guy from a couple days ago?": "Pamiętasz tego kolesia sprzed kilku dni?",
  "Remeber that guy from a couple days ago?": "Pamiętasz tego kolesia sprzed kilku dni?",
  "Hey, remember that guy from a few weeks back? The guy I saw while hiking home on my first day?": "Pamiętasz tego kolesia sprzed kilku tygodni? Natknąłem się na niego pierwszego dnia podczas powrotu.",
  "Remeber the guy from a few weeks ago?": "Pamiętasz tego kolesia sprzed kilku tygodni?",
  "Do you think those girls could be behind this fence?": "Myślisz, że te dziewczyny mogą być za ogrodzeniem?",
  "Could those girls be behind this fence?": "Czy te dziewczyny mogą być za ogrodzeniem?",
  "Hmm. Well, having once been an ornery young woman, the last thing I would want to do is climb a fence. Especially if I knew I was in trouble.": "Za czasów, gdy byłam upartą, młodą kobietą, nie przyszłoby mi \nna myśl, by wspinać się na ogrodzenie. Zwłaszcza gdybym \nwiedziała, że jestem w tarapatach.",
  "Yeah. I don't even know how I would get in.": "No tak. Nie wiem nawet, jakbym miał tam wejść.",
  "It's really strange that that's out there, by the way.": "Swoją drogą, to strasznie dziwna sprawa.",
  "Yeah, it's weird.": "Tak, to dziwne.",
  "Who are they keeping out of here… and why?": "Kogo chcą utrzymać na dystans... i dlaczego?"
}