{
  "Henry": "Henry",
  "Hey, sorry. Guess I slept in.": "Hej, wybacz, chyba zaspałem.",
  "Sorry, guess I slept in.": "Wybacz, chyba zaspałem.",
  "Yeah, Jesus. I guess it's, what, six?": "Jezu, która godzina, szósta?",
  "Delilah": "Delilah",
  "6:45.": "18:45.",
  "Whoops.": "Ups...",
  "Don't worry about it. That hike puts everyone out of commission for a day or two.": "Nie przejmuj się. Taka wyprawa każdego wyłącza z gry \nna dzień czy dwa.",
  "But now that you're up, let me quickly get you acquainted with the job.": "Ale skoro już wstałeś, pozwól, że zapoznam cię z twoimi obowiązkami.",
  "There's a thing in the middle of your room with a round map on it. Do you see it?": "Na środku pokoju jest takie coś okrągłego z mapą. Widzisz?",
  "It's right in the middle of your room.": "Dokładnie na samym środku.",
  "You can't miss it.": "Nie sposób nie zauważyć.",
  "I'll wait.": "Poczekam...",
  "But I won't wait all day. Just radio me when you find it.": "Ale nie mam całego dnia. Odezwij się, jak już to znajdziesz.",
  "Okay, yeah, I see it.": "Dobra, jest, widzę.",
  "Report map table": "Zgłoś stolik z mapą",
  "This is the Osborne Fire Finder, invented in 1914 by W.B….": "To jest kierunkomierz Osborne'a, wynaleziony w 1914 przez W.B...",
  "…Osborne?": "Osborne'a?",
  "Ahh, yes.": "No tak.",
  "Sorry.": "Wybacz...",
  "You use this to spot, you guessed it, fi—what the fuck?": "Używa się go do oznaczania, jak pewnie zgadłeś, poż... \nCo jest, kurwa?",
  "What is it?": "O co chodzi?",
  "Nothing. Um, you use this to—oh, fuck me!": "Nic takiego... Używa się go do... ja pierdolę!",
  "Good god— language, lady…": "Dobry Boże, kobieto, co to za słownictwo...",
  "Out your west-facing window—are you seeing what I'm seeing?": "Wyjrzyj przez zachodnie okno. Widzisz to samo co ja?",
  "Are those fucking fireworks?!": "To fajerwerki!?",
  "I need you to confirm. Do you see them?": "Potwierdź, czy też je widzisz?",
  "Seriously, are you seeing this?": "Serio, też to widzisz?",
  "Henry?": "Henry?",
  "Whoa!": "Rany!",
  "Report fireworks": "Zgłoś fajerwerki",
  "That's not legal, right?": "To nielegalne, prawda?",
  "Uh, no!": "Jasne, że nie!",
  "You need to get down there right now and stop them. Fire danger is through the fucking roof.": "Musisz tam iść i to przerwać. Zagrożenie pożarowe jest kurewsko wysokie.",
  "Go down there and set 'em straight.": "Idź tam i ich naprostuj.",
  "Is that really my job?": "Serio mam się tym zająć?",
  "Your job is whatever I say it is. The closest ranger is, like, two days away.": "Masz się zająć tym, czym mówię. Najbliższy leśniczy jest oddalony o jakieś dwa dni drogi.",
  "Do you think you can handle that?": "Myślisz, że dasz sobie radę?",
  "I'm sorry it's not in the job description.": "Przepraszam, że to wykracza poza twoje obowiązki.",
  "Look, just go down there, okay? Make sure they stop with this shit.": "Po prostu tam idź, dobra? Upewnij się, że przestaną.",
  "Like, kick the shit out of them sorta straight?": "Naprostować ich na kopach?",
  "Like, kick the shit out of them?": "Mam dobrać im się do dupy?",
  "Do I write them a ticket?": "Wypisać im mandat?",
  "Can I write them a ticket?": "Mogę wypisać im mandat?",
  "I’m not really a disciplinarian type of guy.": "Sianie postrachu to nie moja specjalność.",
  "I'm not really into discipline.": "Karcenie innych średnio mi wychodzi.",
  "No no no no no! Jesus, no.": "Nie, nie! Jezu...",
  "What? I’m not a cop. It’s not like I've got a rulebook over here!": "No co? Nie jestem gliną. Przecież nie mam przy sobie podręcznika!",
  "Just make sure they don’t do it again. Take their shit.": "Po prostu upewnij się, że tego nie powtórzą. Skonfiskuj ich rzeczy.",
  "Alright, fine.": "Dobra, spoko.",
  "Don’t feed anyone a knuckle sandwich.": "Tylko nie przywal nikomu.",
  "Easy there, Dirty Harry.": "Spokojnie, Brudny Harry.",
  "Well…?": "No?",
  "Well make them knock it off without smoking a joint with them, okay?": "Po prostu każ im przestać, ale się za bardzo nie spoufalaj, dobra?",
  "Sure. Alright.": "Jasne.",
  "Good.": "Dobrze.",
  "Get going. You’ll probably need a rope to get down the shale between you and the lake if I remember right.": "Idź już. Pewnie będzie ci potrzebna lina, żeby zejść po skałach po drodze nad jezioro, jeśli mnie pamięć nie myli.",
  "There should be one in the supply box on the way.": "Powinieneś znaleźć jakąś po drodze w skrzynce z zasobami.",
  "The code is \"1-2-3-4.\" It’s actually that for all of them.": "Szyfr do kłódki to 1-2-3-4. W sumie do każdej z nich.",
  "Secure.": "Bezpiecznie...",
  "Convenient.": "Wygodnie...",
  "Smart.": "Sprytnie...",
  "Shut up.": "Przymknij się.",
  "That's one word for it.": "Można i tak to ująć.",
  "So now you're ready to work.": "No to jesteś gotowy do pracy.",
  "I'm new. I wanted to look around.": "Jestem nowy. Chciałem się rozejrzeć.",
  "Honestly, on my first day I did the same thing.  So, anyway.": "Szczerze, to pierwszego dnia zrobiłam tak samo. W każdym razie...",
  "Hey, I see your lookout tower.": "Widzę twoją wieżę.",
  "Great. Do you see me flipping you the bird while the Absaroka wilderness burns down thanks to an idiot with a Roman candle?": "Świetnie. A widzisz, jak pokazuję ci środkowy palec, podczas gdy cała Absaroka idzie z dymem przez idiotę z rzymskimi ogniami?",
  "Mmm, no. You're too far away.": "Nie, jesteś za daleko.",
  "Well I am.": "Tak, widzę.",
  "You got a relaxing, what, fourteen hours of sleep? Whew!": "Relaksowałeś się przez jakieś czternaście godzin snu? Nieźle!",
  "Good morning, Henry.": "Dzień dobry, Henry.",
  "Well, I guess \"good afternoon.\" You probably slept like a rock.": "Albo raczej witaj popołudniu. Chyba spałeś jak zabity.",
  "Anyway, there's still a few hours of daylight to get some work in.  I can see you at your desk, so call me when you're ready.": "Mamy jeszcze kilka godzin dnia, żeby popracować. Widzę, że jesteś przy biurku, więc odezwij się, jak będziesz gotów."
}