{
  "Delilah": "Delilah",
  "You're going fishing without a license?": "Idziesz na ryby bez karty wędkarskiej?",
  "Henry": "Henry",
  "It's ONE fish. And I'm sick of all the stuff I've got to eat.": "Chcę tylko jedną rybę. Mam już dość jedzenia, które tu dostaję.",
  "Well maybe you shouldn't have taken SO MUCH of it then.": "Może więc nie powinieneś go tyle zabierać.",
  "I won't tell anyone you're a poacher.": "Nikomu nie powiem, że jesteś kłusownikiem.",
  "That reminds me, I keep hearing reports from Fish & Game about a problem bear they’re trying to keep tabs on. Can you search around the lake for fresh tracks and just let me know what you find?": "Przypomniało mi się, że ciągle dostaję raporty od Fish & Game \no problematycznym niedźwiedziu, którego obserwują. Możesz \nposzukać świeżych śladów przy jeziorze i dać mi znać, jak \ncoś znajdziesz?",
  "There was a crew burning fire lines out to the east and um, you know, I think sometimes it riles up the wildlife.": "Była tam ekipa wypalająca teren na wschód i myślę, że to mogło nieco rozdrażnić dzikie zwierzęta.",
  "“Problem bear?” Fuck that, I’m of the opinion that they are ALL problems.": "„Problematyczny niedźwiedź”? Jebać to, dla mnie one wszystkie \nsą problematyczne.",
  "\"Problem bear?\" Fuck that.": "„Problematyczny niedźwiedź”? Jebać to.",
  "Come on, pleeease.": "No weź, proszę.",
  "Sure, no problem. Remember me fondly.": "Jasne, nie ma problemu. Tylko dobrze mnie wspominaj.",
  "Sure thing.": "Jasne.",
  "You are such a drama queen.": "Nie dramatyzuj.",
  "Does “problem” actually mean “murderer?” Like, is Charles Manson a “problem” cult leader?": "Czy „problematyczny” znaczy tyle co „morderczy”? Tak jak czy Charles Manson to „problematyczny” sekciarz?",
  "Is \"problem\" a euphemism?": "Czy „problematyczny” to eufemizm?",
  "Oh, come on! You just have to look for tracks, that’s it!": "No weź! Masz tylko poszukać śladów, nic więcej!",
  "Yeah well, I’ve seen what they can do a tree and trees aren’t even food.": "Widziałem, jak potrafią załatwić drzewo, a to nawet nie jest dla nich jedzenie.",
  "I can’t believe I’m going to leave this planet as a pile of bear shit.": "Nie mogę uwierzyć, że skończę swój żywot jako niedźwiedzie gówno.",
  "THANK YOU, HENRY.": "Dziękuję, Henry.",
  "Yeah, yeah.": "Dobra, dobra.",
  "Someone left their clipboard out here.": "Ktoś zostawił tutaj swój notatnik.",
  "Report clipboard": "Zgłoś notatnik",
  "Huh, It could've been one of the fish and game folks. See if there's a name or a credential or something, I can call it in.": "Może należeć do kogoś z Fish & Game. Sprawdź, czy jest na nim jakieś imię czy inne dane, mogę to zgłosić.",
  "What the…?": "Co do...",
  "D — I found a clipboard down here and, I… there's something strange going on.": "D... Znalazłem tutaj jakiś notatnik i... jest na nim napisane coś dziwnego.",
  "I found something.": "Znalazłem coś.",
  "At the lake? What’s up?": "Przy jeziorze? Co takiego?",
  "It's — holy shit.": "To... o w mordę.",
  "What's going on? You didn’t actually find a bear, did you?": "Co się dzieje? Chyba nie natrafiłeś na niedźwiedzia, prawda?",
  "Someone has written down what we said to each other. Have been saying.": "Ktoś spisał naszą rozmowę. Wszystko, co do siebie mówiliśmy.",
  "That doesn't make any sense.": "To nie ma najmniejszego sensu.",
  "\"I don't talk to the other lookouts as much as I talk to you. Not in the same way.\"": "„Nie rozmawiam z innymi obserwatorami tyle co z tobą. \nNie w ten sam sposób”.",
  "No way.": "Nie gadaj.",
  "Wait. Hold on. Something's out here.": "Czekaj, chwila. Coś tu jest.",
  "What is it? What's out there?": "Co to? Co tam jest?",
  "Henry? I'm worried.": "Henry? Martwię się.",
  "You didn't find and eat any mushrooms, did you? They can be fun but also, you know, devastating.": "Nie nażarłeś się żadnych grzybków, co? Jasne, sprawiają radość, \nale mogą też oszołomić.",
  "Regardless, just let me know, okay buckaroo?": "Tak czy siak, daj mi znać. Dobrze, kowboju?",
  "Oh God, I don't know why I just called you that.": "Boże, nie wiem, czemu tak cię nazwałam.",
  "I found a walkie-talkie out here too.": "Znalazłem jeszcze krótkofalówkę.",
  "Report dropped radio": "Zgłoś zostawioną krótkofalówkę",
  "Okay…": "Okej...",
  "It's going shit-house.": "To jakaś paranoja.",
  "Get it if you haven't already and then we'll figure out whose it is.": "Weź ją, jeśli jeszcze tego nie zrobiłeś i dowiemy się, do kogo należy.",
  "Will do…": "Zrobi się...",
  "UGH!": "Uch!",
  "Henry? Are you there?": "Henry? Jesteś tam?",
  "What happened?! Henry?": "Co się stało?! Henry?",
  "Hey, Henry, you around?": "Hej, Henry, jesteś tutaj?",
  "I… holy hell, I got hit in the head. Punched or something by someone. ": "Jasna cholera, oberwałem w głowę. Ktoś mi chyba przywalił. ",
  "Report attack": "Zgłoś atak",
  "Are you serious?! What the hell is going on out there?": "Mówisz poważnie?! Co się tam dzieje, do diabła?",
  "I don't know, Jesus Christ!": "Nie wiem, Jezu Chryste!",
  "Let me get this straight, you found a clipboard with, what, transcripts of our conversations? What else is on it?": "Poczekaj... Znalazłeś notatnik z... zapisem naszych rozmów? \nCo tam jeszcze było?",
  "I don't know! It's gone. Along with a radio of theirs. Somebody out here could've just killed me, Delilah.": "Nie wiem! Ktoś go zabrał. Razem z krótkofalówką. \nWłaśnie mogłem zostać zabity, Delilah.",
  "What the fuck… what is going on?": "Kurwa... co się dzieje?",
  "Are you sure you saw what you saw, Henry? Maybe you pissed off some more campers and they came back to sucker punch you.": "Jesteś pewien, że właśnie to widziałeś, Henry? Może wkurzyłeś jakichś biwakowiczów, a oni uderzyli cię z partyzanta.",
  "Look, I know what I saw. It was our words, with initials for our names, H and D, clear as day.": "Wiem, co widziałem. To były nasze słowa z naszymi inicjałami, \n„H” i „D”, wypisane jak na dłoni.",
  "I know what I saw.": "Wiem, co widziałem.",
  "You… you haven’t been drinking, have you?": "Chyba... nie piłeś, prawda?",
  "And you've been feeling okay?": "I czujesz się dobrze?",
  "I feel fine.": "Tak.",
  "NO. Jesus!": "Jezu, nie!",
  "Okay, okay, I'm sorry, I believe you. But that conversation was from TWO WEEKS AGO.": "Dobra, dobra, przepraszam, wierzę ci. Ale ta rozmowa odbyła się dwa tygodnie temu.",
  "Why would I make this up? It's an insane lie at worst and a shitty prank at best.": "Czemu miałbym zmyślać? Nie kłamałbym, a tym bardziej nie robił gównianych żartów.",
  "Why would I make this up?": "Czemu miałbym zmyślać?",
  "There are people listening to our conversations. The person or these people were hiding in the bushes down here. What the fuck, D?": "Jacyś ludzie podsłuchują naszych rozmów. Ktoś czaił się tutaj \nw krzakach. Co to ma być, do cholery, D?",
  "There are people listening.": "Ktoś nas podsłuchuje.",
  "I don't know, Henry. This sounds… crazy.": "Nie wiem, Henry. To brzmi... absurdalnie.",
  "And you're not the one who just saw our words on a clipboard out in the middle of nowhere.": "To nie ty znalazłaś notatnik z zapisem naszych rozmów na zupełnym pustkowiu.",
  "Those words were from two weeks ago.": "Ta rozmowa jest sprzed dwóch tygodni.",
  "This just seems like a misunderstanding or something.": "Wygląda mi to na nieporozumienie, czy coś takiego.",
  "Are you sure you were actually attacked?": "Jesteś pewien, że cię zaatakowano?",
  "You've been out here by yourself for a long time.": "Już od jakiegoś czasu jesteś tam całkiem sam.",
  "Ugh, Henry, those  conversations were from two weeks ago!": "Henry, te rozmowy są sprzed dwóch tygodni!",
  "I know they were. So what's to say they don't have transcripts from three, four, five weeks ago?": "Wiem o tym. Więc dlaczego nie mieliby też zapisów sprzed trzech, czterech albo pięciu tygodni?",
  "Our entire relationship. Friendship. Our whole summer.": "Cały nasz związek. Przyjaźń. Całe nasze lato.",
  "Someone is out here with a walkie talkie taking notes and talking to God knows who.": "Ktoś łazi tu sobie z walkie-talkie, robi notatki i rozmawia z Bóg wie kim.",
  "How do you know that?": "Skąd to wiesz?",
  "I found a radio right before I got hit, and it's gone, along with the notes.": "Zanim mnie ktoś uderzył, znalazłem krótkofalówkę, ale nie ma ani jej, ani notatek.",
  "What is \"Wapiti Station?\"": "Czym jest „Stacja Wapiti”?",
  "I don't know.": "Nie wiem.",
  "I saw the name Wapiti Station right before I was cold-cocked.": "Widziałem napis Stacja Wapiti, zanim ktoś mnie ogłuszył.",
  "Does Wapiti Station mean anything to you?": "Czy nazwa Stacja Wapiti coś ci mówi?",
  "Uhhh, Wapiti Meadow.  Maybe it's Wapiti Meadow.": "Polana Wapiti. Może chodzi o Polanę Wapiti.",
  "It's on our maps; it's not too far from where you are right now.": "Jest na mapie. To niedaleko od miejsca, w którym teraz jesteś.",
  "It's where you saw that damn fence.": "To właśnie tam widziałeś to cholerne ogrodzenie.",
  "It's north of the lake.  It looks like there should be a trail somewhere on the north shore of Jonesy Lake.": "To na północ od jeziora. Gdzieś w pobliżu powinna być ścieżka, \nprzy północnym brzegu jeziora Jonesy.",
  "I'll start hiking that way now. Goddamn, my head…": "Zacznę maszerować w tamtą stronę. Cholera, mój łeb...",
  "I could hike over there and look around but I won't be able to get through the fence.": "Mogę tam pójść i się rozejrzeć, ale nie dam rady przejść przez ogrodzenie.",
  "How do you know?": "Skąd wiesz?",
  "I already tried, months ago, when I was out there hiking.": "Już próbowałam kilka miesięcy temu, kiedy tamtędy przechodziłam.",
  "Curiosity got the best of you, huh?": "Ciekawość nie dała za wygraną, co?",
  "Rightfully so, in hindsight.": "Z perspektywy czasu, to tak.",
  "Well shit.": "Cholera.",
  "I could spend all day banging on it and see, I guess.": "Mógłbym walić w nie cały dzień, żeby się przekonać.",
  "Well, you're probably already on your way. Be safe.": "Pewnie już idziesz w tamtą stronę. Uważaj na siebie.",
  "I'll hike out there and get some answers.": "Pójdę tam i znajdę odpowiedzi.",
  "I'll get to the bottom of this.": "Rozgryzę to.",
  "Great. Just keep a clear head. Don't, you know, do anything crazy.": "Super. Pamiętaj, myśl trzeźwo. Nie zrób nic szalonego.",
  "Like taking a job in the middle of nowhere with literally no escape from whatever or whoever is out there?": "Tak szalonego jak podjęcie pracy na pustkowiu bez możliwości ucieczki przed kimkolwiek lub czymkolwiek?",
  "Well, I meant like, kill anybody.": "Chodziło mi o to, żebyś nikogo nie zabił.",
  "You got it, boss.": "Jasne, szefie.",
  "We should just get the hell out of here.": "Powinniśmy stąd spadać.",
  "We should leave.": "Powinniśmy stąd odejść.",
  "Ugh, it's a two day hike. You're welcome to do it but you're going to catch hell from the service and have to explain yourself.": "To dwa dni wędrówki. Zrobisz po swojemu, ale dostaniesz ochrzan od przełożonych i będziesz się musiał tłumaczyć.",
  "Plus, theres' a fire burning across Rose Creek. You hiked through there on the way in.": "Do tego po drugiej stronie Różanego Potoku szaleje pożar. Przyszedłeś właśnie tamtędy.",
  "Call someone and tell them to come get me.": "Wezwij kogoś i powiedz, żeby mnie stąd zabrali.",
  "I am not going to book a fifteen thousand dollar helicopter ride for you. I'm not doing it.": "Nie zamówię dla ciebie lotu śmigłowcem za piętnaście tysięcy dolarów. W życiu.",
  "We can't freak out. There's got to be a reasonable explanation for all of this.": "Nie dajmy się zwariować. To wszystko na pewno da się logicznie wytłumaczyć.",
  "You're right. You're right.  I'll head to Wapiti Meadow but I swear, if this gets worse, you better get on the horn and get us out of here.": "Masz rację. Pójdę na Polanę Wapiti, ale serio, jeżeli się pogorszy, \nto masz wezwać pomoc i nas stąd zabrać.",
  "I'll call around and see if anything weird is happening to anyone else, okay?": "Podpytam innych, czy im też przytrafiają się dziwne rzeczy, okej?",
  "That sounds good.": "Brzmi nieźle.",
  "What do you think is going on behind that fence?": "Jak myślisz, co jest za ogrodzeniem?",
  "What is going on behind that fence?": "Co jest za tamtym ogrodzeniem?",
  "What the hell do you think is going on at this place?": "Jak myślisz, co jest za tym cholernym ogrodzeniem?",
  "What is going on?": "Co się dzieje?",
  "Uh, apparently a lot of following you around taking notes.": "Najwyraźniej jacyś ludzie, których zadaniem jest śledzić cię i robić notatki.",
  "Which is un-fucking-believable, Henry.": "Co jest, kurwa, nie do uwierzenia, Henry.",
  "You're telling me. Alright I'm on my way to Wapiti Meadow; I'll let you know what I find.": "Nie musisz mi mówić. Dobra, idę w stronę Polany Wapiti. \nDam ci znać, jak coś znajdę.",
  "Okay. There's got to be a reasonable explanation.": "Okej. Na pewno da się to jakoś logicznie wyjaśnić.",
  "Also, I'm going to call around and see if anyone has had anything weird happen to them or seem spooked. Ahh, I don't want to make this bigger  than it is, yet, you know?": "Podpytam innych, czy przydarzyło im się coś dziwnego albo czy coś ich przestraszyło. I nie chcę, żeby to wyglądało poważniej niż już jest, dobrze?",
  "Yeah, understood.": "Rozumiem.",
  "Yeah, okay. Hike safe.": "Dobra, to spokojnej drogi.",
  "So what do you think?": "To co myślisz?",
  "So what, then?": "To co teraz?",
  "What about that university research area. What the fuck are they up to?": "Co z tą uniwersytecką placówką badawczą? Co tam się odpierdala?",
  "What about those researchers?": "Co z tymi badaczami?",
  "What about the missing girls?": "Co z zaginionymi nastolatkami?",
  "What about those missing teens?": "Co z zaginionymi nastolatkami?",
  "What about them?  You think it's them? They've just been out here obsessed with you? That's ridiculous.": "Co z nimi? Myślisz, że to one? Prześladują cię, bo wpadły w obsesję na twoim punkcie? Nie bądź śmieszny.",
  "Or it's whoever is responsible for them disappearing.": "Albo to sprawka osoby odpowiedzialnej za ich zniknięcie.",
  "That's… I don't know.": "Tego... nie wiem.",
  "Hey… fuck, have you seen that fenced off area north of the lake?": "Kurwa, widziałaś ten ogrodzony obszar na północ od jeziora?",
  "Excuse me?": "Słucham?",
  "Okay, so look, the university is out here doing some sort of research. They've been at it for a long time.": "Uniwersytet prowadzi tu jakieś swoje badania. Siedzą w tym miejscu od dłuższego czasu.",
  "Yeah… look, I’ve already tried to get in there. Months ago.": "Próbowałam się tam dostać parę miesięcy temu.",
  "Oh really.": "Serio?",
  "Yeah, I, gave it a whirl.": "Tak, zaszalałam raz.",
  "Well that’s fucking fishy.": "To jest cholernie podejrzane.",
  "Well not in hindsight, is it?  It was locked up too tight back then and I doubt anything’s changed.": "Może z perspektywy czasu. Już wtedy było wyzamykane na cztery spusty, wątpię, by coś się w tej kwestii zmieniło.",
  "Well, if you were a firefighter instead of some piddly lookout, you would’ve gotten in there lickety split.": "Jeśli byłbyś strażakiem, a nie jakimś tam obserwatorem, dostałbyś się tam w mgnieniu oka.",
  "Well, what the hell are they doing?": "Co oni tam, u diabła, wyprawiają?",
  "They were SUPPOSED to be sexing horned toads or some shit.  But what if they're not.": "Mieli ponoć badać rozmnażanie rogatych jaszczurek, czy coś w ten deseń. A co jeśli tak nie jest?",
  "Do you think it’s possible that a university could, be, what, studying people without their consent?": "Sądzisz, że uniwersytet byłby w stanie, nie wiem... prowadzić obserwacje ludzi bez ich zgody?",
  "I don’t trust those fucking bookworms.  If you wanted to study, say, the psychological effects of being alone in the woods, wouldn’t this be a pretty good laboratory?": "Nie ufam tym jajogłowym. Jeśli chciałbyś badać, powiedzmy, psychologiczny efekt życia w odosobnieniu w lesie, nie uważasz, że to miejsce świetnie by się do tego nadawało?",
  "That’s unethical, though.": "To nieetyczne.",
  "That's unethical.": "To nieetyczne.",
  "Oh, Henry.": "Henry.",
  "But yeah, I suppose you're right. We'd make for pretty good lab rats.": "Ale tak, myślę, że masz rację. Bylibyśmy dobrymi królikami doświadczalnymi.",
  "That’s what I would do. Find a bunch of sad sacks in the woods and see what being alone does to them.": "Ja bym tak zrobiła. Wzięła kilka oferm do lasu i obserwowała, co życie w odosobnieniu z nimi zrobi.",
  "That's what I would do.": "Tak bym postąpiła.",
  "We are ONE sad sack.": "My jesteśmy takimi ofermami.",
  "Don’t tell that to Javier.": "Nie mów tego Javierowi.",
  "Oh shut up.": "Zamknij się.",
  "Yeah, I’m not so sure about that.": "Nie jestem tego taki pewien.",
  "Anyway, you should head there and see what you can find.": "Tak czy inaczej, udaj się tam i zobacz, co znajdziesz.",
  "You remember how to get there?": "Pamiętasz, jak tam dotrzeć?",
  "Yeah, it’s north of the lake.": "Na północ od jeziora.",
  "Again, it’s north of the lake.": "Powtarzam, na północ od jeziora.",
  "Got it.": "Jasne.",
  "I can’t get over how ridiculous this all sounds.": "Wciąż do mnie nie dociera, jakie to wszystko jest absurdalne.",
  "I can’t get over the ringing in my ears from being sucker punched.": "Jeszcze mi dzwoni w uszach po tym, jak dostałem w głowę.",
  "I can't get over being punched.": "Nadal dzwoni mi w uszach po tym ciosie.",
  "To hell with this.": "Do diabła z tym."
}