{
  "Henry": "Henry",
  "I’ve got an overgrown trail here.": "Szlak w tym miejscu zarastają chaszcze.",
  "Report overgrown trail": "Zgłoś zarośnięty szlak",
  "There’s really no way past some of this underbrush that’s grown over the trail.": "Szlak w tym miejscu zarosły takie gęstwiny, że nie mam szans się przez nie przedrzeć.",
  "Delilah": "Delilah",
  "See, the thornier the trail is, the less inclined a ranger is to want to deal with it.  They’ll just hike or take their horse a different way.": "Widzisz, chęć leśniczego, by obrać daną ścieżkę spada wprost proporcjonalnie do stopnia jej zarośnięcia. Zwykle obchodzą je wtedy naokoło.",
  "Yeah, that’ll happen.": "Tak, to się zdarza.",
  "So I’m screwed when it comes to getting past it.": "Czyli mogę zapomnieć o tym skrócie?",
  "Screwed until you clear it yourself, yeah.": "Dopóki go sobie nie wykarczujesz, owszem.",
  "Great. Well, if I come across some tools, I’ll add grounds-keeping to my ever increasing list of responsibilities.": "Świetnie. Jeśli napotkam jakieś narzędzia, dopiszę sobie ogrodnictwo do mojej stale rosnącej listy obowiązków.",
  "Guess what?": "Zgadnij, co się stało?",
  "Report blocked trail": "Zgłoś zablokowany szlak",
  "Clearing these trails is oddly satisfying.": "Odkrzaczanie tych ścieżek sprawia mi dziwną satysfakcję.",
  "You’re not getting paid extra for that, you know.": "Tylko nie spodziewaj się podwyżki.",
  "Finding out what the hell is going on is payment enough.": "Wystarczy, że w zamian odkryję, co tu się, u diabła, wyprawia.",
  "Whatcha got?": "No co tam?",
  "I found an axe back near that camp.": "Znalazłem topór w pobliżu tamtego obozowiska.",
  "A firefighter left it?": "Jakiś strażak go zostawił?",
  "Probably, yeah.": "Najpewniej tak.",
  "It’s got, like, a funny little point?": "Jest z jednej strony śmiesznie zakończony?",
  "Sure does.": "Dokładnie.",
  "Okay, that’s called a Pulaski. It's standard issue.": "Dobra, czyli to siekiera Pułaskiego. Standardowe wyposażenie.",
  "Whatever, this PULASKI I found means I can start clearing these trails.": "Nieważne, jak się fachowo nazywa. Grunt, że mogę sobie nią przetrzeć nowe szlaki.",
  "You think I’d have gotten strong enough to climb back up some of these drop offs but, here I am. Stuck.": "Myślałby kto, że po tym czasie mam już dość siły, by wspinać się po tych skarpach, a jednak... Znów utknąłem.",
  "Report long drop": "Zgłoś skarpę",
  "Yeah, well, we’ve all got our limits, Henry.": "Wszyscy mamy swoje ograniczenia, Henry.",
  "I gotta tell you, all this climbing and jumping is pretty invigorating.": "Muszę przyznać, że te wspinaczki i zeskoki pobudzają do działania.",
  "Just wait for the rest of the summer when you’ll be sitting on your fat ass fourteen hours a day!": "Poczekaj tylko, aż resztę lata spędzisz, siedząc na swoim tłuściutkim tyłku przez czternaście godzin dziennie!",
  "Well, I hopped down a drop and now I can’t climb back up.": "Zeskoczyłem właśnie ze skarpy, to była podróż w jedną stronę.",
  "Mmm, that is a pickle.": "Masz ci los.",
  "I can just keep hiking, but I figured I should let you know in case I get myself trapped out here.": "Mogę wędrować dalej, ale wolałem cię o tym poinformować \nna wypadek, gdybym utknął tu na dobre.",
  "Hopefully that doesn’t happen before you find these assholes. I was thinking you should probably head back to where you saw them last.": "Mam nadzieję, że najpierw odnajdziesz te kretynki. Tak sobie myślę, że powinieneś zawrócić do miejsca, gdzie widziałeś je po raz ostatni.",
  "How adventurous of you.": "Drzemie w tobie dusza podróżnika.",
  "I’ve been doing a lot more climbing out here than I expected.": "Muszę łazić po tych górach znacznie częściej, niż zakładałem.",
  "Well, keep your radio charged. I’d hate to one day find a skeleton with an orange backpack at the bottom of a ravine.": "Utrzymuj krótkofalówkę naładowaną. Nie chciałabym któregoś dnia odnaleźć na dnie wąwozu szkieletu z pomarańczowym plecaczkiem.",
  "Report old radio": "Zgłoś starą krótkofalówkę",
  "Hey, about my old, uh, walkie talkie…": "Jeśli chodzi o moje stare walkie-talkie...",
  "I don't care. Destroy it, keep, whatever you want.": "Mam to gdzieś. Zniszcz je albo zatrzymaj, wedle uznania.",
  "No Reception": "Brak zasięgu",
  "Shale Slide": "Osuwisko",
  "Shitty Boss Is Gonna Get Me Killed Hill": "Wzgórze walniętej szefowej, która wpędzi mnie do grobu",
  "Widowmaker": "Wdowiarka",
  "Cripple Gulch": "Wąwóz Inwalidów"
}