{
  "Henry": "Henry",
  "Is it too much of a pain in the ass to bring supplies all the way up our towers?": "Czy naprawdę tak ciężko dostarczyć zaopatrzenie bezpośrednio do naszych wież?",
  "Delilah": "Delilah",
  "Well, I get my stuff hand-delivered.": "Ja dostaję swoje rzeczy do ręki.",
  "How's THAT work?": "Jakim cudem?",
  "The perks of a decade of service. You're hiking in 90 degree heat and I get to do crosswords. Isn't life miserably unfair?": "Plusy dziesięcioletniej służby. Ty wędrujesz \nw trzydziestostopniowym upale, a ja rozwiązuję \nkrzyżówki. Życie jest takie niesprawiedliwe.",
  "Anyway, when you find the supply drop remember: it's not just for you. Other lookouts, biologists, a few people get their food there and I don't want to have to call in for more.": "Właśnie, kiedy znajdziesz miejsce z zaopatrzeniem, pamiętaj, że to nie tylko dla ciebie. Pozostali obserwatorzy, biologowie i inni dostają tam swoje jedzenie, a nie chcę zamawiać więcej.",
  "There should be loads of good stuff though. Beans, prunes, jerky.": "Powinno tam być mnóstwo pyszności. Fasola, suszone śliwki \ni wołowina.",
  "You know, my sister eats six prunes a day. Six. She's, like, really precise about it.": "Wiesz, moja siostra je sześć śliwek dziennie. Sześć. \nJest bardzo precyzyjna w tym temacie.",
  "She'd be great at this job if she didn't need wheelbarrows full of marijuana to function.": "Nadawałaby się do tej roboty, gdyby nie potrzebowała kilku taczek marihuany, aby normalnie funkcjonować.",
  "Found the supplies.": "Znalazłem zaopatrzenie.",
  "Oh good, enjoy.": "Świetnie, smacznego.",
  "So, like two weeks ago you called me in the middle of the night.": "Jakieś dwa tygodnie temu odezwałeś się do mnie w środku nocy.",
  "You were sleeping and all I heard was the name Jules through the mumbles.": "Spałeś i w twoim mamrotaniu usłyszałam tylko imię „Jules”.",
  "And I just thought it was so sweet. I wanted to wake you up but then I thought maybe you were having a nice conversation and I'd just be spoiling it.": "I uznałam, że to słodkie. Chciałam cię obudzić, ale wtedy \npomyślałam, że może prowadzisz przyjemną konwersację, \na ja bym to zepsuła.",
  "I hope you're doing okay, when it comes to her.": "Mam nadzieję, że sobie radzisz, jeśli o nią chodzi.",
  "Is there anything else you want to tell me about her?": "Chcesz powiedzieć mi o niej coś jeszcze?",
  "I've told you everything there is.": "Już wszystko ci powiedziałem.",
  "I've told you everything.": "Wszystko ci powiedziałem.",
  "Hardly.": "Ledwo.",
  "Well, everything I'm going to, I guess.": "Na pewno wszystko, co zamierzałem.",
  "You broke up with a hot, brilliant Aussie. And I'm sure your have your reasons.": "Zerwałeś z seksowną, wspaniałą Australijką. Na pewno miałeś swoje powody.",
  "You should know that I'm selfishly glad it didn't work out because we get to pal around all summer.": "Wiedz, że jestem samolubnie szczęśliwa, że to nie wypaliło, bo teraz możemy się kumplować przez całe lato.",
  "Whatever. Enjoy the rest of your hike, mystery man.": "Nieważne. Baw się dobrze przez resztę wędrówki, tajemniczy człowieku.",
  "No, there's nothing else.": "Nie, nic więcej.",
  "No, there isn't.": "Nie, nic.",
  "Are you sure?": "Na pewno?",
  "Yes.": "Tak.",
  "Yeah, actually. Look. I wasn't honest with you about her.": "Właściwie nie byłem z tobą do końca szczery...",
  "I wasn't totally honest.": "Nie byłem do końca szczery.",
  "Well why not?": "Czemu nie?",
  "Because I messed up.": "Bo spieprzyłem sprawę.",
  "I am.": "Naprawdę.",
  "Good. I'm glad.": "Dobrze. Cieszę się.",
  "I shouldn't be out here.": "Nie powinienem tu być.",
  "I shouldn't be here.": "Nie powinienem tu być.",
  "Yes you should.": "Powinieneś.",
  "No, I just ran away from my problems.": "Nie, po prostu uciekłem od swoich problemów.",
  "No, you didn't.": "Nieprawda.",
  "…": "...",
  "Hey so… who's Jules?": "A właśnie... kim jest Jules?",
  "I mean, I assume it's your ex.": "Domyślam się, że twoja była.",
  "What the fuck is going on?": "O co, kurwa, chodzi?",
  "Excuse me?": "Słucham?",
  "Where did you hear about Julia?": "Skąd wiesz o Julii?",
  "Whoa! Hey- calm down. okay?": "Uspokój się, dobrze?",
  "A couple weeks you called me in the middle of the night and you were talking in your sleep… I guess. I only heard the name \"Jules\" so I figured I'd ask.  Jesus.": "Kilka tygodni temu odezwałeś się do mnie w środku nocy i mówiłeś przez sen. Usłyszałam tylko imię „Jules”, więc pomyślałam, że zapytam. Jezu.",
  "Oh, I… sorry.": "Przepraszam...",
  "Uh, she's… wait, did I tell you about her?": "Ona... czekaj, mówiłem ci o niej?",
  "Did I tell you about her?": "Mówiłem ci o niej?",
  "Uhh… no. Not exactly.": "No, nie do końca.",
  "Then how…?": "Więc skąd...",
  "A couple weeks you called me in the middle of the night and you were, I guess, talking in your sleep. I only heard the name \"Julia,\" so I figured I'd ask.": "Kilka tygodni temu odezwałeś się do mnie w środku nocy i chyba mówiłeś przez sen. Usłyszałam tylko imię „Julia”, więc pomyślałam, że zapytam.",
  "How do you know that name? I haven't said anything about Julia.": "Skąd znasz to imię? Nigdy nie mówiłem nic o Julii.",
  "How do you know that name?": "Skąd znasz to imię?",
  "Um…": "Eee...",
  "Wait, is there something going on that I don't know about?": "Czekaj, czy ja o czymś nie wiem?",
  "Ha, what? No.": "Co? Nie.",
  "Look, a couple of weeks you called me in the middle of the night and you were talking in your sleep I guess. I only heard the name \"Julia,\" so I figured I'd ask.": "Kilka tygodni temu odezwałeś się do mnie w środku nocy i mówiłeś przez sen. Usłyszałam tylko imię „Julia ”, więc pomyślałam, że zapytam.",
  "Well, you called me in the middle of the night a couple of weeks ago and I really only heard the name \"Jules,\" so… I figured I'd ask.": "Odezwałeś się do mnie w środku nocy kilka tygodni temu \ni naprawdę usłyszałam tylko imię „Jules”, więc pomyślałam, \nże zapytam.",
  "Well, look, I'm just going to assume she's the reason you're out here. It's an age-old story.": "Po prostu założę, że jest powodem, dla którego tu jesteś, i że to stara historia.",
  "And… whatever happened, I'm glad because we get to pal around together for a few months. And I'm happy about that.": "I cokolwiek to było, dobrze się stało, bo możemy się kumplować przez te kilka miesięcy. Cieszy mnie to.",
  "I don't mean to pry…": "Nie chcę naciskać...",
  "It's just. Um…": "To tylko...",
  "It's hard to talk about.": "Ciężko mi o tym mówić.",
  "Talk about Julia": "Opowiedz o Julii.",
  "You don't have to.": "Nie musisz.",
  "It's hard because…": "Ciężko, bo...",
  "Well… I fucked up.": "Cóż... zjebałem.",
  "Look, I don't really want to talk about her, alright?": "Nie chcę o niej rozmawiać, dobra?",
  "Don't talk about Julia": "Nie mów o Julii.",
  "Geez. It must've been a real fuck up.": "No, musiałeś nieźle zjebać.",
  "What did I just say?": "A co właśnie powiedziałem?",
  "Look, so, a couple months before I took this job I was with this guy, Javier. He's incredible. Caring. Sexy as hell. He was a driller down in Casper.": "Kilka miesięcy przed rozpoczęciem tej pracy byłam z takim \ngościem, Javierem. Był wspaniały. Troskliwy. \nCholernie seksowny. Był wiertnikiem w Casper.",
  "We'd dated for almost five years. I was working with the Wyoming Outdoor Leadership School and I was obsessed with it.": "Chodziliśmy przez niemal pięć lat. Pracowałam w Plenerowej Szkole Przywództwa w Wyoming i miałam na tym punkcie fioła.",
  "I wanted to be an instructor so badly. And I was sure I was going to marry Javier as soon as I could be bothered.": "Bardzo chciałam zostać instruktorem. Byłam też pewna, \nże wyjdę za Javiera, jak tylko znajdę czas.",
  "WOLS was also a good excuse to get out of town, drink whiskey in the mountains, cut loose.": "PSPW było również dobrą wymówką, żeby wyjechać z miasta, \npić whisky w górach, wyrwać się...",
  "Then, um, Javier's brother got killed working in Gillette.  And for some reason… I didn't come home.": "Potem brat Javiera zginął, pracując w Gillette. A ja z jakiegoś powodu... nie wróciłam do domu.",
  "Javier said it was fine, he'd go to the funeral, take care of his mom, stuff like that. It'd be easier solo.": "Javier nie robił problemów. Miał pójść na pogrzeb, zająć się mamą, takie tam. Samemu miało być mu łatwiej.",
  "When he came back, he left me.": "Kiedy wrócił, zerwał ze mną.",
  "I came out here.  I lied and told my sister he fucked our neighbor.": "Przyjechałam tutaj. Mojej siostrze powiedziałam, że zdradził mnie \nz sąsiadką.",
  "So… I lied to you. I came out here with a broken heart, just like you.": "Więc... okłamałam cię. Przyjechałam tu ze złamanym sercem, tak jak ty.",
  "I've just lied about it for… over ten years and for some reason I wanted you to know.": "Kłamałam o tym przez ponad dziesięć lat i z jakiegoś powodu chciałam, żebyś o tym wiedział.",
  "I figured you've told me so much about you, so, you know, there's something about me. We both fucked up.": "Tyle mi o sobie powiedziałeś i pomyślałam, że i ja uchylę rąbka tajemnicy. Oboje zjebaliśmy.",
  "You haven't told me anything about you and that's okay, but there you go, there's a whole lot about me.": "Nic mi o sobie nie powiedziałeś, w porządku, ale proszę, o mnie wiesz już mnóstwo...",
  "We all fuck up.": "Każdemu zdarza się nawalić.",
  "Lookouts lie to me all the time.": "Obserwatorzy cały czas mnie okłamują.",
  "I mean, I messed up with her.": "Mam na myśli, że z nią.",
  "Let's just leave it, okay?": "Zostawmy ten temat, dobra?",
  "Leave it.": "Odpuść temat.",
  "I couldn't be what she needed and that's all I want to say.": "Chcę tylko powiedzieć, że nie byłem tym, kogo potrzebowała.",
  "You shouldn't live your life feeling bad about that.": "Nie powinieneś obwiniać się przez całe życie.",
  "Whatever.": "Nieważne...",
  "She got really early Alzheimers and I lost her. She's still alive, she's being taken care of back in Australia, because that's where she's from. She's there.": "Zachorowała na Alzheimera i straciłem ją. Wciąż żyje, jest pod dobrą opieką w Australii, bo stamtąd pochodzi. Tam teraz mieszka.",
  "Go on.": "Kontynuuj...",
  "Oh my God, Henry.": "O Boże, Henry...",
  "That's it.": "To wszystko.",
  "I'm so sorry.": "Tak mi przykro.",
  "Yeah.": "No...",
  "Henry, listen… My God,  I am SO sorry you've gone through that.": "Henry... mój Boże, tak mi przykro, że musiałeś przez to przejść.",
  "I don't know if you thought of this way, but her family is taking care of her and you need to take care of you.": "Nie wiem, czy myślałeś o tym w ten sposób, ale jej rodzina zajmuje się nią, a ty musisz zająć się sobą.",
  "Thanks.": "Dzięki.",
  "But being out here can't be some sort of punishment for you.": "Ale przebywanie tutaj nie może być dla ciebie karą.",
  "Whatever you did can't be that bad. And if it is, it's in the past.": "Cokolwiek zrobiłeś, nie mogło być tak złe. A jeśli było, to już przeszłość.",
  "All I would say is be good to yourself.": "Powiem tylko, że powinieneś być dla siebie łaskawszy.",
  "I'll let you keep hiking.": "Nie będę ci już przeszkadzać.",
  "End Day": "Zakończ dzień",
  "Report heading home.": "Zgłoś powrót.",
  "Alright, I got everything I need out of here. Time to chow down.": "W porządku, mam wszystko, czego potrzebowałem. Czas wracać.",
  "Report getting supplies": "Zgłoś odebranie zaopatrzenia",
  "Just yours, right?": "Wziąłeś tylko swoje, prawda?",
  "Who do you think I am?": "Za kogo ty mnie masz?"
}