{
  "Report cassette tape and tracker": "Zgłoś kasetę i lokalizator",
  "Henry": "Henry",
  "Someone left a rope for me to climb up. I'm down near the lake.": "Ktoś zostawił mi linę, żebym mógł się wspiąć. Jestem niedaleko jeziora.",
  "Delilah": "Delilah",
  "How do you know it's for you?": "Skąd wiesz, że to dla ciebie?",
  "There's a tracking collar tied to it, someone was leading me here. And there's another tape.": "Jest do niej przyczepiony lokalizator, ktoś mnie tu naprowadził. Jest też kolejna kaseta.",
  "Oh my God, Henry.": "O Boże, Henry...",
  "Goodwin's Tape": "Kaseta Goodwina",
  "Report clothesline": "Zgłoś sznur na pranie",
  "There's a clothesline.": "Jest tu sznur na pranie.",
  "Report trash pile": "Zgłoś stos śmieci",
  "I guess he's been dumping trash up here for a while.": "Wygląda na to, że wyrzucał tu śmieci przez dłuższy czas.",
  "Report trapdoor": "Zgłoś klapę",
  "There’s a trapdoor in the ground. He was really serious about this place.": "W ziemi jest klapa. Poważnie podchodził do tego miejsca.",
  "Oh my Jesus.": "Chryste...",
  "Listening": "Nasłuchiwanie",
  "Cassette Tape": "Kaseta",
  "Ned": "Ned",
  "Hi, Henry. You better find this before it burns up.": "Cześć, Henry. Obyś odnalazł tę kasetę, zanim się spali.",
  "We've been causing each other a lotta headaches. Now I gotta go stake out a site that's as fit for living as the one you're about to find. You'll get it when you see it.": "Napsuliśmy sobie nawzajem już sporo krwi. Teraz muszę znaleźć kryjówkę przynajmniej tak dobrą jak ta, którą zaraz znajdziesz. Zrozumiesz, jak zobaczysz.",
  "You can't blame me for keeping an eye on you. Not after bumping into you back in May. Down by the cave for fuck's sake.": "Nie możesz mnie winić za obserwowanie cię. Nie po tym, \njak wpadłem na ciebie w maju przy tej pieprzonej jaskini.",
  "I've been up here for three years. I kept it cozy. Winters are harsh as hell, and I ran out of books. But I got that antennae rigged up— and Delilah… she's a record you don't gotta flip.  I kinda get why Brian took to her.": "Spędziłem tutaj trzy lata. Dbałem, żeby było wygodnie. Zimy są cholernie ostre i skończyły mi się książki. Ale zmajstrowałem sobie antenę... a Delilah... można jej słuchać i słuchać. Rozumiem, czemu Brian ją polubił.",
  "About a week ago I stopped worrying about you finding anything out and that's right when everything went shit-house with you two.": "Jakiś tydzień temu przestałem się martwić, że coś znajdziecie \ni wtedy wszystko przez waszą dwójkę poszło się jebać.",
  "You guys don't know anything about having kids, alright? Nobody knows nothing.  It ain't Andy and Opie walking down to the lake to fish every afternoon. It ain't Mayberry. But you gotta know I didn't kill him, alright? We were climbing. I was teaching him. Brian was uneducated in the way to do anything. He just— he just fucking didn't sink his anchor the right way.": "Nie macie zielonego pojęcia o dzieciach, co nie? Nikt nie ma. To nie sielanka, spacery nad jezioro, by powędkować. To nie Mayberry. Wiedz jedno. Nie zabiłem go, jasne? Uczyłem go wspinaczki. Brian nic nie potrafił. On po prostu... nie wbił odpowiednio tego jebanego haka.",
  "You know, I thought about going back, having to answer questions and having to get him put in the ground, and I didn't see the point.": "Myślałem o powrocie. Że musiałbym odpowiedzieć na wszystkie te pytania i urządzić mu pogrzeb, ale nie widziałem w tym sensu.",
  "Don't come looking for me. I'm sorry about your wife.": "Nie szukaj mnie. Przykro mi z powodu twojej żony.",
  "Report Ned Goodwin's message": "Zgłoś wiadomość Neda Goodwina",
  "We found the surveillance operation.": "Znaleźliśmy naszego inwigilatora.",
  "Okay. What does that mean? What is it?": "Dobra... Co to znaczy? O kogo chodzi?",
  "It was Ned Goodwin. He was the one listening to us. Just him.": "To był Ned Goodwin. To on nas podsłuchiwał. Sam.",
  "Ned Goodwin. He made the tape?": "Ned Goodwin nagrał tę kasetę?",
  "Yeah. He's gone. Deeper into the Shoshone. He doesn't want anyone to know he's out here.": "Tak. Uciekł w głąb Shoshone. Nie chce, żeby ktokolwiek wiedział, że tu jest.",
  "D—": "D...",
  "Because he killed Brian. Because he killed his fucking son.": "Bo to on zabił Briana. Zabił swojego pieprzonego syna.",
  "He's got a, a survival bunker with radios and… everything, he made it all up.": "Ned zbudował... schron. Ma radiostację i wszystko inne. To jego robota.",
  "You… need to get back here. They say helicopters are making rounds.": "Musisz wracać. Mówią, że śmigłowce krążą po okolicy.",
  "Okay.": "Dobra.",
  "Report falsified research": "Zgłoś sfałszowane badania",
  "Goodwin was the one who wrote the reports I found at the site.": "To Goodwin napisał te raporty, które znalazłem w ośrodku badawczym.",
  "Report logs of… our activity… ?": "Zgłoś zapisy... naszej aktywności?",
  "He wrote down everything he did to us. Everything he did every day. He was scared shitless.": "Spisywał wszystko, co nam robił. Każdego dnia. \nPewnie robił pod siebie ze strachu.",
  "Wow. I bet.": "Na pewno.",
  "Well, I've got a photo. I'll show you.": "Dobra, mam zdjęcie. Pokażę ci.",
  "Report disassembled stereo": "Zgłoś rozmontowane radio",
  "This boombox looks familiar…": "Ten radiomagnetofon wygląda znajomo...",
  "From the girls?": "To ten od dziewczyn?",
  "Yeah.": "Tak.",
  "I thought you threw it into the lake.": "Myślałam, że wrzuciłeś go do jeziora.",
  "He must've fished it out.": "Musiał go wyłowić.",
  "Report photo of Brian": "Zgłoś zdjęcie Briana",
  "Brian was a nice looking kid.": "Brian był ładnym dzieciakiem.",
  "Report fantasy game rulebook": "Zgłoś księgę zasad gry fantasy",
  "He held onto some of Brian's things. His Wizards & Wyverns.": "Ned zatrzymał kilka rzeczy Briana. Ma tu „Czarodziei i Wiwerny”.",
  "Yeah well, I'm sure he found it riveting.": "Na pewno go to interesowało...",
  "Report Father's Day card": "Zgłoś kartkę z okazji Dnia Ojca",
  "He… God.": "On... Boże...",
  "What?": "Co?",
  "Nothing. Just some of Brian's stuff.": "Nic. Przeglądam rzeczy Briana.",
  "Report improvised power solution": "Zgłoś improwizowane źródło zasilania",
  "He was rigging up stolen batteries to keep his stuff going.": "Chomikował skradzione akumulatory, żeby mieć zasilanie.",
  "He was probably the guy who ripped apart those snow machines.": "To pewnie on opędzlował tamte skutery śnieżne.",
  "Report workbench": "Zgłoś warsztat",
  "You should see some of the stuff he was working on. I guess he had a lot of time on his hands.": "Powinnaś zobaczyć, nad czym tu pracował. Chyba miał za dużo wolnego czasu.",
  "Report radio base station": "Zgłoś stację dokującą krótkofalówki",
  "I think he took the radio base-station out of Two Forks.": "Chyba zabrał stację dokującą z Wieży na Rozdrożach.",
  "He's got a radio base station up here.": "Ma tutaj stację dokującą krótkofalówki.",
  "He was listening to us on that.": "Tak nas podsłuchiwał.",
  "Report view from hideout": "Zgłoś widok z kryjówki",
  "He had quite the view.": "Miał stąd niezły widok.",
  "Report Delilah's lookout": "Zgłoś wieżę Delilah",
  "Yours too.": "Twoją też.",
  "He could see both of our towers. Yours too.": "Widział stąd obie nasze wieże. Twoją też.",
  "He could see your lookout.": "Widział stąd twoją wieżę.",
  "Ugh.": "Ech.",
  "Report Two Forks lookout": "Zgłoś Wieżę na Rozdrożach",
  "And mine too.": "I moją.",
  "He could see both of our towers. Mine too.": "Widział stąd obie nasze wieże. Moją też.",
  "He could see my lookout.": "Widział stąd moją wieżę.",
  "I'm sorry, I don't know what to say. I don't know what you want me to say.": "Przepraszam, nie wiem, co powiedzieć. Nie wiem, co chciałbyś usłyszeć...",
  "We're in the middle of a fire that is at 22,000 acres and growing. Fast.": "Jesteśmy w samym centrum pożaru obejmującego 22 000 akrów. Szybko się rozprzestrzenia.",
  "It's going to burn all of this up.": "Wszystko pójdzie z dymem.",
  "Delilah…": "Delilah...",
  "Take a picture if you're so keen to remember it.": "Zrób zdjęcie, jeśli tak chcesz to uwiecznić.",
  "You're not?": "A ty byś nie chciała?",
  "I don't know.": "Nie wiem.",
  "Well, I took a photo.": "Zrobiłem zdjęcie.",
  "I don't have any photos left.": "Skończyła mi się klisza.",
  "Then take a long look and let's go.": "To przyjrzyj się jeszcze raz i chodź.",
  "Henry… Henry what did you find?": "Henry... Czego się dowiedziałeś?",
  "Henry? Hello? Come on, I'm sick over here.": "Henry? Halo? No dalej, bo aż mnie skręca.",
  "It was Ned Goodwin.": "To był Ned Goodwin.",
  "I've been up here for three years. I kept it cozy. Winters are harsh as hell, and I ran out of books. But I got that antenna rigged up—and Delilah, she's a record you don't gotta flip. I kinda get why Brian took to her.": "Spędziłem tutaj trzy lata. Dbałem, żeby było wygodnie. Zimy są cholernie ostre i skończyły mi się książki. Ale zmajstrowałem sobie antenę... a Delilah... można jej słuchać i słuchać. Rozumiem, czemu Brian ją polubił."
}