{
  "Delilah": "Delilah",
  "Ooh, Hawk's Rest…": "Jastrzębia Perć...",
  "Henry": "Henry",
  "Yeah, yeah, yeah, okay. I see what you're doing.": "Dobra, dobra. Widzę, do czego zmierzasz.",
  "Yeah, yeah…": "Dobra, dobra...",
  "What do you mean? I just like to stay out of haunted places, myself.": "O co ci chodzi? Ja po prostu trzymam się z dala \nod nawiedzonych miejsc.",
  "It's fine. I wouldn't want to hear about it either. Especially if it meant learning about all of the unspeakable things that happened just a short walk from your lookout. But, whatever.": "To zrozumiałe. Też nie chciałabym jej poznać, zwłaszcza że opowiada o makabrycznych wydarzeniach, które miały miejsce ledwie rzut kamieniem od twojej wieży. Jak sobie chcesz.",
  "Okay. Go on. Out with it.": "No dobra, wykrztuś to.",
  "Tell me about this \"haunting.\"": "Opowiedz mi o tym „nawiedzeniu”.",
  "You want to hear about Raccoon Carter.": "Chcesz usłyszeć historię „Szopa” Cartera?",
  "Ha ha ha ha!": "Haha!",
  "It's your funeral.": "To twój pogrzeb.",
  "I'll just explore in relative peace, if you don't mind.": "Wolałbym pozwiedzać w ciszy, jeśli nie masz nic przeciwko.",
  "No, I'll explore in peace, thanks.": "Nie, pozwiedzam w ciszy. Dzięki.",
  "That's your choice. I'd hate for you to have nightmares.": "Twój wybór. Nie chcę, żebyś miał koszmary.",
  "Things are unsettling enough as it is, wouldn't you say?": "Dzieje się tu już dość niepokojących rzeczy, nie sądzisz?",
  "Yeah, I suppose you're right.": "Tak, chyba masz rację.",
  "So, some years ago, way before my time, a man named Winthrop Carter was stationed at Hawk's Rest.": "Lata temu, zanim tu przybyłam, w Jastrzębiej Perci stacjonował facet o imieniu Winthrop Carter.",
  "He was an angry, angry loner. The story was, he lost his life savings betting on horse fights.": "Był bardzo zrzędliwym samotnikiem. Plotka głosiła, że spłukał się \nna obstawianiu walk koni.",
  "Anyway, he lost all of his money betting on Mexican horse fights.": "W każdym razie, przegrał kasę, obstawiając walki meksykańskich koni.",
  "Horse fights?": "Walk koni?",
  "Horse-fights… ?": "Walk koni?",
  "In Mexico.": "W Meksyku.",
  "Anyway, Raccoon Carter, life in the toilet, signs up with the Forest Service to watch for fires, right?": "Tak czy inaczej, „Szop” Carter, którego kariera poszła w piach, wstąpił do Służby Leśnej, by wypatrywać pożarów.",
  "So he did what a lot of us do in times of trouble. He signed up with the Forest Service to watch for fires.": "Postąpił jak wielu z nas w czasach kryzysu. Wstąpił do Służby Leśnej, by wypatrywać pożarów.",
  "His first night in his lookout, there was a break-in.": "Podczas jego pierwszej nocy ktoś włamał się do wieży.",
  "And the break-ins didn’t stop. Finally, one night he awoke to find someone in his lookout.": "Włamania nie ustawały. W końcu, jednej nocy Carter przebudził się i stanął z intruzem oko w oko.",
  "Well, that sounds familiar.": "Brzmi znajomo.",
  "Sounds familiar.": "Brzmi znajomo.",
  "Anyway, on Raccoon Carter's first night he had a break-in.": "Tak czy inaczej, ktoś włamał się do „Szopa” Cartera pierwszej nocy.",
  "Okay, so the thing is, after that first break-in there were more. Until he woke up in the middle of the night to see something standing on the edge of his bed.": "Na jednym włamaniu się nie skończyło, intruz nie dawał za wygraną. Aż pewnej nocy Carter wyrwał się ze snu i zauważył przy skraju swojego łóżka jakąś postać.",
  "He reached for his hand axe and threw it at the figure, and just before the axe killed its target he heard a small voice cry, \"HELP!\"": "Chwycił toporek do ręki i rzucił go w kierunku intruza. Tuż przed tym jak broń dosięgła celu, usłyszał cichy głos wołający: „Pomocy!”.",
  "Where was I? Oh, yeah. Okay. There's a figure standing over Raccoon Carter. He reaches for his axe and throws it at the shadow and just before the axe strikes, killing it, he hears a tiny voice cry, \"HELP!\"": "O czym ja to? Właśnie. Tajemnicza postać stała nad „Szopem” Carterem. Mężczyzna sięgnął po toporek i celnie rzucił nim w nieproszonego gościa. Tuż przed tym jak broń dosięgła celu, usłyszał cichy głos wołający: „Pomocy!”.",
  "What was it?": "Co to było?",
  "A raccoon.": "Szop pracz.",
  "Oh. Of course.": "No jasne.",
  "Anyway,  so Carter killed a raccoon, but his story doesn't end there.": "Tak więc Carter zabił szopa, ale historia wcale się tu nie kończy.",
  "See, back in these days, the Forest Service wasn't so good about dropping off food and supplies and… Carter was hungry.": "Widzisz, w tamtych czasach Służba Leśna nie radziła sobie \ntak dobrze z zapasami, a Carter... był głodny.",
  "Anyway, the story goes on.  Carter didn't have much food and was very, very hungry.": "Jednak historia się tutaj nie kończy. Carter miał mało jedzenia, umierał wręcz z głodu.",
  "So he did what anyone would do. He skinned and ate it.": "Więc postąpił jak każdy inny. Oprawił szopa i go zjadł.",
  "Oh, so starving, Carter skinned the raccoon he killed and ate it.": "Potwornie głodny Carter oprawił szopa, by następnie go zjeść.",
  "Eventually Carter didn't want to eat anything else. It was raccoons or nothing.": "Carter nie chciał już potem jeść nic innego. \nZasmakował tylko w szopach.",
  "So as I was saying, it got to the point where every night Carter would go out and hunt and eat a raccoon": "Z czasem doszło do tego, że Carter wychodził każdej nocy w las, by polować na szopy i potem je jeść.",
  "But one night, as he sharpened his raccoon blade, there was a scratching at the door. He looked towards it and, again, heard a tiny voice. \"HELP! HELP!\"": "Jednak pewnej nocy, gdy ostrzył swój nóż, usłyszał skrobanie \nw drzwi. Spojrzał w ich kierunku, a jego uszu znów doszło \ncichutkie kwilenie: „Pomocy!”.",
  "He approached slowly, knife in hand, and ripped open the door.  But no one was there.": "Podszedł powoli do drzwi z nożem w ręku i otworzył je \nz rozmachem, lecz na zewnątrz nikogo nie zastał.",
  "Okay, so there was a knock on the door and he heard a small voice cry out \"HELP!\"  He approached it slowly, opened the door and nobody was there.": "Coś zapukało do drzwi, po czym dało się słyszeć ciche wołanie: „Pomocy!”. Podszedł do wejścia, otworzył drzwi, lecz nie zastał za nimi nikogo.",
  "But then, from under the bed he heard another small voice. \"HELP! HELP!\"": "Nagle spod łóżka usłyszał inny cichy głos, również wołający\no pomoc.",
  "So there was no one at the door, and then from under the bed he heard the same voice, \"HELP! HELP!\"": "Wpatrywał się w pustkę za drzwiami, gdy nagle spod łóżka usłyszał kolejne ciche wołanie o pomoc.",
  "Carter looked under the bed and, of course, nothing was there either.": "Carter spojrzał pod łóżko, lecz i tam niczego nie zastał.",
  "So, startled, but believing he was just tired, Raccoon Carter went out hunting and for the first night in months, came up empty.": "Przestraszony, lecz zwalając to na karb zmęczenia, „Szop” Carter udał się na polowanie. Jednak pierwszy raz wrócił z pustymi rękoma.",
  "So Carter goes out hunting and the forest is empty. Nothing. No bugs, no birds, nothing. He comes home and gets into bed.": "Carter udał się na polowanie, jednak las był opustoszały. Nigdzie ptaków, owadów, żywej duszy. Wrócił więc do wieży i położył się spać.",
  "Now in bed, his stomach rumbling, he hears the voice again: \"HELP! HELP!\" And now he wonders if it's coming from inside of him…": "Leżąc w łóżku z burczącym brzuchem, raz jeszcze usłyszał kwilenie: \n„Pomocy!”. Zaczął rozmyślać, czy ten głos nie pochodzi czasem \nz jego trzewi...",
  "But then, a figure appears at the edge of the bed. He again reaches for his axe but in its place is another figure.  He looks for the door and there are more and more figures! Beady, glowing eyes peering out through dark masks!": "Nagle, na skraju łóżka pojawiła się obca postać. Carter raz jeszcze \nsięgnął po toporek, ale w jego miejscu już ktoś czyhał. Spojrzał \nw stronę drzwi, a intruzów przybywało z każdą chwilą! \nIch błyszczące, paciorkowate oczka przenikały ciemność nocy!",
  "He leaps out of bed, horrified, slips, and hits his head. And before he can get up, he feels hundreds of little fingers and razor sharp teeth digging into his skin.": "W przerażeniu zerwał się z łóżka, lecz potknął się, uderzając głową \no ziemię. Nim był w stanie się podnieść, setki drobnych palców \noraz ostrych jak brzytwa zębów przebiły jego skórę.",
  "Far away, in Bighorn Tower, the lookout reported hearing a voice echoing through the valley. Loud at first, and then smaller and smaller, until they faded away forever, \"HELP! Help! Help…\"": "Ponoć obserwator z odległej Rogatej Wieży słyszał głos, który \nechem odbijał się w dolinie. Z początku donośny, z czasem \nsłabł, by w końcu odejść w zapomnienie: „Pomocy! Pomocy...”",
  "And that's the story of Raccoon Carter. His ghost still wanders through the valley, moaning \"HELP! HELP!\" on hot summer nights.": "Tak właśnie brzmi historia „Szopa” Cartera. Jego duch wciąż \nbłąka się w dolinie, jęcząc o pomoc w gorące, letnie noce.",
  "So how'd the tower burn down?": "A jak spłonęło to miejsce?",
  "How did the tower burn down?": "Jak spłonęła jego wieża?",
  "Mmm, lightning, I think? I don't really know. Nature trying to purge the ghost.": "Zdaje się, że od uderzenia piorunem. Natura chciała przepędzić ducha.",
  "I don't think that's what happened.": "Mam co do tego inne zdanie.",
  "Well, it's gone now.  The tower, that is.": "Przeszła do historii. Wieża, znaczy się.",
  "So, what did the raccoons want help with in the end?": "Tak właściwie jakiej pomocy potrzebowały te szopy?",
  "Huh?": "Co?",
  "Well, they kept crying out for help, help, help?": "Mówisz, że nieustannie wołały o pomoc?",
  "Oh, hell if I know. Listen- you can't trust raccoons.": "Żebym to ja wiedziała. Szopom nie można ufać.",
  "So, if Raccoon Carter died, how do we know this story?": "Skoro „Szop” Carter zginął, skąd znasz jego historię?",
  "They found his body, ripped to shreds by raccoons.": "Znaleźli jego ciało, rozszarpane przez szopy.",
  "And Hawk's Rest was filled to the brim with raccoon pelts. It's probably what caused the fire.": "A Jastrzębia Perć była wypchana po brzegi skórami z szopów. \nTo prawdopodobnie one zajęły się ogniem.",
  "That doesn't make any sense.": "To nie ma najmniejszego sensu.",
  "Does anything, Henry?": "A czy cokolwiek tutaj go ma?"
}