{
  "Henry": "Henry",
  "There's an old guitar in here.  It's burned up but still intact.": "Mam tu starą gitarę. Troszkę przydymiona, ale wciąż cała.",
  "Report guitar": "Zgłoś gitarę",
  "Delilah": "Delilah",
  "Oh yeah, that was Carter's. Probably strung with raccoon sinew, but I'm getting ahead of myself.": "A tak, to Cartera. Struny ma pewnie ze ścięgien szopów, ale wyprzedzam fakty.",
  "Ah yes. Carter was a known racoon-teur.": "A tak. Carterowi daleko jednak do Szopena.",
  "You didn't.": "Nie zrobiłaś tego.",
  "I did.": "A owszem.",
  "Hey, was Raccoon Carter a veteran?": "Czy „Szop” Carter był weteranem?",
  "Was Raccoon Carter a vet?": "„Szop” Carter był weteranem?",
  "Huh, I found an old hat from a Korean War vet.": "Znalazłem starą czapkę weterana wojny koreańskiej.",
  "Report Veteran's Hat": "Zgłoś czapkę weterana",
  "You'd be surprised how many former service members take this gig.": "Zdziwiłbyś się, jak wielu byłych żołnierzy bierze tę robotę.",
  "It makes sense.": "Ma to sens.",
  "I imagine if you've been through war you probably can't get enough silence.": "Jeśli przeżyło się wojnę, pewnie nigdy nie ma się dosyć ciszy.",
  "Um, I don't think so.": "Nie wydaje mi się.",
  "What? I don't think so. That would explain his proficiency with an axe, though. Okay. Okay, yeah. Carter fought with Custer in the Battle of the Little Bighorn. Yeah, that's right.": "Co? Nie sądzę, ale na pewno wyjaśniałoby to jego umiejętności posługiwania się siekierą. Carter walczył z Custerem w bitwie pod Little Bighorn. Tak właśnie było.",
  "There's a bed in here, and from the looks of it, it's where the fire was the worst.": "Jest tu łóżko, i wygląda na to, że właśnie w tym miejscu ogień szalał najbardziej.",
  "Report burned bed": "Zgłoś spalone łóżko",
  "Let me just tell you this story.": "Opowiem ci, co się stało.",
  "Well imagine Carter laying in that bed, his stomach full of raccoon meat.": "Wyobraź sobie Cartera leżącego na tym łóżku, z żołądkiem pełnym mięsa z szopa.",
  "Hm, no. I don't think I'm going to imagine that.": "Nie, chyba nie chcę sobie tego wyobrażać.",
  "I found an old notepad of… ha, I guess songs? Someone was writing a song called Ol' Shoshone.": "Znalazłem stary notatnik z... piosenkami? Ktoś pisał piosenkę zatytułowaną „Stare Shoshone”.",
  "Report old notepad": "Zgłoś stary notatnik",
  "Ol' Shoshone, where the sky is blue and the teens are nuuuuude…": "Stare Shoshone, gdzie niebo jest błękitne, a nastolatki gołe...",
  "Ha, it's just like that except about ten times more depressing.": "Właśnie tak, tylko dziesięć razy bardziej depresyjnie.",
  "Ol' Shoshone, you're where I come to be alone and drink gin before noon! And if you happen to spot my tower, prepare to see a moon!": "Stare Shoshone, gdzie przychodzę po samotność i drineczka sobie grzmotnąć! Gdy spostrzeżesz moją wieżę, strzeż się, bo zobaczysz zwierzę!",
  "Wow, did you just make that up just now?": "Wymyśliłaś to na poczekaniu?",
  "Yeah! Not bad, right?": "No! Nieźle co?",
  "Not good.": "Niezbyt.",
  "Muhhhh.": "Ech.",
  "Hey, I've got a notepad here in the outhouse near Hawk's Rest.": "Znalazłem notatnik w wychodku niedaleko Jastrzębiej Perci.",
  "Report notepad": "Zgłoś notatnik",
  "It looks like song lyrics, written by a guy named Carter.": "To wygląda jak tekst piosenki napisany przez niejakiego Cartera.",
  "Wow, there's a zero percent chance it's a happy song.": "To na sto procent nie jest wesoła piosenka.",
  "Yeah, it's definitely not.": "No, zdecydowanie nie.",
  "I just got jumped by a, by a…": "Właśnie napadł na mnie...",
  "Report raccoon attack": "Zgłoś atak szopa pracza",
  "By a what, by a who??!": "Kto taki? Co?",
  "A raccoon.": "Szop pracz.",
  "Oh. Well, I hope you don't have rabies.": "Mam nadzieję, że nie dostaniesz wścieklizny.",
  "Thanks. Me too.": "Dzięki. Ja też.",
  "Holy crap, I think I might've just gotten rabies.": "Cholera, chyba zaraziłem się wścieklizną.",
  "Go on…": "Mów dalej...",
  "I'm sniffing around an old lookout and I got attacked by a raccoon.": "Rozglądałem się po starej chacie i zaatakował mnie szop.",
  "Did he bite you?": "Ugryzł cię?",
  "I don't think so.": "Chyba nie.",
  "You're probably fine. Wait, is it burned to a crisp and filled with raccoons?": "Pewnie nic ci nie jest. Chwila, czy chata jest doszczętnie spalona \ni pełna szopów?",
  "Uh, apparently.": "Najwyraźniej.",
  "Report Raccoon Attack": "Zgłoś atak szopa pracza",
  "…": "...",
  "Anything I should know about the cabin at the top of this hill?": "Jest coś, co powinienem wiedzieć o tym domku na wzgórzu?",
  "Report old cabin": "Zgłoś starą chatę",
  "Hello?": "Halo?",
  "Okay then.": "No dobra."
}