{
  "Henry": "Henry",
  "This outhouse is in the middle of nowhere.": "Ten wychodek stoi na zupełnym pustkowiu.",
  "There's an outhouse way out here.": "Znalazłem wychodek na swojej drodze.",
  "If I'm near the outhouse am I going the right way?": "Jestem w pobliżu wychodka, to dobra droga?",
  "Delilah": "Delilah",
  "Well, I hate to tell you, but everything out here is in the middle of nowhere.": "Nie chcę ci psuć zabawy, ale tutaj wszystko jest na zupełnym pustkowiu.",
  "You know what I mean. Am I on the right track?": "Wiesz, co mam na myśli. Idę w dobrym kierunku?",
  "Just keep following the wire to the top of the ridge, and then you can head back.": "Idź za przewodem na sam szczyt wzgórza, potem możesz zawrócić.",
  "I think so… look around you for that wire and let me know when you find it.": "Tak sądzę... Miej oczy szeroko otwarte i odezwij się, kiedy odnajdziesz przewód.",
  "So, from the abandoned outhouse, which way is 5 Mile Creek?": "Idąc od opuszczonego wychodka, w którą stronę jest Pięciomilowy Potok?",
  "Which way is Five Mile Creek?": "W którą stronę jest Pięciomilowy Potok?",
  "It's pretty far southwest from there. Make sure to keep your compass handy so you don't get off track.": "Na południowy zachód stąd. Miej kompas pod ręką, żebyś nie zboczył z trasy.",
  "I guess that old outhouse is where Raccoon Carter did his business.": "Zgaduję, że to do tego wychodka „Szop” Carter udawał się na posiedzenia.",
  "So, this was Raccoon Carter's outhouse.": "To był wychodek „Szopa” Cartera.",
  "I think I found where Raccoon Carter did his business.": "Myślę, że to tutaj „Szop” Carter udawał się na posiedzenia.",
  "I found Raccoon Carter's outhouse.": "Znalazłem wychodek „Szopa” Cartera.",
  "Pardon me?": "Słucham?",
  "There's an old outhouse down the hill from Hawk's Rest.": "U podnóża Jastrzębiej Perci znalazłem stary wychodek.",
  "Haha, yeah, I guess it probably is where he did… that. Thanks for sharing!": "Tak, zakładam, że to tam odcedzał... kartofelki. Dzięki za informację!",
  "Hey, I found a structure that might've been an outhouse once, I think.": "Znalazłem rozklekotaną budkę, która chyba kiedyś robiła \nza wychodek.",
  "Report old outhouse": "Zgłoś stary wychodek",
  "Whoa, you don't need my permission to go the bathroom. But you know, use abandoned shitters at your own peril!": "Nie potrzebujesz mojej zgody na pójście za potrzebą, ale używasz opuszczonego sracza na własną odpowiedzialność!",
  "I mean, I'm in the right area?": "Jestem w dobrym miejscu?",
  "Yeah, the wire runs quite a ways north; just follow it up to the point that I mentioned.": "Przewód ciągnie się daleko na północ. Po prostu podążaj za nim do miejsca, o którym mówiłam.",
  "I do believe… uh, the comms wire runs for a quite a ways. Follow it all the way up to the top of Beartooth point and if it's not damaged, you can loop around back home.": "Tak sądzę... Przewód rozciąga się na sporą odległość. Idź za nim \naż na szczyt Niedźwiedziego Kła i jeśli nie okaże się uszkodzony, \nmożesz zawrócić do wieży."
}