{
  "Henry": "Henry",
  "I'm back at the shale slide. You know, the one that nearly killed me yesterday?": "Jestem znów przy osuwisku. Pamiętasz, przy tym, gdzie wczoraj niemal zginąłem?",
  "I'm back at the shale slide that nearly killed me.": "Jestem znów przy osuwisku, gdzie wczoraj niemal zginąłem.",
  "Delilah": "Delilah",
  "Ready to give it another shot?": "Chcesz spróbować jeszcze raz?",
  "Ugh. Do I seriously have to?": "Naprawdę muszę?",
  "To get down to 5 mile creek? Afraid so. It's quite a ways downhill from here.": "Żeby dotrzeć do Pięciomilowego Potoku? Obawiam się, że tak. \nJest jeszcze trochę niżej.",
  "Uggh.": "Ech.",
  "I'm down by Cripple Gulch.": "Jestem przy Wąwozie Inwalidów.",
  "I'm down by Cripple Gulch again.": "Znów jestem przy Wąwozie Inwalidów.",
  "I'm back at \"My Shitty Boss Is Going To Get Me Killed Hill\".": "Znów jestem przy „Wzgórzu walniętej szefowej, która wpędzi mnie do grobu”.",
  "I'm back at \"My Shitty Boss Is Going To Get Me Killed Hill.\"": "Znów jestem przy „Wzgórzu walniętej szefowej, która wpędzi mnie do grobu”.",
  "We meet again, Widowmaker. You haven't beat me yet.": "Znów się spotykamy, Wdowiarko. Jeszcze mnie nie pokonałaś.",
  "We meet again, Widowmaker.": "Znów się spotykamy, Wdowiarko.",
  "I'm going to head down to the lake and have a look around. That's the last place I saw them.": "Pójdę nad jezioro i się rozejrzę. Tam widziałem je ostatni raz.",
  "I'm going to head down to the lake to look for them.": "Pójdę nad jezioro i rozejrzę się za nimi.",
  "Rodger.": "Przyjęłam.",
  "Hey, so I'm trying to get back to the lake and I'm completely lost.": "Próbuję dojść nad jezioro i zupełnie się zgubiłem.",
  "Right… can I give you some advanced wayfinding advice?": "Mogę dać ci konkretne wskazówki, jak odnaleźć drogę?",
  "Sure?": "Jasne...",
  "You… do know what a lake looks like on your map?": "Wiesz, jak wygląda jezioro na twojej mapie, prawda?",
  "Yes, a lake is represented by a blue circle. And a condescending boss is, what, exactly?": "Tak, takie niebieskie kółko. A jak oznaczają na mapach protekcjonalnych szefów?",
  "I'm at the shale slide. I can't climb down from here without a rope.": "Jestem przy osuwisku. Nie zejdę bez liny.",
  "I can't get down the shale slide anymore.": "Już nie zejdę po tym osuwisku.",
  "Should I be heading towards the lake?": "Czy powinienem iść w stronę jeziora?",
  "Should I be looking for a sign…?": "Powinienem szukać jakiegoś znaku?",
  "Most trails are unmarked out here. But you should be able to find \"Two Forks Lookout\" on your map; that's your lookout.  Which you know. Unless you don't know that which means we're either really bad at on-boarding or you snoozed through the whole thing.": "Większość szlaków nie jest oznaczona. Powinieneś jednak znaleźć Wieżę na Rozdrożach na swojej mapie. To twoja wieża, o czym wiesz. Chyba że nie, co oznaczałoby, że albo jesteśmy naprawdę beznadziejni w dobieraniu pracowników albo przespałeś całe szkolenie.",
  "Anyway, backtrack there and then head north.": "Tak czy siak, wróć tam i idź na północ.",
  "Okay, I'll see what I can do.": "Dobra, zobaczę, co mogę zrobić.",
  "No, the lake is west of where you're going. You want to be heading north, down through the canyon.": "Nie, jezioro jest na zachód od miejsca, do którego idziesz. Masz iść na północ kanionem.",
  "Okay, gotcha.": "Dobra, załapałem.",
  "Oh, you shouldn't need a rope where you're headed. The climb through the canyon has its dangerous bits but you should be able to do it without gear.": "Tam, gdzie idziesz, lina nie powinna być potrzebna. Wspinaczka przez kanion ma swoje niebezpieczne momenty, jednak powinieneś dać sobie radę bez sprzętu.",
  "Which way is the canyon, again?": "To w którą stronę jest ten kanion?",
  "It's just north of your tower.": "Na północ od twojej wieży.",
  "My tower… which way is that from the shale slide?": "W którą stronę jest moja wieża, patrząc od osuwiska?",
  "And which way is that?": "A w którą to stronę?",
  "Oh, that's easy. It's a straight shot eastward.": "To akurat jest proste. Idź prosto na wschód.",
  "Thanks.": "Dzięki.",
  "I'm just wandering around in the forest and I haven't seen one of their red eagle cans for miles.": "Łażę sobie po tym lesie i nie widziałem puszek po Red Eagle od paru kilometrów.",
  "I'm out of ideas at this point.": "Wyprałem się z pomysłów.",
  "Why don't you head back to your tower and see if you can get a better vantage point from there?": "Może wrócisz do swojej wieży i zobaczysz, czy stamtąd nie będziesz miał lepszego widoku?",
  "Okay, I'll try that.": "Dobra, spróbuję.",
  "Yeah, I'm full of 'em!": "Jestem ich pełen!",
  "Hmm, that's a tough one. Why don't you try to get out of the woods so you can get a better view?": "To akurat trudne. Może spróbujesz wyjść z lasu, żeby mieć lepszy widok?",
  "Find a vista or lookout point.": "Znajdź jakiś punkt widokowy."
}