{
  "Henry": "Henry",
  "Any advice about trying to hike north of the lake?": "Masz pomysł, jak mogę wspiąć się na północ od jeziora?",
  "How can I hike north of the lake?": "Jak mogę wspiąć się na północ od jeziora?",
  "Delilah": "Delilah",
  "Just follow the water’s edge and keep an eye out for trails.": "Podążaj wzdłuż linii brzegowej i wypatruj wydeptanego szlaku.",
  "Right. I’m sure there must be a trail somewhere.": "Jasne. Po drodze na pewno będzie jakaś droga.",
  "If you don’t have a more detailed map, folks tend to keep them in cache boxes in case someone gets lost.": "Jeśli twoja mapa nie jest dość dokładna, poszukaj innych w skrzynkach. Ludzie zostawiają je tam dla zagubionych.",
  "I’m hiking through the canyon. Which way is my best bet for getting to Wapiti Meadow?": "Jestem w kanionie. Którędy najlepiej iść do Polany Wapiti?",
  "What's the best way to Wapiti Meadow?": "Jaka jest najkrótsza droga do Polany Wapiti?",
  "It looks like you can find a trail on the north shore of Jonesy Lake, towards the west.": "Wydaje mi się, że szlak prowadzi przez północne wybrzeże jeziora Jonesy, na zachód.",
  "Thanks, D.": "Dzięki, D.",
  "There’s another piece of climbing gear here… looks like this will take me in the direction of that meadow.": "Znalazłem kolejny punkt asekuracyjny... Wydaje mi się, że to zejście prowadzi prosto na polanę.",
  "Is this the way to Wapiti Meadow?": "Dobrze idę na Polanę Wapiti?",
  "Copy that.": "Przyjęłam.",
  "Which way is Wapiti Meadow, again?": "Możesz powtórzyć, którędy dotrę na Polanę Wapiti?",
  "Hey, which way do I go if I’m at the cave in the canyon?": "Hej, którędy teraz, jak jestem przy jaskini w kanionie?",
  "I'm at the cave, which way should I go?": "Jestem przy jaskini, którędy teraz?",
  "Follow the canyon back to the lake and look for a trail that leads around the north shore.": "Idź kanionem w stronę jeziora i rozejrzyj się za szlakiem, który biegnie naokoło północnego brzegu.",
  "I’m down in the Aspen Grove looking for Wapiti Meadow.": "Wylądowałem w zagajniku osikowym, wciąż szukam Polany Wapiti.",
  "You’re a little off course, I think. Wapiti Meadow is north of the lake.": "Chyba zboczyłeś z trasy. Polana Wapiti jest na północ od jeziora.",
  "Alright, so I’ve got to climb back up towards where those kids were, way back when, and then look for a trail by the lake.": "Dobra, czyli mam wrócić do kąpieliska tamtych dzieciaków i rozejrzeć się tam za jakimś przybrzeżnym szlakiem.",
  "Exactly.": "Dokładnie.",
  "I’m back up at the top of the shale slide near Two Forks.": "Jestem znów na szczycie osuwiska w pobliżu Rozdroży.",
  "What's the best route to the southeast?": "Którędy najlepiej iść na południowo-wschodni szlak?",
  "Good.": "Dobrze.",
  "What’s the best route?": "Którą drogę obrać?",
  "Well, it's not far from that medicine wheel.  Hike east-southeast of there and look for the controlled burn.": "To całkiem niedaleko kręgu medycznego. Udaj się na południowy wschód i wypatruj śladów kontrolowanego wypalania.",
  "Well, it’s beyond your tower to the southeast.  Look for the controlled burn.": "To na południowy wschód od twojej wieży. Wypatruj śladów kontrolowanego wypalania.",
  "And good luck keeping ashes off your pants.": "Żeby tylko ci się popiół do majtek nie dostał.",
  "Which way is Ruby River?": "Którędy do rzeki Ruby?",
  "I’m wandering around east of the lake… which way is Ruby River?": "Szwendam się po wschodniej okolicy jeziora... Którędy do rzeki Ruby?",
  "How can I get to Ruby River?": "Jak mogę dotrzeć do rzeki Ruby?",
  "It's in the southeast corner of your map. The scout camp where the firefighters were staged should be on your map. It looks like a little triangle with a flat bottom.": "Spójrz w południowo-wschodni fragment mapy. Obóz skautów, gdzie stacjonowali strażacy, powinien być tam oznaczony. Kształtem przypomina trójkąt o spłaszczonej podstawie.",
  "Yeah, it looks like a tent?": "Coś w rodzaju namiotu?",
  "…How did I never see that before?": "Dlaczego nigdy na to nie wpadłam?",
  "Hey, I'm at that shale slide.": "Hej, jestem przy osuwisku.",
  "Hey, I’m at My Shitty Boss Is Going to Get Me Killed Hill.": "Hej, jestem przy Wzgórzu walniętej szefowej, która wpędzi mnie do grobu.",
  "Hey, I’m at Cripple Gulch.": "Hej, jestem przy Wąwozie Inwalidów.",
  "Hey, I’m at Widowmaker.": "Hej, jestem przy Wdowiarce.",
  "Wapiti Meadow is to the west, back towards the lake and then around to the north.": "Polana Wapiti jest na zachodzie. Musisz wrócić nad jezioro i udać się na północ."
}