{
  "Delilah": "Delilah",
  "I know I should be relieved… relieved that there's no evidence of us starting that fire, relieved that we're not crazy, that there wasn't some conspiracy.": "Wiem, że powinnam czuć ulgę, bo nie ma dowodów, że to my rzekomo jesteśmy podpalaczami. Ulgę, że nie oszaleliśmy i nie było żadnej konspiracji.",
  "But I'm not.": "Ale nie czuję.",
  "He was a sweet kid.": "Był pociesznym dzieciakiem.",
  "With a shitty father who hid out here like a coward after dumping him in a hole.": "Miał tchórzliwego ojca krętacza, który ukrył się zaraz po tym, \njak porzucił go w tamtej dziurze.",
  "Henry": "Henry",
  "Delilah, I think it was an accident. I don't think Ned meant to kill him.": "To mógł być wypadek, Delilah. Nie sądzę, że Ned chciał go zabić.",
  "I think it was an accident.": "To mógł być wypadek.",
  "We don't know what happened for sure.": "Nie mamy pewności, co tak naprawdę się stało.",
  "Ned wanted his son to be able to climb and do the sorts of things he did, himself, but Brian couldn't.": "Ned chciał, by jego syn potrafił się wspinać i robić to, co on. \nAle Brian nie dawał rady.",
  "And how'd that turn out, Henry?": "I co z tego wynikło, Henry?",
  "I think… I think that Ned loved him. He's still had his photo, you know?": "Myślę, że... Ned go kochał. Nadal miał przy sobie jego zdjęcie, wiesz?",
  "Ned loved him.": "Ned go kochał.",
  "I think… I think that Ned loved him.": "Myślę, że... Ned go kochał.",
  "I don't want to hear it.": "Nie chcę tego słuchać.",
  "He obviously didn't want to forget him. He just didn't know what to do.": "Oczywiście, że nie chciał o nim zapomnieć. Po prostu nie wiedział, co robić.",
  "Henry, not knowing what to do isn't okay! When you're supposed to look after someone, you…": "Henry, to niedobrze, jak się nie wie, co robić! Gdy jest się za kogoś odpowiedzialnym, to...",
  "You figure it out.": "Trzeba sobie radzić.",
  "Yes. And Ned Goodwin is a shithead who was incapable of figuring anything out.": "Tak. A Ned Goodwin to pojeb, który z niczym nie dawał sobie rady.",
  "He wasn't a good dad.": "Nie był dobrym ojcem.",
  "No fucking shit.": "No nie pierdol.",
  "But…": "Ale...",
  "But what?": "Ale co?",
  "I wish you were as mad as I am. I wish… I wish I had a minute with Ned and a .357 Magnum.": "Chciałabym, żebyś był tak wściekły jak ja. Chciałabym... mieć minutkę z Nedem i Magnum.",
  "Sorry. God, it would have been so easy to just tell the truth and have him sent home.": "Wybacz. Boże, o wiele prościej byłoby powiedzieć prawdę i wysłać go do domu.",
  "I can't stop thinking about it.": "Nie mogę przestać o tym myśleć.",
  "You didn't do anything wrong.": "Nie zrobiłaś nic złego.",
  "Don't blame yourself.": "Nie obwiniaj się.",
  "You said it yourself, it was Ned's job to look after him.": "Sama powiedziałaś, że to Ned miał się nim opiekować.",
  "Yes, I did.": "Zrobiłam.",
  "And now I've got to decide whether or I tell people that he's down there so they can retrieve the body or not. And if I do, I'm gonna be asked about Ned Goodwin.": "A teraz muszę zdecydować, czy mam powiedzieć, że on tam jest \ni trzeba zabrać stamtąd jego ciało. Jeśli tak zrobię, zapytają mnie \no Neda Goodwina.",
  "You'll let it go and it'll be okay. It'll haunt you for a while. But eventually you'll look back and you'll be far enough away to forgive yourself.": "Odpuść sobie i będzie dobrze. Będzie cię to prześladować jakiś czas. Ale później, nim się obejrzysz, będziesz mogła to sobie wybaczyć.",
  "It'll be okay.": "Będzie dobrze.",
  "Justify to myself, maybe.": "Co najwyżej usprawiedliwić.",
  "Well, that's better than nothing.": "Lepsze to niż nic.",
  "And he'll still be down there in that cave because if I say anything they're going to ask me about Ned.": "A jego ciało nadal będzie w tej jaskini, bo jeżeli coś powiem, zaczną wypytywać mnie o Neda.",
  "You didn't tell the truth, when they asked you. You didn't send him home.": "Nie powiedziałaś prawdy, kiedy cię pytali. Nie wysłałaś go do domu.",
  "Yeah, but you didn't.": "Ale tak nie zrobiłaś.",
  "No.": "Nie.",
  "You just gotta live with it, Delilah. It won't be that hard.": "Musisz z tym żyć, Delilah. Nie będzie tak ciężko.",
  "If you say so.": "Skoro tak mówisz.",
  "Henry? Are you even there? Hello?": "Henry? Jesteś tam? Halo?",
  "This is the first thing in a really long time that I really regret.": "To pierwsza rzecz od bardzo dawna, której naprawdę żałuję.",
  "*chokes up*": "[krztusi się]",
  "D?": "D?",
  "There you are. Oh fuck, they're here.": "No, jesteś. Cholera, już przylecieli.",
  "Oh fuck.": "O kurwa.",
  "Is that a helicopter?": "To śmigłowiec?",
  "Yeah. Hold on.": "Tak, poczekaj.",
  "Hey!": "Hej!",
  "No. There's one more. Yes. Here, yeah. He's coming.": "Nie. Jest jeszcze jeden. Tak, tutaj. Jest w drodze.",
  "Okay. One second.": "Dobrze. Chwileczkę.",
  "They're here but they're making rounds. They'll come back. I think, I think I'm going to go with them.": "Już tu są, ale latają w kółko. Wrócą. Chyba zabiorę się z nimi.",
  "Uh, yeah. That's a good idea.": "Jasne. To dobry pomysł.",
  "Go.": "Leć.",
  "Yeah?": "Tak?",
  "It's dangerous here and if anything were to happen, then that would be on me.": "Tu jest niebezpiecznie i gdyby coś się stało, to byłaby moja wina.",
  "Yeah, you're right. Yeah. You sure that's okay?": "Tak, masz rację. Na pewno tak zrobić?",
  "I said it was.": "Przecież powiedziałem.",
  "Alright, I should go.": "Dobrze, no to się zbieram.",
  "Have a safe flight.": "Leć bezpiecznie.",
  "Alright have a safe hike.": "Dzięki, spokojnej drogi.",
  "Wait. Just wait, okay. I'm not that far.": "Poczekaj na mnie. Nie jestem daleko.",
  "Wait.": "Poczekaj.",
  "Eh… Henry, they're here, they're waiting, right now.": "Henry, oni już tu są, czekają na mnie.",
  "Please.": "Proszę.",
  "Henry, I don't, I don't want to meet you and just sit here in a dead boy's shadow. Okay? I don't want to do that.": "Henry, nie chcę cię spotkać i siedzieć tu, wiedząc o tym martwym chłopcu. Dobrze? Nie chcę tego robić.",
  "I know that sounds harsh.": "Wiem, że to brzmi okrutnie.",
  "Okay, I'll wait.": "Dobrze, poczekam.",
  "I'm not far.": "Nie jestem daleko.",
  "Okay.": "Okej...",
  "Um, D, what if they don't come back for me?": "D, a jak po mnie nie wrócą?",
  "What if they don't come back?": "A jeśli po mnie nie wrócą?",
  "They'll come back. That's their job.": "Wrócą. To ich praca.",
  "Just, what if we missed something about, uh, something, I don't know.": "A jeśli coś przegapiliśmy, na przykład... sam już nie wiem.",
  "Henry, you're tired. There's nothing big going on. They'll come back for you.": "Henry, jesteś zmęczony. Nic wielkiego się nie dzieje. \nWrócą po ciebie.",
  "Just… wait.": "Po prostu... poczekaj.",
  "I'm gonna go.": "Pójdę już.",
  "Okay, if you have to.": "Skoro musisz...",
  "I have to.": "Muszę.",
  "Hike safe.": "Bezpiecznej drogi."
}