{
  "Delilah": "Delilah",
  "Man, you had a full-on Ph.D. at home. Part of me thinks that would be insufferable. But then there's another part of me that can't help but indulge the whole hot-for-teacher thing.": "Stary, miałeś w domu prawdziwą panią doktor. Z jednej strony chyba bym tego nie zniosła, a z drugiej chętnie zrealizowałabym marzenie o romansie z nauczycielem.",
  "Henry": "Henry",
  "We had a lot of fun.": "Dobrze się razem bawiliśmy.",
  "We had fun.": "Było nam dobrze.",
  "I bet you did. Did she wear glasses, the whole nine?": "Nie wątpię. Nosiła okulary przez cały czas?",
  "No, she had 20/20 vision.": "Nie, miała sokoli wzrok.",
  "Ha… I don't know. She's Australian, so.": "No nie wiem. Jest Australijką, więc...",
  "What's that supposed to mean?": "Co to miało znaczyć?",
  "I wore shoes and showered, and when I got drunk I didn't fight half the town.": "Ja nosiłem buty i brałem prysznic. A kiedy się upiłem, nie wszczynałem bójek.",
  "Mm-hmm. And how often was that?": "Jak często się to zdarzało?",
  "Look. Uh, she's actually really sick. She got very sick and we couldn't be together any more and that's why I'm here.": "Jest naprawdę bardzo chora. Zachorowała i już nie mogliśmy być razem, dlatego tu wylądowałem.",
  "She's actually sick.": "Jest chora.",
  "Oh. My god. I…": "O Boże, ja...",
  "I… I mean— fuck. What happened?": "Ja pierdolę. Co się stało?",
  "We can talk about it later.": "Porozmawiamy o tym później.",
  "Okay. Okay, Henry. Um, what's her name?": "Dobrze, Henry. Jak ma na imię?",
  "Julia.": "Julia.",
  "That's a nice name.": "Ładne imię.",
  "Okay, okay. Cool it down.": "Dobrze już. Uspokój się.",
  "Okay, that's enough…": "Dobrze, już wystarczy.",
  "Oof. Not sure we can stop this train now.": "Chyba już nie zatrzymamy tych myśli.",
  "You are ridiculous.": "Jesteś niepoważna.",
  "Come on, I'm just teasing. I know that academia is a pain in the ass. Professors go wherever they can get tenure.": "Tylko się droczę. Wiem, że uczelnie są jak wrzód na tyłku. Wykładowcy idą tam, gdzie akurat dostaną posadę.",
  "Yes they do.": "Dokładnie.",
  "You know, heavy petting in the book stacks…": "Wiesz, namiętne pieszczoty wśród książek...",
  "Furtive glances during lecture…": "Ukradkowe spojrzenia podczas wykładów...",
  "Ooh, ooh! Office hours role play!": "Zabawy podczas dyżurów!",
  "\"But professor, I can't fail chemistry! Isn't there anything I can do to pass the class? Mmm?\"": "„Ależ profesorze, nie mogę oblać chemii! Co mogłabym zrobić, aby zdać?”",
  "Oh god, I think the second part's winning.": "Chyba druga strona wygrywa.",
  "Well, I called to ask about her, but now I think I've entertained myself plenty. Thanks!": "Odezwałam się, by o nią spytać, ale teraz w zupełności zadowoliłam się tą rozmową. Dzięki!"
}