{
  "Delilah": "Delilah",
  "Look, just so you know, I didn't mean to overstep by bounds, earlier, when you brought up your wife.": "Słuchaj, nie chciałam wtedy przegiąć. Wiesz, kiedy wspomniałeś o żonie.",
  "Henry": "Henry",
  "Well you did. You can't just do that, you know?": "Ale przegięłaś. Nie możesz tak robić.",
  "I know.  I don't know anything about you or your life.": "Rozumiem. Nie wiem nic o tobie ani o twoim życiu.",
  "I know you didn't. You were just making conversation. I appreciate it.": "Wiem, chciałaś tylko porozmawiać. Doceniam to.",
  "I know.": "Wiem.",
  "You still grumpy that I called you an asshole earlier?": "Wciąż się dąsasz, że nazwałam cię dupkiem?",
  "I deserved it. She would've said the same thing.": "Zasłużyłem. Ona powiedziałaby to samo.",
  "I deserved it.": "Zasłużyłem.",
  "Yep. You don't really know what you're talking about.": "Tak. Nawet nie wiesz, o czym mówisz.",
  "Yep.": "Ano.",
  "I guess you still must be. Well, I'm sorry — the distance between my brain and my mouth is… pretty short.": "Czyli wciąż się dąsasz. Przepraszam. Odległość pomiędzy moim mózgiem a ustami jest... dosyć krótka.",
  "…": "...",
  "You can tell me about her, though, if you want.": "Możesz mi o niej opowiedzieć, jeśli chcesz.",
  "So, tell me about her. If you want.": "Opowiedz mi o niej. Jeśli chcesz.",
  "I'd rather not talk about it.": "Wolałbym o tym nie mówić.",
  "She's a college professor.": "Jest wykładowcą.",
  "She's actually sick.": "Jest chora.",
  "For starters, she's my wife, not my girlfriend.": "To moja żona, nie dziewczyna.",
  "Oh.": "Och.",
  "She's actually very sick.": "Jest bardzo chora.",
  "I shouldn't be here.": "Nie powinienem tu być.",
  "I'm sorry again.": "Przykro mi.",
  "She's a college professor.   She's a PhD in Biology— evolution and stuff.": "Jest wykładowcą na uczelni. Ma doktorat z biologii... ewolucja i takie tam.",
  "Oooh, evolution. That's a risque subject in these parts. Man, she's sound sexy.": "Ewolucja. To ryzykowny temat w tej okolicy. Kurczę, musi być atrakcyjna.",
  "She sure was.": "Jak najbardziej.",
  "Where does she teach?": "Gdzie wykłada?",
  "Yale.": "W Yale.",
  "Yale?": "Yale?",
  "Yep. The Yale.": "Tak, w tym Yale.",
  "Shit, Henry.": "A niech mnie.",
  "She flew back and forth. I hated it.": "Latała tam i z powrotem. Nienawidziłem tego.",
  "Yeah, I would too.": "Też bym się tak czuła.",
  "Boulder.": "W Boulder.",
  "That's a great school. My cousin went there.": "Świetna uczelnia, mój kuzyn tam chodził.",
  "Yep, anyway, that's her.": "Tak, więc to właśnie ona.",
  "You know honestly, I would just really rather not, okay?": "Wiesz, szczerze, wolałbym o tym nie mówić, dobrze?",
  "You're going to spend all summer out here in that mood?": "Chcesz spędzić całe wakacje w takim nastroju?",
  "We'll see.": "Zobaczymy.",
  "Hm. I bet you don't.": "Na pewno nie.",
  "Yeah, well. Okay.": "No cóż.",
  "I, of course, eschew serious relationships at all costs.": "Ja za wszelką cenę unikam poważnych związków.",
  "I don't mean that the way it sounds. I care about people and I like companionship as much the next person.": "Źle to zabrzmiało. Jestem troskliwa i lubię towarzystwo innych ludzi.",
  "But why does it come from the same person for your whole life?": "Ale dlaczego przez całe życie miałaby mi towarzyszyć ta sama osoba?",
  "My aunt Cathy was married to the same man for four decades and when he died she found out he'd been having an affair with a real estate broker. For fifteen years.": "Moja ciotka Cathy czterdzieści lat spędziła z tym samym \nmężczyzną. Kiedy zmarł, zdała sobie sprawę, że miał romans \nz agentką nieruchomości. Przez piętnaście lat.",
  "Whereas my aunt Judy travelled the world dating artists and musicians as she saw fit.": "Za to moja ciotka Judy zwiedziła cały świat, spotykając się \nz artystami i muzykami.",
  "Call me crazy, but I'd rather spend a week in bed with Sonny Bono than half a lifetime with some cheating stockbroker.": "Może uznasz, że jestem szalona, ale wolałabym spędzić tydzień \nw łóżku z Sonnym Bono niż połowę życia ze zdradzającym mnie \nmaklerem.",
  "Well, at least you have someone to NOT talk about, which is more than most lookouts.": "Przynajmniej masz kogoś, o kim nie rozmawiasz. To i tak więcej niż inni obserwatorzy."
}