{
  "Delilah": "Delilah",
  "What are you gonna do when the fire season wraps up?": "Co zrobisz, kiedy skończy się sezon pożarowy?",
  "Henry": "Henry",
  "I don't know. I haven't really thought about it. Right now I'm trying to hunt down some vandals, and I don't even know what I'm going to do when I find them.": "Nie wiem, jeszcze o tym nie myślałem. Na razie staram się wytropić tych wandali, a jeszcze nie wiem, co im zrobię, kiedy ich znajdę.",
  "I don't know yet.": "Nie wiem jeszcze.",
  "I'm not thinking very far ahead.": "Nie wybiegam tak daleko w przyszłość.",
  "You should go see her.": "Powinieneś ją odwiedzić.",
  "I'll probably just head back to Boulder and, I don't know, figure out what's next.": "Pewnie wrócę do Boulder i wtedy wymyślę, co dalej.",
  "I'm going home to Boulder.": "Wrócę do domu, do Boulder.",
  "Maybe I'll move.": "Pewnie się przeprowadzę.",
  "Heh. No.": "Nie.",
  "Yes! You love her.": "Tak! Kochasz ją.",
  "I know I don't know anything about your situation, but… I think you should go or you'll regret it. She'd love to see you.": "Nie wiem, w jakiej jesteś sytuacji, ale... powinieneś ją odwiedzić, inaczej będziesz tego żałował. Ucieszyłby ją twój widok.",
  "If she remembers me.": "Jeśli mnie pamięta.",
  "I think you should go.": "Powinieneś to zrobić.",
  "Maybe I'll go visit. I don't know.": "Może wpadnę z wizytą, nie wiem.",
  "Maybe I'll go visit her.": "Może ją odwiedzę.",
  "Well, why not?": "Czemu nie?",
  "She's with her family, in Melbourne.": "Jest z rodziną, w Melbourne.",
  "They're not big fans of mine.": "Nie przepadają za mną.",
  "Oh.": "Och.",
  "Her sister Susan is great. But her parents… I think they always thought she could do better.": "Jej siostra Susan jest świetna, ale jej rodzice... zawsze uważali, że ich córka mogła trafić lepiej.",
  "And… that I could've done a better job looking after her.": "I że mogłem lepiej się nią opiekować.",
  "Fuck that. I have no doubt you did your best.": "Pieprzyć to. Zrobiłeś, co w twojej mocy.",
  "I don't know.": "Nie wiem.",
  "If you want go visit her, you should go. Don't let a couple assholes keep you away from someone you love.": "Jeśli chcesz ją odwiedzić, powinieneś. Nie pozwól, by ta para dupków odebrała ci miłość życia.",
  "I'll think about it.": "Pomyślę o tym.",
  "Are you gonna go be with her? Just go back to Boulder?": "Pojedziesz do niej? Wrócisz do Boulder?",
  "You should go be with her.": "Powinieneś do niej pojechać.",
  "That's my opinion.": "Takie jest moje zdanie.",
  "Ah, sorry. For the umpteenth time.": "Przepraszam cię po raz enty.",
  "Anyway, call me when you find the girls. Or… anything. Or call me whenever you want.": "Daj znać, kiedy znajdziesz te dziewczyny. Albo po prostu. \nOdezwij się, kiedykolwiek chcesz.",
  "You didn't tell me how you met.": "Nie powiedziałeś, jak się spotkaliście.",
  "Suppose that will remain a mystery.": "Niech pozostanie to tajemnicą.",
  "…": "..."
}