{
  "Delilah": "Delilah",
  "Hey, sorry about snapping at you earlier. I thought about it and I suppose that must've sounded kinda weird when you heard me take that other call.": "Wybacz, że wcześniej tak na ciebie naskoczyłam. Ta rozmowa, którą słyszałeś, rzeczywiście mogła zabrzmieć dziwnie.",
  "Plus, you're just out here in your own head. Trust me, I know how it is.": "Do tego zapomniałam, że jesteś tam całkiem sam. Zaufaj mi, wiem, jak to jest.",
  "So, you have a girlfriend back in Colorado, huh?": "Czyli masz dziewczynę w Kolorado?",
  "So… did you break any hearts back in Colorado when you took this job?": "Złamałeś komuś serce w Kolorado, wyjeżdżając do tej pracy?",
  "I, myself, have chosen to never get attached to anyone who would miss me, but I know I'm a bit of an outlier.": "Sama zdecydowałam, by nigdy nie związać się z kimś, kto by za mną tęsknił. Trochę odstaję od normy, wiem.",
  "Henry": "Henry",
  "We don't really need to talk about this stuff, right?": "Nie musimy rozmawiać o takich rzeczach, co nie?",
  "Well, what would you prefer?": "O czym wolałbyś więc pogadać?",
  "Literally anything.": "O czymkolwiek innym.",
  "I didn't think so.": "Nie wydaje mi się.",
  "Do you want to know about the homeopathic remedy for yeast infections I came up with last summer?": "Chcesz usłyszeć o środku homeopatycznym na drożdżaki, na który wpadłam ostatniego lata?",
  "Okay, never mind.": "Dobra, nieważne.",
  "Your loss, pal.": "Twoja strata.",
  "No, I didn't break any hearts when I left.": "Nie, nie złamałem niczyjego serca.",
  "No, I didn't have anyone.": "Nie, nie miałem nikogo.",
  "So you guys broke up?": "A więc zerwaliście?",
  "Something like that.": "Coś w tym rodzaju.",
  "And you're just bursting at the seams to talk about it?": "A ciebie język świerzbi, by o tym mówić?",
  "Hm. Well, I suppose your silence means I am incorrect. Maybe another time.": "Sądząc po twoim milczeniu, chyba się mylę. Może innym razem.",
  "You really are very perceptive.": "Rzeczywiście jesteś spostrzegawcza.",
  "Obviously.": "Oczywiście.",
  "I know. It's one of my many gifts.": "Wiem, to jedna z wielu moich mocnych stron.",
  "Along with accents and impeccable night vision.": "Tak jak akcenty czy doskonałe widzenie nocne.",
  "Incredible.": "Niesamowite.",
  "Why, thank you very much guv'na!": "Ależ bardzo dziękuję!",
  "I'm actually married.": "Właściwie to mam żonę.",
  "I'm married.": "Mam żonę.",
  "I don't mean that the way it sounds. I care about people and I like companionship as much the next person.": "Źle to zabrzmiało. Jestem troskliwa i lubię towarzystwo innych ludzi.",
  "But why does it come from the same person for your whole life?": "Ale dlaczego przez całe życie miałaby mi towarzyszyć ta sama osoba?",
  "My aunt Cathy was married to the same man for four decades and when he died she found out he'd been having an affair with a real estate broker. For fifteen years.": "Moja ciotka Cathy czterdzieści lat spędziła z tym samym \nmężczyzną. Kiedy zmarł, zdała sobie sprawę, że miał romans \nz agentką nieruchomości. Przez piętnaście lat.",
  "Whereas my aunt Judy travelled the world dating artists and musicians as she saw fit.": "Za to moja ciotka Judy zwiedziła cały świat, spotykając się \nz artystami i muzykami.",
  "Call me crazy, but I'd rather spend a week in bed with Sonny Bono than half a lifetime with some cheating stockbroker.": "Może uznasz, że jestem szalona, ale wolałabym spędzić tydzień \nw łóżku z Sonnym Bono niż połowę życia ze zdradzającym mnie \nmaklerem."
}