{
  "Delilah": "Delilah",
  "What does she have?": "Co jej dolega?",
  "Okay. Maybe I'll ask you again in a little while.": "Dobra. Może spytam później.",
  "Sorry, I don't mean to just leap into it if you're not ready.": "Wybacz, nie chcę drążyć tego tematu, jeśli nie jesteś gotowy.",
  "Henry": "Henry",
  "She's got Alzheimers. Like, dementia.": "Ma Alzheimera. No wiesz, demencję.",
  "Whoa. How old was she?": "Ile miała lat?",
  "Is she. She's alive. She's with her family in Melbourne, Australia. She's 43.": "Nadal żyje. Mieszka z rodziną w Melbourne, w Australii. Ma 43 lata.",
  "Fuck.": "Ja pierdolę.",
  "Yeah.": "Tak.",
  "What was it like when you guys found out?": "Co czuliście, kiedy się dowiedzieliście?",
  "Devastating. Especially for her.  You can understand.": "To było druzgocące. Szczególnie dla niej, wiadomo.",
  "Devastating.": "To było druzgocące.",
  "And for you.": "Ale dla ciebie też.",
  "Anyway, everything she worked for was taken away, and that was it.": "Tak czy inaczej, cały jej życiowy dorobek przepadł. I tyle.",
  "We didn't really understand what was happening. You don't get Alzheimers in your late 30's.": "Nie byliśmy w pełni świadomi, co się działo. Nie dostaje się Alzheimera, ledwie dobiegając czterdziestki.",
  "We didn't get it.": "Nie rozumieliśmy tego.",
  "No kidding.": "No bez jaj.",
  "But even then  we didn't really get it until she couldn't work anymore and I couldn't leave her alone.": "Nie rozumieliśmy tego do chwili, kiedy nie mogła już dłużej pracować i zostać sama w domu.",
  "It wasn't until then that I said  \"Oh, this is it. This is over.\"": "Dopiero wtedy powiedziałem: „A więc to koniec”.",
  "That was hard.": "Nie było łatwo.",
  "Hence the drinking and the DUI.": "Stąd wzięło się picie i jazda pod wpływem.",
  "It's okay.": "W porządku.",
  "Scary.": "Strach.",
  "We were scared shitless.": "Naprawdę się baliśmy.",
  "We went straight to the doctor after her first spell, or whatever.": "Poszliśmy do lekarza zaraz po pierwszym ataku.",
  "And the first time she really started to slip, we just made dinner and acted like it didn't happen.": "I kiedy pierwszy raz zaczęła błądzić, zrobiliśmy obiad i udawaliśmy, że nic się nie stało.",
  "Eventually it was impossible to ignore and we saw all the doctors and all of that.": "W końcu nie mogliśmy tego dłużej ignorować, chodziliśmy do lekarzy i takie tam.",
  "They diagnosed her and we were both just very scared.": "Postawili diagnozę, która przeraziła nas do szpiku kości.",
  "You can't really tell when Julia is scared. She just gets quiet. She was very quiet.": "Trudno stwierdzić, kiedy Julia się boi. Zwyczajnie wtedy cichnie. Była bardzo cicho.",
  "I'm sorry to be such a downer.": "Przepraszam, że wkręcam taki nastrój.",
  "Don't even. I'm happy to listen.": "Przestań. Miło mi, że mogę cię wysłuchać.",
  "And, y'know, we'll try to have SOME fun this summer, I promise.": "Spróbujemy się choć trochę rozerwać tego lata. Obiecuję."
}