{
  "Delilah": "Delilah",
  "Henry. Henry, wake up.": "Henry. Henry, obudź się.",
  "Get out of bed and pick up the radio.": "Wstawaj z łóżka i weź krótkofalówkę.",
  "Henry, pick up the radio.": "Henry, weź krótkofalówkę.",
  "Don't go outside. I need to talk you.": "Nie wychodź. Muszę z tobą porozmawiać.",
  "Henry": "Henry",
  "What do you want?": "Czego chcesz?",
  "Hey, you big dumb idiot.": "Cześć, duży głuptasie.",
  "I said hi, dummy.": "Powiedziałam cześć, głuptasie.",
  "I'm sorry to wake you up.": "Przepraszam, że cię budzę.",
  "Hi Jules.": "Cześć, Jules.",
  "Hi Julia.": "Cześć, Julia.",
  "Aww, you sound tired.": "Brzmisz na zmęczonego.",
  "I am.": "Bo jestem.",
  "You're a big dumb idiot.": "Sama jesteś dużym głuptasem.",
  "You're the big dumb idiot.": "Sama jesteś dużym głuptasem.",
  "Oh baby, you sound tired.": "Kochanie, brzmisz na zmęczonego.",
  "Babe, it's late.": "Kotku, jest późno.",
  "I know it is. You sound tired.": "Wiem. Brzmisz na zmęczonego.",
  "Are you having a nice time?": "Wszystko w porządku?",
  "Henry? Are you having a nice time?": "Henry? Wszystko w porządku?",
  "You must just be so tired. I'm sorry.": "Musisz być przemęczony. Przepraszam.",
  "Yeah, it's good here. Beautiful, ya know.": "Tak, dobrze mi tutaj. Jest pięknie...",
  "It's good here.": "Dobrze mi tu.",
  "That's great, Henry. Really great.": "To świetnie, Henry. Naprawdę świetnie.",
  "Sure. Are you? Everything good there?": "Jasne. A co u ciebie? Wszystko gra?",
  "I'm fine, are you?": "U mnie dobrze, a u ciebie?",
  "Jules?": "Jules?",
  "What? Oh, sorry Henry. Yeah, I'm good.": "Co? Przepraszam, Henry. Tak, u mnie dobrze.",
  "That's good.": "To dobrze.",
  "I don't know, there's some weird stuff going on.": "Nie wiem, dzieje się tu coś dziwnego.",
  "Some weird stuff happened.": "Wydarzyło się coś dziwnego.",
  "Aww, that's too bad.": "To niedobrze.",
  "I'm sure it'll be fine.": "Na pewno będzie lepiej.",
  "I'll let you get back to sleep then.": "No to dam ci jeszcze pospać.",
  "Okay Jules.": "Dobrze, Jules.",
  "Delilah seems nice.": "Delilah wydaje się miła.",
  "Mmhmm. Sure.": "Ano.",
  "Bye baby.": "Pa, kochanie.",
  "Put that down.": "Odłóż to."
}