{
  "Delilah": "Delilah",
  "All kidding aside, what happened with the professor?": "A mówiąc poważnie, co się stało z panią profesor?",
  "Henry": "Henry",
  "She got a huge grant to work in the uh, South Pacific, so she is doing that.": "Dostała duży grant na badania na południowym Pacyfiku, więc tym się teraz zajmuje.",
  "She left me for work.": "Zostawiła mnie dla pracy.",
  "And we'd been having problems, so we're just taking a break.": "I mieliśmy problemy, więc robimy sobie przerwę.",
  "How long you been married?": "Jak długo jesteście małżeństwem?",
  "Thirteen years.": "Trzynaście lat.",
  "Wow.": "Łał.",
  "Yeah.": "Tak.",
  "You're sad. You wish she wasn't there.": "Jesteś smutny. Nie chcesz, żeby tam była.",
  "Yeah, I am.": "Tak.",
  "I'm sorry, Henry.": "Przykro mi, Henry.",
  "It's for the best.": "Tak jest lepiej.",
  "Yeah, but you can still be sad.": "Tak, ale masz prawo się smucić.",
  "It'll all work out better than you think.": "Wszystko będzie lepiej, niż myślisz.",
  "…": "...",
  "I'm sure of it.": "Jestem pewna.",
  "It doesn't matter, does it?": "To nie ma znaczenia, prawda?",
  "Does it matter?": "Czy to ma znaczenie?",
  "I don't know.": "Nie wiem.",
  "We're not together and we won't be ever again.": "Nie jesteśmy razem i już nigdy nie będziemy.",
  "Jesus, Henry. Dramatic much?": "Jezu, Henry. Nie dramatyzuj tak.",
  "Okay.": "Okej...",
  "When she got sick. That's when it stopped.": "Kiedy zachorowała. Wtedy wszystko się popsuło.",
  "She got sick.": "Zachorowała.",
  "That's when it stopped.": "Wtedy wszystko się popsuło.",
  "If you guys had so much fun, when did it stop?": "Skoro tak dobrze się dogadywaliście, kiedy coś się popsuło?",
  "I'm just making conversation, you know. Maybe it all works out for you at the end of the summer.": "Po prostu podtrzymuję rozmowę, wiesz? Może wszystko dobrze się ułoży pod koniec lata."
}