{
  "Delilah": "Delilah",
  "You're not one of those guys who is building the “Great Plan” to get her back while you're out here, are you?": "Nie jesteś jednym z tych, którzy w samotności obmyślają wielki plan odzyskania ukochanej, prawda?",
  "Henry": "Henry",
  "How many different ways do I need to make it clear that I do not want to talk about this?": "Ile razy mam ci jeszcze tłumaczyć, że nie chcę o tym mówić?",
  "Can you just stop?": "Możesz przestać?",
  "Uhh… at least one more, I guess.": "Może jeszcze z raz.",
  "Then here it is: Just. Stop. Okay?": "Proszę bardzo: przestań. Dobrze?",
  "Okay.": "Okej...",
  "I am happy to hear about the birds, the chance of lightning, whatever weird shit you've got going on, but can we please not talk about me?": "Lubię słuchać o zwierzątkach, o nadciągających burzach i innych dziwnych rzeczach, które się tu dzieją, ale czy możemy nie rozmawiać o mnie?",
  "Sure, okay. I'm sorry.": "Jasne. Przepraszam.",
  "It's fine.": "W porządku.",
  "I'm not one of those guys; that's not what I'm doing.": "Nie jestem jednym z nich. Nie robię tego.",
  "I'm not one of those guys.": "Nie jestem jednym z nich.",
  "Whew! Well that's a relief.": "A to ulga.",
  "Look, I might just be full of shit, you know?": "Równie dobrze mogę pieprzyć głupoty.",
  "I had considered that.": "Brałam to pod uwagę.",
  "She's sick, alright? Can you just shut the fuck up?": "Jest chora, dobrze? Mogłabyś przestać pierdolić?",
  "She's fucking sick, okay?": "Jest kurewsko chora.",
  "I… I…": "Ja...",
  "I'm sorry. She got early onset Alzheimers and now she's back in Australia with her family and I am here and that's just the way it is.": "Wybacz. Wykryto u niej wczesnego Alzheimera. Teraz jest w Australii z rodziną, a ja jestem tutaj i tak toczy się życie.",
  "I'm sorry, Henry.": "Przykro mi, Henry.",
  "And I've been trying to not talk about it and not be an asshole but you're too… whatever the hell you are to leave it alone.": "Nie chciałem o tym mówić i nie chciałem być dupkiem, ale jesteś zbyt... cholernie jakaś-tam, by sobie odpuścić.",
  "I'm sorry.": "Przepraszam.",
  "It's fine.  I would just like to get through the day, okay?": "W porządku. Chcę tylko jakoś przeżyć dzień, dobrze?",
  "Because you don't want to be that guy.": "Bo nie chcesz nim być.",
  "I know everyone sees that guy in the movies and thinks “I can do that, I can get her back.”": "Wszyscy widzą takiego faceta w filmie i myślą: „potrafię to, mógłbym ją odzyskać”.",
  "But you should know— we hate that guy.": "Ale wiedz jedno. Nienawidzimy tego faceta.",
  "If she broke up with you she's already with someone else.": "Jeśli zerwała z tobą, jest już z kimś innym.",
  "And if you broke up with her, she won't have you back if she's worth a damn.": "A jeśli ty z nią zerwałeś, nie zechce cię z powrotem, jeśli choć trochę się szanuje.",
  "Eh, but what do I know. Maybe you got to her in September and you've got twins by June.  But it won't be because of your skills as a conversationalist.": "Ale co ja tam wiem. Może spotkaliście się we wrześniu, a w czerwcu pojawiły się bliźniaki. Ale nie byłoby to zasługą twoich umiejętności prowadzenia rozmów.",
  "Seriously. I've called you three times to ask about your life and you haven't said a word. I suppose that's a fine way to do a job, but it's a really shitty way to make friends.": "Serio. Odzywałam się trzy razy, by spytać o twoje życie, a ty zbywałeś mnie milczeniem. To pewnie dobry sposób na wykonywanie swojej pracy, ale gówniany na poznawanie przyjaciół."
}