{
  "Delilah": "Delilah",
  "You know, if it makes you feel any better, you're a member of a diverse club of lookouts that have come to the Thorofare after a breakup.": "Jeśli cię to pocieszy, należysz do bogatego grona obserwatorów, którzy przybyli w leśną dzicz, by leczyć złamane serce.",
  "I mean, I assume you went through a breakup. At least that's my best guess at this stage.": "To znaczy zakładam, że jesteś po rozstaniu. Na razie mogę tylko zgadywać.",
  "Henry": "Henry",
  "We didn't break up. We didn't choose to break up. She got sick.": "Nie rozstaliśmy się, nie chcieliśmy tego. Ona zachorowała.",
  "We didn't break up, she got sick.": "Nie rozstaliśmy się, ona zachorowała.",
  "It wasn't anyone's fault.": "To nie była niczyja wina.",
  "You know, neither of us boned the neighbor.": "Wiesz, żadne z nas nie wskoczyło sąsiadowi do łóżka.",
  "So you just grew apart?": "Oddaliliście się od siebie?",
  "We just couldn't be together anymore.": "Już nie mogliśmy być razem.",
  "How does that make you feel?": "Jak się z tym czujesz?",
  "Not very good.": "Niezbyt dobrze.",
  "Not great.": "Niedobrze.",
  "Sorry.": "Wybacz...",
  "Eh, what are you gonna do?": "Nic nie poradzisz.",
  "Well, it's behind you now.  Hopefully it makes you feel like anything is possible.": "Było, minęło. Mam nadzieję, że teraz czujesz, że otworzyły się przed tobą nowe możliwości.",
  "…": "...",
  "Who'd you leave?": "Kogo zostawiłaś?",
  "Well, who'd you leave to come out here?": "Kogo zostawiłaś, by tu przyjechać?",
  "Okay, that jockey story— it's actually about you, huh?": "Ta historia o dżokeju tak naprawdę była o tobie, co?",
  "Ha, no. But can you believe that? It's crazy, right?": "Nie, ale dasz wiarę? To obłędne.",
  "So then who?": "Więc kogo?",
  "I'm the rare breed. My heart's intact.": "Jestem rzadkim okazem, moje serce jest nietknięte.",
  "That's great. You should buy a lottery ticket when you get home.": "Powinnaś kupić los na loterii po powrocie do domu.",
  "That's nice.": "To miło.",
  "Wyoming doesn't have the lottery.": "W Wyoming nie ma loterii.",
  "Come to Colorado. I'll take you to the res.": "Przyjedź do Kolorado. Zabiorę cię do rezerwatu.",
  "It's not luck. I just choose to not let a man dictate how my life goes.": "To nie kwestia szczęścia. Po prostu nie chcę być zależną od żadnego mężczyzny.",
  "Well, that's not normal.": "To nie jest normalne.",
  "Whatever you say, Hank.": "Mów, co chcesz, Hank.",
  "Mmm. You know, I don't believe you.": "Wiesz co... nie wierzę ci.",
  "I don't believe you.": "Nie wierzę ci.",
  "Why put on such a show?": "Po co ta gra?",
  "\"There's more to life than sex and romance.\" Get bent.": "„Życie to nie tylko seks i romanse”. Wal się.",
  "It's not a show.": "To nie jest gra.",
  "It's your business. Just don't lie.": "Twoja sprawa. Tylko nie kłam.",
  "Maybe I'm horribly disfigured.": "Może jestem oszpecona.",
  "Uh, I'm not, by the way. In fact, I'm looking damn good, if I do say so myself.": "To znaczy, nie jestem. Stwierdzam, że tak naprawdę wyglądam bajecznie.",
  "Are you?": "Naprawdę?",
  "Hahaha! Play your cards right and maybe you'll find out, fella.": "Rozegraj to dobrze, a może sam się przekonasz.",
  "That doesn't mean I didn't join up to get away.": "To nie znaczy, że jestem tutaj, by od czegoś uciec.",
  "But there's more to life than sex and romance.": "Życie to nie tylko seks i romanse.",
  "I don't think about anything I'm missing out here that I could be getting back there.": "Chyba nie tęsknię tutaj za niczym, do czego mogłabym wrócić.",
  "And I recommend you try and do the same.": "Tobie też polecam ten stan.",
  "There was Vernon, whose wife got put away for running cocaine.": "Znałam Vernona, którego żona poszła siedzieć za handel kokainą.",
  "Becca, who was widowed after her husband, a jockey, was trampled by his horse.": "Beccę, wdowę po dżokeju, który został stratowany przez konia.",
  "And Sharon whose boyfriend had his own boyfriend.": "I Sharon, której chłopak znalazł sobie chłopaka.",
  "Maybe you boned the neighbor. Maybe she boned the neighbor. Maybe you both did.": "Może przeleciałeś sąsiadkę. Może ona przeleciała sąsiada. Może oboje to zrobiliście.",
  "I don't judge and if you ever want to talk breakups, I'm your gal.": "Nie osądzam, więc jeśli chcesz pogadać o rozstaniach, chętnie wysłucham."
}