{
  "Delilah": "Delilah",
  "Just call me when you get there.": "Daj znać, jak już tam dotrzesz.",
  "Whatever these people are doing is illegal, right?": "Cokolwiek się tam wyrabia jest nielegalne, prawda?",
  "We need to find out how they're doing it, why, everything.": "Musimy dowiedzieć się jak najwięcej o tym, co i dlaczego tam robią.",
  "You understand?": "Zrozumiano?",
  "Henry?": "Henry?",
  "Henry": "Henry",
  "What the fuck is going on?!? People are listening to us?": "Co tu się odpierdala?! Jesteśmy podsłuchiwani?",
  "What the fuck is going on?": "O co, kurwa, chodzi?",
  "I don't know.": "Nie wiem.",
  "Our radios are tapped? Are you fucking serious?!": "Nasze krótkofalówki mają założone pluskwy? O chuj chodzi?!",
  "Our radios are definitely tapped. That's why I left you the one you just got.": "Tak, nasze krótkofalówki są na podsłuchu. Dlatego dostarczyłam ci nową sztukę.",
  "How is this even possible?": "Jak to w ogóle możliwe?",
  "I don't know, Henry.": "Nie wiem, Henry.",
  "What do you know?": "A co wiesz?",
  "I know that I'm scared.": "Że jestem przerażona.",
  "Tell me everything right now. All of it. You know what's going on and you're going to tell me right this minute.": "Zacznij sypać, i to już. Wiesz doskonale, co jest grane \ni wytłumaczysz mi to właśnie teraz.",
  "You are in on this!": "Jesteś w to zamieszana!",
  "Why would you think I know what the hell is going on? I snuck out in the middle of the night and figured out how to get you a new, untapped radio because, what, I'm fucking with you?": "Skąd pomysł, że wiem, co tu się wyrabia? Wymknęłam się w środku nocy i znalazłam sposób, by dostarczyć ci nową krótkofalówkę wolną od podsłuchu, bo lecę z tobą w chuja?",
  "Are you okay?": "Wszystko w porządku?",
  "People have been listening to us all summer. How is this actually happening?": "Ktoś podsłuchiwał nas przez całe lato. Jak to jest w ogóle możliwe?",
  "I don't know. I'm… I'm scared.": "Nie mam pojęcia... Przeraża mnie to.",
  "I'm headed back to the gate and now I've got an axe so we'll know something soon.": "Kieruję się w stronę tamtej bramy. Jestem uzbrojony w siekierę, więc wkrótce poznamy prawdę.",
  "I'm going to find answers.": "Dowiem się, o co tu chodzi.",
  "Who is doing this?": "Kto za tym stoi?",
  "I don't know who could be doing this.": "Nie wiem, kto mógłby mieć motyw.",
  "Henry, I've been at this job off and on for thirteen years.": "Henry, pracuję tutaj już od trzynastu lat.",
  "Sometimes here, sometimes over near Jackson. A couple times down in Wind River.": "Raz tutaj, raz w okolicy Jackson. Kolejnych kilka razy przy rzece Wind.",
  "And nothing like this has EVER happened before.": "I coś takiego spotkało mnie po raz pierwszy w życiu.",
  "Are there any other lookouts this is happening to? Someone else in on this? Anyone?": "Czy inni obserwatorzy też są w to wszystko zamieszani? \nSłyszałaś o kimś? Kimkolwiek?",
  "What about the other lookouts?": "A co z innymi obserwatorami?",
  "Ugh… This is just happening to us. Everyone else is fine.": "To przytrafiło się tylko nam. Inne wieże nie zgłaszały problemów.",
  "Are you sure?": "Na pewno?",
  "Yes. I've tried to bring it up to Chimney Rock, Elk's Fork, and Beartooth lookout and every one of them got confused, asked me if I'm okay and if I need to be relieved.": "Tak. Próbowałam poruszyć ten temat z obserwatorami z Kominowej Skały, Jelenich Rozdroży i Niedźwiedziego Kła, ale byli zaskoczeni. Wypytywali, czy wszystko u mnie dobrze i czy chcę już wrócić do domu.",
  "Our fucking state coordinator asked if I was just having lady troubles.": "A jebany kierownik regionalny miał czelność spytać, czy to kwestia „tych dni”.",
  "So no, this isn't happening to anyone else. And I'm done asking.": "Jak widzisz, to tylko nasz problem. Nie będę już drążyć tego tematu.",
  "Am I just… making all of this up? The eavesdropping, the spying, is this… fuck, are you… is any of this real?": "Czy to wszystko... dzieje się w mojej głowie? Podsłuchy, szpiedzy... Ja pierdolę, czy to wymysł mojej wyobraźni?",
  "Is this all in my head?": "Zmyśliłem sobie to wszystko?",
  "What? Are you serious?": "Co? Ty tak na poważnie?",
  "Maybe I'm just. Maybe I'm just losing my mind.": "Może ja po prostu... popadam w obłęd.",
  "None of it makes any sense.": "Nic się tu nie trzyma kupy.",
  "I just changed clothes laying on the floor because I don’t know who could be watching.": "Przebrałam się właśnie na podłodze, bo nie mam pojęcia, kto może mnie teraz podglądać.",
  "Ughh, just get into that site, okay? Call me with anything you find.": "Po prostu dostań się do tego ośrodka badawczego, okej? Daj znać, jak coś odkryjesz.",
  "You need to get into that site. Call me when you find something.": "Musisz dostać się na teren tego ośrodka. Daj znać, jak coś odkryjesz.",
  "Those most important thing, Henry, is that we don’t turn on each other.": "Henry, przede wszystkim musimy pozostać sprzymierzeńcami.",
  "Maybe there’s a plausible explanation for this.": "Może to wszystko ma racjonalne wyjaśnienie.",
  "Maybe it’s a hidden camera show.": "Może jesteśmy ofiarami ukrytej kamery.",
  "Maybe it’s just people getting their kicks. Maybe it's… I don’t know.": "Może ktoś świetnie się bawi naszym kosztem. A może... sama nie wiem.",
  "Fuck if I know! Just, get into that site, okay? And call me as soon as you find anything.": "Skąd mam, kurwa, wiedzieć?! Dostań się do ośrodka. Daj znać od razu, jak coś odkryjesz.",
  "Maybe you're working for the government, and this whole thing is some sort of program that you're a part of.": "Może działasz na zlecenie rządu, a to wszystko jest częścią tajnej operacji, w której bierzesz udział.",
  "Maybe you work for them.": "Może pracujesz dla nich.",
  "Maybe you've been brainwashed, and this is some sort of a… program and you're, uh, an accomplice. Complicit.": "Może zrobili ci pranie mózgu, a to wszystko jest... tajną operacją, \nw którą jesteś zamieszana. Też za to odpowiadasz.",
  "Maybe you've been brainwashed.": "Może zrobili ci pranie mózgu.",
  "You're insane.": "Oszalałeś.",
  "Tell me you're not.": "Powiedz, że nie.",
  "Henry, I'm not. I need you to hear me.": "Oczywiście, że nie, Henry. Wysłuchaj mnie.",
  "You and I have a thing. This is real, okay? You and I really happened.": "Zaiskrzyło między nami. Naprawdę, słyszysz? To żadna iluzja.",
  "I care about you. That's not made up. It's real.": "Zależy mi na tobie. Nie zmyślam tego.",
  "And I know you've been through so much with Julia.": "Wiem, że wiele przeszedłeś razem z Julią.",
  "And I know you didn't just take this job because you thought it'd be fun. I know whatever is going on at home is intense.": "Wiem, że nie podjąłeś się tej pracy dla zabawy. Twoja sytuacja rodzinna jest... skomplikowana.",
  "But please, don't spin off into outer space. Something is happening and it's happening to both of us, okay?": "Ale błagam, pozostań przy zdrowych zmysłach. To, co się tu dzieje, dotyczy nas obojga, rozumiesz?",
  "Maybe… maybe you're not real. Maybe I'm losing my mind.": "Może... tak naprawdę nie istniejesz, a ja popadam w obłęd.",
  "…What?": "Co proszę?",
  "Like Julia. Maybe it's happening to me and I'm imagining that I have a boss out here and that we're being spied on.": "Tak jak Julia. Może spotkało mnie to samo i wymyśliłem sobie szefową razem z całą tą historią o szpiegowaniu.",
  "Henry…": "Henry...",
  "Like Julia.": "Tak jak Julia.",
  "What happened to Julia?…": "Co stało się Julii?",
  "She lost her mind. Her, memory. She has dementia.": "Straciła rozum, swoje wspomnienia. Choruje na demencję.",
  "She has dementia.": "Choruje na demencję.",
  "And now it's happening to me.": "A teraz to dopadło i mnie.",
  "HENRY.": "Henry.",
  "Nothing, it doesn't matter. Just…": "To nieistotne. Po prostu...",
  "Nothing.": "Nic.",
  "Maybe there was something in the water. Or our condo was underneath some power lines and, you, Delilah, you're not real.": "Może coś było w wodzie. Albo mieszkałem przy linii wysokiego napięcia. A ty, Delilah, jesteś wytworem mojej wyobraźni.",
  "Henry. Think about her. If what happened to her were happening to you, you wouldn't even be able to realize it.": "Henry. Przemyśl to sobie. Gdyby spotkało cię to, co ją, \nnawet nie zdawałbyś sobie z tego sprawy.",
  "[crying, upset breathing]": "[szloch]",
  "How the fuck would you even know?! Do you know what it's like to see someone just… just decompose?!": "A ty kiedy zostałaś jebaną specjalistką?! Masz pojęcie, jak to jest widzieć, że ktoś po prostu... gaśnie w oczach?!",
  "How would you know?": "Skąd możesz to wiedzieć?",
  "I don't. I'm sorry, Henry, I don't. But you're not crazy. Okay? You're okay.": "Nie mogę. Przepraszam, Henry. Ale nie zwariowałeś. Wszystko z tobą dobrze.",
  "You're losing your shit right now and… I want you to take a breath.": "Zaczynasz popadać w paranoję. Weź głęboki oddech.",
  "It's true. You're right. Julia only knew early on. And she was so scared.": "Masz rację. Julia rozumiała to tylko na początku. Była przerażona do szpiku kości.",
  "You're right.": "Masz rację.",
  "Henry, it's okay. It's okay. Just breathe. Breathe, Henry.": "Już dobrze, Henry. Oddychaj głęboko. Wdech, wydech...",
  "Henry, you ARE losing it. I don't know everything that's happened to you, but you have to pull yourself together. I am REAL, okay?": "Henry, dajesz się ponieść szaleństwu. Nie wiem o wszystkim, co cię spotkało, ale musisz wziąć się w garść. Jestem prawdziwa, słyszysz?",
  "Okay.": "Okej...",
  "Henry, sweetie. I am real and this is happening. I'm as real as the sky is blue.": "Henry, skarbie, jestem prawdziwa jak niebo nad nami. \nI to co się dzieje też.",
  "Take a second and then call me back. I'm on your side.": "Weź głęboki wdech i odezwij się za chwilę. Gramy w jednej drużynie.",
  "I've got it now.": "Mam ją.",
  "Good. I spent all day getting you that radio.": "Świetnie. Straciłam cały dzień na zdobycie tej krótkofalówki.",
  "I hiked to a cache box, lied to a ranger, lied to ANOTHER ranger and hopefully you are now holding a clean, untapped radio.": "Zawędrowałam do skrzynki i wcisnęłam kit dwóm leśniczym, ale mam nadzieję, że trzymasz teraz w ręce krótkofalówkę bez ogona.",
  "Hopefully.": "Oby.",
  "Holy fuck Henry, we have to get into that site.": "Ja pierdolę, Henry, musimy dostać się do tego ośrodka."
}