{
  "I think I lost the trail.": "Chyba zboczyłem ze szlaku.",
  "Henry": "Henry",
  "So, I'm at the medicine wheel.": "Jestem przy kręgu medycznym.",
  "Delilah": "Delilah",
  "So you're near your lookout.": "Czyli niedaleko twojej wieży.",
  "Yeah, sure.": "Tak, jasne.",
  "Hey, I'm at this medicine wheel and I can't see the smoke anymore. Where am I headed again?": "Dotarłem do kręgu medycznego, ale zgubiłem ślad unoszącego się dymu. Dokąd mam zmierzać?",
  "I can't see the smoke from here…": "Nie widzę stąd źródła dymu...",
  "Towards 5 mile creek, in the southwest quadrant of your map.": "W kierunku Pięciomilowego Potoku, spójrz w południowo-zachodni fragment mapy.",
  "Okay, heading over there now.": "Okej, zmierzam w tamtym kierunku.",
  "Hey, from this medicine wheel, where do I hike to to get that rope you mentioned?": "Idąc od tego kręgu medycznego, w którą stronę mam się udać, by zdobyć tamtą linę?",
  "Where do I get that rope?": "Gdzie znajdę tę linę?",
  "Hey, I'm still at that medicine wheel and think I might be turned around.": "Nadal jestem przy kręgu medycznym. Chyba kręcę się w kółko.",
  "I think I'm turned around.": "Mam wrażenie, że kręcę się w kółko.",
  "So if I'm at this medicine wheel near my tower, where should I go to find the fireworks?": "Zakładając, że jestem przy kręgu medycznym w pobliżu mojej wieży, gdzie są te fajerwerki?",
  "Where should I head towards?": "W którą stronę mam się udać?",
  "Ugh, I'm still at that medicine wheel and not sure where to go.": "Dalej krążę przy kręgu medycznym i nie mam pojęcia, co dalej.",
  "Hey, still lost.": "Wciąż się błąkam.",
  "I'm lost.": "Zgubiłem się.",
  "Where are you?": "Gdzie jesteś?",
  "Near the Indian wheel.": "W okolicy indiańskiego kręgu.",
  "Native American medicine wheel.": "Przy indiańskim kręgu medycznym.",
  "Sorry. It's dark.": "Przepraszam, jest ciemno.",
  "And you're frightened, aww.": "A ty sikasz w majtki.",
  "I'm not frightened.": "Nieprawda.",
  "*makes a scary noise*": "*przeraźliwe dźwięki*",
  "Don't do that.": "Przestań.",
  "Because it's scary. And you're scared.": "Bo zaczynasz się bać jeszcze bardziej.",
  "Yes.": "Tak.",
  "Your tower is to the east.": "Twoja wieża jest na wschód.",
  "Thank you.": "Dziękuję.",
  "It's okay, there should be a couple trails that head north from there. Take the one on the left, the westerly one.": "Przebiegają tamtędy dwa szlaki zmierzające na północ. \nUdaj się zachodnią odnogą, tą po lewej.",
  "Okay, I think I can figure that out.": "Dzięki, dalej już sobie poradzę.",
  "They're to your northwest from there, I think. If you hike north from there you should find the shale slide I mentioned.": "Są na północnym zachodzie, tak myślę. Jeśli wyruszysz na północ, powinieneś natknąć się na osuwisko, o którym mówiłam.",
  "Okay. I mean, it's your first day. There should be a trail that leads away from there towards the northeast. Take that.": "Okej, to w końcu twój pierwszy dzień. W pobliżu znajduje się szlak prowadzący na północny wschód, to nim masz się poruszać.",
  "Yeah, alright.": "Przyjąłem.",
  "Oh it's, hmm… like north-northeast of you. It looks like it's uphill from you so try to head up and north.": "Na północnym wschodzie. I najwyraźniej na wzniesieniu, więc spróbuj wyruszyć przed siebie i na północ.",
  "Got it.": "Jasne.",
  "Wow, there's an old uh, I think it's called a medicine wheel out here?": "Natknąłem się na starodawny... mówi się na to chyba krąg medyczny, co?",
  "Report medicine wheel": "Zgłoś krąg medyczny",
  "Can you tell me anything about this medicine wheel?": "Co możesz mi powiedzieć o tym kręgu medycznym?",
  "Yeah, it was made by Crow American Indians hundreds of years ago.  There are lots of small ones; have you ever been to Medicine Wheel Monument over in the Bighorns?": "To dzieło indiańskiego plemienia Wron, liczy sobie setki lat. Istnieje też kilka mniejszych wersji. Miałeś kiedyś okazję zobaczyć zabytkowy kamienny krąg w Bighorns?",
  "No, I sure haven't.": "Z całą pewnością nie.",
  "Well, it's worth the three hour detour on the way home in August.": "Warto o to zahaczyć, gdy udasz się w sierpniu w drogę powrotną.",
  "Neat. I'll keep it in mind.": "Nieźle. Zapamiętam.",
  "So… if I'm at the medicine wheel, am I getting close to that wire?": "Czyli... ten krąg medyczny znajduje się w pobliżu przewodu?",
  "Where's the wire in relation to the medicine wheel?": "Jak daleko jest ten przewód w odniesieniu do kręgu medycznego?",
  "Uh, no. You're off-track. The easiest thing to do would be to head back to your tower, then north through the Canyon.": "Nie, zboczyłeś z trasy. Najlepiej będzie, jeśli zawrócisz do wieży \ni udasz się na północ, w stronę kanionu.",
  "Feel free to find a landmark and call me from there if you're still lost.": "W razie problemów znajdź kolejny punkt widokowy \ni odezwij się do mnie.",
  "Uh, little help?": "Pomożesz mi trochę?",
  "Mmhmm, yes?": "Czego ci trzeba?",
  "Hey, I know you said to head back to my tower, but I ended up back at the medicine wheel again.": "Wiem, że kazałaś mi wyruszyć w stronę wieży, ale zatoczyłem koło \ni znów wylądowałem przy kręgu.",
  "Your compass is your friend, Henry. And your tower is… just a little bit northeast of you.": "Twój kompas nie gryzie, Henry. A wieża znajduje się... \nna północny wschód od miejsca, w którym jesteś.",
  "And the canyon is due north from there.": "Gdy już tam dotrzesz, kanion będzie na północy."
}