{
  "Henry": "Henry",
  "How many hikers go missing in the Shoshone?": "Ilu turystów zaginęło w Shoshone?",
  "Delilah": "Delilah",
  "More than none, unfortunately. With most of them being in this area, the Thorofare, because it's so remote. Why?": "Niestety więcej niż zero. Większość z nich w tej okolicy, bo jest dość nieprzystępna. Dlaczego pytasz?",
  "Why? You hoping these girls didn't make it back to the trailhead? Because that's a little dark, Hank.": "Dlaczego pytasz? Masz nadzieję, że te dziewczyny nie odnalazły szlaku? To dość mroczna myśl, Hank.",
  "Why? You don't think you're going to end up on a milk carton, do you?": "Czemu pytasz? Chyba nie boisz się, że też dołączysz do tego grona?",
  "I found an old flyer for a missing hiker. It just got me thinking, that's all.": "Znalazłem stary plakat z zaginionym turystą. Po prostu zacząłem się zastanawiać.",
  "Like how you said one day you were talking to the Goodwins and the next you weren't.": "Jak wtedy, gdy mówiłaś, że jednego dnia rozmawiałaś \nz Goodwinami, a następnego już nie.",
  "Ned Goodwin didn't get mauled by a bear or stuck in a ravine. He was just a PTSD'd a-hole who dragged his son out to do a job and realized it was a bad idea.": "Neda nie zaatakował niedźwiedź ani nie utknął w jarze. Był dupkiem cierpiącym na zespół stresu pourazowego. Zaciągnął tu swojego syna, co okazało się złym pomysłem.",
  "Eh, I probably shouldn't give that guy such a hard time. He just really rubbed me the wrong way.": "Może nie powinnam go tak krytykować. Po prostu naprawdę nadepnął mi na odcisk.",
  "So…": "Więc...",
  "You sure a grizz didn't eat the Goodwins?": "Jesteś pewna, że Goodwinów nie zjadł grizzly?",
  "What, grizzlies won't kill an a-hole? They don't have a taste for unapologetic pricks?": "No co, grizzly nie pokuszą się na dupka? Czyżby nie gustowały \nw zgryźliwych palantach?",
  "Grizzlies won't kill a-holes?": "Grizzly nie zabiją dupka?",
  "Nope. It's why we haven't lost a ranger in eleven years.": "Nie. Dlatego nie straciliśmy żadnego leśniczego przez jedenaście lat.",
  "So you don't think anything bad happened to those guys?": "Więc nie uważasz, że stało im się coś złego?",
  "I guess it's possible but we usually find evidence of stuff like that.": "To możliwe, ale zwykle wskazują na to jakieś dowody.",
  "For instance, if you were to be hunted down and torn to shreds I'm sure someone would come across a bloody beard and shredded pair of ugly cargo shorts.": "Na przykład jeśli to ty zostałbyś upolowany i rozszarpany, jestem pewna, że ktoś natknąłby się na szczątki zakrwawionej brody i pozostałości po brzydkich szortach.",
  "I like these shorts.": "Lubię te spodenki.",
  "I'm sure you do, Henry.": "Nie wątpię, Henry.",
  "PTSD? That doesn't sound good.": "Zespół stresu pourazowego? Nie brzmi dobrze.",
  "Eh, I don't know. He was in the Army. He was… off. It's actually the saddest story. He was only discharged because his mother, Brian's grandmother, died. She'd been taking care of him and Ned was the only next of kin.": "Sama nie wiem. Służył w wojsku. Był trochę... nieobecny. To właściwie najsmutniejsze. Został zwolniony ze służby tylko dlatego, że jego matka, babcia Briana, zmarła. Opiekowała się nim, a Ned był jego najbliższym krewnym.",
  "Damn.  And you go to know Brian a little bit?": "Cholera. Miałaś okazję lepiej poznać Briana?",
  "Yeah. I talked to him way more than I talked to Ned, that's for sure.": "Tak. Na pewno rozmawiałam z nim częściej niż z Nedem.",
  "How was he at, you know, spotting fires?": "Jak mu szło, no wiesz, zauważanie pożarów?",
  "Better than you! He actually liked to stay in the tower.": "Lepiej niż tobie! On lubił zostawać w wieży.",
  "Did you say PTSD?": "Powiedziałaś zespół stresu pourazowego?",
  "Isn't your radio supposed to be in the river?": "Czy twoja krótkofalówka nie miała wylądować w rzece?",
  "I couldn't bring myself to do it.": "Nie zdobyłem się na odwagę.",
  "Well, I guess I'm stuck with you then.": "No to chyba z tobą utknęłam.",
  "Yeah.": "Tak.",
  "So, did you mention something about Ned Goodwin having PTSD? That doesn't sound good.": "Wspomniałaś coś o Nedzie Goodwinie i jego stresie pourazowym? To nie brzmi dobrze.",
  "You said Ned didn't get mauled by a grizzly but… it's possible right?": "Powiedziałaś, że Ned nie został zaatakowany przez grizzly... \nAle to możliwe, nie?",
  "You really didn't like that guy, did you?": "Naprawdę go nie lubiłaś, co?",
  "You really didn't like that guy, huh?": "Naprawdę za nim nie przepadałaś, co?",
  "I don't know. I honestly… I just had a hard time talking to him. There are lookouts who seriously won't shut up, who call me about every little thing that pops into their head. And then there are those who just want to be left alone. He was the latter.": "Nie wiem. Szczerze mówiąc... Po prostu nie był łatwym rozmówcą. \nJedni obserwatorzy są strasznymi gadułami i mówią mi, co im ślina \nna język przyniesie. Są też tacy, którzy po prostu chcą być sami. \nOn był tym drugim typem.",
  "And I'm the former, aren't I?": "A ja jestem pierwszym?",
  "Well, I didn't want to say anything…": "Nie chciałam nic mówić...",
  "It's fine. I'll just chuck my walkie-talkie into the river.": "W porządku. Po prostu wrzucę swoje walkie-talkie do rzeki.",
  "Heh, oh come on…": "Nie wygłupiaj się...",
  "And, uh, you'll never hear from me again.": "I już nigdy nie usłyszysz ode mnie słowa.",
  "Finally, peace and quiet, woohoo!": "Jest, wreszcie cisza i spokój!"
}