{
  "Wave Receiver": "Detektor fal",
  "Henry": "Henry",
  "This receiver just picked something up.": "Detektor fal właśnie coś wyłapał.",
  "Report wave receiver beeping": "Zgłoś pikający detektor fal",
  "Delilah": "Delilah",
  "Uh, what thingy? What now?": "O czym ty mówisz? Co?",
  "I found a device that picks up frequencies. It's how I found the reports last night and it's going off now.": "Znalazłem urządzenie, które odbiera częstotliwości, tak znalazłem wczoraj te raporty. A teraz znowu się odzywa.",
  "It just picked up a freq- frequency? ": "Odbiera częstotliwości? ",
  "Like a signal? It's going “beep beep”?        ": "Masz na myśli sygnał? Robi „bip bip”?        ",
  "Yeah. What could it be?": "Tak. Co to może być?",
  "I don't know. You gotta find out.": "Nie wiem. Musisz się dowiedzieć.",
  "Alright, I'm on my way now.": "Tak jest, już wyruszam.",
  "You know what I just picked up?": "A wiesz, co ja mam?",
  "Uh, no?": "Nie...",
  "A fifth of Major Bueno tequila from the creek.": "Butelkę schłodzonej w wodzie tequili Major Bueno.",
  "Are you DRUNK!?": "Jesteś pijana?",
  "NO. I am GETTING drunk!": "Nie. Dopiero się upijam!",
  "But YOU better stay sober. We need a right mind between the pair. No what I'm sayin?": "Ale ty lepiej zostań trzeźwy. Potrzebujemy choć jednego bystrego umysłu. Czaisz?",
  "My thinking is I could stay up all night worried I'm gonna lose my job because of the site fire. Or, I could not worry and let the chips fall where they may. It's not like there's any proof we were down there.": "Mogłabym nie zmrużyć oka przez całą noc, martwiąc się, że stracę \npracę przez ten pożar. Lub też zdać się na los i nie przejmować. \nNie ma przecież żadnych dowodów, że tam byliśmy.",
  "My thinking is I'm going to follow this wave receiver.": "A ja myślę, że podążę za dźwiękiem detektora fal.",
  "Oooh, I like it when you think.": "Lubię, gdy myślisz.",
  "Aye yai yai.": "Ajajaj...",
  "I’ll just leave you alone with whatever these thoughts are.": "Pozwolę ci więc snuć swoje rozmyślania w spokoju.",
  "Last thing I need is another big crossword breakthrough.": "Ostatnim czego mi trzeba, jest kolejny krzyżówkowy przełom.",
  "Don't do that!": "Nie rób tego!",
  "I know, I know… everything has gone to total shit but, but, you gotta live a little. Ya gotta LAL Hank.": "Wiem, wiem. Wszystko się pochrzaniło, ale trzeba cieszyć się chwilą. Żyje się tylko raz, Hank.",
  "No no, you're right, D. I can't think of any good reason why you wouldn't want your decision making inhibited right now.": "Masz rację. Nie ma dobrego powodu, dla którego nie chciałabyś ograniczyć swojej zdolności do podejmowania decyzji.",
  "Good plan.": "Dobry plan.",
  "I'm a good planner.": "Umiem dobrze planować.",
  "Hey D, I don't wanna “harsh your vibe” but maybe, just maybe that's a bad idea?": "Nie chciałbym „psuć twojej aury”, ale nie uważasz, że to zły pomysł?",
  "Maybe a bad idea?": "Zły pomysł?",
  "Henry. Henry. Henry.": "Henry. Henry. Henry.",
  "What?": "Co?",
  "You’re harshin’ my vibe.": "Psujesz moją aurę.",
  "Radio Off": "Krótkofalówka wyłączona",
  "Are you leaving your lookout?": "Opuszczasz wieżę?",
  "This receiver picked something up. I’m just checking it out.": "Detektor fal coś wyłapał, chcę to sprawdzić.",
  "I really don’t think you should do that. I think we should just hunker down. Things are getting out of hand.": "Nie powinieneś tego robić. Powinniśmy to przeczekać. \nSprawy wymykają się spod kontroli.",
  "I won’t go far.": "Nie odejdę daleko.",
  "Henry…": "Henry...",
  "And I think we should keep things quiet.": "Powinniśmy siedzieć cicho.",
  "Report Backpack": "Zgłoś plecak",
  "Shit!": "Cholera!",
  "Ah!": "Ach!",
  "D— I found some sort of supply bag.  Light camping gear, some clothes. Basics. But it was alarmed. I think that’s what was making the receiver go haywire.": "Znalazłem jakiś plecak z zapasami. Sprzęt turystyczny, kilka ubrań, podstawowe rzeczy. Był podpięty pod alarm. Pewnie dlatego detektor fal wariował.",
  "Report alarmed bag": "Zgłoś plecak-pułapkę",
  "You're okay? It's not a trap or anything?": "Nic ci nie jest? To nie była pułapka?",
  "I'm fine. But… there's also a set of keys here. I don't know why they'd be hidden out here, they say “Shoshone National Forest, Cave 452.” Is that the one in the canyon?": "Jestem cały. Są tu też jakieś klucze, nie wiem, dlaczego ktoś je tu \nschował. Są podpisane: „Las Państwowy Shoshone, jaskinia 452”. \nTo ta w kanionie?",
  "Yeah, it is.": "Dokładnie ta.",
  "Who the hell took them?": "Kto je zabrał?",
  "And what the hell is in that cave?": "I co jest w tej cholernej jaskini?",
  "Okay, let's just think.": "Pomyślmy.",
  "Says the woman with half a bottle of tequila in her belly.": "Mówi kobieta, która wlała w siebie pół butelki tequili.",
  "Maybe they're panicking and were preparing to beat it. They fire has them spooked and we have new walkie talkies so we have the upper hand.": "Może spanikowali i szykowali się, by stamtąd zwiać, ogień musiał \nich wystraszyć. A my mamy przewagę z nowym walkie-talkie.",
  "Maybe they're panicking and were preparing to beat it. The fire must have them spooked.": "Może spanikowali i szykowali się, by stamtąd zwiać. Ogień musiał ich wystraszyć.",
  "Well, I'm standing in the dark in the middle of the woods. So, you know. They don't have a monopoly on being spooked.": "Stoję otoczony ciemnościami w środku lasu, wiec wiesz... Oni nie mają monopolu na odczuwanie strachu.",
  "It's hard to feel like you have the upper hand when you're standing in the dark in the middle of the woods.": "Nie czuć tej przewagi, kiedy stoi się otoczonym ciemnościami \nw środku lasu.",
  "Oh, well you're back in your tower. Maybe you need a drink too.": "Jesteś już w swojej wieży, może też potrzebujesz się napić.",
  "I’m not in my tower.": "Nie jestem w wieży.",
  "I am looking at a man standing in your lookout. And it's not you?": "Patrzę właśnie na mężczyznę stojącego na wieży. To nie ty?",
  "It is not me.": "To nie ja.",
  "Oh my God. Go.": "Mój Boże. Pędź tam.",
  "I'm going.": "Lecę!",
  "Two Forks Lookout": "Wieża na Rozdrożach",
  "Hey, I got turned around… is that person still there?": "Coś mnie zatrzymało... Czy on wciąż tam jest?",
  "Is that person still there?": "Wciąż tam jest?",
  "No, he’s gone.": "Nie, poszedł.",
  "I’ll call you when I’m back.": "Odezwę się, kiedy wrócę.",
  "Hey is that person still up there?": "Nadal tam jest?",
  "Alright. I’m close, I just didn’t want to run into him.": "Jestem blisko. Nie chciałem tylko na niego wpaść.",
  "Yeah… look, be careful.": "Tak... Bądź ostrożny.",
  "I’ll call you when I get up there.": "Odezwę się, kiedy będę na miejscu.",
  "Empty Lookout": "Opustoszała wieża",
  "I don’t see anyone up here.": "Nikogo tu nie widzę.",
  "He was just there.": "Był tam przed chwilą.",
  "Hmm. Left a cassette player taped to my damn door…": "Taśmą przykleił do drzwi odtwarzacz kaset...",
  "Report cassette tape player": "Zgłoś odtwarzacz kaset",
  "I don’t even know what to say to that.": "Nawet nie wiem, co powiedzieć.",
  "Well, let’s see what’s on it.": "Przekonajmy się, co jest na nagraniu.",
  "It’s a tape of us talking down at the site. It sounds like it was recorded from somewhere nearby.": "To zapis naszej rozmowy z ośrodka. Brzmi tak, jakby ktoś nagrywał to z bliska.",
  "It's a tape of us talking.": "To nagranie naszej rozmowy.",
  "Oh Jesus.": "O Jezu.",
  "Yeah. And… it sounds like we were the ones who burned it down— and that it was your idea.": "Brzmi to tak, jakbyśmy to my go spalili... i że był to twój pomysł.",
  "No.": "Nie.",
  "We are screwed.": "Już po nas.",
  "NO.": "Nie.",
  "D, just don't freak out, okay? Don't freak out.": "Tylko nie panikuj, dobrze? Nie panikuj.",
  "Don't freak out.": "Nie panikuj.",
  "Oh my God. WHAT THE FUCK IS HAPPENING HENRY?!?": "Mój Boże. Henry, co tu się odpierdala?!",
  "What’s on the tape, Henry.": "Co jest na nagraniu?",
  "Henry, do you hear me?": "Henry, słyszysz mnie?",
  "What is it? What's on it, Henry?": "Co się dzieje, co jest na kasecie?",
  "Did he leave something? C'mon I can see you over there.": "Zostawił coś? Dalej, przecież cię widzę.",
  "Is that a tape player? Did he leave you a tape?!": "Czy to magnetofon? Zostawił kasetę?",
  "Would you tell me what’s on the tape?!": "Powiesz mi, co jest na taśmie?!",
  "TELL ME WHAT’S ON THE GODDAMN TAPE!": "Powiedz, co jest na tej cholernej taśmie!",
  "What are you doing over there?": "Co tam robisz?",
  "Report bag and key": "Zgłoś plecak i klucz",
  "Hello?": "Halo?",
  "If that thing is driving you crazy just turn it off or throw it away.": "Jeśli doprowadza cię do szału, wyłącz to i wyrzuć.",
  "OR… just pace around your tower like you are right now.": "Albo kręć się po swojej wieży, jak robisz to teraz.",
  "Henry, you're freaking me out.": "Henry, przerażasz mnie.",
  "Henry?": "Henry?",
  "Uh… I'm not there.": "Nie jestem na wieży.",
  "What?!": "Co?!",
  "I followed the beeping and I found a hidden of bag of supplies and keys, and I think maybe they're for the cave.  But what's going on?": "Kierowałem się detektorem fal i znalazłem ukryty plecak i klucze, które pewnie otwierają bramę w jaskini. Co się dzieje?",
  "Henry, there's someone in your tower right now.": "Henry, ktoś jest teraz w twojej wieży.",
  "And apparently it's not you.": "I najwidoczniej to nie ty.",
  "GET BACK HERE.": "Wracaj tam.",
  "I'm so sick of letting these people do this to us. We should just burn the place down!    ": "Czas położyć kres zabawie tych szajbusów. Powinniśmy puścić \nto miejsce z dymem!    ",
  "Yeah. Fuck 'em.": "Tak, jebać ich!",
  "We'll dump an ocean of water on it and these assholes will spend the rest of the summer picking up the pieces.": "Strażacy wyleją tu ocean wody i minie całe lato, zanim te dupki się pozbierają.",
  "We get to finish out our contracts. Hell, we'll even call in the fire.": "Będziemy mogli doczekać końca kontraktu. Co tam, sami zgłosimy ten pożar.",
  "Yeah. Okay.": "Dobrze.",
  "I'm so sick of letting these people do this to us. We should just burn the place down!": "Czas położyć kres zabawie tych szajbusów. Powinniśmy puścić \nto miejsce z dymem!",
  "Delilah.": "Delilah.",
  "What? Think about it!": "Co? Przemyśl to!",
  "I am.": "Myślę.",
  "The grass is dry as hell here. It would go up in a second!": "Trawa jest sucha jak wiór. Zajęłaby się ogniem w momencie!",
  "Think about it! We'll dump an ocean of water on it…": "Przemyśl to! Strażacy wyleją tu ocean wody...",
  "…And these assholes will spend the rest of the summer picking up the pieces!": "...i minie całe lato, zanim te dupki się pozbierają!",
  "Maybe they're panicking and were preparing to beat it. The fire has them spooked and we have new walkie talkies so we have the upper hand.": "Może spanikowali i szykowali się, by stamtąd zwiać, ogień musiał \nich wystraszyć. A my mamy przewagę z nowym walkie-talkie."
}