{
  "Delilah": "Delilah",
  "Hey, did that go okay?": "I jak poszło?",
  "I might have got a little hot.": "Może mnie nieco poniosło.",
  "I hope they drown.": "Mam nadzieję, że się utopią.",
  "It's done.": "Po sprawie.",
  "It went fine.": "Dobrze.",
  "Henry": "Henry",
  "It went fine. Hopefully there won’t be any more trouble.": "Poszło dobrze. Oby nie było więcej problemów.",
  "Hey.": "Hej.",
  "Good, thanks for going down there.": "Dobrze. Dzięki, że to załatwiłeś.",
  "It’s done.": "Zrobione.",
  "Well that’s… ominous.": "Zabrzmiało złowrogo...",
  "Hopefully there won’t be any more trouble.": "Oby nie było więcej problemów.",
  "I mighta got a little hot.": "Może mnie nieco poniosło.",
  "I might'a got a little hot.": "Może mnie nieco poniosło.",
  "What’s “a little hot.”": "Zdefiniuj „poniosło”.",
  "Some of their personal property took a swim.": "Część ich dobytku poszła popływać.",
  "Oof.": "Ech...",
  "Well, I can’t do anything about it now.": "Teraz już po ptokach.",
  "Nope… thanks for dealing with them though. Seriously.": "I tak dzięki, że odpowiednio się tym zająłeś. Serio.",
  "No problem.": "Żaden problem.",
  "Yeow.": "Łał.",
  "If they torched everything between here and Cody, do you think they’d regret it?": "Myślisz, że żałowałyby spalenia wszystkiego stąd aż do Cody?",
  "I don’t think anyone would mourn a couple of future arsonists.": "Chyba nikomu nie byłoby szkoda pary przyszłych podpalaczy.",
  "I’m just going to go ahead and NOT log that as a threat.": "Uznam, że nie była to groźba.",
  "Thanks.": "Dzięki.",
  "But, seriously though, thanks for dealing with it.": "Ale serio, dzięki, że się tym zająłeś.",
  "It went fine, I—": "Poszło dobrze, po prostu...",
  "Oh, wow— the music's a little loud!": "Kurczę, muzyka daje całkiem głośno!",
  "Oh, sorry.": "Przepraszam...",
  "I took their stereo.": "Zabrałem im granie.",
  "Okay! Well, I guess we're all even then?": "Dobra! To chyba jesteśmy kwita?",
  "Yeah, I think so.": "Tak myślę.",
  "I might'a got a little—": "Może mnie nieco...",
  "[Frustrated Sigh]": "[Zniecierpliwione wzdychnięcie]",
  "Well, look, if you can hear me, try to get back soon, okay?": "Jeśli mnie słyszysz, postaraj się niedługo wrócić, dobrze?",
  "…": "...",
  "It's getting late.": "Robi się późno.",
  "You there? Henry?": "Jesteś tam? Henry?",
  "Oh, there you are.": "A, tu jesteś."
}