{
  "Trapped in Cave": "Uwięziony w jaskini",
  "Henry": "Henry",
  "Hey, hey you there?": "Hej, jesteś tam?",
  "Report being trapped in cave.": "Zgłoś uwięzienie w jaskini",
  "Delilah": "Delilah",
  "Yeah, what is it? What did you find?": "Co się dzieje? Co znalazłeś?",
  "You saw someone?!": "Widziałeś kogoś?!",
  "No, someone slammed the gate behind me and then ran away. I found another way out. But if I hadn't… Jesus!": "Nie, ktoś zatrzasnął za mną bramkę i uciekł. Znalazłem inną drogę wyjścia, ale gdyby mi się nie udało... Jezu!",
  "Nothing yet. Because someone tried to trap me in there.": "Jeszcze nic, bo ktoś próbował mnie uwięzić.",
  "So… so you didn't find anything?": "Więc... nic nie znalazłeś?",
  "No. There's a spot where someone had sunk an anchor but the hardware's gone now.": "Nie. Znalazłem tam skałę, w którą ktoś wcześniej wbił hak, \nale nie ma po nim śladu.",
  "I don't have any climbing equipment.": "Nie mam sprzętu do wspinaczki.",
  "I just have my ropes. I'm going to hike back to Two Forks and see if I can find anything that could double as an anchor to use in the spot.": "Mam tylko swoje liny. Wrócę do wieży i sprawdzę, czy uda mi się znaleźć coś, co może posłużyć jako zamiennik haka.",
  "That doesn't sound dangerous.": "Brzmi jak bułka z masłem.",
  "What do you think is in there?": "Jak myślisz, co tam jest?",
  "I don't know really… we gotta find out. What do you think?": "Nie mam pojęcia. Musimy się dowiedzieć. A ty co uważasz?",
  "I don't know, what do you think?": "Nie wiem. Co ty sądzisz?",
  "Probably something that will kill me. So, you know, just sort of getting myself right with God or whatever there is.": "Pewnie coś, co mnie zabije. Więc wiesz, szykuję się już na spotkanie z Bogiem, czy czymkolwiek, co mnie tam czeka.",
  "I'm probably going to be killed.": "Pewnie tam zginę.",
  "Henry…": "Henry...",
  "There's got to be something. Why else try to kill me?": "Coś na pewno. Z jakiego innego powodu chcieliby mnie zabić?",
  "There's something in there.": "Coś na pewno.",
  "Whatever's it is, they don't want you telling anyone about.": "Cokolwiek tam jest, nie chcą, żebyś o tym rozpowiadał.",
  "They closed the door when they could've just…": "Zatrzasnęli bramkę, a mogli po prostu...",
  "Bashed your head in with a rock or chopped you with a…": "Zmiażdżyć ci głowę kamieniem albo porąbać cię...",
  "Are you serious with this shit right now?": "Ty tak na serio?",
  "…hatchet. God, are you sure you want to go back in there?": "...toporkiem. Jezu, naprawdę chcesz tam wracać?",
  "No, I think I'm probably good. Bring on jail.": "Nie, zmieniłem zdanie. Więzienie brzmi przytulniej.",
  "No.": "Nie.",
  "You’d probably just get probation. I’d be the one stuffed away in the Lusk Women’s prison for the next ten years.": "Dostałbyś tylko zawieszenie. To ja utknęłabym w więzieniu \ndla kobiet w Lusk na następne dziesięć lat.",
  "Yeah. Especially now that I'm thinking about all the fun ways to be killed.": "Tak. Zwłaszcza teraz, gdy rozmyślam o wszystkich fajnych sposobach na zostanie zabitym.",
  "Yeah.": "Tak.",
  "Sorry. At least whoever locked you in doesn't know you've gotten out. Hopefully you find whatever they're hiding in there and it'll be worth the risk.": "Wybacz. Przynajmniej ten, kto cię zamknął, nie wie, \nże się wydostałeś. Może dowiesz się, co tam ukrywają \ni okaże się to warte ryzyka.",
  "Honestly, I just want to know. I want to know what is worth doing everything that's been done to us.": "Szczerze mówiąc, chcę po prostu wiedzieć. Zrozumieć, co jest warte zgotowania nam takiego piekła.",
  "I gotta know what it is.": "Muszę się tego dowiedzieć.",
  "Yeah, me too. And not going to jail would be a nice kicker.": "Ja też. A uniknięcie więzienia byłoby miłym dodatkiem.",
  "Well, let me know before you go back in, okay?": "Poinformuj mnie, zanim tam wrócisz, dobrze?"
}