{
  "Henry": "Henry",
  "I'm going back in.": "Wracam tam.",
  "Report cave": "Zgłoś jaskinię",
  "I said I'm going back in.": "Powiedziałem, że tam wracam.",
  "Delilah": "Delilah",
  "What do you think you're actually going to find?": "Myślisz, że co tam znajdziesz?",
  "More elk?": "Więcej jeleni?",
  "I'll call you when I'm out.": "Dam ci znać, jak wyjdę.",
  "Can you hear me? Damn.": "Słyszysz mnie? Cholera.",
  "Ah shit…": "Do diabła...",
  "Are you… oh God.": "Jesteś... O Boże.",
  "You're Brian Goodwin.": "Jesteś Brian Goodwin.",
  "Oh no.": "O nie.",
  "God.": "Boże.",
  "You poor kid.": "Biedny dzieciaku.",
  "You fell.": "Spadłeś.",
  "Your… stuff gave out.": "Twój sprzęt... zawiódł.",
  "You poor fucking kid.": "Biedaku...",
  "Report body": "Zgłoś ciało",
  "Delilah.": "Delilah.",
  "Hey D.": "Hej, D.",
  "There you are. I've been worrying my ass off.": "Nareszcie! Zamartwiałam się na śmierć.",
  "Brian Goodwin is dead. His body is the only thing I found in the cave.": "Brian Goodwin nie żyje. Nie znalazłem w tej jaskini nic poza jego ciałem.",
  "Brian Goodwin is dead.": "Brian Goodwin nie żyje.",
  "What?!": "Co?!",
  "He's dead, D.": "On nie żyje, D.",
  "Hey, I um… I'm sorry, Delilah. I'm so sorry.": "Przykro mi, Delilah. Tak strasznie mi przykro.",
  "I'm sorry, D.": "Przykro mi, D.",
  "About what? You're freaking me out.": "Dlaczego? Przerażasz mnie.",
  "He's in there.": "On tam jest.",
  "What are you saying, Henry?": "O czym ty mówisz, Henry?",
  "The only thing in the cave is Brian. He's dead. His body is in the cave, Delilah.": "Ta jaskinia skrywała jedynie Briana. Nie żyje. Jego ciało spoczywa \nw jaskini, Delilah.",
  "You need to call search and rescue.": "Musisz wezwać służby ratunkowe.",
  "Call search and rescue.": "Wezwij służby ratunkowe.",
  "Uh, what?": "Że co?",
  "There's a body in the cave. It's Brian Goodwin.": "W jaskini jest ciało. To Brian Goodwin.",
  "Hey, you might want to take a seat.": "Będzie lepiej, jeśli usiądziesz.",
  "Sit down.": "Usiądź.",
  "I've been sitting this entire time. I'm almost always sitting. What's wrong?": "Siedzę, odkąd rozmawiamy. Właściwie to ciągle siedzę. Co jest?",
  "The only thing in the cave was a body.": "W tej jaskini nie było niczego poza ciałem.",
  "A body? Gah, what a mess.": "Ciałem? Chryste, co za bajzel.",
  "Delilah. It's Brian Goodwin": "Delilah. To Brian Goodwin.",
  "You've got to be fucking kidding me.": "To chyba jakiś jebany żart.",
  "Who does that… What—I don't—": "Kto by mógł... Co? Ja nie...",
  "How?": "Jak?",
  "Climbing, I think. Or made to look like a climbing accident.": "Myślę, że podczas wspinaczki. Albo ktoś upozorował wypadek.",
  "Mmhmm.": "Mhm.",
  "He just left him out here. He left his son.": "Po prostu go tam zostawił. Porzucił swojego syna.",
  "Whoever is out there did it.": "Ktokolwiek to zrobił, jest tutaj.",
  "Whoever is out there did it. They killed him.": "Ktokolwiek to zrobił, jest tutaj. To oni go zabili.",
  "Can we put this stupid shit aside for a minute? That boy is dead. He was just a sweet kid. \"They\" didn't kill him. Why kill a boy?": "Czy możemy odłożyć te głupoty na bok? Chłopak nie żyje. Był tylko słodkim dzieciakiem... „Oni” go nie zabili. Po co zabijać dziecko?",
  "I don't know.": "Nie wiem.",
  "Maybe it was Ned.": "Może to sprawka Neda.",
  "I don't know, maybe it was Ned.": "Nie wiem, może to sprawka Neda.",
  "If not him directly he put enough stupid fucking know-how in his head to get him killed. Son of a bitch.": "Nawet jeśli nie zrobił tego umyślnie, wyszkolił go wystarczająco dobrze, by mogło do tego dojść. Skurwysyn.",
  "Yeah.": "Tak.",
  "I think that's just what it was. He was exploring the cave and maybe his rope gave out.": "Myślę, że właśnie tak się stało. Zwiedzał jaskinię i widocznie jego lina puściła.",
  "I think it was an accident.": "To mógł być wypadek.",
  "Whoever's after us probably didn't even know about him.": "Ktokolwiek nas śledzi, pewnie nawet o nim nie wiedział.",
  "Whoever locked me in there probably didn't even know about him.": "Ktokolwiek mnie tam zamknął, pewnie nawet o nim nie wiedział.",
  "Delilah… you should've told someone he was out here.": "Delilah... Powinnaś była kogoś zawiadomić o jego obecności.",
  "You should've told someone about him.": "Miałaś obowiązek kogoś o nim powiadomić.",
  "Just stop. Okay? I know.": "Przestań, dobrze? Wiem o tym.",
  "Maybe he would've—": "Może wtedy...",
  "Henry, you insensitive shit. You don't think I know he'd be alive if it weren't for me?": "Henry, ty nieczuły bydlaku. Myślisz, że nie wiem, że nadal by żył, gdyby nie ja?",
  "And I fucking know it's my fault. I'll never forget that it's on me.": "I wiem, że to moja pierdolona wina. Nigdy sobie tego nie wybaczę.",
  "What do we do now, D? I mean, are you okay?": "Co teraz robimy, D? To znaczy... dobrze się czujesz?",
  "What do we do now?": "Co teraz robimy?",
  "No, I'm not.": "Nie.",
  "I'm sorry, Delilah. I'm so sorry.": "Przykro mi, Delilah. Tak bardzo mi przykro.",
  "I'm sorry, Delilah.": "Przykro mi, Delilah.",
  "He'd be alive had I told someone he was out here.": "Gdybym powiedziała komuś, że tu był, nadal by żył.",
  "I don't know where he'd be but I can assure you it would not be rotting at the bottom of that cave.": "Nie wiem, gdzie by teraz był, ale jestem pewna, że nie gniłby \nna dnie tej jaskini.",
  "I…": "Ja...",
  "There's—there's—there's nothing to say. Hike back. I think we're leaving tomorrow, anyway.": "Tu... tu nie ma nic do dodania. Wracaj do siebie. \nJutro i tak wyjeżdżamy."
}