{
  "Delilah": "Delilah",
  "Henry, what the fuck are you doing?": "Henry, co ty odpierdalasz?",
  "They. Can. Hear. Us.": "Oni nas słyszą...",
  "Henry": "Henry",
  "I don’t care.": "Mam to gdzieś.",
  "Please, Henry, just go where I told you to.": "Proszę, Henry. Po prostu idź tam, gdzie ci kazałam.",
  "Please go there right now.": "Proszę, idź tam w tej chwili.",
  "Goddammit Henry! Fine.": "Cholera jasna, Henry! Dobra.",
  "I left you a new a radio, dammit. But to hell with it.  Just do whatever you want.": "Zostawiłam ci nową krótkofalówkę, do cholery. Ale chrzanić to. Rób sobie, co chcesz.",
  "Oh, I’ll go get it.": "Wrócę się po nią.",
  "Oh.": "Och.",
  "Forget it.  We’ve danced around it so much now it’s probably gone, now.": "Zapomnij. Kręciliśmy się wokół niej na tyle długo, że pewnie już jej nie ma.",
  "But maybe you’ll luck out and whoever is listening to us ran down to the market for a gallon of milk.": "Ale może dopisze ci szczęście i ktokolwiek nas podsłuchuje, akurat wyskoczył do sklepu po mleko.",
  "Seriously. For fuck’s sake.": "Na poważnie, kurwa mać.",
  "I'm busting the gate down. There's nobody around and it's the quickest way in.": "Wyważam bramę. Nikogo nie ma w pobliżu, a to najszybszy sposób.",
  "Gate, meet axe.": "Bramo, oto siekiera.",
  "Copy that.": "Przyjęłam.",
  "I smashed open the gate. Should I try to fix or hide this?": "Udało mi się wyważyć bramę. Naprawić to albo zamaskować?",
  "Should I try and fix this?": "Mam to naprawić?",
  "No, screw it.": "Nie, chrzanić to.",
  "Okay then.": "Okej.",
  "Research Site": "Ośrodek badawczy",
  "There's nobody here. It's just tents and equipment and, yeah that's it.": "Nikogo tu nie ma. Same namioty i trochę sprzętu, to wszystko.",
  "Report empty site": "Zgłoś opustoszały ośrodek",
  "Look everywhere. Maybe you can find something that will help us know what's going on.": "Rozglądaj się uważnie. Może znajdziesz coś, co pomoże nam zrozumieć, o co tu chodzi.",
  "For now.": "Póki co.",
  "Come on, D.": "No weź, D.",
  "No, I’m pissed. You’re out there on your own.": "Nie. Jestem wściekła. Musisz działać na własną rękę.",
  "This place feels like there's bad shit afoot, you know? It's sterile. Dead.": "Mam co do tego bardzo złe przeczucia. To miejsce jest sterylne. I martwe.",
  "People are up to some bad shit here.": "Tu się dzieją jakieś niefajne rzeczy.",
  "Just get out of there. You never have to come back.": "Po prostu spadaj stamtąd. Już tam nie wrócisz.",
  "Uh huh.": "Taa.",
  "Just see where that thing leads you and then get out.": "Sprawdź, dokąd to prowadzi, a potem wiej.",
  "Hopefully we find some proof to back that up.": "Mam nadzieję, że znajdziemy jakiś dowód na poparcie tego.",
  "Yeah, well, hopefully you find something to back that up.": "Ta. No cóż, miejmy nadzieję, że znajdziesz jakiś dowód.",
  "Why would something like this even be out here?": "Dlaczego coś takiego w ogóle tu jest?",
  "Why would this be here?": "Po co to tu jest?",
  "Wouldn't it be easier to spy on people in a city? Somewhere you can blend into the background?": "Nie byłoby łatwiej szpiegować ludzi w mieście? Gdzieś, gdzie można łatwo wtopić się w tło?",
  "It's also a lot harder to get rid of problems if there are people around.": "Poza tym ciężej pozbyć się kłopotów, jeśli dokoła są ludzie.",
  "Out here you can just disappear.": "Tutaj możesz zwyczajnie zniknąć.",
  "Thanks for that. How about I stay in my lookout and you do all the hiking around?": "Dzięki. A może to ja zostanę w wieży, a ty zajmiesz się tym całym spacerowaniem?",
  "Thanks for that.": "Dzięki.",
  "Ahh… no thank you.": "Nie, dzięki.",
  "I don't know, Henry.": "Nie wiem, Henry.",
  "I'm sure whoever is listening to you right now has their reasons.": "Z pewnością osoba, która nas teraz słucha ma swoje powody.",
  "Okay, I'm at the site. I don't see anybody around.": "Dobra, dotarłem na miejsce. Nikogo nie widać.",
  "Lucky for us.": "Całe szczęście.",
  "Yeah, lucky for us.": "Ta, całe szczęście.",
  "There's a few structures out here.  Stuff you could live in for months.": "Są tu jakieś zabudowania. Można by w nich mieszkać miesiącami.",
  "Report shed": "Zgłoś budę",
  "That makes sense.": "To ma sens.",
  "I'm sorry, alright?": "Przepraszam, okej?",
  "Yeah.": "Tak.",
  "Maybe they keep their equipment in there.": "Może trzymają tam swój sprzęt.",
  "Maybe they keep themselves in there.": "Może tam mieszkają.",
  "They might. I'll look around.": "Możliwe. Rozejrzę się.",
  "With their equipment.": "Ze swoim sprzętem.",
  "Let's hope this equipment isn't machine guns.": "Miejmy nadzieję, że ten sprzęt to nie karabiny maszynowe.",
  "Or any guns.": "Ani żadne inne karabiny.",
  "And you don't see anybody?": "Na pewno nikogo tam nie ma?",
  "No, not yet. But it's definitely in use. They're just gone right now.": "Chyba nie, ale sprzęty są w użyciu. Po prostu wszyscy gdzieś zniknęli.",
  "Report monitoring tower": "Zgłoś wieżę monitorującą",
  "D, there is some serious comms equipment out here.  Wireless stuff.": "D, jest tu jakiś sprzęt do komunikacji bezprzewodowej. \nRobi wrażenie.",
  "I'm not even sure a new radio would do us any good.": "Nie jestem pewien, czy nowa krótkofalówka w czymś by nam pomogła.",
  "Yeah, well.": "Bywa.",
  "What do you mean?": "Co masz na myśli?",
  "I'm talking a big, twenty-foot tall transmission tower. They can probably listen to whoever the hell they want.": "Wysoką na sześć metrów wieżę transmisyjną. Mogą pewnie podsłuchiwać, kogo tylko zechcą.",
  "They're nestled down in this valley which makes it impossible for you or any lookout to see them.": "Ukryli się w tej dolinie. Nie ma możliwości dostrzeżenia ich z żadnej wieży obserwacyjnej.",
  "Report soil grid": "Zgłoś siatkę pomiarową",
  "They're doing something with the soil out here too. It's gridded off.": "Prowadzą też jakieś badania nad glebą. Jest częściowo wydzielona siatką.",
  "Maybe you were right about the lichens.": "Chyba miałaś rację z tymi porostami.",
  "Who knows what else they’re up to.": "Kto wie, co jeszcze tu kombinują.",
  "There's all sorts of contraptions and shit out here.": "Jest tu pełno przyrządów i innych dupereli.",
  "Report monitoring equipment": "Zgłoś sprzęt monitorujący",
  "Just keep searching. They've got to be back any second now.": "Szukaj dalej. Mogą wrócić w każdej chwili.",
  "Like what?": "Na przykład?",
  "Dishes and stuff on metal legs. There's wires all over the place I don't know. I'm not really up on high tech.": "Anteny satelitarne i ustrojstwa na metalowych podpórkach. Wszystko jest okablowane, a ze mnie żaden spec.",
  "This equipment is not stuff from the hardware store.": "To nie sprzęt z byle sklepu.",
  "This stuff looks expensive.": "Wszystko wygląda na drogie.",
  "I mean how the hell did they get all of this stuff out here?": "Znaczy, jak u diabła oni to wszystko tu ściągnęli?",
  "How could they get this out here?": "Jak oni to tu przytargali?",
  "The Army Corps of Engineers put our towers out here, so…": "Nasze wieże postawił korpus wojsk inżynieryjnych, więc...",
  "You think it was the government?": "Myślisz, że to rząd za tym stoi?",
  "I have no idea. I just mean it's possible. I mean, every once in a while I'll meet a lookout who's deep into that like, black helicopter conspiracy shit. Maybe they actually flew it out here in one of those.": "Nie mam pojęcia. Niewykluczone. Znaczy się, od czasu do czasu mam do czynienia z obserwatorem, który wierzy w te wszystkie teorie spiskowe o czarnym helikopterze. Może z jakiegoś tu korzystali.",
  "Tent": "Namiot",
  "I'm in their main tent.": "Jestem w ich głównym namiocie.",
  "What's it like?": "Jak wygląda?",
  "…Tell me what you see.": "Powiedz, co widzisz.",
  "It's definitely some sort of monitoring station.": "To zdecydowanie jakiś ośrodek badawczy.",
  "Report swinging light": "Zgłoś rozhuśtaną lampę",
  "Someone’s been in here. The light fixture is swinging": "Ktoś tu niedawno był. Lampa wciąż się huśta.",
  "You’re sure it wasn’t the wind or something?": "Jesteś pewien, że to nie wiatr?",
  "Yes.": "Tak.",
  "Holy shit.  Find out whatever you can before they come back.": "Cholera. Dowiedz się jak najwięcej, zanim wrócą.",
  "Report cots": "Zgłoś łóżka polowe",
  "This place sleeps three.  They’ve got a row of cots here.": "To trzyosobowy namiot. Jest tu rząd składanych łóżek.",
  "I want to know what that thing finds. Look, you should get out before they come back.": "Chcę się dowiedzieć, dokąd to prowadzi. Powinieneś się wynosić, zanim wrócą.",
  "You should get out before they come back.": "Powinieneś się wynieść, zanim wrócą.",
  "So they live and work in same tent?": "A więc żyją i pracują w tym samym namiocie?",
  "Yeah, it's all one operation.": "Tak, wszystko w jednym miejscu.",
  "Ha, like us.": "Zupełnie jak my.",
  "Yeah, like us.": "Ta, jak my.",
  "Report belongings": "Zgłoś zapasy",
  "I just wonder where they are. All of their stuff is here.": "Zastanawia mnie, gdzie oni wszyscy poleźli. Zostawili wszystkie rzeczy.",
  "Well don't hang around to find out.": "Chyba lepiej, żebyś tego nie wiedział.",
  "Figure out what that thing does and then get the hell out.": "Dowiedz się, gdzie prowadzi to urządzenie i spadaj.",
  "Oh they probably just popped down to bar to catch the game.": "Pewnie urządzają sobie właśnie wesoły wieczorek w jakiejś knajpie.",
  "I’m getting a little nervous, here.": "Zaczynam się lekko denerwować.",
  "Did I tell you I’m a palm sweater? I don’t think I’ve told you that. Maybe I did. I don’t know. My palms are very sweaty.": "Mówiłam ci, że gdy się denerwuję, pocą mi się dłonie? Chyba nie. A może? Nie wiem. Mam strasznie spocone dłonie.",
  "And they know you’re there. So see what you can find and get out.": "I wiedzą, że tam jesteś. Dowiedz się, ile zdołasz i spadaj stamtąd.",
  "Yeah well, whatever this thing is detecting is on this desk.": "No cóż, cokolwiek ta rzecz wykrywa, znajduje się na biurku.",
  "Report equipment": "Zgłoś sprzęt",
  "Find it, Henry.": "Znajdź to, Henry.",
  "I found their main monitoring desk.": "Znalazłem chyba ich centrum dowodzenia.",
  "Hey, this desk seems to be where all the monitoring is recorded.": "Najwyraźniej to na tym biurku składują cały sprzęt monitorujący.",
  "My God. What do you see?": "Mój Boże. Co widzisz?",
  "Tell me what you see, quick.": "Szybko, mów mi, co widzisz.",
  "Just, dials and computers and sorts of doodads. Holy shit, you don’t think they’re able to record our heart-rate and stuff, do you?": "Pokrętła, sprzęty elektroniczne i inne ustrojstwa. Jasny gwint, chyba nie sądzisz, że są w stanie badać nasze tętno i w ogóle?",
  "Seriously, at this stage I’d believe just about anything.": "W tej sytuacji mogę już uwierzyć chyba we wszystko, serio.",
  "There’s a box here with a dial. It has a needle; like it measures earthquakes.": "Leży tu jakieś pudło z pokrętłem i igłą. \nZ wyglądu przypomina mi sejsmograf.",
  "Report earthquake monitor": "Zgłoś sejsmograf",
  "You mean like a lie detector?": "Czyli jakby wykrywacz kłamstw?",
  "I’m not sticking around to get hooked up to it.": "Nie mam zamiaru czekać, aż mnie do tego podłączą.",
  "Yeah. Alright. Okay.": "Jasne, rozumiem.",
  "There’s some sort of monitor. I don’t know what it does. Maybe air quality or something?": "Jest tu jakieś urządzenie. Nie wiem, do czego służy. Może mierzy jakość powietrza, czy coś.",
  "Report device": "Zgłoś urządzenie",
  "Henry, you need to go, okay?": "Henry, musisz stamtąd iść, rozumiesz?",
  "Yeah, I just, I want to look around.": "Tak, tak. Chcę się tylko rozejrzeć.",
  "Please be careful.": "Bądź ostrożny, proszę.",
  "Maybe they’re keeping data on everything that could impact our moods.": "Może zachowują informacje o wszystkim, co mogłoby wpłynąć \nna nasz nastrój.",
  "That looks… possible. This is crazy!": "To... możliwe. Ależ to jest porąbane!",
  "Seems plausible.": "Całkiem możliwe.",
  "What… they’re measuring the barometric pressure, too. Why?!": "Że co? Mierzą też ciśnienie atmosferyczne. Po jaką cholerę?!",
  "Report barometer…?": "Zgłoś... barometr?",
  "Maybe it's just a diversion.": "Może to dla zmyły.",
  "Who knows.": "Kto wie.",
  "This stuff just looks like it got lifted out of the space shuttle.": "To wszystko wygląda jak wyciągnięte ze statku kosmicznego.",
  "Leave it behind.": "Zostaw to.",
  "Yeah, I know, it’s just, you should see it.": "Ta, wiem, ale powinnaś to zobaczyć.",
  "I have to tell you, if I found out this was NASA, I’d be a lot happier.": "Gdyby się okazało, że stoi za tym NASA, byłabym zachwycona.",
  "Uggh. Copy that.": "Przyjęłam.",
  "There’s a computer monitor in here but I don’t know how to turn it on to see what it displays.": "Jest tu jakiś monitor komputerowy, ale nie wiem, jak go włączyć, by sprawdzić, co wyświetla.",
  "Report computer monitor": "Zgłoś monitor",
  "Now is probably not the time to get tech savvy.": "Chyba nie czas na technologiczne rozkminy.",
  "Well, there’s always time to go back to college and learn a trade, says every day time TV commercial ever.": "Zawsze jest czas, żeby wrócić do szkoły i nauczyć się czegoś. Tak ci powie każda jedna reklama w telewizji.",
  "I think I’m done with exotic new jobs after this.": "Chyba dam sobie spokój z wymyślnymi fuchami.",
  "Keep looking around.": "Szukaj dalej.",
  "Okay, shit. I've got a map here that confirms they're tracking my, our, people's movements.": "Mam przed oczami mapę. Zdaje się potwierdzać, że ja... że my jesteśmy śledzeni.",
  "Report map": "Zgłoś mapę",
  "They’ve got a map with with all sorts of paths and areas marked out on it.": "Mają tu mapę z pozaznaczanymi trasami i obszarami.",
  "Okay, shit, I've got another clipboard here that confirms that they're tracking our movements.": "Jest tu jakiś notatnik. Z zapisków wynika, że śledzą każdy nasz ruch.",
  "Report clipboard": "Zgłoś notatnik",
  "Okay, so there's a log here tracks the movement of four distinct subjects.": "Mam przed sobą wpis, zgodnie z którym śledzono ruchy czterech obiektów.",
  "The map’s got all sorts of paths and areas marked off on it.": "Na mapie są pozaznaczane jakieś trasy i obszary.",
  "There are lines that look like some of the paths I normally take.": "Są tu linie, które zdają się wyznaczać ścieżki, którymi normalnie chodzę.",
  "Are you POSITIVE it’s you?": "Jesteś pewien, że chodzi o ciebie?",
  "I’m not sure, but I think so.": "Pewności nie mam, ale tak myślę.",
  "Um, some of their descriptions seem like uncharitable ways of describing me, yeah": "Niektóre opisy z całą pewnością pasują do mnie.",
  "The log they’ve got tracks the movement of four subjects.": "Zapisują ruchy czterech obiektów.",
  "You and me?": "Ciebie i mnie?",
  "Uh, yeah, definitely me, and I suppose you too.": "Z całą pewnością mnie. Ciebie pewnie też.",
  "What about the other two?": "Co z pozostałą dwójką?",
  "Maybe the Goodwins? What if they were following them last summer?": "Może Goodwinowie? Co jeśli ostatniego lata to ich śledzono?",
  "The Goodwins?": "Goodwinowie?",
  "God, Henry. I don't know. If they were there's no way Brian knew. He would've said something.": "Boże, Henry, nie wiem. Jeśli tak, to Brian nie miał o tym pojęcia. Inaczej coś by powiedział.",
  "Yeah, I can't imagine a kid like that could've kept this under his hat.": "Tak, dzieciak taki jaki jak on nie utrzymałby tego w sekrecie.",
  "Maybe the missing girls?": "Może zaginione dziewczyny?",
  "The missing teens?": "Zaginione nastolatki?",
  "Like, they’re still out here and these people are following them?": "Sądzisz, że nadal gdzieś tu są, a ci ludzie śledzą każdy ich ruch?",
  "Maybe. It’s possible, right?": "To możliwe, nie?",
  "But then why haven’t you seen them?": "Ale w takim razie czemu ty ich nie spotkałeś?",
  "I don’t know.": "Nie wiem.",
  "Maybe those two rangers, Ron and Dave? They used to be all over out here, right?": "Może tych dwóch leśniczych, Ron i Dave? Przecież kręcili się po tej okolicy, nie?",
  "Ron and Dave?": "Ron i Dave?",
  "I keep finding notes between those rangers, Dave and Ron. Maybe it’s them.": "Co jakiś czas znajduję listy tych leśniczych, Dave'a i Rona. Może to oni?",
  "I haven’t heard from them all summer. I don’t even know if they’re working.": "Nie miałam od nich żadnych wieści przez całe lato. Nawet nie wiem, czy nadal pracują.",
  "Maybe it’s old data. I don’t know.": "Może to stare dane, nie wiem.",
  "I have no idea. Maybe another couple that’s out here?  Do you have any ideas?": "Nie mam pojęcia. Może jeszcze ktoś tu jest? Jakieś pomysły?",
  "I don't know.": "Nie wiem.",
  "It’s just you and me, Henry.": "Tylko my, Henry.",
  "Yeah, I know.": "Tak, wiem.",
  "Well, I have no idea who else it could be. They're actually recording our movements? Christ.": "Nie mam pojęcia, kto inny mógłby to być. A więc faktycznie nas inwigilują? Chryste.",
  "I really think you should just get out of there. Get home and we’ll regroup.": "Naprawdę powinieneś już wracać. Potem zastanowimy się, co dalej.",
  "We’ll talk this over and figure out how to get the hell out of here.": "Obgadamy wszystko i znajdziemy sposób, żeby się stąd wynieść.",
  "Every once in a while a lookout will totally lose it and bug out.": "Zdarza się, że jakiś obserwator popada w obłęd i przepada.",
  "Pop his top, like you said.": "Odbiło mu, jak powiedziałaś.",
  "That's starting to make a lot of sense.": "To zaczyna mieć sens.",
  "Maybe it's not the isolation. Maybe it's whatever this is.": "Może to nie izolacja. Może to coś zupełnie innego.",
  "Maybe it's why the Goodwins left in such a hurry.": "Może to dlatego Goodwinowie wyjechali w takim pośpiechu.",
  "Maybe the Goodwins too?": "Może Goodwinowie również?",
  "Maybe those girls were targeted by these people as well.": "Może te nastolatki też były na ich celowniku.",
  "Maybe those girls were targeted too.": "Może te dziewczyny też były śledzone.",
  "Yeah. Maybe. Or maybe they don't get a chance to leave.": "Albo nigdy nie miały szansy stąd wyjechać.",
  "Jesus.": "Jezu.",
  "I mean, you've already been punched. Who's to say they wouldn't do worse?": "Pamiętaj, że ty zostałeś uderzony. Skąd pewność, że nie posuną się krok dalej?",
  "Great, I'm thinking about THAT now.": "Świetnie, teraz będę myślał tylko o tym.",
  "Yeah, and I'm going to lock my door.": "A ja zabarykaduję drzwi.",
  "The desk in here is a mess.": "To biurko jest strasznie zagracone.",
  "Report desk mess": "Zgłoś zagracone biurko",
  "It’s like someone was in a rush, or knocked a bunch of stuff over on accident.": "Wygląda, jakby ktoś miał niewiele czasu i w pośpiechu postrącał \nte rzeczy.",
  "I think this thing is responding to something in this pile of crap on the desk.": "Zdaje mi się, że to urządzenie łapie sygnał czegoś, co jest pod tą stertą papierzysk.",
  "Dig through it.": "Przekop się przez nią.",
  "I think I found what’s making this receiver go haywire. There’s a small black box on the desk; I think maybe it’s a tracker.": "Chyba znalazłem źródło uaktywnienia detektora. To mała, czarna skrzynka leżąca na biurku, chyba coś w rodzaju lokalizatora.",
  "Report tracked thing…?": "Zgłoś ustrojstwo",
  "Turn it off and take it with you": "Wyłącz go i weź ze sobą.",
  "Yeah, I’m going to.": "Tak zrobię.",
  "I think I found the thing they use to track us.": "Chyba znalazłem urządzenie, którym nas śledzą.",
  "Report tracking device instructions": "Zgłoś instrukcję obsługi detektora",
  "Holy shit.": "Cholera.",
  "You know you swear like, a lot.": "Naprawdę przesadzasz z przeklinaniem.",
  "Not the time, Hank.": "Daruj sobie, Hank.",
  "Anyway, It’s called a wave receiver. It looks like it picks up anything that emits a signal. It’s got basic orienteering capabilities, everything. Holy–": "W każdym razie, to detektor fal. Urządzenie, które odbiera wszystko, co emituje jakiś sygnał. Ma wbudowany moduł imitujący kompas i inne dziwne rzeczy. Jasny...",
  "Holy shit, Henry?": "Jasny gwint, Henry?",
  "Yeah, holy shit.": "Ta, jasny gwint.",
  "You're gonna take it, right?": "Zabierasz go, prawda?",
  "Yeah, of course.": "Oczywiście.",
  "Report wave receiver": "Zgłoś detektor fal",
  "They keep this wave receiver thing in a crate, it looks like their prize piece of equipment.": "Trzymają ten detektor w jakiejś walizce. Tak jakby to był ich największy skarb.",
  "Well it’s ours now.": "Teraz jest już nasz.",
  "You hear that, assholes?": "Słyszycie, dupki?",
  "Please don’t let any anger towards Delilah be directed towards me. She doesn’t mean that as harsh as it sounds.": "Proszę, nie kierujcie swojej złości na Delilah w moją stronę. Ona naprawdę nie chciała użyć tak ostrych słów.",
  "I'm sorry about her!": "Przepraszam za nią!",
  "Yes I fucking do.": "A właśnie, kurwa, że chciałam.",
  "Wave Receiver": "Detektor fal",
  "Uh, this thing is beeping like crazy.": "To coś pika jak oszalałe.",
  "Report beeping": "Zgłoś pikanie",
  "So it’s finding something, and someone is about to find YOU, and you keep talking about it!": "Czyli wyłapało jakiś sygnał, a ciebie zaraz też ktoś złapie, jeśli będziesz o tym paplał!",
  "Delilah can you just not? I've got this thing okay, and I'm the one out here and I'd appreciate it if you ditched the attitude.": "Delilah, możesz się uspokoić? Panuję nad wszystkim. Poza tym to ja nadstawiam karku, więc z łaski swojej spuść z tonu.",
  "Fine. Alright. You’re right.": "Dobra. Masz rację.",
  "I’m gonna go figure out what this thing is picking up.": "Postaram się dowiedzieć, jaki sygnał wyłapało to ustrojstwo.",
  "I was just gonna say that. Go figure out what that thing is picking up.": "Miałam to powiedzieć. Dowiedz się, jaki sygnał wyłapało to ustrojstwo.",
  "Okay, this thing is losing its mind. Beeping like crazy.": "To urządzenie chyba całkiem zgłupiało. Pika jak oszalałe.",
  "I can hear it. What’s it after?": "Słyszę. Na co tak reaguje?",
  "I don’t know. I’m gonna go find out.": "Nie wiem, ale się dowiem.",
  "Are you shitting me…": "Co to, kurwa, jest?",
  "Report binder": "Zgłoś segregator",
  "What is it?": "O co chodzi?",
  "There’s a folder of reports here.": "Znalazłem segregator wypełniony raportami.",
  "What do they say?": "O czym?",
  "They’re assessments. About the two of us.": "To opisy naszej dwójki.",
  "There's stuff in here about Julia.": "Mają też informacje na temat Julii.",
  "It says things about my life. Stuff you don't know.": "Mnóstwo wzmianek z mojego życia. Takich, o których nie wiesz.",
  "Stuff I didn’t tell you. This is–": "Rzeczy, o których nie mówiłem. To...",
  "What does it say about me?  You said there was one about me.": "A co takiego jest tam o mnie? Mówiłeś, że mają coś o mnie.",
  "And it looks like they’ve been following me around.  What I do when I’m out hiking.  Jesus!": "Wygląda na to, że śledzili każdy mój krok. Opisywali wszystko, \nco robię po opuszczeniu wieży. Jezu!",
  "Henry, do you hear me?": "Henry, słyszysz mnie?",
  "They say you and your boyfriend are still together.": "Napisano tutaj, że nadal spotykasz się ze swoim chłopakiem.",
  "What?! We’re not. They’re messing with us.": "Co?! To bzdura. Pogrywają sobie z nami.",
  "Yeah. Okay.": "Dobrze.",
  "They are. How do they even know who he is? How the hell does this—": "Naprawdę. Skąd w ogóle wiedzą, kim on jest? Jakim, kurwa, cudem...",
  "You have a boyfriend. Javier.": "Masz chłopaka o imieniu Javier.",
  "What the fuck?": "Co, kurwa?",
  "Wish you hadn’t left that out.": "Szkoda, że to ukrywałaś.",
  "I don’t. I didn’t. This is insane.": "Nie, ja nie... To jakiś obłęd!",
  "I'm so sick of letting these people do this to us.": "Czas położyć kres zabawie tych szajbusów.",
  "We should just burn the place down.": "Powinniśmy puścić to miejsce z dymem.",
  "Yeah. Fuck 'em.": "Tak, jebać ich!",
  "They’ll dump an ocean of water on it and these assholes will spend the rest of the summer picking up the pieces. We get to finish out our contracts. Hell, we'll even call in the fire.": "Strażacy wyleją tu ocean wody i minie całe lato, zanim te dupki się pozbierają. Będziemy mogli doczekać końca kontraktu. Co tam, sami zgłosimy ten pożar.",
  "Yeah, okay.": "Tak, jasne.",
  "You don't sound too excited about that.": "Nie wydajesz się być zbytnio podekscytowany.",
  "I'm not.": "Nie gniewam.",
  "Look, worst case scenario…": "Słuchaj, w najgorszym wypadku...",
  "…Worst case scenario, the fire rages out of control and kills a bunch of people.": "W najgorszym wypadku ogień wymknie się spod kontroli i zabije jakichś ludzi.",
  "Worst case.": "W najgorszym wypadku.",
  "The whole forest burns down along with whoever's in it?": "Las spłonie doszczętnie, a z nim wszyscy wokół?",
  "The forest burns down.": "Las spłonie doszczętnie.",
  "A firefighter dies trying to put out what we started and we live with that on our conscience for the rest of our lives.": "Jakiś strażak zginie, próbując ugasić wzniecony przez nas pożar. Będziemy żyć ze świadomością tego faktu do końca życia.",
  "A firefighter dies.": "Zginie strażak.",
  "We are trapped by the fire and burn alive, alone in the wilderness.": "Zostaniemy uwięzieni w tej dziczy i spłoniemy żywcem.",
  "We are trapped by fire.": "Zostaniemy odcięci przez ogień.",
  "Uhh, fuck… Yeah. Worst case.": "Tak... to jest najgorszy wypadek.",
  "Delilah…": "Delilah...",
  "That's insane.": "To czysty obłęd.",
  "What? Think about it.": "No co? Pomyśl tylko.",
  "I am and I think it's insane.": "Myślę i uważam to za szalone.",
  "They'd be fucked.": "Dojebalibyśmy im.",
  "And how about if that fire comes up the mountain? Or someone were to die in it?": "A co jeśli ogień rozprzestrzeni się dalej? Jeśli ktoś przez to zginie?",
  "We call it in.": "Zgłosimy to.",
  "WE CALL IT IN?": "Zgłosimy to?",
  "Yeah, maybe.": "Może.",
  "My God, Delilah. No. No way.": "Nie, Delilah, nie ma takiej opcji.",
  "Maybe that's what they want us to do.": "Może chcą, byśmy właśnie do tego doprowadzili.",
  "Maybe that's what they want.": "Może oni tego właśnie chcą.",
  "Maybe they’re trying to push us to the point where we do something crazy.": "Może starają się tak zamieszać nam w głowach, aż popełnimy nieodwracalną głupotę.",
  "The grass is dry as hell here. It would go up in a second.": "Trawa jest sucha jak wiór. Zajęłaby się ogniem w momencie.",
  "Well, now I’m thinking what if you’re right.": "Jak tak teraz o tym myślę, to możesz mieć rację.",
  "I just don't think we should do anything we can't undo.": "Nie powinniśmy robić niczego, czego nie cofniemy.",
  "Think about it.": "Przemyśl to.",
  "Worst case scenario…": "W najgorszym wypadku...",
  "Hmm…": "Hm...",
  "Worst case scenario, I guess… a bunch of people die.": "W najgorszym wypadku... zginie grupa ludzi.",
  "Well… maybe it's not the best idea.": "Cóż... może to nie najlepszy pomysł.",
  "It's definitely not the best idea.": "To zdecydowanie nie jest dobry pomysł.",
  "I'm so fucking wound up.": "Mam już tego, kurwa, dość.",
  "It's alright. I'm just going to hike back. We have the wave receiver and tomorrow we can figure out what to do.": "Spokojnie. Wrócę teraz do wieży. Mamy detektor fal, jutro wspólnie zdecydujemy, co robić dalej.",
  "It's okay. I'm heading back.": "Spokojnie. Wracam do wieży.",
  "You could've told me about your guy.": "Mogłaś mi o nim powiedzieć.",
  "I didn't want to.": "Nie chciałam.",
  "It’s a real wonder you’ve been alone in the woods for a decade.": "Zastanawiające, że żyłaś w lesie sama przez całą dekadę.",
  "Ouch.": "Auć.",
  "I’ll call you when I get home.": "Odezwę się, gdy dotrę do wieży.",
  "When I find these people I don’t know what I’m gonna do.": "Kiedy znajdę tych ludzi to nie wiem, co im zrobię.",
  "When I find these people…": "Kiedy ich znajdę...",
  "That’s probably for the best considering they can still hear us.": "To chyba najlepsze wyjście, biorąc pod uwagę, że ciągle nas słyszą.",
  "Nothing good.": "Nic dobrego.",
  "I havebeen pretty upset about things for a long time now and I haven’t really had anywhere to put that anger. And now, maybe I do.": "Od dłuższego czasu dławiło mnie uczucie złości, nie mogłam znaleźć dla niego żadnego ujścia. Teraz chyba mam rozwiązanie.",
  "Anyway, I’m sure you are too. Get the hell out of there if you’re not already and call me when you get home. I don’t know what the hell we’re going to do.": "W każdym razie, pewnie też jesteś wściekły. Więc jeśli jeszcze się stamtąd nie wyniosłeś, zrób to w tej chwili i daj mi znać, gdy dotrzesz do wieży. Nie mam pojęcia, co dalej.",
  "I guess we're not burning the place down.": "Czyli nie puszczamy tego miejsca z dymem.",
  "Ha, no, we're not.": "Nie, zdecydowanie nie.",
  "Nope. We are not.": "Nie ma mowy.",
  "Hike safely.": "Bezpiecznej drogi.",
  "Um… Delilah… there's smoke from the site. I just climbed out of there and the bridge collapsed…": "Delilah... z terenu ośrodka unoszą się kłęby dymu. Właśnie opuściłem to miejsce, a most za mną się zawalił...",
  "Report smoke": "Zgłoś dym",
  "Uh… HENRY.": "Henry.",
  "I think there is smoke coming from north of Jonesy Lake.": "Chyba widzę kłęby dymu na północ od jeziora Jonesy.",
  "That is SUSPICIOUSLY close to where you just were.": "Zadziwiająco blisko miejsca, w którym właśnie byłeś.",
  "Do you see it?": "Widzisz to?",
  "HENRY.": "Henry.",
  "It’s burning like hell over there. Tell me you did not start it.": "Ogień pochłania wszystko wokół. Powiedz, że to nie ty go wznieciłeś.",
  "Hello?": "Halo?",
  "Henry, tell me you did not start it.": "Henry, powiedz, że to nie ty.",
  "Holy shit, what if you did.": "Cholera, a co jeśli to ty?",
  "Calm down, Delilah, that's crazy. Of course he didn't do that. He wouldn't do that. WOULD HE, HENRY?": "Uspokój się, Delilah, to szalony pomysł. Jasne, że tego nie zrobił, nie byłby w stanie. Prawda, Henry?",
  "Alright, I hope you're headed home right now.": "Mam nadzieję, że zmierzasz w kierunku wieży.",
  "What the hell do I do?": "Co ja mam zrobić?",
  "Hey, shit, the bridge collapsed climbing out of here and, uh, now it looks like there's smoke coming from the site.": "Szlag, most zawalił się, gdy go przekroczyłem. Wygląda też na to, że z terenu ośrodka unoszą się kłęby dymu.",
  "Report rock bridge collapse": "Zgłoś zawalenie się mostu",
  "Jesus, okay, yeah— I see it.": "Jezu, tak... Widzę, o czym mówisz.",
  "THERE you are!": "Tu jesteś!",
  "Three hours later. Come the eff on, Henry": "Trzy godziny później. No dalej, Henry.",
  "Was it you?!": "To twoja sprawka?!",
  "NO! Of course not.": "Nie! Oczywiście, że nie.",
  "What the hell happened to “IT’S DEFINITELY NOT THE BEST IDEA?”": "A gdzie się, do diabła, podziało: „to zdecydowanie nie jest dobry pomysł”?!",
  "It wasn’t me!": "To nie ja!",
  "What do we do?": "Co robimy?",
  "We ignore it, obviously. If they come to put water on it then we know the Forest Service is connected, somehow.": "Ignorujemy, rzecz jasna. Jeśli przylecą to gasić, to znaczy, \nże Służba Leśna jest jakoś w to wszystko zamieszana.",
  "Ignore it.": "Ignorujemy.",
  "The person who did it is still out there right now, Henry.": "Ktokolwiek to zrobił, nadal jest w pobliżu, Henry.",
  "We just call it in like any other fire.": "Zgłosimy to jak każdy inny pożar.",
  "Call it in.": "Zgłaszamy.",
  "I don’t know. I have no idea what to do.": "Nie wiem, nie mam pojęcia.",
  "We have a fire burning in the woods, the one thing I know how to respond to and all of this shit has me wondering what the hell to do.": "W lesie szaleje pożar. Jesteśmy wyszkoleni, by bez zastanowienia \nzgłaszać takie sytuacje, ale przez to, co tu się wyrabia, nie wiem, \nco robić.",
  "And what about who started it? What about them?": "A ci, którzy go wzniecili? Co z nimi?",
  "The person who started it?": "Co z podpalaczami?",
  "We’re talking about people watching us out here who are now burning the forest and everything in it around us. I don’t know what to do about that.": "Mówimy o ludziach, którzy nas śledzą, podpalają las \ni są gotowi puścić z dymem wszystko, co nas otacza. \nNie mam pojęcia, co z tym zrobić.",
  "Except get the hell out.": "Oprócz ucieczki z tego miejsca.",
  "Yes. Get us the hell out of here.": "Tak. Najwyższy czas stąd spieprzać.",
  "It’d be a lot easier to work together had you gotten that radio.": "Byłoby łatwiej współpracować, gdybyś zdobył tamtą krótkofalówkę.",
  "I’m sure you can figure it out on your own.": "Z pewnością sobie poradzisz.",
  "I’ll try.": "Spróbuję.",
  "I will.": "Tak zrobimy.",
  "Do we just treat it like a normal fire?": "Traktujemy to jak zwykły pożar?",
  "It’s not a normal fire, though! But… argh, maybe it is. God.": "Ale to nie jest zwykły pożar! Choć... w sumie chyba jest. Boże.",
  "You know what? Screw it. I’m leaving it and we’ll see what happens. And I’m going to try to get us out of here by… well, I’m going to try. Over and out.": "Wiesz co? Pieprzyć to. Niech się dzieje, co chce, będziemy obserwować rozwój sytuacji. Skupię się na tym, by nas stąd wydostać... jakoś. Bez odbioru.",
  "Report Bee Sting": "Zgłoś użądlenie",
  "I got stung by a bee.": "Użądliła mnie pszczoła.",
  "Report bee sting": "Zgłoś użądlenie",
  "Okay.": "Okej...",
  "Is that it?": "To wszystko?",
  "Did it hurt?": "Bolało?",
  "Yes, kind of.": "Trochę.",
  "I’m sorry.": "Przykro mi."
}