{
  "Fenced Area": "Ogrodzony teren",
  "Henry": "Henry",
  "Alright, I’m here.": "Dobra, jestem na miejscu.",
  "I'm here.": "Dotarłem.",
  "It looks like goddamn Area 51.": "To wygląda jak pieprzona Strefa 51.",
  "This place is crazy.": "To czyste szaleństwo.",
  "Delilah": "Delilah",
  "Maybe they’ve got aliens. That’d be exciting.": "Może trzymają tam kosmitów. To byłoby ekscytujące.",
  "We’ll see about that.": "Przekonamy się.",
  "Whoa, Delilah— there's a big chain-link fence between me and the meadow. I don't think I can get past it.": "Delilah, trafiłem na wysokie ogrodzenie z metalowej siatki, oddzielające mnie od polany. To chyba koniec drogi.",
  "Report fence": "Zgłoś ogrodzenie",
  "Okay, I'm at the fence. I don't see anyone around but I'm not sure I can get past it.": "Dobra, jestem przy ogrodzeniu. Nikogo nie widzę, ale nie wiem, \nczy uda mi się przejść.",
  "How big is it?": "Jak wysokie?",
  "Uh, a fence?": "Ogrodzenie?",
  "Yeah.": "Tak.",
  "How big?": "Jak wysokie?",
  "Big. It goes off in both directions. Acres.": "Bardzo. Ciągnie się w obie strony na kilometry.",
  "What the fuck is going on out here?!": "Co tu się, kurwa, dzieje?!",
  "Whatever it is someone doesn't want anyone to know about it.": "Cokolwiek jest grane, komuś zależy, by utrzymać to w tajemnicy.",
  "Sometimes biologists will cordon off a little area to study flora or whatever, but that's only a few square feet, usually.": "Czasem biolodzy oddzielają mały obszar, żeby badać tamtejszą florę, ale to zwykle tylko kilka metrów kwadratowych.",
  "That's not what this is.": "To jest większe.",
  "Well, see what you can do to get past it.": "Sprawdź, czy uda ci się przedostać na drugą stronę.",
  "Yeah, I've tried to get in here before. No dice.": "Próbowałem już wcześniej, bez powodzenia.",
  "Report gate": "Zgłoś bramę",
  "And the gate is locked up, obviously.": "Brama jest oczywiście zamknięta.",
  "Obviously.": "Oczywiście.",
  "I’ll see if I can break in somehow.": "Sprawdzę, czy uda mi się włamać.",
  "Alright, be careful.": "Dobra, bądź ostrożny.",
  "…and what are the odds they left the gate unlocked?": "Jakie są szanse, że zostawili bramę otwartą?",
  "All part of their mind games, Delilah.": "To wszystko część ich gierek, Delilah.",
  "Pretty low, I’d imagine.": "Raczej niewielkie.",
  "It looks like they call this place Wapiti Station.": "Wygląda na to, że nazywają to miejsce Stacją Wapiti.",
  "Report information box": "Zgłoś skrzynkę informacyjną",
  "I’ve never heard that name before.  Wapiti means elk, though.": "Nigdy nie słyszałam tej nazwy. Ale wapiti to gatunek jelenia.",
  "There’s a notice out here to hikers saying stay away.  Apparently someone named Dr. Simmons is in charge.": "Jest tutaj uwaga dla turystów, żeby trzymali się z daleka. Najwyraźniej jakiś dr Simmons zarządza tym miejscem.",
  "Should you have? Is any of this strange to you?": "A powinnaś o niej słyszeć? Czy coś z tego brzmi znajomo?",
  "I don’t know. All I know is these pasty dorks have been out here for years and sometimes their supplies get mixed in with ours. That’s it.": "Nie mam pojęcia. Wiem tylko, że ci jajogłowi zjeżdżają tutaj od paru lat i czasem ich zapasy mieszają się z naszymi. To wszystko.",
  "Bee Sting": "Użądlenie",
  "I got stung by a bee.": "Użądliła mnie pszczoła.",
  "Report bee sting": "Zgłoś użądlenie",
  "Okay.": "Okej...",
  "Is that it?": "To wszystko?",
  "Did it hurt?": "Bolało?",
  "Yes, kind of.": "Trochę.",
  "I’m sorry.": "Przykro mi.",
  "Can't get in": "Nie wejdę tam",
  "Alright, I’ve beat the hell out of this gate latch, tried to pry it open and nada, I can’t get in.": "Dobra, spuściłem jej łomot, próbowałem wyważyć i dalej nic, brama ani drgnie.",
  "I can't get in.": "Nie mogę się dostać.",
  "Okay. I've given it the good college try and no dice.": "Dobra. Spróbowałem wszystkiego, to na nic.",
  "Look, I’m not going to be able to get into this place.": "Nie uda mi się tam dostać.",
  "Shit.": "Cholera.",
  "I don’t know how long I can dick around out here until someone notices.": "Nie wiem, jak długo mogę się tutaj wałęsać, zanim ktoś mnie zauważy.",
  "God, if you were an actual firefighter you’d have that gate down in two shakes.": "Boże, gdybyś był strażakiem, po tej bramie już dawno nie byłoby śladu.",
  "Hey, actually— those guys doing the controlled burn. They might be able to help.": "Tak właściwie... Może ci goście, którzy przeprowadzają kontrolowane pożary mogliby nam pomóc.",
  "Where are they?": "Gdzie ich znajdę?",
  "Beyond Ruby River — there's a scout camp.  They burned a line a few days ago that should let you hike right to them.": "Za rzeką Ruby. Jest tam obozowisko skautów. Kilka dni temu wypalili obszar, którym powinieneś dotrzeć wprost do nich.",
  "Well, that's great.": "Świetna wiadomość.",
  "If they haven't left they're probably the type of guys who would help you get through that fence.": "Jeśli jeszcze nie wyjechali, najprawdopodobniej pomogą ci przedostać się przez to ogrodzenie."
}