{
  "Henry": "Henry",
  "Do people lose their shit doing this job? There's a note that says a guy just left his post.": "Czy ludziom tu odbija? Znalazłem notatkę o tym, że jakiś gość po prostu opuścił wieżę.",
  "Do people lose their shit out here?": "Czy ludziom tu odbija?",
  "Delilah": "Delilah",
  "It happens, yeah.": "Tak, zdarza się.",
  "You're not going to pop your top, are you Henry?": "Ale tobie nie odbije, prawda, Henry?",
  "I wasn't planning on it.": "Nie planuję takiego scenariusza.",
  "Hmm.": "Hm...",
  "That's probably Dave Gaskill. He's completely nuts.": "To najprawdopodobniej Dave Gaskill. Kompletny świr.",
  "Is that right?": "Naprawdę?",
  "Harmless, but yeah— one of those fall-off-the-grid and eat ants for a week type. Totally fucking cuckoo.": "Nieszkodliwy, ale tak... Jeden z tych, którzy odcinają się od świata i jedzą przez tydzień mrówki. Prawdziwy szajbus.",
  "Which is kinda what the job attracts.": "W sumie ta robota przyciąga takich ludzi.",
  "Hey, I found a note to a guy named Ron from some guy, Dave.": "Znalazłem notkę do kolesia o imieniu Ron od jakiegoś Dave'a.",
  "I found a note between a couple guys.": "Znalazłem liścik od jednego gościa do drugiego.",
  "Who are these guys, Ron and Dave? They're leaving notes for each other in the boxes.": "Co to za ludzie, Ron i Dave? Zostawiają dla siebie listy \nw skrzynkach.",
  "Report note between Ron and Dave": "Zgłoś liścik Rona i Dave'a",
  "Is there any chance one of them was that guy I saw in the canyon? You know, the guy with the flashlight?": "Czy jest możliwe, że któryś z nich to ten koleś, którego widziałem \nw kanionie? Wiesz, ten z latarką?",
  "Is there any chance they had anything to do with to those girls disappearing?": "Czy to możliwe, że mieli coś wspólnego z zaginięciem tych dziewczyn?",
  "No, they're both rangers. They're not out here this season. I didn't really know them that well, but I always assumed the only thing Ron cared about was chasing tail and getting loaded.": "Nie, to leśniczowie. Nie ma ich tu w tym sezonie. Nie poznałam ich za dobrze, ale zawsze sądziłam, że Ron przejmuje się tylko wyrywaniem lasek i nawalaniem się.",
  "It's somehow comforting to know he was able to keep up a correspondence with someone who wasn't going to send him a topless Polaroid.": "To dość pocieszające, że korespondował z kimś, kto nie wysłał mu rozbieranych zdjęć.",
  "Do you think they have anything to do with what's happening? Would they know anything, at least?": "Myślisz, że mają coś wspólnego z tym, co się tu dzieje? Albo że cokolwiek wiedzą?",
  "They were both rangers but they're not out here this season. So, no I don't think so… but, I mean, I probably shouldn't claim to know anything given the circumstances.": "Byli leśniczymi, ale nie ma ich tu w tym sezonie. Więc raczej nie... ale może nie powinnam twierdzić, że cokolwiek wiem, zważywszy na okoliczności.",
  "Well, maybe they're not out here \"officially.\"": "Może nie ma ich tutaj tylko „oficjalnie”.",
  "I heard Ron moved and Dave quit last winter. But maybe we should keep an eye out for other notes.": "Słyszałam, że Ron się przeprowadził, a Dave zrezygnował zeszłej zimy. Ale może powinniśmy szukać innych notek.",
  "Report \"Boss Tracks\"": "Zgłoś kasetę „Boss Tracks”",
  "Hey, remember those guys Ron & Dave?": "Pamiętasz Rona i Dave'a?",
  "Yeah? What do they have to do with anything?": "Tak. Ale co oni mają z tym wspólnego?",
  "So, I've found notes between these two rangers Ron & Dave. You know them?": "Znalazłem liściki, jakie pisali do siebie Ron i Dave. Znasz ich?",
  "Yeah. What do they have to do with anything?": "Tak. Ale co oni mają z tym wspólnego?",
  "Nothing, I don't think. I just found a cassette tape one of them left for the other.": "Chyba nic. Po prostu znalazłem kasetę, którą jeden z nich zostawił drugiemu.",
  "…Do you think it could be anything like the tape you have of us?": "Myślisz, że może być na niej coś takiego jak na tej naszej?",
  "No it's definitely not. It's just music, don't worry.": "Nie, na pewno nie. To tylko muzyka, nie przejmuj się.",
  "I think it's just music.": "To raczej tylko muzyka.",
  "Well if it's the new Milli Vanilli it could be just as incriminating.": "Jeśli to nowy album Milli Vanilli, to nie ma większej różnicy.",
  "Do you know whatever happened to Dave, the ranger?": "Wiesz, co się stało z Dave'em, tym leśniczym?",
  "Do you know what happened to Dave?": "Wiesz, co się stało z Dave'em?",
  "No. Why?": "Nie. Dlaczego?",
  "I was just wondering about him and the other guy, Ron.": "Myślałem po prostu o nim i tym drugim kolesiu, Ronie.",
  "Last I heard Ron was in Alaska. His ex-girlfriend Debbie is the one who works the Forest Service desk in Cody.": "Słyszałam, że Ron jest na Alasce. Jego była dziewczyna, Debbie, pracuje dla Służby Leśnej w Cody.",
  "Dave got beat up pretty bad in a bar fight last year.": "Dave został pobity w barze w zeszłym roku.",
  "Huh, I never heard about that. I've heard people give him a hard time because he, uh… isn't exactly a lady's man.": "Nigdy o tym nie słyszałam. Ale ponoć ludzie nie są dla niego mili, bo Dave... chyba nie do końca lubi kobiety.",
  "Oh.": "Och.",
  "Oh. I see.": "Rozumiem...",
  "Yeah. People are shitty.": "No. Ludzie są okropni.",
  "That's fucked up.": "To popierdolone.",
  "That's just bullshit.": "To chore.",
  "I agree. People are shitty.": "Zgadzam się. Ludzie są okropni.",
  "I don't want to gossip.": "Nie chcę plotkować.",
  "I don't want to gossip about the guy.": "Nie chcę o nim plotkować.",
  "Well that would make you unique among Forest Service personnel.": "To czyni cię wyjątkowym pracownikiem Służby Leśnej."
}