{
  "Henry": "Henry",
  "The bridge out to the camp is out.": "Most prowadzący do obozu jest zawalony.",
  "Report collapsed bridge": "Zgłoś zawalony most",
  "Delilah": "Delilah",
  "Damn.": "Cholera.",
  "I'm going to walk the ravine and see if I can find some high-ground to get across.": "Przejdę się krawędzią zbocza i rozejrzę za wystarczająco bezpiecznym zejściem.",
  "Good plan.": "Dobry plan.",
  "I'm still looking for a way across the ravine.": "Dalej szukam drogi przez jar.",
  "I'm still looking for a way across.": "Dalej szukam jakiegoś zejścia.",
  "Well, there must be one. I mean, the firefighters made it from the camp to Ruby River.": "Na pewno coś znajdziesz. W końcu strażacy przedostali się z obozu do rzeki Ruby.",
  "Scout Camp": "Obóz skautów",
  "About the Scouts": "Co do skautów",
  "Hey, I wandered into an old scout camp. I'm going to look around here first, okay?": "Dotarłem do starego obozowiska skautów. Porozglądam się tutaj trochę, dobrze?",
  "Alright. That's the operating area of the Hot-Shot crew who were doing the controlled burn.  Keep me in the loop, okay?": "W porządku. To strefa operacyjna strażaków przeprowadzających kontrolowane wypalania. Informuj mnie na bieżąco.",
  "Sure thing.": "Jasne.",
  "I'm at the camp.": "Jestem w obozie.",
  "Report scout camp": "Zgłoś obóz skautów",
  "Great. Have a look around. If anyone is still there they might be able to help.": "Świetnie. Rozejrzyj się. Jeśli kogoś spotkasz, być może będzie w stanie pomóc.",
  "I'm going to sound crazy.": "Zabrzmię jak szaleniec.",
  "Maybe you just ask them to help you get inside the fence. If I didn't know it was out there, they probably don't either.": "Po prostu poproś o pomoc w sforsowaniu ogrodzenia. Skoro ja nie wiedziałam, co tam jest, oni pewnie też nie wiedzą.",
  "This place looks dead but I'll see what I can find.": "Teren wygląda na opustoszały, ale rozejrzę się tu.",
  "You ever talk to a scout?": "Gadasz czasem ze skautami?",
  "Camp Arapahoe.": "Obóz Arapahoe.",
  "Report camp sign": "Zgłoś wejście do obozu",
  "You're there?": "Dotarłeś tam?",
  "Yeah, I am.": "Tak.",
  "It's been out there since the fifties.": "Znajduje się tu od lat pięćdziesiątych.",
  "I was never into the idea of the scouts.": "Nigdy nie rozumiałem idei skautów.",
  "Something about men organizing boys around their ideals has never sat well with me.": "Faceci zmuszający małych chłopców, by żyli pod ich dyktando, \nnie kupuję tego.",
  "Beware Webelos in large numbers.": "Bój się dużej liczby ćwików.",
  "Beware of anyone in large numbers.": "Bój się dużej liczby czegokolwiek.",
  "I guess these little shelters are where they keep the Webelos.": "Ćwikowie zapewne mieszkali w tych małych domkach.",
  "Report old shelters": "Zgłoś stare domki",
  "For the past thirty five years, yep.": "Przez ostatnie trzydzieści pięć lat, tak.",
  "Firefighters are gone": "Strażacy odeszli",
  "Yeah, these guys are gone. I found where they were sitting around before getting picked up.": "Po strażakach nie ma już śladu. Znalazłem miejscówkę, gdzie spędzali czas, czekając na transport.",
  "Report missing firefighters": "Zgłoś brak strażaków",
  "There are bear traps out here. In the scout shelters.": "Znalazłem pułapki na niedźwiedzie. W domkach skautów.",
  "Report bear trap": "Zgłoś pułapkę",
  "Scouts are stalwart prey.": "Skauci to łatwy łup.",
  "That’s messed up.": "To chore.",
  "I found an axe.": "Znalazłem siekierę.",
  "Report axe": "Zgłoś siekierę",
  "If one of the crew left it that thing is actually called a pulaski.": "Jeśli ktoś ze strażaków ją zostawił, to jest to siekiera Pułaskiego.",
  "It looks like an axe to me. This thing will be a huge help.": "Wygląda jak zwykła siekiera. Grunt, że będzie pomocna.",
  "For both getting through the backcountry AND getting through that fence.": "Zarówno w przedzieraniu się przez chaszcze, jak i przedostaniu się przez ogrodzenie.",
  "Yeah. I'm outta here.": "Tak. Spadam stąd.",
  "I found a little trowel. Maybe I should take it with me; I could use it to pop open beers.": "Znalazłem małą łopatkę. Może wezmę ją ze sobą, przyda się \ndo otwierania piw.",
  "Report trowel": "Zgłoś łopatkę",
  "Ninety nine percent sure that’s for burying poop.": "Na dziewięćdziesiąt dziewięć procent służy do zakopywania kup.",
  "I’ll just leave it here.": "No to zostawię ją tutaj.",
  "And I already touched it.": "A ja już jej dotknąłem.",
  "And I’m holding it.": "A ja ją trzymam.",
  "Well.": "Cóż.",
  "Maybe drop it?": "Może ją upuść?",
  "I’m still holding it; why am I still holding it?": "Dalej ją trzymam. Dlaczego dalej ją trzymam?",
  "Now that’s a real mystery.": "To ci dopiero tajemnica.",
  "Nothing Here": "Nic tu nie ma",
  "This place is a bust, D.  There’s no one here and the fire crew didn’t leave much.": "To miejsce jest bezużyteczne, D. Nikogo tutaj nie ma, a strażacy prawie nic nie zostawili.",
  "I can't find anything.": "Nic nie mogę znaleźć.",
  "Dammit.": "Cholera.",
  "What do you think?": "Co myślisz?",
  "Just give it a once over and then we'll reassess, okay?": "Rozejrzyj się raz jeszcze, a potem pomyślimy, co dalej, dobrze?",
  "Will do.": "Zrobi się.",
  "Leaving Camp": "Opuszczam obóz",
  "I’m getting out of here.": "Wynoszę się stąd.",
  "I'm getting out of here.": "Wynoszę się stąd.",
  "Great. Maybe think about looping back; if folks are following you, you might as well try to lose them.": "Świetnie. Rozważ zatarcie śladów. Jeśli ktoś cię śledzi, możesz chociaż spróbować ich zgubić.",
  "Hey, D, they left something behind. It's like a memo from their boss.": "Hej, D, coś tutaj zostawili. To wygląda jak notatka od ich szefa.",
  "Report memo": "Zgłoś notatkę",
  "It say anything of note?": "Jest na niej coś ważnego?",
  "Hmm.": "Hm...",
  "Next few days… dropping into the Thorofare… on behalf of Dr. Simmons at— Wapiti Station.": "W ciągu najbliższych dni... wysłany w Region Główny... w imieniu \ndr. Simmonsa ze... Stacji Wapiti.",
  "Wapiti Station.": "Stacji Wapiti.",
  "Holy crap.": "Jasny gwint.",
  "Keep reading!": "Czytaj dalej!",
  "Oh, I just thought I would maybe stop there. Let the mystery percolate.": "Pomyślałem, że przestanę. Stworzę atmosferę tajemnicy.",
  "My mother always said I would meet someone who'd give me a taste of my own medicine.": "Moja matka zawsze powtarzała, że w końcu spotkam kogoś, \nkto odpłaci mi pięknym za nadobne.",
  "They're running a research site out there.  He was worried about wildfires.": "Prowadzą tutaj ośrodek badawczy. Bał się, że wypalanie może wymknąć się spod kontroli.",
  "Someone is writing down our conversations. And now we find out there's a research site out here that we don't know about? What are they researching?…": "Ktoś zapisuje nasze rozmowy. A teraz dowiadujemy się o ośrodku badawczym, o którym nie mieliśmy pojęcia? Co mogą tam badać?",
  "I mean, you and I aren't very interesting.": "Znaczy się, nasza dwójka nie jest wielce interesująca.",
  "Well, you're not. I'm infinitely complex.": "W sumie to ty. Ja mam bardzo złożoną osobowość.",
  "But why record us?": "Ale po co nas nagrywać?",
  "How could they let them do that? Study people who sign up to watch fires?  How?": "Jak mogli im na to pozwolić? Badać ludzi, którzy chronią lasy przed pożarami? Jak?",
  "Us.  They're researching us.": "Nas. Badają nas.",
  "Us.": "Nas.",
  "You think they're studying you and me.": "Myślisz, że badają ciebie i mnie.",
  "I do, yeah. Maybe it's about studying two strangers who talk every day.": "Tak. Może to badania nad dwójką nieznajomych, którzy codziennie ze sobą rozmawiają.",
  "Like, if you put someone in isolation with someone else, what they do.": "Sprawdzają, co się stanie, kiedy umieścisz dwie osoby \nw odosobnieniu.",
  "Yeah. That's what I think.": "Dokładnie. Tak właśnie myślę.",
  "Well fuck THAT.": "Niech to chuj.",
  "Agreed.": "Zgadzam się.",
  "I think they are studying me.": "Myślę, że badają mnie.",
  "Me.": "Mnie.",
  "Because of what happened to you before? Everything with Julia?": "Z powodu tego, co spotkało cię wcześniej? Z Julią?",
  "Yeah. Maybe they're studying the effects of something like that. Grief… Grief when you have no other choice but to be alone with your thoughts.": "Tak. Może badają skutki czegoś takiego. Żalu... W sytuacji, gdy nie masz innego wyjścia niż przebywanie sam na sam ze swoimi myślami.",
  "So they set up an entire site just for you?": "Więc założyli cały ośrodek badawczy tylko dla ciebie?",
  "Maybe.": "Może.",
  "Oof.": "Ech...",
  "Why? What makes you so special?": "Dlaczego? Co czyni cię tak specjalnym?",
  "I… nothing. I'm normal. I just wonder if it's about me.": "Nic. Jestem przeciętniakiem. Zastanawiam się po prostu, czy chodzi o mnie.",
  "Because something happened to you before you came out here.": "Bo coś ci się przydarzyło, zanim tutaj trafiłeś.",
  "Nothing crazy, I didn't do anything. I'm normal. I… I just wonder if it is all about me.": "Nic niesamowitego. Jestem przeciętniakiem. Po prostu... zastanawiam się, czy może chodzić o mnie.",
  "So maybe they just picked you at random? You're the guinea pig?": "Może po prostu cię wylosowali? Jesteś królikiem doświadczalnym?",
  "Oh, you know, probably just horned toads.": "No wiesz, pewnie rogate jaszczurki.",
  "Horned toads.": "Rogate jaszczurki.",
  "Maybe Turt was an escapee.": "Może Żółwino jest zbiegiem.",
  "Maybe Shelly was an escapee.": "Może Scorupco jest zbiegiem.",
  "Maybe your turtle was an escapee.": "Może twój żółw jest zbiegiem.",
  "And a Wapiti Station clipboard with our conversations on it is just, what, recreation for them?": "A notatnik ze Stacji Wapiti z zapisem naszych rozmów to po prostu ich rozrywka?",
  "I'm just messing around. Somebody is obviously up to something.": "Po prostu się wydurniam. Ktoś tutaj coś knuje, bez dwóch zdań.",
  "I'm freaking out here.": "Ja tu wariuję.",
  "At least we know there is something real happening behind that fence.": "Przynajmniej wiemy, że za tym ogrodzeniem naprawdę coś się dzieje.",
  "I think that we should consider that— maybe— this is all just a coincidence, but my gut says there is something bad going on.": "Myślę, że powinniśmy rozważyć, że może... to wszystko jest tylko zbiegiem okoliczności, choć intuicja podpowiada mi coś zgoła innego.",
  "Mine too.": "Mnie też.",
  "I think we should allow for the possibility that this is all just a big misunderstanding but… if you saw what you said you did… Fuck, Henry.": "Powinniśmy rozważyć możliwość, że to wszystko jest jednym wielkim nieporozumieniem, ale jeśli widziałeś to, co widziałeś... Kurwa, Henry.",
  "Yeah, I saw it.": "Tak, widziałem.",
  "Okay. So, what's next?": "Dobra. To co teraz?",
  "I've got an axe so I can figure out a way to get over the ravine and back towards the site.": "Jestem uzbrojony w siekierę, więc mogę przeprawić się przez jar \ni udać w kierunku ośrodka.",
  "I'm going to do a scan for supplies and then figure out a way to get back over that ravine and hike towards the site.": "Poszukam jakichś zapasów, znajdę sposób, by przeprawić się przez jar i udam się w kierunku ośrodka.",
  "Sounds good. Check in when you can.  And keep an eye out for anyone following you.": "Brzmi dobrze. Zgłaszaj się przy każdej możliwej okazji. \nI pilnuj, czy ktoś cię nie śledzi.",
  "But why write down our conversations.": "Ale po co spisywać nasze rozmowy?",
  "I think we should allow for the possibility that this is all just a big misunderstanding but… if you saw what you said you did… fuck Henry.": "Powinniśmy rozważyć możliwość, że to wszystko jest jednym wielkim nieporozumieniem, ale jeśli widziałeś to, co widziałeś... Kurwa, Henry."
}