{
  "Henry": "Henry",
  "Hey, I'm really lost. I'm back at the rock slide. I don't know how to get back.": "Kompletnie się zgubiłem. Wróciłem do osuwiska, nie wiem, którędy wrócić.",
  "Delilah": "Delilah",
  "I'm sure you can get back through the canyon. Go back to the lake and then turn north.": "Jestem pewna, że droga powrotna prowadzi przez kanion. Zawróć nad jezioro i skręć na północ.",
  "You're not lost. Those fireworks are going off to the west of you. It's down the slide and across the meadow. Okay?": "To dobra trasa. Fajerwerki puszczają na zachód od ciebie. \nZejdź po osuwisku i przepraw się przez polanę, dobrze?",
  "Hey, I'm going the right way if I'm at the shale slide, right? Toward the fireworks?": "Skoro jestem nad osuwiskiem to zmierzam w dobrą stronę, tak? \nW kierunku fajerwerków?",
  "Am I headed the right direction?": "Zmierzam w dobrym kierunku?",
  "I think I might be lost.  I'm still at the shale slide.": "Chyba się zgubiłem. Wciąż jestem przy osuwisku.",
  "I think I'm lost.": "Chyba się zgubiłem.",
  "Yes. Just head down and keep going west.": "Tak. Udaj się na dół i kontynuuj drogą na zachód.",
  "Hey, it looks like there's some climbing equipment to help me get down the incline here, but there's no rope.": "Widzę tu jakiś sprzęt wspinaczkowy, dzięki któremu zejdę po zboczu, ale brakuje mi liny.",
  "Report climbing gear": "Zgłoś sprzęt wspinaczkowy",
  "Right. There should be a rope back in the supply box to the east.  It's between where you are right now and your lookout.": "No tak. Linę powinieneś znaleźć w skrzynce na wschód stąd. Znajduje się pomiędzy twoją aktualną lokacją a wieżą.",
  "Oh, right—1-2-3-4.": "Racja... 1-2-3-4.",
  "Right, 1-2-3-4.": "Racja, 1-2-3-4.",
  "Yep, the really secure one.": "Tak, ten bardzo bezpieczny.",
  "Yep, that is the super-smart code.": "Tak, ten bardzo sprytny.",
  "Convenient as ever.": "Wygodny jak zawsze.",
  "This shale slide is steep. How do you expect me to get down this?": "To kamienne osuwisko jest bardzo strome. Jak mam z niego zejść?",
  "Report shale slide": "Zgłoś kamienne osuwisko",
  "I don't remember it being that bad. It's not even named on our topos.": "Nie kojarzę, by było takie kłopotliwe. Brak mu nawet nazwy \nna naszych mapach.",
  "What about “Shitty Boss Is Going to Get Me Killed Hill”": "Co powiesz na: „Wzgórze walniętej szefowej, \nktóra wpędzi mnie do grobu”?",
  "What about \"Shitty Boss Is Going to Get Me Killed Hill?\"": "Co powiesz na: „Wzgórze walniętej szefowej, która wpędzi mnie do grobu”?",
  "Yeah, well I'd go with “Widowmaker.”": "Ja bym je nazwał „Wdowiarka”.",
  "I'd go with \"Widowmaker.\"": "Proponuję: „Wdowiarka”.",
  "It should be called “Cripple Gulch,” just east of “Gonna Pee in a Bag Forever Flats.”": "Powinno nosić nazwę „Wąwozu Inwalidów”, tuż na wschód \nod „Zaraz narobię w gacie”.",
  "Maybe call it \"Cripple Gulch.\"": "Może nazwij je „Wąwozem Inwalidów”?",
  "Oh, is that Absaroka Indian? Maybe Creek?": "Czy to w języku plemienia Wron? A może Krików?",
  "It's actually English for “not in my job description.”": "To angielskie wyrażenie na: „wykracza poza zakres moich obowiązków”.",
  "Come on. It's really not that bad.": "Daj spokój. Dasz sobie radę.",
  "It's a fifty-foot cliff made of rocks that look like knives!": "To 15-metrowa skarpa pełna ostrych ostrych jak nóż kamieni!",
  "They just look like knives, okay? Plus, there's already a Widowmaker on the backside of Carter Mountain. It would be confusing.": "Sprawiają tylko takie wrażenie, jasne? Poza tym Wdowiarką nazwano jedną ze skarp na górze Cartera. To byłoby mylące.",
  "How do you expect me to get down this?": "Jak niby mam stąd zejść?",
  "How do I get down?": "Jak mam stąd zejść?",
  "Well, did you get that rope?": "A udałeś się po linę, jak prosiłam?",
  "Yeah, I got it.": "Tak, mam ją.",
  "Okay. Just lash it to something nearby and take it slow.": "Świetnie. Zaczep ją o coś w pobliżu i powoli się opuść.",
  "No, I didn't.": "Nie.",
  "Well, go back and get it. If you break your leg on your first day I will not be pleased.": "W takim razie wróć po nią. Jeśli złamiesz nogę pierwszego dnia pracy to się wkurzę.",
  "So this guy in Medicine Bow Lookout dropped his radio in the shitter.": "W każdym razie, facet z Wieży Cheyenne upuścił swoją krótkofalówkę w kiblu.",
  "And I've spent the past twenty minutes making spooky voices from inside his outhouse while he digs around for it.": "A ja spędziłam ostatnie 20 minut, wydając upiorne odgłosy z wnętrza jego wychodka. Biedak szukał wszędzie wokół.",
  "Well, this is what passes for entertainment around here. Anyway, hope the hike is going well.": "To właśnie jest uważane tu za rozrywkę. Tak czy inaczej, mam nadzieję, że przyjemnie ci się spaceruje.",
  "Ugh, hey.": "Hej...",
  "Oww.": "Auć.",
  "What the hell's wrong with you?": "A tobie co dolega, do diabła?",
  "Cripple Gulch got me.": "Wąwóz Inwalidów mnie dojechał.",
  "Widowmaker got the best of me.": "Wdowiarka zebrała swoje żniwo.",
  "My rope snapped coming down the shale slide.": "Lina się zerwała, gdy schodziłem po zboczu.",
  "My shitty boss almost got me killed.": "Walnięta szefowa prawie wpędziła mnie do grobu.",
  "First, your boss is a delight. Secondly,  Jesus!": "Po pierwsze, twoja szefowa to cud-kobieta. Po drugie, Jezu!",
  "What exactly happened?": "Co się dokładnie stało?",
  "Think you'll have to pee in a bag for the rest of your life?": "Jak myślisz, będziesz teraz robił pod siebie przez resztę życia?",
  "You didn't break anything, did you?": "Ale nic sobie nie złamałeś?",
  "No, I think I'll make it.": "Nie, chyba się wyliżę.",
  "Well be careful for chrissake.": "Bądź ostrożniejszy, na litość boską.",
  "Hey, I had an accident.": "Hej, miałem wypadek.",
  "Report fall": "Zgłoś upadek",
  "I'm lost.": "Zgubiłem się.",
  "Okay, uh—I'd head back to the lake and then turn north. There's a canyon there you can take back.": "Na twoim miejscu zawróciłabym nad jezioro i obrała drogę na północ. Trafisz na wąwóz, którym wrócisz do wieży.",
  "With this rope snapped I don't know how to get home.": "Przez tę urwaną linę nie wiem, jak się dostać do domu.",
  "How do I get back up the shale slide?": "Jak mam się wspiąć w górę osuwiska?",
  "You'll have to find another way but that shouldn't be too hard.": "Musisz znaleźć inną drogę, ale to nie powinno stanowić problemu.",
  "If you head back to the lake I think you can find a path through the canyon to the north.": "Jeśli wrócisz do jeziora, powinieneś odnaleźć tam ścieżkę prowadzącą na północ, przez kanion.",
  "Alright. Thanks.": "W porządku. Dzięki.",
  "You betcha. Over and out.": "Nie ma problemu. Bez odbioru.",
  "I'd keep heading towards the lake, deal with these idiots, and then keep your eyes out for a path.": "Udałabym się w stronę jeziora, zajęła tymi idiotami, a następnie poszukała jakiejś ścieżki.",
  "This vista is incredible.": "Ten widok jest obłędny.",
  "There really is a whole lot of nothing out here, huh?": "Naprawdę wylądowałem na kompletnym zadupiu, co?",
  "Well, nothing civilized, no. It's a good thing, Henry. You'll like it.": "Jesteś daleko od cywilizacji, fakt. Ale spodoba ci się tu, Henry, zobaczysz.",
  "Which one?": "Który?",
  "Um, down the hill from my tower. There's a canyon and then the rest of, well, everything.": "Ze wzgórza niedaleko mojej wieży. Jest tu kanion rozpościerający się na... no, wszystko.",
  "You should see what I'm looking at. An eagle has been hovering over this gorge for the past hour. Maybe if you're good you can come by and see it at the end of the summer.": "Żałuj, nie widzisz tego, co ja. Orzeł krążył nad tym wąwozem już \nod przeszło godziny. Jeśli się spiszesz, może pozwolę ci zobaczyć \nto na własne oczy pod koniec lata.",
  "Report Climbing Accident": "Zgłoś upadek",
  "No, no, noooo!": "Nie, tylko nie to!"
}