{
  "Henry": "Henry",
  "There’s some old snowmobiles out here.": "Znalazłem tu parę skuterów śnieżnych.",
  "Report wrecked snowmobile": "Zgłoś uszkodzony skuter śnieżny",
  "Delilah": "Delilah",
  "That's crazy.": "To jakiś absurd.",
  "It looks like one of the poor bastards was cruising across old Pork Pond and dumped it.": "Wygląda na to, że jakieś skurczybyki przeprawiły się przez Świński Staw i je tu porzuciły.",
  "It looks like one of the poor bastards was cruising across this pond and dumped it.": "Wygląda na to, że jakieś skurczybyki przeprawiły się przez staw i je tu porzuciły.",
  "That was not a fun hike back to civilization.": "To nie było udane zderzenie z cywilizacją.",
  "So is the scout camp anywhere near Pork Pond?": "Czyli obóz skautów znajduje się gdzieś w okolicy Świńskiego Stawu?",
  "Is the scout camp near Pork Pond?": "Obóz skautów jest niedaleko Świńskiego Stawu?",
  "Yeah, it is. Just keep heading east. You'll cross a small ravine and you shouldn't be able to miss it.": "Dokładnie. Kieruj się dalej na wschód, aż trafisz na wąwóz. \nNie sposób tego przegapić.",
  "There's an old pond out here, not much more than a pile of mud. Do you have it on your map?": "Trafiłem na zmurszały staw, właściwie bardziej przypomina błotną kałużę. Jest na twojej mapie?",
  "Report pond": "Zgłoś staw",
  "Ah, I know where you are.": "Tak, wiem dokładnie, gdzie jesteś.",
  "Yeah, where am I?": "I gdzie to jest?",
  "Pork Pond. There used to be a sign up for it but folks kept stealing it.": "Przy Świńskim Stawie. Kiedyś informował o tym znak, ale ludzie wciąż go kradli.",
  "Because it's called Pork Pond?": "Bo widniała na nim nazwa Świński Staw?",
  "Because it's called \"Pork Pond\"?": "Bo widniała na nim nazwa „Świński Staw”?",
  "It's a good goddamn name. The sign would look in great in a den. Or, you know, anywhere.": "To cholernie dobra nazwa. Ten znak idealnie wpasowałby się \nw wystrój jakiejś meliny. Czy gdzieś...",
  "Whoa, someone stripped these snowmobiles down to the bone.": "Ktoś orżnął te skutery śnieżne do ostatniej śrubki.",
  "Report missing engine parts": "Zgłoś zrabowane części silnika",
  "Hey, I found a pair of old totaled snowmobiles out here. It looks like someone stripped them of a bunch of parts.": "Natrafiłem na dwa wysłużone skutery śnieżne. Wygląda na to, że ktoś użyczył sobie z nich kilku części.",
  "Huh.": "Hm...",
  "That’s weird, right?": "Dziwna sprawa, nie?",
  "I mean, I can come up with a bunch of not-weird reasons someone would do that out here, but given what’s happened, yeah that’s weird.": "Pewnie znalazłabym mnóstwo rozsądnych teorii na wyjaśnienie tego, ale zważywszy na okoliczności... Tak, to dość dziwne."
}