{
  "Delilah": "Delilah",
  "I think I'm going to be sick.": "Chyba się pochoruję.",
  "And no, it's not because I'm hungover.": "I kac nie ma z tym nic wspólnego.",
  "Henry": "Henry",
  "So your little bender isn't looking like such a good idea under the light of a new day, huh?": "Gdy wstaje nowy dzień, nocna popijawa nagle okazuje się być \nnie najlepszym pomysłem, co?",
  "Hungover?": "Kac?",
  "No, it isn't, but that's not it.": "Owszem, ale to inna kwestia.",
  "It's going to be okay. We haven't done anything wrong.": "Wszystko będzie dobrze. W niczym nie zawiniliśmy.",
  "It's going to be okay.": "Wszystko będzie dobrze.",
  "What's wrong?": "Co się stało?",
  "Someone claiming to be \"Henry in Two Forks\" called a lookout in another sector early this morning and said that I knew what caused the Wapiti Meadow fire.": "Dzisiaj o brzasku ktoś podający się za „Henry'ego z Rozdroży” skontaktował się z wieżą obserwacyjną w innym sektorze, twierdząc, że znam przyczynę pożaru Polany Wapiti.",
  "Uh…": "Eee...",
  "So, I just got off the horn with that lookout who's wondering what I know. Or that I'm an arsonist. Or that I'm fucking losing it.": "Właśnie skończyłam gadać z tamtejszym obserwatorem. Zastanawia się, co wiem i czy to ja jestem podpalaczką. Albo czy ześwirowałam do reszty.",
  "Furthermore, I bet you don't have the only tape of us from last night. So someone has evidence to back it up.": "W dodatku zapewne nie posiadasz jedynej kopii tej kasety z wczoraj. Innymi słowy, ktoś ma dowód na poparcie tej historii.",
  "We need to find out what someone's been keeping in that cave.": "Musimy się dowiedzieć za wszelką cenę, co skrywa tamta jaskinia.",
  "I'm going down there now.": "Wyruszam tam w tej chwili.",
  "We don't have a lot of time left out here. If we don't find some fucking answers when they lift us out it's going to be in handcuffs.": "Nie zostało nam wiele czasu. Jeśli nie zdobędziemy jakichś pierdolonych odpowiedzi, ewakuują nas stąd, ale w kajdankach.",
  "It's fine. What was I going back to anyway?": "Nie martw się. Zresztą, do czego miałbym wracać?",
  "That's fine.": "Nie martw się.",
  "Henry, you're going back to whatever you choose. Come on, this is serious.": "Henry, jesteś panem swojego losu, to twój wybór. \nDaj spokój, to poważna sprawa.",
  "I am serious. Look, we just tell the truth and the chips will land where they land.": "Biorę to na poważnie. Słuchaj, powiemy prawdę i zobaczymy, \njak się to potoczy.",
  "US? What's this US? You're the boss. I was just…": "Nas? Jakie niby „nas”? To ty jesteś szefem. Ja tylko...",
  "Us??": "Nas?!",
  "What, following orders?": "Co, wykonywałeś rozkazy?",
  "You know I didn't start this fire. You just tell them the truth, right? That's all you can do.": "Wiesz, że to nie ja wznieciłem ten pożar. Po prostu powiesz im prawdę. Tylko tyle możesz zrobić.",
  "Yeah, I suppose you're right.": "Tak, chyba masz rację.",
  "I know.": "Wiem.",
  "We just have to stick together. Keep our story straight. From the first day with those girls, to the person breaking in our conversation, everything. We gotta be honest and consistent.": "Musimy się wspierać, obstawać przy jednej wersji tej historii. Począwszy od pierwszego dnia i tych dziewczyn, aż do osoby podsłuchującej nasze rozmowy. Musimy być szczerzy i zgodni.",
  "We just stick together.": "Musimy trzymać się razem."
}