{
  "Henry": "Henry",
  "Thorofare tower, this is Two Forks, calling you for the oh, fiftieth time today.": "Wieżo Główna, tu Rozdroża, wzywam już chyba z pięćdziesiąty raz dzisiaj.",
  "The Big Fire continues to move in a southerly fashion.": "Wielki Pożar zdaje się kierować na południe.",
  "The Flapjack Fire continues to move in a southerly fashion.": "Pożar Ciapciaka zdaje się kierować na południe.",
  "The June Fire continues to move in a southerly fashion.": "Czerwcowy Pożar zdaje się kierować na południe.",
  "The Elk Fire continues to move in a southerly fashion.": "Pożar Wapiti zdaje się kierować na południe.",
  "Delilah, for fuck’s sake, answer your radio.": "Delilah, do kurwy nędzy, odezwij się.",
  "Delilah": "Delilah",
  "Helloooo sunshine! Sorry, I went out for a little bit. What can I do you for?": "Witaj, złotko! Wybacz, nie było mnie chwilę. Co mogę dla ciebie zrobić?",
  "You “can do me for” a call to your folks with the helicopter and a ride out of here. AND I DON’T CARE WHO IS HEARING ME ASK THAT.": "Możesz dla mnie zrobić tyle, że wezwiesz śmigłowiec i zabierzesz mnie stąd. I w dupie mam, kto może tego słuchać!",
  "You can \"do me for\" a trip out of here.": "Możesz mnie stąd zabrać.",
  "You can “do me for” a trip out of here. I don’t care if it’s on horseback, or a helicopter or in a canoe. Just get me out of here!": "Możesz mnie stąd wyciągnąć. Nieważne czy na koniu, śmigłowcem, czy w kajaku. Po prostu mnie zabierz!",
  "Henry, we have work left to do! Let’s chat about what’s bothering you and you’ll feel better.": "Henry, mamy robotę do wykonania! Porozmawiajmy o tym, \nco cię trapi, a poczujesz się lepiej.",
  "Are you serious?!": "Poważnie?!",
  "Let's. Talk. Okay?": "Porozmawiajmy. Dobrze?",
  "I didn’t sleep a wink last night and I’ve been going crazy for the past six hours of sun-up.  How are you so chipper?": "Nie zmrużyłem oka zeszłej nocy i odchodziłem od zmysłów przez ostatnie sześć godzin. A coś ty taka w skowronkach?",
  "Why are you so chipper?": "Coś ty taka w skowronkach?",
  "Well it's a new day. What a day, this day we've been given!": "Mamy nowy dzień. I to nie byle jaki!",
  "Maybe I am actually asleep right now. Maybe I didn't stay up all night knowing that someone is—": "Może nadal śnię. Może tak naprawdę nie czuwałem całą noc, wiedząc, że ktoś się tam...",
  "Are you kidding right now?": "Jaja sobie robisz?",
  "Are you kidding?": "Jaja sobie robisz?",
  "Did you not stay up all night knowing that someone is—": "Nie czuwałaś całą noc, wiedząc, że ktoś się tam...",
  "Isn’t this just the most beautiful day?  What a glorious day we’ve been given. Well, I suppose I should get back to work!": "Czyż nie jest to najpiękniejszy dzień? Wspaniały dzień. \nNo, ale powinnam już wracać do pracy!",
  "The Flapjack Fire is becoming quite the problem!": "Pożar Ciapciaka powoli staje się problematyczny!",
  "The Big Fire is becoming quite the problem!": "Wielki Pożar powoli staje się problematyczny!",
  "The June Fire is becoming quite the problem!": "Czerwcowy Pożar powoli staje się problematyczny!",
  "The Elk Fire is becoming quite the problem!": "Pożar Wapiti powoli staje się problematyczny!",
  "I actually slept just great!": "Właściwie to świetnie mi się spało!",
  "Uhh… okay.": "Okej...",
  "By the way, I was wondering if your Flora of the Shoshone info poster was still up inside your tower?": "W sumie to ciekawiło mnie, czy ciągle wisi u ciebie plakat informacyjny z florą Shoshone?",
  "…What?": "Co proszę?",
  "It's just protocol that those stay up, you know, info about your tower, the surrounding tree species, etc.": "Taka jest procedura, żeby wiedzieć, jakie w okolicy danej wieży są gatunki drzew, i tak dalej.",
  "Uh, alright…?": "Okej...",
  "Just, you know, have a look at it. Make sure it’s in ship-shape.": "Spójrz może na ten plakat i upewnij się, że jest w dobrym stanie.",
  "Report poster": "Zgłoś plakat",
  "Okay, yeah, it's up. Why are you acting like this?": "Tak, nadal tu wisi. Czemu się tak zachowujesz?",
  "Great! Just wonderful. Do you see the tree in the top row, second from the left?": "Świetnie! Wręcz wspaniale. Widzisz drzewo w górnym rzędzie, drugie od lewej?",
  "Sure…?": "Jasne...",
  "Let me look at it and I'll tell you.": "Niech no spojrzę i ci powiem.",
  "It's the uh—": "Chodzi o...",
  "NO. You don't need to tell me. Just um, internalize it. It's a great tree. And there's an area called, um, that tree's name in your sector that maybe you should take a mid-day hike to. Maybe.": "Nie! Nie mów. Przyjrzyj mu się. To świetny gatunek. Jest takie miejsce, które ma w sobie... nazwę tego drzewa. Jest w twoim sektorze, może powinieneś się tam przespacerować. Może...",
  "Oooh…": "Aaa...",
  "Oh. Yeah. Okay. Maybe I should go for a hike.": "No tak, dobra. Chyba się przejdę.",
  "Nothing like afternoon in the Rockies, I tell ya.": "Nie ma to jak popołudniowa przechadzka po górach.",
  "Radio me the moment you get there.": "Daj znać, jak dotrzesz na miejsce.",
  "Um, which tree am I supposed to “internalize” again?": "Któremu drzewu muszę się przyjrzeć?",
  "Top row, second from the left.": "Górny rząd, drugie od lewej.",
  "Head to place named after that tree and you’ll have a WONDERFUL afternoon.": "Idź do miejsca z tym drzewem w nazwie, a to popołudnie na pewno zaliczysz do udanych.",
  "Strange Noise": "Dziwny hałas",
  "I just heard something.": "Właśnie coś usłyszałem.",
  "Report strange noise": "Zgłoś dziwny hałas",
  "What is it?": "O co chodzi?",
  "I don't know. It was goddamn terrifying, though.": "Nie wiem. Ale było przerażające.",
  "Well, it could be an elk or it could be someone trying to get you to radio about a loud noise so they know where you are.": "Może to wapiti, a może ktoś próbuje namierzyć w ten sposób twoją pozycję.",
  "Fuck.": "Ja pierdolę.",
  "How about you don't do that again.": "Lepiej, byś unikał tego w przyszłości.",
  "Are you SERIOUS—": "Poważnie?"
}