{
  "Report beer can": "Zgłoś puszkę po piwie",
  "Henry": "Henry",
  "Found one of their empties. Guess we're on the right track.": "Znalazłem kolejną puszkę. Chyba jestem na ich tropie.",
  "Delilah": "Delilah",
  "Roger that.": "Przyjęłam.",
  "Found another.": "Kolejna puszka.",
  "More empties. Maybe I'm getting close.": "Więcej pustych puszek. Chyba jestem coraz bliżej.",
  "What's with the \"roger thats\"?": "O co chodzi z tym ciągłym „przyjęłam”?",
  "I'm trying not scream every time you tell me about the trash they're leaving in my forest.": "Próbuję nie krzyczeć za każdym razem, kiedy zgłaszasz sterty śmieci zalegające w moim lesie.",
  "Oh.": "Och.",
  "Instead I'm focusing on some meditative poses.": "Zamiast tego skupiam myśli na jakichś pozach medytacyjnych.",
  "Haha. Really.": "Mówisz serio?",
  "No. I'm actually stress eating a Mister Funbar. Well, my second Mister Funbar. Oof, Jesus.": "Nie, właściwie to ze stresu pożeram batonik. Właściwie to już drugi. Rany.",
  "I found some of their empties. I think their campsite's just up ahead.": "Znalazłem kilka pustych puszek. Ich obóz jest chyba tuż przede mną.",
  "Roger that. Keep an eye out.": "Przyjęłam. Miej oko na okolicę.",
  "Alright, I think I'm getting close.": "Wydaje mi się, że jestem coraz bliżej.",
  "Let me guess. More beer cans?": "Niech zgadnę. Więcej pustych puszek?",
  "Yeah.": "Tak.",
  "ARRRRRGH.": "Argh!",
  "Did you just yell into a pillow?": "Czy ty właśnie wrzasnęłaś w poduszkę?",
  "The crook of my arm.": "W zgięcie łokcia.",
  "Report campfire": "Zgłoś ognisko",
  "I’ll take care of their fire.": "Zajmę się ich ogniskiem.",
  "That would be great, as always.": "Byłoby super, jak zawsze.",
  "Report campsite": "Zgłoś obozowisko",
  "I see a campsite and it looks like they've got a fire.": "Widzę obóz. Zdaje się, że tli się tam ognisko.",
  "Is it them?": "To ich?",
  "Seems like it. I swear they must've dragged four cases of beer out here.": "Na to wygląda. A niech mnie, musiały tu przytaszczyć ze cztery skrzynki piwa.",
  "Track them down. And don't let them see you.": "Znajdź je. Tylko nie pozwól, żeby cię zobaczyły.",
  "What a job this is.": "Cóż za robota!",
  "There's some cloth out here. It looks like it was torn from something.": "Znalazłem skrawek materiału. Wygląda, jakby był z czegoś wyrwany.",
  "Report scrap of cloth": "Zgłoś skrawek materiału",
  "Strange…": "Dziwne...",
  "I'll keep looking around.": "Rozejrzę się po okolicy.",
  "I found, well, part of their tent.": "Znalazłem... właściwie to fragment ich namiotu.",
  "Report scrap of torn tent": "Zgłoś strzępek porwanego namiotu",
  "It's really torn up, huh?": "Jest naprawdę porwany, co?",
  "Yeah. Big time.": "Oj tak.",
  "Well, they're not here.": "Cóż, tutaj ich nie ma.",
  "Report state of campsite": "Zgłoś stan obozowiska",
  "Okay. Um, you might have to wait. And that gives us some time to come up with something real horrifying.": "Okej, musisz chyba trochę poczekać. A to daje nam czas na wymyślenie czegoś naprawdę przerażającego.",
  "I… we might be too late.": "Wydaje mi się, że przybyliśmy za późno.",
  "What do you mean?": "Co masz na myśli?",
  "This place is trashed. Destroyed.": "To miejsce jest całkowicie zdemolowane.",
  "What happened?": "Co się stało?",
  "I don't know. Maybe they had a fight or something.": "Nie wiem. Może wdały się w bójkę, czy coś.",
  "Maybe they had a fight.": "Może wdały się w bójkę.",
  "It's that bad?": "Jest aż tak źle?",
  "It's not good.": "Nie jest dobrze.",
  "You've got that camera, right?": "Masz ten aparat, prawda?",
  "It might be a good idea to get a few snaps. Just in case.": "Powinieneś zrobić kilka zdjęć. Tak na wszelki wypadek.",
  "Yeah, good thinking.": "Dobra myśl.",
  "Well, if they've already turned on each other maybe there's nothing we can do. Have a look around.": "Cóż, jeśli obraziły się na siebie, może już nic tu nie zdziałamy. Rozejrzyj się po okolicy.",
  "I have no idea. It's pretty bad.": "Nie mam pojęcia. Wygląda to kiepsko.",
  "I have no idea.": "Nie mam bladego pojęcia.",
  "Well, just look around. Make sure they weren't, you know, injured or…": "Rozejrzyj się. Sprawdź, czy nie zostały ranne albo...",
  "Uh, murdered?": "Zamordowane?",
  "They weren't murdered.": "Nie zostały zamordowane.",
  "Remember when I came out here to quietly look for fires?": "Pamiętasz, kiedy przyjechałem tu, żeby w spokoju wypatrywać pożarów?",
  "They weren't. Just look around.": "Nie zostały. Po prostu się rozejrzyj.",
  "Honestly, it looks like it could've been a bear.": "Serio, wygląda, jakby to była robota niedźwiedzia.",
  "Looks like it could have been a bear.": "To miejsce wygląda jak po ataku niedźwiedzia.",
  "Oh, Jesus.": "Chryste.",
  "I need to be honest with you. If I find a dead body out here, I'm gonna be sick.": "Muszę być z tobą szczery. Jeśli znajdę tutaj martwe ciało, zwymiotuję.",
  "Well, don't yack. Just look around and let me know what you find.": "Spróbuj się powstrzymać. Po prostu rozejrzyj się i daj mi znać, jeśli coś znajdziesz.",
  "Hey, just look around, okay? See what the deal is.": "Po prostu obadaj okolicę, dobrze? Sprawdź, co jest grane.",
  "Actually… You've got that camera, right?": "Swoją drogą... Masz ten aparat, prawda?",
  "Report stolen sheets": "Zgłoś skradzioną pościel",
  "Ah, found my sheets!": "Znalazłem swoją pościel!",
  "The girls stole them?": "Dziewczyny ją ukradły?",
  "Yeah. But the thing is, their entire campsite is wrecked.": "Taa. Problem w tym, że cały ich obóz jest zdemolowany.",
  "So they did break into your tower.": "Czyli to one włamały się do twojej wieży.",
  "Looks like.": "Na to wygląda.",
  "Report sleeping bags": "Zgłoś śpiwory",
  "I found their campsite. You know, maybe I'll take one of their sleeping bags for myself.": "Znalazłem ich obóz. Wiesz co, chyba zagarnę dla siebie jeden z ich śpiworów.",
  "You're there right now?": "Jesteś tam?",
  "You know, maybe I should take one of their sleeping bags as payback.": "Może powinienem wziąć jeden z ich śpiworów w ramach zemsty?",
  "At this stage, take whatever you want.": "Bierz cokolwiek chcesz.",
  "These girls have a full case of beer left here. A full case.": "Te dziewczyny mają tu cały karton piwa. Cały karton.",
  "Report case of beer": "Zgłoś karton z piwem",
  "You found them?": "Znalazłeś je?",
  "Well, they're impressive little shits, I guess.": "Godne podziwu jak na małe gówniary.",
  "That is some dedication.": "To niemałe poświęcenie.",
  "Report torn clothes": "Zgłoś porwane ubrania",
  "Hey, so I found the campsite. It doesn't look good here.": "Znalazłem ich obóz. Nie wygląda za dobrze.",
  "Some of their clothes are all torn up.": "Część ich ubrań jest w strzępach.",
  "And they're not there?": "A ich tam nie ma?",
  "Yeah. And the thing is, their entire campsite is wrecked.": "Ano, nie ma. Co więcej, cały ich obóz wygląda jak pobojowisko.",
  "Uh… That's not good.": "To nie za dobrze.",
  "Yeah, it looks like the same stuff I saw yesterday, so it is definitely them.": "Te rzeczy wyglądają jak z wczoraj, więc to muszą być ich ubrania.",
  "Report note": "Zgłoś notatkę",
  "Looks like someone left a note.": "Wygląda na to, że ktoś zostawił notatkę.",
  "Intriguing. Maybe you should read it.": "Intrygujące. Może powinieneś ją przeczytać?",
  "Okay. Yeah.": "No jasne.",
  "Let me know what it says.": "Daj mi znać, co jest tam napisane.",
  "They're gone, for sure.": "Na pewno już ich tu nie ma.",
  "Report teens' angry note": "Zgłoś notatkę wściekłych nastolatek",
  "How can you tell?": "Skąd wiesz?",
  "The girls left someone— me, I guess— a note.": "Dziewczyny zostawiły komuś... zgaduję, że mnie... notatkę.",
  "The girls?": "Dziewczyny?",
  "I found their campsite. Someone or something tore it to shreds and the girls left me a note behind.": "Znalazłem ich obóz. Ktoś lub coś wywróciło go do góry nogami, a dziewczyny zostawiły mi pożegnalny liścik.",
  "What's it say?": "Co jest tam napisane?",
  "Hello?  Henry, are you there?": "Halo? Henry, jesteś tam?",
  "Honestly, I'm just glad they're gone.  It's probably the best-case scenario for us, and now we can just get back to work.": "Cieszę się, że odeszły. Sprawy nie mogły przybrać lepszego obrotu, możemy dzięki temu bez przeszkód wrócić do pracy.",
  "They're threatening to call the police because they think I attacked them.": "Grożą mi wezwaniem policji, ponieważ myślą, że je zaatakowałem.",
  "They're calling the police, they think I attacked them.": "Wzywają policję, bo myślą, że je zaatakowałem.",
  "Oh my god. Well… did you?": "O mój Boże. A zrobiłeś to?",
  "No, but I destroyed their stereo.": "Nie, zniszczyłem tylko ich stereo.",
  "No, I didn't do this, okay? Someone or something went to town here but it wasn't me.": "Nie. To nie moja sprawka, okej? Ktoś urządził tu prawdziwe pobojowisko, ale nie byłem to ja.",
  "Because I told you to scare them, not assault them.": "Mówiłam ci, żebyś je nastraszył, nie zaatakował.",
  "I didn't. Of course I didn't. I just threw their stereo in the lake.": "Oczywiście, że tego nie zrobiłem. Ja tylko wrzuciłem ich radio do jeziora.",
  "Yeah, I really wish you wouldn't have done that.": "Wolałabym, żebyś i tego nie zrobił.",
  "This is, I don't know, weird as hell. But it wasn't me.": "To jest cholernie dziwne. Ale to nie moja robota.",
  "It's okay. I believe you.": "W porządku, wierzę ci.",
  "No way, I just stole their booze.": "Nie, ja tylko ukradłem im gorzałę.",
  "Yeah, I took their whiskey back at the lake but that just felt like, I don't know, the cost of doing business.": "Zabrałem im whisky, ale uznałem to po prostu za cenę załatwienia tej sprawy.",
  "Well that's different. And I don't blame you.": "To co innego. I nie winię cię.",
  "I didn't do anything to them.": "Nic im nie zrobiłem.",
  "I didn't do anything to them. But it looks like someone had it out for them.": "Nic im nie zrobiłem. Ale wygląda na to, że ktoś inny tak.",
  "Then why do they think it's you?": "Skoro tak, to czemu myślą, że to ty?",
  "Fuck, I don't know!": "Kurwa, nie mam pojęcia!",
  "Huh.": "Hm...",
  "Hey, I don't!": "Naprawdę!",
  "I believe you! Come on, Henry.": "Wierzę ci! Wrzuć na luz, Henry.",
  "Alright, alright. It's just weird, what happened out here.": "Dobra, dobra. To, co się tu wydarzyło, jest po prostu dziwne.",
  "Don't be ridiculous.": "Nie bądź śmieszna.",
  "That's not ridiculous. Ridiculous is chucking people's stuff into a lake.": "To nie jest śmieszne. Śmieszne jest wrzucanie czyjegoś przybytku do jeziora.",
  "It's not ridiculous. I've known you, what, twenty-four hours? Maybe you're nuts.": "To nie jest śmieszne. Znam cię ile, dwadzieścia cztery godziny? Może jesteś szurnięty?",
  "Look, I just came out here to sit in a tower, alright? Not get into some mess with a bunch of coeds.": "Przyjechałem tu, żeby siedzieć w wieży, okej? A nie po to, żeby mieszać się w jakiś syf z grupką dziewczyn.",
  "It's fine. They're gone?": "W porządku. Nie ma ich tam?",
  "Yeah. They're gone.  But you should see this place. It's just… it's weird.": "Nie ma. Ale powinnaś zobaczyć to miejsce na własne oczy. \nTo jest po prostu... dziwne.",
  "Henry, did you attack or do anything that could be perceived as an attack to these campers?": "Henry, czy zaatakowałeś je albo zrobiłeś cokolwiek, co mogłoby być postrzegane jako atak?",
  "Hello?!": "Halo?!",
  "Look, just… Just get out of there, okay? I'm sure whatever happened wasn't your fault.": "Po prostu odejdź stamtąd, dobrze? Jestem pewna, że cokolwiek tam zaszło, nie było twoją winą.",
  "If you can hear me, I'm sure it's just a weird misunderstanding.": "Jeśli mnie słyszysz, jestem pewna, że to dziwne nieporozumienie.",
  "It's just, uh… It's an apology for all of the trouble.": "To... to tylko przeprosiny za sprawienie tylu kłopotów.",
  "Well, good. They should be sorry. Is everything okay? Can we put this to bed?": "To świetnie. Powinno być im głupio. Wszystko dobrze? \nMożemy zamknąć tę sprawę?",
  "Well, maybe not a full apology…": "No, może niezupełnie przeprosiny...",
  "Well… I mean, I'm using apology a little loosely here.": "Cóż... Możliwe, że używam słowa „przeprosiny” nieco na wyrost.",
  "Ohhh really?": "Czyżby?",
  "They were upset about getting busted over the fireworks, I think.": "Myślę, że były po prostu wkurzone za tę sprawę z fajerwerkami.",
  "So they, what, tore apart their own campsite in a rage?": "Czyli co, rozwaliły swój obóz w napadzie szału?",
  "No, no. But I think they think that maybe I did it?": "Nie, nie. Ale sądzę, że są przekonane, że to moja robota.",
  "Look. You didn't, right?": "Ale tego nie zrobiłeś, prawda?",
  "Right.": "Prawda.",
  "'Cause what's done is done.": "Bo co się stało, to się nie odstanie.",
  "I mean, their campsite is destroyed. My tower got trashed. Maybe they did do both. I don't know. It's really weird.": "Obóz jest zniszczony. Moja wieża zdemolowana. Może to ich robota w obu przypadkach. Nie wiem. Cholernie to dziwne.",
  "We're good.": "Wszystko dobrze.",
  "Yeah, we're good.": "Tak, wszystko dobrze.",
  "Yeah?": "Tak?",
  "Yeah. It was probably just a bear down here. Who knows, right?": "To prawdopodobnie tylko niedźwiedź. Kto to wie, prawda?",
  "Exactly. I mean, it's the wilderness. It's wild. It says so right in the name, I mean…": "Dokładnie. W końcu jesteśmy w dziczy. Nawet sama nazwa \nna to wskazuje.",
  "Wow, you are a dork, huh?": "Serio jesteś głupkiem, co?",
  "Hey, look who's talking! Alright, well, you know, maybe we can actually just get to work from now on.": "Przyganiał kocioł garnkowi! Dobra, więc może teraz będziemy mogli rzeczywiście wrócić do pracy.",
  "Their camp was attacked, so…": "Obóz został zaatakowany, więc...",
  "What if someone else attacked them?": "Co jeśli ktoś inny je zaatakował?",
  "I don't think there is a killer on the loose. This is not a “Teddy Krueger” situation.": "Nie sądzę, żeby gdzieś tu grasował zabójca. Takie rejony \nnie przyciągnęłyby Teddy'ego Kruegera.",
  "Kreuger? It's FREDDY Krueger.": "Kruegera? On się nazywał Freddy.",
  "Wait, really?": "Czekaj, serio?",
  "Yeah. For sure.": "Tak. Serio.",
  "Huh. I've been saying it wrong for—": "Wychodzi na to, że żyłam w kłamstwie przez...",
  "For like five years.": "Przez jakieś pięć lat.",
  "Wow, that's embarrassing. But, I mean, yeah. Who knows what happened to their campsite?": "To upokarzające. Ale, no... Kto wie, co się stało z ich obozowiskiem?",
  "We're good, right? I mean, an apology is an apology.": "Wszystko dobrze, prawda? W końcu, przeprosiny to przeprosiny.",
  "Maybe you're out of range.": "Może jesteś poza zasięgiem.",
  "Weird stuff happens in the woods.  It could be other campers. They could be having a bad mushroom trip. We really don't know.": "Dziwne rzeczy dzieją się w lasach. Mogli to być inni obozowicze. \nA może zaliczyły jakieś odpały po grzybkach? Ciężko stwierdzić.",
  "But they're gone. There's no way to call the cops.  They're not coming back, and we can get to work.": "Ale już ich tu nie ma. Nie zdołają wezwać glin. Nie wrócą też \nz powrotem, więc możemy brać się do roboty.",
  "So they're gone, which is great. They're not coming back and we can get to work.": "Nie ma ich, a to świetnie. Skoro nie mają zamiaru wracać, możemy zająć się własną robotą.",
  "I'd really like to start enjoying a quiet summer.": "Serio chciałabym zacząć delektować się spokojnym latem.",
  "Yeah. Me too.": "Tak, ja też.",
  "Report Dangerous Hunks": "Zgłoś „Niebezpieczne Ciacha”",
  "Well, I found some Dangerous Hunks.": "Znalazłem parę „Niebezpiecznych Ciach”.",
  "What on earth… are you…?": "Na litość boską, o czym ty...",
  "It’s the name of a magazine for girls.": "To tytuł jakiegoś pisemka dla dziewczyn.",
  "It’s on the ground here, at their camp.": "Leży na ziemi w ich obozie.",
  "You found them? Where are they?": "Znalazłeś je? Gdzie są?",
  "No idea.": "Nie mam pojęcia.",
  "The thing is, their entire campsite is wrecked.": "Problem w tym, że cały obóz jest zdemolowany.",
  "It's another one of those magazines.": "To kolejny z ich magazynów.",
  "I don't get why the hunks are dangerous.": "Nie łapię, co niebezpiecznego może być w ciachach.",
  "I don't get why the hunks have to be so dangerous.": "Nie łapię, dlaczego te ciacha muszą być niebezpieczne.",
  "Well, you're clearly not a young woman.": "Widocznie nie jesteś młodą kobietą.",
  "Girls should want nice hunks.": "Dziewczyny powinny marzyć o miłych ciachach.",
  "Ugh, boring.": "Nuda.",
  "Report Teen Zone": "Zgłoś „Strefę Nastolatek”",
  "I have entered… the Teen Zone.": "Wkroczyłem w... „Strefę Nastolatek”.",
  "Oh really? And where's that?": "Serio? A gdzie to jest?",
  "Apparently, pants are back.": "Wychodzi na to, że spodnie wróciły.",
  "Huh, pants are back.": "Spodnie wróciły.",
  "I… I'm sorry… pants are back?": "Przepraszam... spodnie wróciły?",
  "According to the experts at Teen Zone magazine.": "Według ekspertów ze „Strefy Nastolatek”.",
  "It’s unclear where they’ve been.": "Nie jest wyjaśnione, gdzie były.",
  "The pants, I mean.": "Spodnie, mam na myśli.",
  "Report destroyed tent": "Zgłoś zniszczony namiot",
  "Whoa… their tent is demolished.": "Ich namiot jest rozniesiony w strzępy.",
  "Their tent looks like it’s been through the shredder.": "Namiot wygląda, jakby przepuściły go przez wyżymaczkę.",
  "Which would explain that scrap I found.": "Co tłumaczyłoby ten strzępek materiału, który znalazłem.",
  "What could've done that? Like, a bear? Or, I know it sounds crazy, but even a bull elk if it's off its rocker.": "Czyja to może być sprawka? Niedźwiedzia? Albo, to zabrzmi dziwnie, jakiegoś wapiti, który odłączył się od stada?",
  "Whatever did it did not hold back.": "Ktokolwiek to zrobił, poszedł na całość.",
  "Well, I found the source of that fabric.": "Wygląda na to, że znalazłem źródło tego materiału.",
  "You’re there? Where are they?": "Jesteś tam? Gdzie one są?",
  "I don’t know. Gone.": "Nie mam pojęcia. Nie tutaj.",
  "This whole place is torn apart.": "To miejsce wygląda jak pobojowisko."
}