{
  "Delilah": "Delilah",
  "Hello, Henry. Having a nice afternoon?": "Cześć, Henry. Miło spędzasz popołudnie?",
  "Henry": "Henry",
  "Not too bad. I could get used to it out here.": "Nie jest źle. Mógłbym tu zamieszkać na stałe.",
  "Yeah, great.": "Tak, jest świetnie.",
  "That's nice.": "To miło.",
  "I might never leave.": "Chyba się tu zadomowię.",
  "Well, uh… I called with some bad news.": "No tak... Mam dla ciebie złe wieści.",
  "Well, I was.": "Było miło do teraz.",
  "Well, I was…": "Było miło do teraz...",
  "Hardee har. I'm finally paying for all those years of giving my bosses attitude.": "W końcu mi się dostaje za lata rozstawiania ludzi po kątach.",
  "Look, um… I called with bad news.": "Posłuchaj... nie mam dobrych wieści.",
  "Two young women, Chelsea Stevens and Lily McClain were reported missing. They've got parents out in California who haven't heard from them in a week.": "Zgłoszono zaginięcie dwóch młodych kobiet, Chelsea Stevens \ni Lily McClain. Ich rodzice, mieszkający w Kalifornii, ostatni raz \nkontaktowali się z nimi tydzień temu.",
  "They were supposed to meet an aunt down in Cody.  If they're the girls from last week then you're probably the last person to have seen them.": "Miały spotkać się ze swoją ciotką w Cody. Jeśli to te dziewczyny sprzed tygodnia, prawdopodobnie to ty widziałeś je jako ostatni.",
  "You should tell whoever that I'm happy to be questioned.": "Powinnaś zgłosić, że chętnie odpowiem na wszelkie pytania.",
  "I'm happy to be questioned.": "Chętnie odpowiem na wszelkie pytania.",
  "I yelled at ’em, but that's it.": "Okrzyczałem je, nic poza tym.",
  "I caused them some trouble but nothing major. I never even got very close to them.": "Napsułem im trochę krwi, ale to nie było nic poważnego. Nawet się do nich nie zbliżyłem.",
  "Well…": "Cóż...",
  "ONE stereo. That’s it.": "Tknąłem radio. Nic więcej.",
  "I didn't do anything to them.": "Nic im nie zrobiłem.",
  "I didn't do anything.": "Nic nie zrobiłem.",
  "Except destroyed their stuff.": "Poza zniszczeniem ich rzeczy.",
  "What about their camp?": "A co z ich obozowiskiem?",
  "That wasn't me. You know that.": "Dobrze wiesz, że nie mam z tym nic wspólnego.",
  "Just their stereo.": "Tknąłem tylko radio.",
  "Don't get defensive.": "Nie podnoś głosu.",
  "It's a coincidence. How many pairs of girls go backpacking?": "Czysty przypadek. Mało to dziewczyn wybiera się w góry?",
  "It's probably a coincidence.": "To pewnie zbieg okoliczności.",
  "Probably a lot.": "Zapewne wiele.",
  "Yeah, probably a lot.": "Taa, zapewne wiele.",
  "So I guess you didn't get their names then?": "Czyli nie masz pojęcia, jak się nazywały?",
  "Well, it's a big if. It might not be them.": "Tak, wielka niewiadoma. To mógł być ktoś inny.",
  "Look, it's not gonna be an issue. I mean, if they turn up dead, then maybe.  Should I just not say anything and save us the trouble?": "Słuchaj, to żaden problem. No, chyba że okażą się martwe. \nMoże powinnam to przemilczeć i oszczędzić nam kłopotu?",
  "Yeah, don't.": "Tak, dobry pomysł.",
  "That's what I was thinking.": "Tak też myślałam.",
  "I… I think it's worth mentioning something.": "Wydaje mi się, że warto o tym wspomnieć.",
  "It's worth mentioning.": "Lepiej o tym wspomnieć.",
  "Yeah. I'll keep it vague. I really don't want to talk to the cops.": "Dobra, napiszę zwięzłą notatkę. Naprawdę nie chcę \nmieć glin na głowie.",
  "Me neither.": "Ja też.",
  "…": "...",
  "I’m going to take your silence as maybe we just don’t say anything.": "Uznam, że milczysz, bo też chcesz to zachować w tajemnicy.",
  "Alright, Henry. Thanks. Enjoy the sunset.": "Dzięki, Henry. Ciesz się resztką zachodzącego słońca."
}