{
  "Henry": "Henry",
  "Well their underwear is still strewn all over down here.": "Ich bielizna nadal jest porozrzucana wszędzie wokół.",
  "Should probably make sure those roman candles aren’t there when they come back.": "Powinienem się chyba upewnić, że te fajerwerki znikną stąd przed ich powrotem.",
  "They left a lot of their stuff down here.": "Zostawiły tu mnóstwo swoich gratów.",
  "So they just left their stuff down here, but… it would be a bad idea for me to toss it all in the lake, right?": "Zostawiły tu mnóstwo swoich rzeczy, ale... to byłoby okropne \nz mojej strony, gdybym wrzucił je do jeziora, co?",
  "They just left their stuff down here…": "Tak po prostu zostawiły tu swoje rzeczy...",
  "Delilah": "Delilah",
  "Yes, that would be a very bad idea. I think you've done enough.": "Tak, to byłby bardzo zły pomysł. Dość już dziś zrobiłeś.",
  "Yes, I don't think that'd be wise. If you could refrain from criminal destruction of personal property while on this job, that'd be great, okay?": "Tak, to nie byłoby mądre posunięcie. Byłabym wdzięczna, gdybyś \nw trakcie pracy powstrzymał się przed niszczeniem cudzego mienia, \nsłyszysz?",
  "Right… whoops.": "Racja...",
  "Their underwear is still here...": "Zostawiły tu swoją bieliznę...",
  "Well, it is a particularly warm evening. I'm not sure I blame them.": "Mamy całkiem ciepły wieczór, jestem w stanie je zrozumieć.",
  "Any chance of those kids getting a disease in this lake? Like diphtheria or consumption or…?": "Istnieje szansa, że te dzieciaki zarażą się jakimś syfem z jeziora? Może błonicą albo suchotami, czy coś?",
  "Any chance of those kids catching a disease in this lake?": "Istnieje szansa, że te dzieciaki zarażą się jakimś syfem z jeziora?",
  "Consumption? Not if they're not 19th century chimney sweeps, no.": "Suchotami? Marna szansa, o ile nie są XIX-wiecznymi kominiarzami.",
  "You know, whatever.": "No to czymkolwiek.",
  "If they drank a bunch, giardia maybe. But probably not this time of year.": "Gdyby nałykały się wody, może lamblią. Choć to niespotykane \no tej porze roku.",
  "Huh. That's too bad.": "Szkoda.",
  "Well, this lake does seem like a good spot to swim.": "To jezioro wygląda na świetne kąpielisko.",
  "This lake does seem like a good spot to swim.": "To jezioro wygląda na świetne kąpielisko.",
  "Even if the last people to do so were assholes.": "Nawet jeśli zdaje się przyciągać idiotów.",
  "Yeah, right now it's all snowmelt so you'll freeze your balls off. But as hot as it is maybe that's a fair trade.": "Teraz wypełniają je wody roztopowe, więc odmroziłbyś sobie tyłek. Choć przy tych upałach to może i niezły pomysł.",
  "It's starting to feel like it.": "Zaczyna to brzmieć kusząco.",
  "Hey, there's a trail to Two Forks tower down here near the lake.": "Hej, niedaleko jeziora znajduje się szlak prowadzący do Wieży na Rozdrożach.",
  "Report trail sign": "Zgłoś znak szlaku turystycznego",
  "Yeah, that's your tower.": "Tak, to nazwa twojej wieży.",
  "So I should go this way.": "Czyli powinienem obrać ten kierunek.",
  "Well, you're not climbing back up that slide.": "Na pewno nie wespniesz się w górę osuwiska.",
  "I know that's my tower.  Why is there sign to it?": "Wiem o tym. Po co umieszczono tu ten znak?",
  "Hikers like to pick landmarks; it's a nice one.": "To punkt widokowy, turyści go lubią. Urokliwe miejsce.",
  "So there's no noise ordinances or rules out here?": "Nie istnieją żadne przepisy zakazujące hałasowania?",
  "Ugh, no, but that music I hear makes a good case for them.": "Nie, ale muzyka, którą słyszę, skłania mnie do stworzenia takowych.",
  "Yeah, no kidding.": "Co ty nie powiesz."
}