{
  "Okay, I see that smoke.": "Dobra, widzę ten dym.",
  "Henry": "Henry",
  "Okay, I have eyes on that smoke plume.": "Dobra, widzę tę smugę dymu.",
  "Delilah": "Delilah",
  "Great. Find your way over there and give 'em hell.": "Świetnie. Idź tam i zgotuj im prawdziwe piekło.",
  "Report smoke column": "Zgłoś smugę dymu",
  "I see a really thin plume of smoke.": "Widzę cienką smugę dymu.",
  "Yeah, I see it too. A thin plume like this is either a new fire or a campfire.": "Tak, też ją widzę. Smuga cienka jak ta oznacza albo początek pożaru, albo ognisko.",
  "A campfire. You think it's them?": "Ognisko. Myślisz, że to one?",
  "I reckon so.": "Tak sądzę.",
  "It looks like it's to the… southwest of me.": "Zdaje się, że to na południowy zachód ode mnie.",
  "That's right. If you hike towards Five Mile Creek that should put you in the neighborhood.": "Zgadza się. Jeśli pójdziesz w kierunku Pięciomilowego Potoku, powinieneś znaleźć się w pobliżu.",
  "Keep an eye on that smoke plume. Let me know if it's getting any larger.": "Kontroluj tę smugę. Daj mi znać, jeśli się powiększy.",
  "Will do.": "Zrobi się.",
  "Hey, do you see that?": "Hej, widzisz to?",
  "See what?": "Widzę co?",
  "No. Uh, maybe. See what, exactly?": "Nie... A może? Co dokładnie?",
  "I can barely make it out, but there's a small wisp of smoke way down to the southwest.": "Na południowym zachodzie można dostrzec cienką smugę dymu.",
  "You mean that smoke plume?": "Masz na myśli tę smugę dymu?",
  "Yeah, I think so. That thin plume of smoke?": "Tak, tak mi się wydaje. Ta cienka smuga dymu?",
  "Yep. Looks like it's way down to the southwest.": "Tak. Wygląda, że to na południowy zachód.",
  "You should be able to find a way over there from the meadow by the lake.": "Powinieneś móc tam dotrzeć z polany obok jeziora.",
  "Towards 5 mile creek, in the southwest quadrant of your map.": "W kierunku Pięciomilowego Potoku, spójrz w południowo-zachodni fragment mapy.",
  "You think it's those girls?": "Myślisz, że to te dziewczyny?",
  "I'm pretty sure it's a campfire, so yeah. I'd call that a safe bet.": "Jestem prawie pewna, że to ognisko, więc tak. To bezpieczne założenie.",
  "Man, they really don't give a shit, do they?": "Naprawdę mają wszystko gdzieś, co?",
  "Not a one.": "Po całości.",
  "I think I just spotted something.": "Chyba coś zauważyłem.",
  "Smart money says it's those same girls with another campfire.": "To chyba te same dziewczyny, ale z nowym ogniskiem.",
  "Teens' Area": "Obozowisko nastolatek",
  "Report former campsite": "Zgłoś poprzednie obozowisko",
  "Report teens' former campsite": "Zgłoś poprzednie obozowisko nastolatek",
  "I came back to where they were yesterday thinking they might not have gone far.": "Wróciłem tam, gdzie były wczoraj. Nie mogły odejść daleko.",
  "I figured the smoke might be from that same campfire.": "Myślałem, że dym może pochodzić z tego samego ogniska.",
  "That’s a good instinct. I take it they’re not there?": "Dobra myśl. Rozumiem, że tam ich nie ma?",
  "Not currently.": "Nie w tej chwili.",
  "I bet they didn’t go far.": "Nie mogły odejść daleko."
}