{
  "Henry": "Henry",
  "HEY! Hey you fucking kids!": "Hej! Wy tam, pieprzone dzieciaki!",
  "Hey you fucking kids!": "Wy tam, pieprzone dzieciaki!",
  "Chelsea": "Chelsea",
  "Hey, you fucking fatso! Leave us alone.": "No cześć, pieprzony tłuściochu! Odwal się.",
  "Lily": "Lily",
  "Haha, leave us alone!": "Odwal się od nas!",
  "I left all your stuff back there!": "Nie tknąłem waszych rzeczy palcem!",
  "I didn't touch your stuff!": "Nie ruszałem waszych rzeczy!",
  "You gotta take it easy with the fireworks, alright?!": "Dajcie sobie na wstrzymanie z fajerwerkami, słyszycie?!",
  "Please cool it with the fireworks, OK?": "Przestańcie się bawić fajerwerkami, okej?",
  "Don't pull any more shit or you're fucked, alright?": "Skończcie się wydurniać albo będziecie mieć przejebane, zrozumiano?",
  "Quit the fireworks shit or else!": "Koniec z fajerwerkami, bo pożałujecie!",
  "I know you guys are setting off bottle rockets out here, okay?!": "Wiem, że zabawiacie się tu z fajerwerkami, słyszycie?!",
  "I know you're lighting fireworks!": "Wiem, że odpalacie fajerwerki!",
  "YOU oughta take it easy at the Sizzler buffet!": "To ty musisz dać sobie na wstrzymanie z fast foodami!",
  "Ha, Chelsea!": "Chelsea!",
  "What!? He's just some loser out in the woods. I mean, he's grody!": "Co?! To tylko jakiś leśny zboczeniec. W dodatku obrzydliwy!",
  "Don't threaten us!": "Nie groź nam!",
  "Yeah, who the hell are you, creep?": "Coś ty za jeden, czubku?",
  "HOW? Because you're hiding in the bushes spying on us?!": "Skąd? Bo siedzisz w krzakach i nas podglądasz?!",
  "Give him a break, Lily, he probably hasn't seen boobs in twenty years!": "Wyluzuj, Lily, to pewnie pierwsze cycki, które widzi \nod dwudziestu lat!",
  "Haha! He's probably still a virgin!": "Pewnie nadal jest prawiczkiem!",
  "He's just one of those lonely guys who likes to boss people around.": "To pewnie kompletny smutas, który lubi rozstawiać innych \npo kątach.",
  "Well, I took all your shit!": "Zabrałem wasze graty!",
  "I took your shit!": "Zabrałem wasze graty!",
  "Well, I took your whiskey!": "Zgarnąłem sobie waszą whisky!",
  "I took your whiskey!": "Wziąłem sobie waszą whisky!",
  "Well, I took them!": "Zgarnąłem je!",
  "Hey, just so you're aware, I confiscated your fireworks.": "Jeśli chcecie wiedzieć, skonfiskowałem wasze fajerwerki.",
  "I took your fireworks!": "Zabrałem wasze fajerwerki!",
  "So, you'll have to find another way to act like total shits!": "Więc musicie znaleźć inny sposób na zachowywanie się jak gnojki!",
  "Anything else of yours you'd like to see take a swim?!": "Coś jeszcze chciałybyście zobaczyć w wodzie?!",
  "What else should I toss into the lake?": "Co jeszcze ma wylądować w jeziorze?",
  "I took all of your stuff! The fireworks, the whiskey, you name it.": "Zabrałem wszystkie wasze graty! Fajerwerki, whisky, całą resztę.",
  "I took all of your shit!": "Zabrałem wasze graty!",
  "You don't know a damn thing about me!": "Gówno o mnie wiecie!",
  "You don't know anything about me.": "Nic o mnie nie wiecie.",
  "We know you're a PEEPING TOM! How long have you been standing over there?": "Wiemy, że jesteś zboczeńcem! Jak długo się tam ukrywałeś?",
  "Look, I'm sorry for bothering you. Can you just… knock it off, please?": "Wybaczcie, że przeszkadzam. Możecie się po prostu... uspokoić?",
  "I'm sorry for bothering you.": "Przepraszam, że wam przeszkadzam.",
  "Yeah, you should be. This is a free country, and we should be free to do whatever we want!": "Mamy gdzieś twoje przeprosiny. To wolny kraj, mamy prawo robić, co nam się tylko zamarzy!",
  "I said sorry!": "Przecież przeprosiłem!",
  "Oh my God, is that what you are?! Barf me out!": "O mój Boże, serio? Odczep się!",
  "Eww!": "Fuj!",
  "Can we just get out of here?": "Możemy stąd spadać?",
  "Eww, totally.": "Zdecydowanie.",
  "You're just some sad man out in the woods!": "Jesteś jakimś ponurackim dzikusem!",
  "You're GROSS!": "Jesteś obleśny!",
  "And FREE from any Peeping Toms!": "I prawo trzymać się z dala od zboczuchów!",
  "No! I was— I DIDN'T—": "Nie! Ja... nie chciałem...",
  "YOU— YOU ASSHOLE!!!": "Ty... Ty dupku!",
  "Whoa! HEY! PUT THAT DOWN!": "Hej! Odłóż to!",
  "What? You were messing with our packs?!": "Co? Grzebałeś przy naszych plecakach?!",
  "What?! Gross.": "Co?! Ohyda.",
  "What the hell were you looking for, panties!?": "Czego niby szukałeś, majtek?!",
  "NO, no—": "Nie, nie...",
  "WHAT?!": "Co?!",
  "You dick!": "Ty chuju!",
  "Also, setting off fireworks out here isn't just stupid, it's illegal!": "A odpalanie tu fajerwerków jest nie tylko głupie, ale też nielegalne!",
  "Yeah, so is STEALING, asshole!": "Tak jak kradzież, dupku!",
  "That's so FUCKING bogus!": "Kurwa, no po prostu nie wierzę!",
  "You're gonna pay for that!": "Zapłacisz nam za to!",
  "Our fireworks?!": "Nasze fajerwerki?!",
  "COOL STEREO!": "Fajne radyjko!",
  "HEY! Put that down!": "Hej! Odłóż to!",
  "Seriously! It was expensive!": "Serio! Wywaliłam na nie sporo kasy!",
  "Yeah well out here, fireworks aren't just stupid, they're illegal!": "Odpalanie tu fajerwerków jest nie tylko głupie, ale też nielegalne!",
  "PLEASE, JUST PUT IT DOWN! We won't light any more!": "Proszę, odłóż je! Już nie będziemy odpalać fajerwerków!",
  "Ugh, this guy's creepy, Chelsea!": "Ten gość to jakiś czubek, Chelsea!",
  "Yeah, you hear that, CREEP?!": "Słyszysz, czubku?!",
  "I don't like this.": "Nie podoba mi się to.",
  "You're gross!": "Jesteś obleśny!",
  "Can we go? Let's just swim to the other side of the lake or something.": "Możemy stąd spadać? Przepłyńmy na drugą stronę jeziora, czy coś.",
  "Ha! You probably have a tiny dick!": "Pewnie masz małego fiutka!",
  "Chelsea!": "Chelsea!",
  "It's my boom box!": "To mój grajek!",
  "You're a creep!": "Jesteś czubkiem!",
  "TOTAL creep!": "Czubem do kwadratu!",
  "Go get a girlfriend, creep!": "Znajdź sobie dziewczynę, świrusie!",
  "Light another firework and it won't be your stereo I wreck!": "Odpalcie fajerwerki jeszcze raz, a rozpieprzę coś więcej niż radio!",
  "Oh FUCK you, psycho!": "Pieprz się, psycholu!",
  "Yeah! Fuck you!": "Taa, pierdol się!",
  "You'll fucking pay for this! You can't just harass girls in the woods!": "Zapłacisz za to, kurwa! Nie masz prawa napadać na dziewczyny w lesie!",
  "Let's get out of here.": "Zmywajmy się stąd.",
  "THANK you. Now leave us alone!": "Dzięki. A teraz zostaw nas w spokoju!",
  "I found them in the lake.": "Są w jeziorze.",
  "I found them in the lake. Naked.": "Są w jeziorze. Nagie.",
  "Delilah": "Delilah",
  "Skinny dipping.": "Pływają na golasa.",
  "Yeah.": "Tak.",
  "Is that a guy over there?!?": "Czy tam stoi jakiś facet?!",
  "Ha ha… oh boy. Enjoy dealing with that!": "O rany... Życzę powodzenia!",
  "What the?!": "Co do...",
  "Are you throwing stuff at us?!": "Rzucasz w nas czymś?!",
  "What was that?": "Co to było?",
  "Your fucking fireworks!": "Wasze pieprzone fajerwerki!",
  "Fucking COOL IT with the fireworks!": "Zostawcie te pieprzone fajerwerki w spokoju!",
  "Why do guys think it's alright to just stare at girls?": "Dlaczego faceci zawsze myślą, że wolno im podglądać dziewczyny?",
  "We hiked ALL THE WAY OUT HERE to get away from guys like you!": "Przeszłyśmy całą tę drogę, by uwolnić się od gości takich jak ty!",
  "And now HE'S over there with his mouth hanging open.": "A teraz stoi tu z jęzorem wywalonym do ziemi.",
  "Ugh, I know.": "No nie?",
  "I hate this.": "To jakiś koszmar.",
  "Hey! He's going to go mess with our stuff!": "Ma zamiar grzebać w naszych rzeczach!",
  "What is that guy doing over there?": "Co ten facet wyprawia?",
  "Is he skeezing?": "Czy on sobie trzepie?",
  "HEY GUY! ARE YOU SKEEZING?!": "Ej, gościu! Walisz gruchę?!",
  "GET OUTTA HERE!": "Wynocha stamtąd!",
  "Hey! Where's he going?!": "Hej! Gdzie on lezie?!",
  "Whoa, hey! Did you mess with any of our stuff?!": "Ej! Grzebałeś w naszych rzeczach?!",
  "OUR STUFF!": "Nasze rzeczy!",
  "WHOA! Where are you going with that?!": "Co masz zamiar z tym zrobić?!",
  "Don't go back there you dick!": "Nie wracaj się tam, frajerze!",
  "My STEREO!": "Moje radio!",
  "WHO THE HELL ARE YOU?!? You can't just STEAL from us!": "Ktoś ty, kurwa, za jeden?! Nie masz prawa nas okradać!",
  "Argh, you fucker!": "Ty kutasiarzu!",
  "I wanna go like RIGHT now!": "Zabierajmy się stąd w tej chwili!",
  "Shit! Let's just get OUT of here.": "Cholera! Po prostu się stąd zmywajmy.",
  "YOU'LL PAY FOR THIS YOU THIEF!": "Zapłacisz nam za to, złodzieju!",
  "I don't like this, can we go?!": "Nie podoba mi się to, możemy spadać?!",
  "Shit! Let's go to the other side of the lake.": "Cholera! Spadajmy na drugą stronę jeziora.",
  "LATER SKEEZER! We're gonna tell everyone there's a perv out here!": "Nara, fajansiarzu! Opowiemy wszystkim o zboczku, który tu grasuje!"
}