{
  "Henry": "Henry",
  "I found a bra.": "Znalazłem stanik.",
  "Report bra": "Zgłoś stanik",
  "Delilah": "Delilah",
  "A nudie pyromaniac. Remain professional.": "Naga piromanka. Zachowaj profesjonalizm.",
  "There's uh… oof.": "Tu jest...",
  "Report second set of underwear": "Zgłoś drugi komplet bielizny",
  "Yes?": "Tak?",
  "There are two naked ladies out here.": "W pobliżu są dwie nagie kobiety.",
  "There are TWO naked women.": "Są tu DWIE nagie kobiety.",
  "Can you handle that?": "Poradzisz sobie z tym?",
  "Of course, come on. I like naked ladies same as anyone. But there's, you know—": "Jasne, nie żartuj. Nagie kobiety podobają mi się jak każdemu. \nAle problem w tym, że...",
  "Two?": "Są ich dwie?",
  "Yeah!": "Dokładnie!",
  "I know this will be tough for you, but try to pick your tongue up off the ground and do your job.": "Wiem, że to może być trudne zadanie, ale zbierz język z ziemi \ni weź się do roboty.",
  "Okay…": "Okej...",
  "Uh, nothing. Forget it.": "Nieważne. Zapomnij.",
  "Forget it.": "Mniejsza z tym.",
  "If you say so.": "Skoro tak mówisz.",
  "I should probably just head back.": "Powinienem po prostu zawrócić.",
  "I should just head back.": "Powinienem zawrócić.",
  "You SHOULD probably tell these people off and THEN head back.": "Powinieneś przemówić im do rozsądku i dopiero wtedy zawrócić.",
  "But—": "Ale...",
  "And if you *GASP* see a penis… you're gonna have to deal with that too.": "A jeśli natkniesz się na widok... penisa... z tym też będziesz musiał się uporać.",
  "No, see, they're—": "Nie, zrozum, one...",
  "Just deal with it, Henry.": "Po prostu to załatw, Henry.",
  "Well, they're naked.": "Są nagie.",
  "Aaaaand that’s two.": "Obie.",
  "Try to contain yourself.": "Spróbuj się opanować.",
  "Shut up.": "Przymknij się.",
  "Uh, there are p—panties…": "Znalazłem tu majtki...",
  "Report underwear": "Zgłoś bieliznę",
  "Where?": "Gdzie?",
  "Down where the idiots were shooting fireworks. I think they're naked.": "Niedaleko miejscówki, gdzie wystrzeliwały fajerwerki. Chyba są nagie.",
  "Neat.": "No ładnie.",
  "There are what?": "Znalazłeś co?",
  "I don't want to say that word again.": "Nie każ mi tego powtarzać.",
  "Why, because you're twelve?": "Dlaczego, bo masz 12 lat?",
  "Because of the \"p-panties.\"": "Bo majtki...",
  "Yeah.": "Tak.",
  "Who isn't?": "A kto nie jest?",
  "Alright.": "Niech będzie.",
  "They left their clothes out to dry.  Looks like two people.  Uhhh, what if they're naked?": "Rozłożyli tu swoje ubrania do wyschnięcia. To chyba dwie osoby... \nA jeśli są nadzy?",
  "Report clothes": "Zgłoś ubrania",
  "Won't that be exciting.  Look, they're obviously still there so tell them off and then head on back.": "Czyż to nie ekscytująca myśl? Słuchaj, najwyraźniej nadal tam są, więc nawtykaj im i wracaj do wieży.",
  "Who?": "Kto?",
  "Ohhh, this should be exciting.": "To będzie ekscytujące.",
  "The folks with the fireworks.": "Ludzie od fajerwerków."
}