{
  "Henry": "Henry",
  "Finding a bunch of empty beers cans. They threw them all over hell.": "Znajduję po drodze mnóstwo pustych puszek po piwie. \nZaśmiecają cały teren.",
  "Report beer cans": "Zgłoś puszki po piwie",
  "Found the fireworks. They didn't even try to hide them.": "Znalazłem fajerwerki. Leżą całkiem na widoku.",
  "Report fireworks": "Zgłoś fajerwerki",
  "They left half a bottle of whiskey. Decent stuff.": "Znalazłem też butelkę porządnej whisky.",
  "They left a bottle of whiskey.": "Zostawili butelkę whisky.",
  "Delilah": "Delilah",
  "The idiots down at the lake?": "Mówisz o idiotach znad jeziora?",
  "Yeah, them. I just found where they're hanging out.": "Tak, o nich. Właśnie dotarłem do ich miejscówki.",
  "Are you fucking serious?": "Jaja sobie, kurwa, robisz?",
  "Yeah, sure am.": "Chciałbym.",
  "I would like retract my statement about knuckle sandwiches; Feed away.": "Cofam swoje wcześniejsze słowa. Przywal im, aż zobaczą gwiazdy.",
  "Ugh. People are just the worst, aren't they.": "Niektórzy ludzie to naprawdę prymitywy, co?",
  "They're not great, no.": "Nie da się temu zaprzeczyć.",
  "Oh look, they decided to have a campfire too.": "No popatrz, ognisko też sobie rozpalili.",
  "They decided to have a campfire too.": "Rozpalili też ognisko.",
  "Well, I put out their fire.": "Zgasiłem ognisko.",
  "They decided to have a campfire, too.": "Rozpalili też ognisko.",
  "I put out their fire.": "Ugasiłem ognisko.",
  "You know, they color coded the fire danger signs in case people were illiterate but I guess that doesn't take into account just plain stupid, does it?": "Znaki ostrzegające o zagrożeniu pożarowym mają różne kolory przez wzgląd na analfabetów, ale widać nie są idiotoodporne, czyż nie?",
  "Ugh, well, confiscate them.": "W takim razie zarekwiruj je.",
  "Don't fuck with them — the last thing we need is some hikers filing a report about harassment.": "Tylko nic z nimi nie odwal... Nie potrzeba nam turystów składających skargę o nękanie.",
  "Drunk pyromaniacs. Fucking great.": "Najebani piromani. Kurwa, cudownie.",
  "What, you don't like a cold Muskwa Lite on a hot day?": "Co, nie lubisz sobie wypić chłodnego Muskwa Lite w upalny dzień?",
  "No no, I do. But then again I didn't say my manners were any good.": "Nie, wręcz przeciwnie. W końcu nigdy nie twierdziłem, że mam dobre maniery.",
  "Better than these fucking litter bugs, though. That's for sure.": "Ale są z pewnością lepsze niż u tych pieprzonych śmieciarzy.",
  "You know what, fuck it. I'm not the maid.": "A jebać to. Nie będę robić za sprzątaczkę.",
  "What do you know, people with shitty manners drink shitty beer.": "No popatrz, ludzie o gównianych manierach pijają gówniane piwo.",
  "People with shitty manners drink shitty beer.": "Ludzie o gównianych manierach pijają gówniane piwo.",
  "Oh shit, Ferriter Irish.": "A niech mnie, Ferriter Irish.",
  "I probably don't need this in my life right now.": "To chyba ostatnie, czego teraz potrzebuję.",
  "They didn't hire me to be a cop.": "Nie zatrudniono mnie w roli gliny.",
  "That should take care of that.": "To powinno wystarczyć.",
  "They left their packs tied up here.": "Zostawili tu swoje plecaki.",
  "Well, they have good taste in whiskey.": "Mają dobry gust jeśli chodzi o whisky.",
  "Man, I would've named that forest fire something good, too.": "Szkoda, znalazłabym na ten pożar lasu jakąś chwytliwą nazwę.",
  "Hey, I can always restart it.": "Zawsze mogę go ponownie wzniecić.",
  "No, I think your first instinct was the right one.": "Lepiej nie, twój pierwszy odruch był słuszny.",
  "Hey, I'm back near that big rock outcropping but not sure how to get back.": "Zawróciłem do tych sporych skał, ale nie wiem, co dalej.",
  "How do I get back?": "Jak mogę wrócić?",
  "Okay, so from these rocks… where do I go again?": "No dobra... Możesz powtórzyć, gdzie miałem się udać?",
  "Hey, still kinda lost.": "Nadal się błąkam.",
  "I'm staring at the big outcropping down here but I'm not quite sure where to look for our, uh, pyrotechnicians.": "Wgapiam się właśnie w duże masywy skalne, ale nie mam pomysłu, gdzie szukać naszych... piromanów.",
  "Hey, I'm not sure where to look?": "Masz pomysł, gdzie ich szukać?",
  "Hmm. Maybe keep heading west towards the lake.": "Spróbuj udać się na zachód, w stronę jeziora.",
  "Go back towards the lake, turn north and east through the canyon. There should be a trail at the far east side of it.": "Zawróć nad jezioro, skręć na północ i udaj się na wschód przez kanion. Powinieneś nieco dalej znaleźć szlak.",
  "I'd head west back towards the lake and then turn north towards the canyon.": "Na twoim miejscu udałabym się na zachód, w stronę jeziora \ni skręciła na północ do kanionu.",
  "It is a hell of a nice camping spot down here by the lake.": "Ta miejscówka nad jeziorem to świetne miejsce na biwakowanie.",
  "Hell of a nice camping spot.": "Świetne miejsce na biwakowanie.",
  "I haven't been down there in years but yeah, Jonesy Lake area is perfect.": "Ostatni raz byłam tam lata temu, ale owszem, okolice jeziora Jonesy są piękne.",
  "Yeah, it makes for good camping. There used to be a group of guys who would boulder out there a couple times a year.": "Tak, to dobre miejsce na obozowisko. Kiedyś odwiedzała je grupka gości, urządzali sobie wspinaczki kilka razy do roku.",
  "What happened to them?": "Co się z nimi stało?",
  "Dunno. Just stopped coming out.": "Cholera wie. Przestali przyjeżdżać.",
  "Wow, there's a big rock outcropping down here near the lake. It's really something.": "Niedaleko jeziora znajduje się wielki masyw skalny. \nNieziemski widok.",
  "These cliffs down here are something.": "Te skały naprawdę robią wrażenie.",
  "Hey, there's a tie off point off here, just a little way from the shale slide.": "Znalazłem kolejny punkt asekuracyjny, niedaleko tamtego osuwiska.",
  "Report tie-off point.": "Zgłoś punkt asekuracyjny",
  "You're ready to get back on that horse, huh?": "Masz ochotę na więcej wrażeń, co?",
  "Well, I can't go any further is what I'm saying.": "Chodzi mi o to, że nie mogę pójść w dalszą drogę.",
  "That heads south down to the creek, but you should be able to get to the lake just by continuing west. Without any, y'know, mountaineering.": "To zejście prowadzi na południe, do rzeki. Ty chcesz się dostać nad jezioro, więc idź na zachód. Zostaw wspinaczki górskie na inną okazję.",
  "Alright.": "Niech będzie.",
  "It's a long summer. You can explore later.": "Przed nami długie lato. Na zwiedzanie przyjdzie czas.",
  "That probably could’ve ended poorly.": "To się mogło źle skończyć.",
  "How’d you get fired and wind up in jail all on your first day, Henry?": "Chcesz zostać wylany i trafić za kratki już pierwszego dnia pracy, Henry?",
  "Oh, I thought it'd be a good idea to chuck some Roman candles into a smoldering fire-pit. I'm a regular Forrest Byrnes.": "Pomyślałem, że wetknięcie fajerwerków w dogasające ognisko byłoby fajnym pomysłem. Lesiek Podpałka pękałby z dumy."
}