{
  "Henry": "Henry",
  "Do these things have an expiration date?": "Czy te rzeczy mają datę przydatności?",
  "Do ropes… expire?": "Czy liny mają... termin ważności?",
  "I tracked down that rope; it was right where you said.": "Znalazłem linę. Dokładnie w miejscu, o którym mówiłaś.",
  "I found that rope.": "Znalazłem linę.",
  "I'm at the cache box.": "Jestem przy skrzynce.",
  "Delilah": "Delilah",
  "“1-2-3-4.” The whole lot of them.": "1-2-3-4. Do każdej z nich.",
  "Yeah, we've got them all over the Shoshone. They save us a lot of back and forth from the trailhead.": "Tak, są rozmieszczone po całym Shoshone. Dzięki nim oszczędzamy sporo czasu podczas wędrówek.",
  "Don't take all the good stuff.": "Tylko nie opróżnij jej do czysta.",
  "Yeah, alright.": "Przyjąłem.",
  "I found the supply box.": "Znalazłem skrzynkę.",
  "Great, you should be set to get down to the lake.": "Świetnie, w takim razie możesz wyruszyć nad jezioro.",
  "Those boxes are bear proof. I wouldn't worry about it.": "Te skrzynki są odporne na ich ataki. Nie przejmuj się tym.",
  "It looks a little worse for wear.": "Wygląda na trochę zużytą.",
  "A rope's a rope, Hank.": "Lina to lina, Hank.",
  "People just stuff these things with old food? That's how you get bears.": "Ludzie upychają tu stare jedzenie? W ten sposób przyciąga się niedźwiedzie.",
  "I thought we weren't supposed to leave food out.": "Myślałem, że nie wolno nam zostawiać tu jedzenia.",
  "Whatever's in there has been in there for years. That's how you get food poisoning.": "Cokolwiek tam jest, leży od lat. Zatrucie pokarmowe jak się patrzy.",
  "Oh, good.": "Cudownie.",
  "Hey, what's the code again?": "To jak brzmiał ten szyfr?",
  "What's the code again?": "To jaki był ten szyfr?",
  "You definitely do not want to do that.": "Naprawdę nie chcesz tego robić.",
  "There's a snack in here. I'm probably going to eat it.": "Jest tu jakiś batonik. Chyba go zjem.",
  "Hey, a snack!": "O, batonik!",
  "So are there a lot of these out in the woods?": "Dużo tu macie tych skrzynek?",
  "Where's that?": "Gdzie dokładnie?",
  "Great.": "Świetnie."
}