{
  "Henry": "Henry",
  "Someone broke in.": "Ktoś się włamał.",
  "Report vandalism": "Zgłoś wandalizm",
  "Delilah": "Delilah",
  "They what?": "Co takiego?",
  "They just, they wrecked the place. Threw my typewriter out the window…": "Wywrócili to miejsce do góry nogami. Wyrzucili moją \nmaszynę do pisania przez okno...",
  "MOTHERFUCKER!": "Skurwysyny!",
  "Holy shit. I'll let the Forest Service know what happened.": "Cholera jasna. Powiadomię Służbę Leśną o zajściu.",
  "There's glass everywhere.": "Wszędzie leży potłuczone szkło.",
  "My fucking sheets are gone!": "Podpierdolili mi nawet pościel!",
  "Report stolen sheets": "Zgłoś skradzioną pościel",
  "They stole your sheets? That's just mean!": "Ukradli ci pościel? To już jest podłe!",
  "Yeah, it sucks.": "No, słabo...",
  "I'm going to have to fix the window.": "Będę musiał naprawić okno.",
  "Tomorrow, Henry. You won't be cold.": "Zrobisz to jutro, Henry. Nie zmarzniesz.",
  "Okay, I put in a call.": "No dobrze, zgłosiłam to.",
  "Okay. Thanks.": "Dzięki.",
  "Thanks.": "Dzięki.",
  "Do you have any idea of who would've done this?": "Podejrzewasz, kto mógłby to zrobić?",
  "That was fast.": "Szybka akcja.",
  "Yeah, well. Do you have any idea who could've done this?": "Masz pomysł, kto mógł się tego dopuścić?",
  "What can they do about it? Will they catch whoever did it?": "Jakie działania mogą podjąć? Są w stanie złapać sprawcę?",
  "What can they do?": "Co mogą zrobić?",
  "This is the Forest Service Henry, they're not exactly Hawaii Five-O.": "Mowa o Służbie Leśnej, Henry, nie o oddziale komandosów.",
  "I did probably piss off the girls at the lake.": "Możliwe, że wkurzyłem te dziewczyny znad jeziora.",
  "The girls at the lake?": "Dziewczyny znad jeziora?",
  "Ugh. Fuck them.": "Jebać je.",
  "Well, I'll have the rangers keep an eye out for a couple of young women and question any they find.": "Poinformuję leśniczych, by zwracali uwagę na dwójkę młodych kobiet i przesłuchiwali wszystkie, które spotkają.",
  "Maybe that guy I saw in the canyon… but I don't know why the fuck he'd want to mess with my stuff.": "Może ten facet, którego widziałem w kanionie... ale nie mam pojęcia, czemu chciałby zniszczyć moje rzeczy.",
  "Maybe the guy in the canyon… ?": "Może ten facet z kanionu?",
  "Well, I'll have the rangers keep an eye out for a man hiking on his own and question him if they find him.": "Poinformuję leśniczych, by zwracali uwagę na samotnie podróżującego mężczyznę i przesłuchali go, jeśli go znajdą.",
  "I don't know. Who's out here?": "Nie wiem. Kogo można tu spotkać?",
  "Who is out here?": "Kogo można tu spotkać?",
  "I mean, I don't know either. I've never had a lookout be a target for violence.": "Nie mam pojęcia. Moja wieża nigdy nie stanowiła celu dla wandali.",
  "Great.": "Świetnie.",
  "Uh…": "Eee...",
  "Report typewriter": "Zgłoś maszynę do pisania",
  "What can I do for you?": "Co mogę dla ciebie zrobić?",
  "Well, my typewriter is on the ground. Outside of my tower.": "Znalazłem swoją maszynę do pisania. Na ziemi, poza wieżą.",
  "Report to Delilah": "Zgłoś się do Delilah",
  "You write?": "Jesteś pisarzem?",
  "Yeah — look… uh, the wind? No. How the hell…": "Pomyślmy... wiatr? Nie. To niby jak...",
  "You should get inside.": "Powinieneś wejść do środka.",
  "Yeah.": "Tak.",
  "Fuck me.": "Kurwa mać.",
  "Report broken window": "Zgłoś wybitą szybę",
  "Report broken glass": "Zgłoś potłuczone szkło",
  "You've only been here 24 hours!": "Jesteś tu ledwie dobę!",
  "The place is trashed.": "Zdemolowali to miejsce.",
  "I can’t believe this shit.": "Nie wierzę, co tu się odpierdala.",
  "You hear anything yet?": "Wiesz już coś?",
  "I can't believe someone would do this… I worry about bears and fires and that's about it and now I've got to worry about… who knows what out there.": "Nie wierzę, że ktoś byłby do tego zdolny... Dotychczas źródłem moich zmartwień były niedźwiedzie i pożary, teraz mam do tego dodać... cholera wie, co!",
  "I can't believe someone would do this… I worry about bears and fires and that's about it and now I've got to worry about some… what, violent campers?": "Nie wierzę, że ktoś byłby do tego zdolny... Dotychczas źródłem moich zmartwień były niedźwiedzie i pożary, teraz mam do tego dodać... agresywnych biwakowiczów?",
  "I can't believe someone would do this… I worry about bears and fires and that's about it and now I've got to worry about a deranged hiker going after lookouts? Great.": "Nie wierzę, że ktoś byłby do tego zdolny... Dotychczas źródłem moich zmartwień były niedźwiedzie i pożary, teraz mam do tego dodać obłąkanego turystę demolującego wieże obserwacyjne? Świetnie.",
  "Okay, in the morning I'm going to call my friend Patty who works the desk down in Cody. They keep a list of everyone who's officially been in and out of the trailhead since, well forever, and see if we can get a list of names.": "Z samego rana skontaktuję się z moją koleżanką, Patty, która \npracuje w administracji w Cody. Prowadzą tam spis wszystkich \nosób, które oficjalnie odwiedzały nasze szlaki od... od zawsze. \nMoże zdobędziemy listę nazwisk.",
  "We won’t get much but at least if anything else happens we can refer to it and see if anything comes up.": "To może niewielka pomoc, ale zawsze coś. W razie kolejnych incydentów będziemy mieli jakiś punkt zaczepienia.",
  "I need you to feel safe out here.": "Chcę, byś czuł się tu bezpieczny.",
  "Well, I sure don’t now.": "Na to już chyba za późno.",
  "I don't.": "Za późno.",
  "You will. I promise.": "Zmienisz zdanie. Obiecuję.",
  "Don’t worry about it.": "Nie martw się o to.",
  "Don't worry.": "Nie martw się.",
  "You can protect yourself, huh?": "Potrafisz o siebie zadbać, co?",
  "I’ve done it before.": "To nie pierwszy raz.",
  "Okay, tough guy.": "No dobra, twardzielu.",
  "I just don’t worry about it.": "Po prostu się tym nie przejmuję.",
  "Perfect. Keep that attitude up and you’ll have an excellent summer.": "Świetnie. Nie zmieniaj tego nastawienia, a czeka cię cudowne lato.",
  "Just point me to the Forest Service weapons cache and I'll feel safer than the Pope in his little car.": "Po prostu zdradź mi, gdzie Służba Leśna składuje swoją broń, \na poczuję się bezpieczniej niż papież w papamobilu.",
  "Just tell me where to find a gun.": "Powiedz tylko, gdzie znajdę broń.",
  "Yeah… someone made the choice years ago that leaving people with infinite amounts of alone time and a gun was kind of a bad idea.": "Ktoś kiedyś zdecydował, że pozostawienie dostępu do broni \nludziom, którzy mają nieskończone pokłady wolnego czasu \nto dość głupi pomysł.",
  "Grenades?": "Granaty?",
  "I’ll see what I can do.": "Zobaczę, co da się zrobić.",
  "Anyway. I hope you can sleep. I'll talk to you in the morning.": "Tak czy inaczej, mam nadzieję, że zaśniesz. Porozmawiamy rano."
}