{
  "Henry": "Henry",
  "Whoa, I uh, found a turtle. Maybe it's a tortoise? It's a thing with a shell.": "Znalazłem żółwia. Chyba lądowy? To to stworzonko ze skorupą.",
  "Report turtle": "Zgłoś żółwia",
  "Delilah": "Delilah",
  "Well isn't that something!": "Coś podobnego!",
  "It's actually pretty cute.": "Jest całkiem uroczy.",
  "Well, Henry, if you decide you want it to keep you company, nobody will mind.": "Jeśli postanowisz go zatrzymać dla towarzystwa, nikt nie będzie miał nic przeciwko.",
  "What do I call it? It looks a, hmm…": "Jakby go tu nazwać? Wygląda jak...",
  "Oh, this ought to be good.": "O, to będzie dobre.",
  "Actually, I think I'll come up with this thing's name on my own. Something special.": "Nadam mu jakieś wyjątkowe imię.",
  "It's a secret.": "To tajemnica.",
  "What a lucky creature.": "Szczęściarz z niego.",
  "Mayhem Junior.": "Masa Junior.",
  "Ha. Perfect.": "Idealne.",
  "I think so.": "Tak myślę.",
  "That is peculiar.": "Wyjątkowe, doprawdy.",
  "It has sentimental value.": "Ma wartość sentymentalną.",
  "Bucket Junior.": "Biszkopt Junior.",
  "Shelly Duval.": "Izabella Scorupco.",
  "Shelly Duvall.": "Izabella Scorupco.",
  "Shell-ee. I see what you did there. Very nice.": "Scorup-co. Załapałam, całkiem niezłe.",
  "She's dainty yet powerful.": "Filigranowa, ale nieustraszona.",
  "Well, I loved her in The Shining.": "Co racja, to racja.",
  "Turt Reynolds.": "Al Żółwino.",
  "Haha, well now I can't wait to see him!": "Nie mogę się doczekać, by go zobaczyć!",
  "The mustache is impressive.": "Zarost całkiem mu pasuje.",
  "Tell him I love Cannonball Run.": "Przekaż, że uwielbiam go w „Ojcu chrzestnym”.",
  "Be Free!": "Bądź wolny!",
  "I could never send you away. Take me back.": "Nie mógłbym cię odesłać. Przyjmij mnie z powrotem."
}