{
  "1974, when you approach Julia.": "1974, gdy podchodzisz do Julii.",
  "Said yeah, let's have kids.": "Powiedziałeś, że fajnie byłoby mieć dzieci.",
  "Said kids would be good some day.": "Powiedziałeś, że na dzieci jeszcze przyjdzie pora.",
  "Picked Mayhem, the German Shepherd.": "Wybrałeś Masę, owczarka niemieckiego.",
  "Chose Bucket the Beagle.": "Wybrałeś Biszkopta, beagle'a.",
  "Intimidated the mugger when approached.": "Zastraszyłeś bandytę.",
  "Beat the mugger's face in.": "Rozkwasiłeś twarz bandycie.",
  "Told Julia to go to Yale and commute back and forth.": "Powiedziałeś Julii, żeby jeździła na Yale tam i z powrotem.",
  "Julia stayed at Boulder.": "Julia została w Boulder.",
  "Went straight to the doc when she had a spell.": "Poszliście do lekarza zaraz po pierwszym ataku.",
  "Didn't make a big deal out of Julias' first spell.": "Nie przejąłeś się zbytnio pierwszym atakiem Julii.",
  "Gave Julia the silent treatment in a fight.": "Podczas kłótni nie odzywałeś się do Julii.",
  "Called Julia a butthole during a fight.": "Podczas kłótni ubliżyłeś Julii.",
  "Decide to take care of Julia alone.": "Zamierzasz sam zaopiekować się Julią.",
  "Decide to get fulltime care for Julia.": "Zamierzasz zorganizować dla Julii opiekę.",
  "Put chair in front of door when going to bar.": "Ustawiłeś krzesło przed drzwiami, zanim poszedłeś do baru.",
  "You trust she sleeps like a rock.": "Zaufałeś, że śpi kamiennym snem.",
  "You pose like He-Man": "Pozujesz jak He-Man.",
  "You lounge/frolic like a Victoria's Secret model": "Pozujesz jak modelka Victoria's Secret.",
  "Get DUI. I think you get this any way you play but that might change.": "Get DUI. I think you get this any way you play but that might change.",
  "Didn't get DUI. I think you get this any way you play but that might change.": "Didn't get DUI. I think you get this any way you play but that might change."
}