{
  "Henry": "Henry",
  "I'm up in my tower again. At least they didn't steal any more of my stuff.": "Wróciłem do wieży. Przynajmniej nic więcej nie ukradły.",
  "I'm up in my tower again.": "Jestem znowu na wieży.",
  "Delilah": "Delilah",
  "That's good. Can you see any sign of them from the observation deck?": "Dobrze. Widzisz z tarasu jakieś wskazówki co do miejsca ich pobytu?",
  "I'll check.": "Już patrzę.",
  "I'm near my tower now, but still no sign of those kids.": "Jestem blisko wieży, ani śladu tych dzieciaków.",
  "Okay, I trekked all the way back to my tower. Still no sign of those kids around here.": "Wróciłem z powrotem do wieży. Ani śladu dzieciaków po drodze.",
  "Well damn. If only you had some way to look out over the forest.": "Kurczę, gdybyś tylko miał możliwość rozejrzenia się z wysokości...",
  "Alright, alright…": "No już, dobrze...",
  "That sure would be handy, wouldn't it…": "Ułatwiłoby nam to szukanie, co nie?",
  "Hey, which way am I supposed to go from my tower?": "W którą stronę od wieży mam się kierować?",
  "Which way should I go from my tower?": "W którym kierunku od wieży mam się udać?",
  "You're still at your tower? I thought you left already!": "Wciąż jesteś przy wieży? Myślałam, że już poszedłeś!",
  "I… did, but the trail must loop back around somewhere.": "Tak, ale droga chyba gdzieś zatoczyła koło i wróciłem.",
  "It's straight north from there. Just use your compass if you feel a \"loop\" coming on, okay?": "Idź prosto na północ. Następnym razem użyj kompasu, kiedy wyczujesz nadchodzące „zataczanie koła”, dobrze?",
  "Sure, will do.": "Tak zrobię.",
  "This is embarrassing, but… I definitely looped again.": "To krępujące, ale... znowu zawróciłem.",
  "Oh my God. You're back at your tower?": "O mój Boże. Znowu doszedłeś do wieży?",
  "Yep.": "Ano.",
  "Just head north of your tower, past your outhouse. I KNOW you've found the outhouse by now.": "Kieruj się na północ od wieży, w stronę wychodka. Na pewno go już znalazłeś.",
  "Ah, that's all I needed to hear.": "To wszystko, czego potrzebuję."
}