{
  "Delilah": "Delilah",
  "Hey Henry…": "Hej, Henry...",
  "This isn't that hard.": "To nie jest trudne.",
  "Now this can't be that hard.": "Przecież to nie jest trudne.",
  "Think of your closet. Open it in your mind.  What is inside?": "Pomyśl o swojej szafie. Zobacz ją oczami wyobraźni. \nCo widzisz w środku?",
  "HENRY….!": "Henry!",
  "Ugh, I'm guessing nothing but really gross bowling shirts. Congratulations.": "Najwyraźniej nic poza obciachowymi koszulkami polo. Gratulacje.",
  "Okay, fine. At least tell me about your face.": "Dobra, dobra. To chociaż opisz mi swoją twarz.",
  "Unless you just don't want to answer…": "Chyba że nie masz ochoty odpowiadać...",
  "In which case…": "A w takim wypadku...",
  "I'm going to say that you're lopsided like the hunchback and hairy like the Man in the Iron Mask. Take that.": "Uznam, że masz garba jak Quasimodo i bujne owłosienie godne Człowieka w żelaznej masce.",
  "Henry": "Henry",
  "Yeah?": "Tak?",
  "Um, what do you look like?": "Jak ty właściwie wyglądasz?",
  "Why are you asking?": "Dlaczego chcesz wiedzieć?",
  "Because I'm horribly superficial.": "Bo tylko wygląd ma dla mnie znaczenie.",
  "Do you know Rollie Fingers, he pitched for the A's?": "Kojarzysz Rolliego Fingersa, miotacza grającego dla A's?",
  "Do you know Rollie Fingers?": "Kojarzysz Rolliego Fingersa?",
  "Okay, well that gives me a good start.": "Dobra, to już jakiś początek.",
  "Now tell me about your face. I'm looking at you across the bar. What do I see?": "A teraz opisz mi swoją twarz. Siedzę przy barze i spoglądam \nna ciebie. Co widzę?",
  "Uhh… hmm.": "Hm...",
  "Now let's see… in my scope I can only tell you're a white guy wearing shorts.": "Pomyślmy... Patrząc przez lornetkę, mogę jedynie stwierdzić, \nże jesteś białasem w szortach.",
  "It's hot.  And maybe, by the way, I'm not white. That's not very, you know, PC or whatever they say.": "Jest gorąco. A poza tym, może wcale nie jestem biały. \nWiesz, to niezbyt poprawne politycznie, czy coś.",
  "Oh my God, you are the whitest man. I don't need a spotting scope for that.": "O mój Boże, masz skórę jak albinos. Mogę to stwierdzić \ni bez lornetki.",
  "And if not shorts then what do you normally like to wear?": "A pomijając szorty, co jeszcze lubisz nosić na co dzień?",
  "I could be Tom Cruise's good looking twin brother.": "Mógłbym być przystojniejszym bratem bliźniakiem Toma Cruise'a.",
  "If Tom Cruise had a good looking twin.": "Jak przystojny bliźniak Toma Cruise'a, gdyby istniał.",
  "Oh that's too bad. I read in People he's like five foot nothing.": "To niedobrze. Czytałam w magazynie „People”, że ma ledwie \nmetr sześćdziesiąt.",
  "Yeah, well you can't win 'em all.": "Nie można mieć wszystkiego.",
  "No.": "Nie.",
  "I'm the spitting image of him.": "Jesteśmy jak dwie krople wody.",
  "Oh, wait! Is he the guy with Snidely Whiplash mustache, from the 70's? My dad LOVED him.": "Moment! Czy to nie ten gościu z sumiastym wąsem \nrodem z lat siedemdziesiątych? Mój tata go uwielbiał.",
  "Yeah, that's him.": "Dokładnie on.",
  "That mustache… mmm. Now you have my attention. Rawr!": "Te wąsiska... Teraz przykułeś moją uwagę.",
  "Okay…": "Okej...",
  "I get confused for Burt Reynolds all the time.": "Ludzie często mylą mnie z Burtem Reynoldsem.",
  "Like Burt Reynolds.": "Jak Burt Reynolds.",
  "Ohhh, is that so.": "Czyżby?",
  "Women say that we have a similar musk.": "Według kobiet roztaczamy podobną męską woń.",
  "Uh huh…": "Aha...",
  "Hey, you asked.": "Sama chciałaś wiedzieć.",
  "Clothes.  I don't really think about it.": "Ubrania. Nie przywiązuję do nich wagi.",
  "Oh come on!": "No daj spokój!",
  "I got a sweatshirt I like. A good jacket I got at the Buckle Barn.": "Mam ulubioną bluzę. I porządną kurtkę kupioną w Buckle Barn.",
  "Ooh, I love the Buckle Barn.": "Uwielbiam Buckle Barn.",
  "It's just one of those brown ones, you know.": "Jedną z tych brązowych, kojarzysz.",
  "I do.": "Tak.",
  "Tuxedos, as often as possible.": "Smokingi, przy każdej możliwej okazji.",
  "Oh really.": "Serio?",
  "You bet.": "No ba.",
  "How cosmopolitan. I didn't realize Boulder was so chic.": "Ale z ciebie modniś. Nie wiedziałam, że Boulder to taka kolebka mody.",
  "It is the peak of high society.": "Obraca się tam śmietanka towarzyska.",
  "Mmm, good to know dear, yes.": "Dobrze wiedzieć.",
  "I dunno. I like to look nice, usually. Well, I try now, I guess.": "Sam nie wiem. Lubię dobrze wyglądać. No, teraz się staram.",
  "I try to look nice, usually.": "Staram się wyglądać ładnie.",
  "Had a bit of schlubby period, did we?": "Uwielbiałeś styl na obdartusa, co?",
  "Yeah, a good twenty-five, thirty years.": "Przez jakieś 25-30 lat, zgadza się.",
  "But now you'll put on a clean shirt?": "Ale teraz już nosisz czyste koszulki?",
  "Yeah, I have one that I got for Christmas. It's just navy with white buttons but I like it. I don't wear it that much, though.": "Mam jedną, dostałem w prezencie świątecznym. Granatowa, \nz białymi guzikami, ale lubię ją. Choć rzadko ją zakładam.",
  "Well it sounds just perfect.": "Brzmi idealnie.",
  "A pretty thick beard.": "Dość gęstą brodę.",
  "I have a thick beard.": "Mam gęstą brodę.",
  "Oh. Have you always had a beard?": "Od zawsze jesteś brodaczem?",
  "For a while, yeah.": "Już od dłuższego czasu.",
  "Alright, perfect.": "Dobra, super.",
  "I got a broken nose. It's not bad or anything, but yeah.": "Miałem złamany nos. Nie wygląda to źle, czy coś, ale no...",
  "My nose has been broken.": "Miałem złamany nos.",
  "How'd you do that? Your illustrious boxing career?": "Jak do tego doszło? Pamiątka po świetlanej karierze bokserskiej?",
  "I wish. No, a guy was drunk and jumped on my back and I slipped and ate a parking meter.": "Fajnie by było. Nie, jakiś pijany facet skoczył na mnie od tyłu, potknąłem się i pocałowałem parkometr.",
  "Yeesh.": "Auć...",
  "I have a thin mustache, a real thin mustache. And I gotta long scar that goes down across my eye and across my cheek.": "Mam bardzo cieniutki wąs. I długą bliznę, która biegnie \nod oka i na wskroś policzka.",
  "You'll enjoy my thin mustache and long scar.": "Spodobałby ci się drobny wąsik i spora blizna.",
  "And you only wear tuxes.": "I zakładasz tylko smokingi.",
  "Well I just happen to have a thing for thin mustaches. The thinner and pervier the better.": "Zawsze podobały mi się cienkie wąsy. Im węższe i bardziej perwersyjne, tym lepiej.",
  "Well then you are in luck.": "Więc to twój szczęśliwy dzień.",
  "AND a horrible scar? Just perfect.": "I do tego okropna blizna? Idealnie.",
  "I know it's not easy.": "Wiem, to niełatwe.",
  "Come on! You're no fun.": "No dalej! Nie umiesz się bawić.",
  "Fine. Forget it, one last one.": "Dobra. Pomińmy to, ostatnia kwestia.",
  "Okay.": "Okej...",
  "Sorry…": "Przepraszam...",
  "Okay, I'll try one last one.": "Dobra, ostatnia rzecz.",
  "Yeah.": "Tak.",
  "Are you a freaking Bond villain?": "Jesteś czarnym charakterem z Bonda?",
  "I uhh… I get up to stuff, yeah.": "Nadałbym się do tego.",
  "I don't think you're taking this very seriously.": "Chyba nie traktujesz tego zbyt poważnie.",
  "I want to know about your eyes.": "Chcę posłuchać o twoich oczach.",
  "Get out of here.": "Daj spokój.",
  "I'm drawing you. I need to know.": "Szkicuję cię. Muszę to wiedzieć.",
  "You're what?": "Co takiego?",
  "Is that okay?": "Masz coś przeciwko?",
  "Uhhhhh…": "Eee...",
  "Don't answer, I'm going to do it, regardless.": "Nie odpowiadaj, i tak nie przestanę.",
  "Fine.": "Dobra...",
  "Your eyes. Tell me.": "Opowiedz mi o swoich oczach.",
  "They're steely. A cold, hard stare.": "Są nieczułe. Zimne, twarde spojrzenie.",
  "Steely.": "Nieczułe.",
  "I'm just gonna make it up. And because I'm nice you won't look too disfigured.": "Sama coś wymyślę. A ponieważ jestem miła, nie oszpecę cię zanadto.",
  "Hmm… like a Siberian Husky.": "Czyli jak husky syberyjski.",
  "Ha, sure.": "Właśnie tak.",
  "They're happy, I think. I've been told they look happy.": "Są szczęśliwe. Tak mi ktoś kiedyś powiedział.",
  "Happy.": "Szczęśliwe.",
  "Aww.": "Ooo...",
  "Julia told you that, huh?": "To słowa Julii, co?",
  "Look, I don't know how to describe eyes.": "Słuchaj, nie umiem opisywać oczu.",
  "Happy is good. That's good.": "„Szczęśliwe” jest okej. Nada się.",
  "They look tired, I think.": "Chyba sprawiają wrażenie zmęczonych.",
  "Tired.": "Zmęczone.",
  "Aw, yeah?": "Czyżby?",
  "Yeah, you know, you hit a certain age and you just think you're a younger person who looks tired all the time.": "No wiesz, dobijasz do pewnego wieku i wydaje ci się, że jesteś młodzikiem, który wygląda na wiecznie zblazowanego.",
  "Ha, speak for yourself, mister.": "Mów za siebie, szanowny panie.",
  "But I guess that's getting old.": "Ale tak chyba wygląda starzenie.",
  "Well, some people might see distinguished.": "Niektórzy pewnie mieliby inne zdanie.",
  "Okay got it. Thank you, Henry.": "Dobra, to wystarczy. Dzięki, Henry.",
  "You get what you need?": "Masz, czego chciałaś?",
  "Absolutely.": "Bez dwóch zdań.",
  "Ready to work": "Gotów do pracy",
  "Really ready now": "Naprawdę gotów do pracy",
  "I got that window all patched up.": "Zabiłem okno deskami.",
  "Oh, and that window is all patched up.": "Przy okazji, zabiłem okno deskami.",
  "What should I do now? What's next?": "Co teraz? Jakie jest moje kolejne zadanie?",
  "What's next? What do you think is next?": "Co teraz? A jak myślisz?",
  "You've been the one giving me tasks for two days straight.": "To ty od dwóch dni rozstawiasz mnie po kątach.",
  "What's next is you sit in that room until September 1st and call me at the first sign of smoke.": "Teraz masz przesiadywać w tym pokoju, aż nastanie 1 września \ni informować mnie o wszelkich oznakach dymu.",
  "Oh yeah.": "No tak.",
  "Why don't you let me know when you're mentally prepared for that task and I'll give it to you.": "Daj znać, jak będziesz psychicznie gotowy do tego zadania. Wtedy cię poinstruuję.",
  "Okay. I think I am ready to tackle my long-term commitment of keeping this national forest safe from total destruction.": "Dobra. Chyba jestem gotów stawić czoła długoterminowemu wyzwaniu ochrony tego lasu przed całkowitym zniszczeniem.",
  "Okay, I'm ready.": "Jestem gotów.",
  "I am glad to hear you've really thought this through.": "Dobrze wiedzieć, że porządnie to przemyślałeś.",
  "Of course.": "Oczywiście.",
  "We've issued you a comfy chair to sit in and everything.": "Zapewniliśmy ci wygodne krzesło do siedzenia i w ogóle.",
  "You know, it's really not that comfy.  It's wooden, there's no padding, I actually think I got splinter in my thigh this morning…": "Tak szczerze to nie nazwałbym go wygodnym. Jest drewniane, nie ma obicia, a dziś rano w udo wbiła mi się z niego drzazga.",
  "Aww. Regardless, take a seat. The forest depends on you.": "Tak czy inaczej, siadaj. Ten las liczy na ciebie.",
  "You know, I'm gonna hike around for a while before I really put my nose to the grindstone.": "Wiesz co, chyba przejdę się na krótki spacer, zanim zacznę harować jak wół.",
  "Actually…": "Tak właściwie...",
  "Hmm, yeah! You do that.": "Jasne, nie krępuj się.",
  "It seems like you're having some doubts. Why don't you hike around for a bit and let me know when you're ready.": "Chyba targają tobą wątpliwości. Może pospaceruj po okolicy przez jakiś czas i odezwij się, gdy będziesz gotowy.",
  "Okay… NOW I'm ready. Let's get to work.": "Dobra... Teraz jestem gotów. Bierzmy się do roboty.",
  "Okay, now I'm ready.": "Teraz jestem gotów.",
  "How were those precious few seconds of jobless freedom?": "I jak było przez te kilka cennych sekund wolnych od obowiązków?",
  "Oh, magical.": "Magicznie.",
  "Good! Now get to to work.": "Świetnie! A teraz do roboty."
}