{
  "Delilah": "Delilah",
  "Wake up.": "Pobudka.",
  "Hey, wake up.": "Wstawaj.",
  "Henry": "Henry",
  "I'm awake. I'm awake. What's your problem?": "Nie śpię. Jaki masz problem?",
  "I'm awake.": "Nie śpię.",
  "Our problem.": "Jaki mamy problem.",
  "Sorry, our problem.": "Mamy, wybacz.",
  "That storm knocked out the phone line I use to talk to the service which means we're cut off. I tried radio'ing out and that's not working either.": "Burza zerwała linię telefoniczną, dlatego nie mogę skontaktować się ze służbami. Jesteśmy odcięci. Radiokomunikacja też leży.",
  "I don't really know why that would be the case.": "Nie wiem, jaki może być tego powód.",
  "I mean, we've had issues with the radios going out in this area before.": "To znaczy bywało, że mieliśmy problemy \nz odbiornikami w tym miejscu.",
  "It's frustrating, but not entirely unexpected. Sorry, I'm just thinking out loud.": "Frustrujące, ale do przewidzenia. Przepraszam, tylko głośno myślałam.",
  "Anyway, I'm sending all the lookouts out to check the wire in their areas.": "Wysyłam wszystkich obserwatorów, by sprawdzili \nprzewód na swoim terenie.",
  "Should I be worried?": "Mam się martwić?",
  "About what?": "Czym?",
  "We can't get help if we need it.": "Nie będziemy mogli wezwać pomocy.",
  "You're tough, Hank. You don't seem like the guy who likes to ask for help.": "Jesteś silny, Hank. Nie wyglądasz na kogoś, kto często prosi \no pomoc.",
  "Sure…?": "Jasne...",
  "What I need you to do, though, is hike out to where the wire runs through your area and report back if it's down. Then I can track down a ranger to get someone on it.": "Chciałabym, byś wybrał się tam, gdzie przechodzi przewód i zgłosił \nmi, czy jest uszkodzony. Wtedy mogłabym skontaktować się \nz leśniczym i załatwić sprawę.",
  "Can I go fix it?": "Mogę coś z tym zrobić?",
  "Well, you probably CAN'T but what you can do is hike out to where the wire runs through your area and report back if it's down. Then I can track down a ranger to get someone on it.": "Pewnie nie, ale możesz wybrać się tam, gdzie przechodzi przewód \ni zgłosić mi, czy jest uszkodzony. Wtedy mogłabym powiadomić \nleśniczego i załatwić sprawę.",
  "There's no back-up?": "Nie będę miał wsparcia?",
  "The backup is the two day hike out of here.": "Wsparcie jest dwa dni drogi stąd.",
  "So… that's a no?": "Więc nie?",
  "It's easier for me to send all the lookouts out to check the status of the wire in their areas.": "Łatwiej jest mi wysłać obserwatorów, by sprawdzili przewody na swoim terenie.",
  "Yours is a good hike away. If you find any portion of it down I can try to get ahold of a ranger and he'll bring someone in to fix it.": "Czeka cię dłuższy spacer. Jeśli znajdziesz jakieś uszkodzenia, zawiadomię leśniczego. On sprowadzi kogoś, kto naprawi przewód.",
  "Okay, I can do that! Where is it?": "Jasne, dam radę! Gdzie to jest?",
  "You probably had to hike through a cave yesterday to get home.": "Wczoraj pewnie wracałeś do wieży przez jaskinię.",
  "Remember that cave you hiked through yesterday?": "Pamiętasz jaskinię, przez którą wczoraj przechodziłeś?",
  "Will do.": "Zrobi się.",
  "Yeah, I did.": "Tak.",
  "Yeah, of course": "Oczywiście.",
  "Thanks Hank.": "Dzięki, Hank.",
  "So you're going to want to go back there, go through it and keep going straight to the north when you come out.": "Wrócisz tam, przejdziesz przez jaskinię, a potem będziesz \nkierował się na północ.",
  "It's Henry.": "Henry.",
  "Henry.": "Henry.",
  "What, you don't like Hank?": "Nie podoba ci się Hank?",
  "Yeah, I don't like Hank.": "Nie podoba mi się Hank.",
  "But “thanks” rhymes with Hank.": "Ale Hank rymuje się z „dzięki”.",
  "No, it doesn't.": "Wcale nie.",
  "Okay, alright.": "Niech ci będzie."
}