{
  "Henry": "Henry",
  "Okay, this wire runs all the way to the top of this ridge.": "Przewód biegnie aż na szczyt wzgórza.",
  "The wire runs up this ridge.": "Przewód biegnie na wzgórze.",
  "Delilah": "Delilah",
  "Go up and have a look and if it's fine, you can turn around and head home.": "Rozejrzyj się tam. Jeśli wszystko jest w porządku, wracaj do domu.",
  "Hey, so the wire is definitely down out here.  I just found it.": "Tak, przewód jest tutaj przerwany. Właśnie go znalazłem.",
  "Report cut wire": "Zgłoś przecięty przewód",
  "That's actually good to hear. I can send someone out to fix it. Good find.": "Dobrze to słyszeć. Teraz mogę wysłać kogoś, by to naprawił. Świetna robota.",
  "Yeah, the thing is…": "Chodzi o to, że...",
  "What?": "Co?",
  "It doesn't look like the wind. It looks like it was cut, deliberately.": "To nie wina wiatru. Przewód został umyślnie przecięty.",
  "I don't follow.": "Nie rozumiem.",
  "It's snipped clean through and they left us a, uh, message.": "Przecięły przewód czymś ostrym i zostawiły nam wiadomość.",
  "I KNEW it the moment you said you found their trash.": "Wiedziałam to już kiedy wspomniałeś o ich śmieciach.",
  "It's snipped clean through and there's a bunch of beer cans out here — the same beer those girls were drinking.  They also left us a, uh, message.": "Przewód został przecięty czymś ostrym, a dookoła leżą puszki po piwie... Tej samej marki, którą piły tamte dziewczyny. Zostawiły nam też wiadomość.",
  "Those stupid shits cut our wire!?": "Te gówniary przecięły przewód?!",
  "I've got a pair of their whites out here with a note on them. It says Go To Hell, Forrest Byrnes.": "Mam tu ich bieliznę, na której napisały wiadomość: „Idź do piekła, Leśku Podpałko”.",
  "So yeah, those stupid shits cut our wire.": "Więc to te gówniary przecięły przewód.",
  "So, it wasn't the wind. They cut it.": "Więc to nie był wiatr. To ich wina.",
  "These idiots are going to pay.": "Te idiotki za to zapłacą.",
  "I'm serious, this is unacceptable. This is criminal and I'm not going to wait around for some ranger to get off of his ass.": "Mówię serio, to niedopuszczalne. To przestępstwo i nie zamierzam czekać, aż jakiś leśniczy przestanie się obijać.",
  "Do they realize this is how people die?": "Zdają sobie sprawę, że tak giną ludzie?",
  "I mean, what if something happened to one of my lookouts while this was going on?!": "A gdyby w tym czasie coś się stało jednemu z obserwatorów?!",
  "And God forbid there is an actual fire burning out of control.": "A nie daj Boże wybuchnie straszliwy pożar.",
  "Just… gahhh. I'm in a full rage here.": "Jestem strasznie wkurzona.",
  "Someone needs to do something. You need to do something.": "Ktoś musi coś zrobić. Ty musisz coś zrobić.",
  "Whoa, take it easy.": "Hej, spokojnie.",
  "Take it easy.": "Spokojnie.",
  "I see that… so… take it easy, maybe.": "Rozumiem, ale... może nieco wyluzuj?",
  "Don't tell me to take it easy. We've got a pair of criminal morons running around putting the forest and everyone in it in danger.": "Nie każ mi się wyluzować. Mamy do czynienia z dwójką zidiociałych kryminalistek, które narażają las i wszystkich w nim na niebezpieczeństwo.",
  "Also, \"take it easy?\" You know I'm still your boss.": "A tak poza tym, „wyluzuj”? Nie zapominaj, kto tu rządzi.",
  "Alright sorry.": "Jasne, przepraszam.",
  "What do you want to do?": "Co chcesz zrobić?",
  "I see that… I'm pissed too. What do you want to do?": "Rozumiem. Też jestem wkurzony. Co chcesz zrobić?",
  "I'm pissed too.": "Też jestem zły.",
  "I want you to go find them.": "Chcę, byś je znalazł.",
  "And then what?": "I co potem?",
  "I… I haven't thought that far ahead. That's not true. Everything that comes to mind is illegal.": "O tym nie myślałam. No dobrze, to kłamstwo. Ale wszystko, o czym myślę, jest nielegalne.",
  "Alright. This is what I want you to do.": "Dobra. Chcę, żebyś zrobił, co następuje.",
  "You're the boss.": "Ty tu rządzisz.",
  "What's that supposed to mean?": "Co to miało znaczyć?",
  "It means if I end up in the clink I'm sending them after you.": "To znaczy, że jeśli skończę w pace, wsypię cię bez zastanowienia.",
  "You were just following orders.": "Po prostu wykonywałeś polecenia.",
  "You got it.": "Jasne.",
  "Let's hear it.": "No to słucham.",
  "Oh yeah?": "Serio?",
  "I came out here for a breath of fresh air and some adventure. What do you got?": "Jestem tutaj, by zaczerpnąć świeżego powietrza i przeżyć przygodę. Dajesz.",
  "I think I want you to just find them and scare the HELL out of them.": "Chcę, byś je znalazł i wystraszył na śmierć.",
  "Yeah, I'd make a spooky ghost costume but they stole my sheets.": "Przebrałbym się za ducha, ale ukradły mi prześcieradła.",
  "Hmm.  I don't know… wait for them to wander off and wreck their camp. Something that would make a teenage girl run home to mommy and daddy.": "Sama nie wiem... Zaczekaj, aż się oddalą i wywróć ich obóz do góry nogami. Tak, aby uciekły prosto do domu, do mamusi i tatusia.",
  "Yeah, okay.": "Tak, jasne.",
  "Okay, I know that sounds nuts but we have to do something to get them the hell out of the woods. Okay?": "Dobra, to zabrzmi jak szaleństwo, ale musimy zrobić coś, co wykurzy je z lasu. W porządku?",
  "You're nuts, huh?": "Jesteś szalona.",
  "Just stay on my good side — but seriously, this is not my normal form of conflict resolution.": "Po prostu mi nie podpadaj. A tak na poważnie, zwykle inaczej radzę sobie w takich sytuacjach.",
  "I'll find them.": "Znajdę je.",
  "Excellent.": "Świetnie.",
  "Can't you call a Ranger?": "Nie możesz wezwać leśniczego?",
  "It will *actually* take three days. Please go run them off.": "To naprawdę zajmie trzy dni. Proszę, przegoń je.",
  "Fine.": "Dobra...",
  "Thanks.": "Dzięki.",
  "But I am going to need a raise.": "Ale przyda mi się podwyżka.",
  "Don't hold your breath.": "Tylko się nie napalaj.",
  "I'd start by hiking back towards your tower and just keep an eye out for anything that would lead you to them.": "Idź w stronę wieży, a po drodze rozglądaj się za śladami, \nktóre cię do nich doprowadzą.",
  "Well, they're big into Red Eagle.": "Wiesz, gustują w Red Eagle.",
  "Great.": "Świetnie.",
  "See if you can find the path they took down from there. Maybe they looped back around towards the lake or something.": "Poszukaj ścieżki, którą mogły się kierować. Może zawróciły w stronę jeziora.",
  "I doubt they're where they were yesterday but they obviously can't have gone far.": "Wątpię, by były tam, gdzie wczoraj, ale też nie mogły odejść \nza daleko.",
  "I think I just saw you at the top of Beartooth Point. Was everything okay up there?": "Chyba właśnie zobaczyłam cię na szczycie Niedźwiedziego Kła. Wszystko w porządku?",
  "Nope. Those drunk dumb-asses cut the comms wire and left a pair of their whites as a calling card.": "Nie. Te pijane dziewuchy przecięły przewód i zostawiły wizytówkę w postaci swojej bielizny.",
  "I'm sorry, WHAT?!": "Co proszę?!",
  "I’m going to go find them.": "Poszukam ich.",
  "Wa—uh, GOOD. And why don’t you call me the next time you find something like that?": "I dobrze. Dlaczego nie kontaktujesz się ze mną od razu po odkryciu czegoś takiego?",
  "I was just trying to be a self-starter.": "Chciałem po prostu być samodzielny."
}